<a href="https://colab.research.google.com/github/alokchoudharyguliya/Transformers/blob/main/Search_Query.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Challenge Link - https://www.aicrowd.com/challenges/esci-challenge-for-improving-product-search

In [ ]:
!pip install aicrowd-cli

In [ ]:
!aicrowd login

In [ ]:
!aicrowd dataset download -c esci-challenge-for-improving-product-search

In [ ]:
!unzip "/content/train-v0.3.csv.zip" -d "/content/dataset"

Archive:  /content/train-v0.3.csv.zip
  inflating: /content/dataset/data/processed/public/task_3_product_substitute_identification/train-v0.3.csv

In [ ]:
!unzip "/content/product_catalogue-v0.3.csv.zip" -d "/content/dataset"

Archive:  /content/product_catalogue-v0.3.csv.zip
  inflating: /content/dataset/data/processed/public/task_3_product_substitute_identification/product_catalogue-v0.3.csv

In [ ]:
!cp /content/dataset/data/processed/public/task_3_product_substitute_identification/train-v0.3.csv "/content/drive/MyDrive/Query-Search Engine Dataset"

In [ ]:
!cp /content/dataset/data/processed/public/task_3_product_substitute_identification/product_catalogue-v0.3.csv "/content/drive/MyDrive/Query-Search Engine Dataset"

In [ ]:
import numpy as np, pandas as pd, os

In [ ]:
filepath_train="/content/drive/MyDrive/Query-Search Engine Dataset/train-v0.3.csv"
filepath_catalogue="/content/drive/MyDrive/Query-Search Engine Dataset/product_catalogue-v0.3.csv"

In [ ]:
df_catalogue=pd.read_csv(filepath_catalogue)
df_train=pd.read_csv(filepath_train)

In [ ]:
df_train

         example_id       query  product_id query_locale substitute_label
0                 0  11 degrees  B079VKKJN7           es    no_substitute
1                 1  11 degrees  B079Y9VRKS           es    no_substitute
2                 2  11 degrees  B07D2DDCZH           es    no_substitute
3                 3  11 degrees  B07DP4LM9H           es    no_substitute
4                 4  11 degrees  B07G37B9HP           es    no_substitute
...             ...         ...         ...          ...              ...
1834739     1834739    針なしほっちきす  B08XGQ9RH7           jp       substitute
1834740     1834740    針なしほっちきす  B0987RGRF2           jp    no_substitute
1834741     1834741    針なしほっちきす  B099NFJWP6           jp    no_substitute
1834742     1834742    針なしほっちきす  B09F3B413J           jp    no_substitute
1834743     1834743    針なしほっちきす  B09F3F1KDP           jp    no_substitute

[1834744 rows x 5 columns]

In [ ]:
df_catalogue

,product_id,product_title,product_description,product_bullet_point,product_brand,product_color_name,product_locale
0,B079VKKJN7,"11 Degrees de los Hombres Playera con Logo, Ne...",Esta playera con el logo de la marca Carrier d...,11 Degrees Negro Playera con logo\nA estrenar ...,11 Degrees,Negro,es
1,B079Y9VRKS,Camiseta Eleven Degrees Core TS White (M),NaN,NaN,11 Degrees,Blanco,es
2,B07DP4LM9H,11 Degrees de los Hombres Core Pull Over Hoodi...,La sudadera con capucha Core Pull Over de 11 G...,11 Degrees Azul Core Pull Over Hoodie\nA estre...,11 Degrees,Azul,es
3,B07G37B9HP,11 Degrees Poli Panel Track Pant XL Black,NaN,NaN,11 Degrees,NaN,es
4,B07LCTGDHY,11 Degrees Gorra Trucker Negro OSFA (Talla úni...,NaN,NaN,11 Degrees,Negro (,es
...,...,...,...,...,...,...,...
1815211,B09FJYBVKS,スポーツブラ 揺れない ヨガウェア レディース トップス 通気性 ナイトブラ スポーツブラジ...,<p>【注意事項】</p><p>※商品内容以外のアクセサリー・小物等は付属しません.</p>...,シンプルのデザインで合わせやすいです。コート、半袖、シャツを合わせて、家で着てもいい、寝てい...,Doworspaw,ベージュ,jp
1815212,B09FTJ3S1N,ブラジャー レディース 補正ブラ Gabrioir 揺れない 大きいサイズ バストアップ美胸...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,パープル,jp
1815213,B09G72LDQZ,レディース ブラジャー 補正ブラ トップス Gabrioir 大きいサイズ 揺れない 脇高設...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,ベージュ,jp
1815214,B09GBGRTPB,ナイトブラ ノンワイヤーブラ ブラジャー レディース Gabrioir 大きいサイズ パット...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,パープル,jp
1815215,B09GBKN83Q,インナーキャミソール レディース ブラトップ キャミソール Gabrioir ノーワイヤー ...,<p>【配送】</p><p>普通には2-3日後出荷できますが。出荷した後15-25日ぐらい届...,【いろんな場合に適用】軽い運動時、家事、外出、長時間移動、温泉旅行などに活用なセクシルームブ...,Gabrioir,ブラック,jp

In [ ]:
df_train.shape

(1834744, 5)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1834744 entries, 0 to 1834743
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   example_id        int64
 1   query             object
 2   product_id        object
 3   query_locale      object
 4   substitute_label  object
dtypes: int64(1), object(4)
memory usage: 70.0+ MB

In [ ]:
df_train.describe()

         example_id
count  1.834744e+06
mean   9.173715e+05
std    5.296451e+05
min    0.000000e+00
25%    4.586858e+05
50%    9.173715e+05
75%    1.376057e+06
max    1.834743e+06

In [ ]:
df_train.isna().sum()

example_id          0
query               0
product_id          0
query_locale        0
substitute_label    0
dtype: int64

In [ ]:
def get_label(label):
  if label=='exact':
    return 1.0
  elif label=='substitute':
    return 0.7
  elif label=='complement':
    return 0.5
  else:
    return 0.0

In [ ]:
model_id=''

In [ ]:
model=TFAutoModel.from_pretrained(model_id)
model.summary()