<a href="https://colab.research.google.com/github/alokchoudharyguliya/Transformers/blob/main/Text_Summarization_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch torchvision

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.25.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.4.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torch.nn.utils.rnn import pad_sequence
from spacy.tokenizer import Tokenizer
from sklearn.model_selection import train_test_split
import spacy
import pandas as pd
import numpy as np
import os, re
from nltk.corpus import stopwords
import random
from tqdm import tqdm
import math

Tokenizer using spacy

In [3]:
nlp=spacy.load('en_core_web_sm')
tokenizer=Tokenizer(nlp.vocab)

In [4]:
# Add data from files into dataframes for easier access
def create_dataframe(source_text_path,target_text_path):
  txt_files_source=[file for file in os.listdir(source_text_path) if file.endswith('.txt')]
  txt_files_target=[file for file in os.listdir(target_text_path) if file.endswith('.txt')]
  df=pd.DataFrame(columns=['headlines','text'])
  for source,target in zip(txt_files_source,txt_files_target):
    assert source==target
    source_file_path=os.path.join(source_text_path,source)
    target_file_path=os.path.join(target_text_path,target)

    # Read the content of the file
    with open(source_file_path,'r',encoding='latin-1') as file:
      source_text=file.read()
    with open(target_file_path,'r',encoding='latin-1') as file:
      target_text=file.read()
    df.loc[len(df.index)]=[source_text,target_text]
  return df

In [5]:
def check_accuracy(output,labels):
  _, predpos=(output.max(1))
  num_samples=len(labels)
  num_correct=(predpos==labels).sum()
  return (num_correct/num_samples)*100

def save_checkpoint(state,filename='weights.pth.tar'):
  print("Saving weights")
  torch.save(state,filename)

def load_checkpoint(checkpoint,model,optim):
  print("Loading weights ---- ")
  model.load_state_dict(checkpoint['state_dict'])
  optim.load_state_dict(checkpoint['optimizer'])

Kaggle Dataset Fetch

In [6]:
import os
from google.colab import userdata

os.environ["KAGGLE_USERNAME"] = "pseudophoenix"
os.environ["KAGGLE_KEY"] = "7a2cb2f192719312c0d0e000fbb07af1"

In [7]:
!kaggle kernels pull kiranraghavendra/text-summarization-transformer-from-scratch

Source code downloaded to /content/text-summarization-transformer-from-scratch.ipynb

In [8]:
import kagglehub
# Download the specific dataset
base_path = kagglehub.dataset_download("pariza/bbc-news-summary")

Downloading to /root/.cache/kagglehub/datasets/pariza/bbc-news-summary/2.archive...

100%|██████████| 8.91M/8.91M [00:00<00:00, 162MB/s]

Extracting files...

Extracting all the articles and summaries data

In [9]:
articles_root=f"{base_path}/BBC News Summary/News Articles"
summaries_root=f"{base_path}/BBC News Summary/Summaries"
df1 = create_dataframe(f"{articles_root}/business",f"{summaries_root}/business")
df2 = create_dataframe(f"{articles_root}/entertainment",f"{summaries_root}/entertainment")
df3 = create_dataframe(f"{articles_root}/politics",f"{summaries_root}/politics")
df4 = create_dataframe(f"{articles_root}/sport",f"{summaries_root}/sport")
df5 = create_dataframe(f"{articles_root}/tech",f"{summaries_root}/tech")

Combining all the df s into one dataframe

In [10]:
df=pd.concat([df1,df2,df3,df4,df5],ignore_index=True)

In [11]:
df.head()

,headlines,text
0,ID theft surge hits US consumers\n\nAlmost a q...,"The biggest slice of the 246,570 ID fraud case..."
1,Dollar gains on Greenspan speech\n\nThe dollar...,The dollar has hit its highest level against t...
2,Market unfazed by Aurora setback\n\nAs the Aur...,"Despite its string of bad luck, he pointed out..."
3,UK Coal plunges into deeper loss\n\nShares in ...,"UK Coal said it was making ""significant progre..."
4,Troubled Marsh under SEC scrutiny\n\nThe US st...,The US stock market regulator is investigating...

In [12]:
df=df.rename(columns={"headlines":"source_text","text":"summary_text"})
X,y=df['source_text'],df['summary_text']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)
train_df=pd.DataFrame({'source_text':X_train,'summary_text':y_train})
test_df=pd.DataFrame({'source_text':X_test,'summary_text':y_test})

In [13]:
X_train.head(),X_test.head(), y_train.head(), y_test.head(), train_df.head(), test_df.head()

(1490    Hodges announces rugby retirement\n\nScarlets ...
 2001    'Blog' picked as word of the year\n\nThe term ...
 1572    European medal chances improve\n\nWhat have th...
 1840    Sun offers processing by the hour\n\nSun Micro...
 610     UK TV channel rapped for CSI ad\n\nTV channel ...
 Name: source_text, dtype: object,
 414     Metlife buys up Citigroup insurer\n\nUS bankin...
 420     Yukos accused of lying to court\n\nRussian oil...
 1644    Mourinho plots impressive course\n\nChelsea's ...
 416     Brazil approves bankruptcy reform\n\nA major r...
 1232    Abortion not a poll issue - Blair\n\nTony Blai...
 Name: source_text, dtype: object,
 1490    The 36-year-old, who has 54 caps, was Llanelli...
 2001    The term "blog" has been chosen as the top wor...
 1572    Diane Allahgreen has been our best hurdler for...
 1840    Sun likened grid computing to the development ...
 610     The promotion material was sent in brown envel...
 Name: summary_text, dtype: object,
 414     US banking giant Citigroup has sold its Travel...
 420     Russian oil firm Yukos lied to a US court in a...
 1644    Mourinho doesn't simply talk a good game - he'...
 416     The new legislation changes this, giving prior...
 1232    In a statement, he said abortion was a "very k...
 Name: summary_text, dtype: object,
                                             source_text  \
 1490  Hodges announces rugby retirement\n\nScarlets ...
 2001  'Blog' picked as word of the year\n\nThe term ...
 1572  European medal chances improve\n\nWhat have th...
 1840  Sun offers processing by the hour\n\nSun Micro...
 610   UK TV channel rapped for CSI ad\n\nTV channel ...

                                            summary_text
 1490  The 36-year-old, who has 54 caps, was Llanelli...
 2001  The term "blog" has been chosen as the top wor...
 1572  Diane Allahgreen has been our best hurdler for...
 1840  Sun likened grid computing to the development ...
 610   The promotion material was sent in brown envel...  ,
                                             source_text  \
 414   Metlife buys up Citigroup insurer\n\nUS bankin...
 420   Yukos accused of lying to court\n\nRussian oil...
 1644  Mourinho plots impressive course\n\nChelsea's ...
 416   Brazil approves bankruptcy reform\n\nA major r...
 1232  Abortion not a poll issue - Blair\n\nTony Blai...

                                            summary_text
 414   US banking giant Citigroup has sold its Travel...
 420   Russian oil firm Yukos lied to a US court in a...
 1644  Mourinho doesn't simply talk a good game - he'...
 416   The new legislation changes this, giving prior...
 1232  In a statement, he said abortion was a "very k...  )

In [14]:
contraction_mapping={}

In [15]:
def process_dataframe(df,tokenizer, text_cleaner_func):
  df['summary_text']=df['summary_text'].apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner_func(x))])
  df['source_text']=df['source_text'].apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner_func(x))])
  return df

In [16]:
# def text_cleaner(text):
#   # This is a placeholder for the actual text cleaning logic
#   # Based on common text summarization pipelines, this function would typically handle:
#   # - Removing special characters, punctuation, and numbers
#   # - Removing extra spaces
#   # - Lowercasing (though your current code does this separately)
#   # - Removing stopwords (if desired)
#   # - Expanding contractions (if using the contraction_mapping)
#   # For now, it just returns the text as is.
#   new_text = text.lower()
#   new_text = re.sub(r"[^a-zA-Z0-9 ]", "", new_text) # Remove special characters
#   new_text = re.sub(r"\s+", " ", new_text) # Remove extra spaces
#   return new_text

In [17]:
# def process_dataframe_text(df, tokenizer, text_cleaner_func):
#   df['source_text'] = df['source_text'].apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner_func(x))])
#   df['summary_text'] = df['summary_text'].apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner_func(x))])
#   return df

In [18]:
# # Tokenize and lowercase text using spacy
# train_df = process_dataframe_text(train_df, tokenizer, text_cleaner)
# test_df = process_dataframe_text(test_df, tokenizer, text_cleaner)

In [19]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [20]:
def text_cleaner(text):
  newString=text.lower()
  newString=newString.replace('"',"'")
  newString=re.sub(r'\([^)]*\)','',newString)
  newString=re.sub('"','',newString)
  # newString=' '.join([contraction_mapping[t] if t in contraction_mapping else t for t in newString.split(" ")])
  tokens=[w for w in newString.split() if not w in stop_words]
  return " ".join(tokens)

In [21]:
contraction_mapping = {"ain't": "is not", "aren't": "are not","can't": "cannot", "'cause": "because", "could've": "could have", "couldn't": "could not",

                           "didn't": "did not", "doesn't": "does not", "don't": "do not", "hadn't": "had not", "hasn't": "has not", "haven't": "have not",

                           "he'd": "he would","he'll": "he will", "he's": "he is", "how'd": "how did", "how'd'y": "how do you", "how'll": "how will", "how's": "how is",

                           "I'd": "I would", "I'd've": "I would have", "I'll": "I will", "I'll've": "I will have","I'm": "I am", "I've": "I have", "i'd": "i would",

                           "i'd've": "i would have", "i'll": "i will",  "i'll've": "i will have","i'm": "i am", "i've": "i have", "isn't": "is not", "it'd": "it would",

                           "it'd've": "it would have", "it'll": "it will", "it'll've": "it will have","it's": "it is", "let's": "let us", "ma'am": "madam",

                           "mayn't": "may not", "might've": "might have","mightn't": "might not","mightn't've": "might not have", "must've": "must have",

                           "mustn't": "must not", "mustn't've": "must not have", "needn't": "need not", "needn't've": "need not have","o'clock": "of the clock",

                           "oughtn't": "ought not", "oughtn't've": "ought not have", "shan't": "shall not", "sha'n't": "shall not", "shan't've": "shall not have",

                           "she'd": "she would", "she'd've": "she would have", "she'll": "she will", "she'll've": "she will have", "she's": "she is",

                           "should've": "should have", "shouldn't": "should not", "shouldn't've": "should not have", "so've": "so have","so's": "so as",

                           "this's": "this is","that'd": "that would", "that'd've": "that would have", "that's": "that is", "there'd": "there would",

                           "there'd've": "there would have", "there's": "there is", "here's": "here is","they'd": "they would", "they'd've": "they would have",

                           "they'll": "they will", "they'll've": "they will have", "they're": "they are", "they've": "they have", "to've": "to have",

                           "wasn't": "was not", "we'd": "we would", "we'd've": "we would have", "we'll": "we will", "we'll've": "we will have", "we're": "we are",

                           "we've": "we have", "weren't": "were not", "what'll": "what will", "what'll've": "what will have", "what're": "what are",

                           "what's": "what is", "what've": "what have", "when's": "when is", "when've": "when have", "where'd": "where did", "where's": "where is",

                           "where've": "where have", "who'll": "who will", "who'll've": "who will have", "who's": "who is", "who've": "who have",

                           "why's": "why is", "why've": "why have", "will've": "will have", "won't": "will not", "won't've": "will not have",

                           "would've": "would have", "wouldn't": "would not", "wouldn't've": "would not have", "y'all": "you all",

                           "y'all'd": "you all would","y'all'd've": "you all would have","y'all're": "you all are","y'all've": "you all have",

                           "you'd": "you would", "you'd've": "you would have", "you'll": "you will", "you'll've": "you will have",

                           "you're": "you are", "you've": "you have"}

In [22]:
def text_cleaner(text):
    if text is None:
      return ""
    if type(text) is not str:
      print(text)
      return ""
    newString = text.lower()
    newString = newString.replace('"', "'")
    newString = re.sub(r'\([^)]*\)', '', newString)
    newString = re.sub('"','', newString)
    # newString = ' '.join([contraction_mapping[t] if t in contraction_mapping else t for t in newString.split(" ")])
    newString = re.sub(r"'s\b","",newString)
    newString = re.sub("[^a-zA-Z]", " ", newString)
    tokens = [w for w in newString.split() if not w in stop_words]
    return " ".join(tokens)

In [23]:
# Tokenize and lowercase text using spacy
train_df['source_text']=train_df['source_text'].apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner(x))])
# train_df=process_dataframe(train_df,tokenizer,text_cleaner)
train_df['summary_text']=train_df['summary_text'].apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner(x))])

# Fill NaN values with empty strings before tokenization to prevent TypeError
test_df['source_text']=test_df['source_text'].fillna('').apply(lambda x:[token.text.lower() for token in tokenizer(text_cleaner(x))])
test_df['summary_text']=test_df['summary_text'].fillna('').apply(lambda x: [token.text.lower() for token in tokenizer(text_cleaner(x))])

In [24]:
train_df['source_text']=train_df['source_text'].apply(lambda x:['_START_']+x+['_END_'])
train_df['summary_text']=train_df['summary_text'].apply(lambda x:['_START_']+x+['_END_'])

test_df['source_text']=test_df['source_text'].apply(lambda x:['_START_']+x+['_END_'])
test_df['summary_text']=test_df['summary_text'].apply(lambda x:['_START_']+x+['_END_'])

In [25]:
train_df.head()

,source_text,summary_text
1490,"[_START_, hodges, announces, rugby, retirement...","[_START_, year, old, caps, llanelli, player, s..."
2001,"[_START_, blog, picked, word, year, term, blog...","[_START_, term, blog, chosen, top, word, us, d..."
1572,"[_START_, european, medal, chances, improve, e...","[_START_, diane, allahgreen, best, hurdler, ti..."
1840,"[_START_, sun, offers, processing, hour, sun, ...","[_START_, sun, likened, grid, computing, devel..."
610,"[_START_, uk, tv, channel, rapped, csi, ad, tv...","[_START_, promotion, material, sent, brown, en..."

In [28]:
# Builind vocabularies - each word has an index, note: words sorted in ascending order
all_tokens=train_df['source_text'].tolist()+train_df['summary_text'].tolist()+test_df['source_text'].tolist()+test_df['summary_text'].tolist()
source_vocab={actual_word:idx for idx, (word_num, actual_word) in enumerate(sorted(enumerate(set(token for tokens in all_tokens for token  in tokens)),key=lambda x: x[1]))}
target_vocab={actual_word: idx for idx, (word_num, actual_word) in enumerate(sorted(enumerate(set(token for tokens in all_tokens for token in tokens)), key = lambda x: x[1]))}

In [29]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("using ",device)

using  cuda

In [30]:
temp=list(sorted(source_vocab.items()))
for word, idx in temp[-5:]:
  print(word, idx)

zuluaga 27632
zurich 27633
zutons 27634
zvonareva 27635
zvyagintsev 27636

In [31]:
# Define a custom dataset class
class CustomDataset(Dataset):
  def __init__(self, source_texts, target_summaries, source_vocab, target_vocab):
    self.source_texts=source_texts
    self.target_summaries=target_summaries
    self.source_vocab=source_vocab
    self.target_vocab=target_vocab

  def __len__(self):
    return len(self.source_texts)

  def __getitem__(self,idx):
    source_text=[self.source_vocab[word] for word in self.source_texts[idx]]
    target_summary=[self.target_vocab[word] for word in self.target_summaries[idx]]
    return torch.tensor(source_text), torch.tensor(target_summary)

In [32]:
train_dataset=CustomDataset(train_df['source_text'].tolist(),train_df['summary_text'].tolist(),source_vocab, target_vocab)
test_dataset=CustomDataset(test_df['source_text'].tolist(),test_df['summary_text'].tolist(),source_vocab,target_vocab)

In [33]:
def get_max_seqlen():
  max_length=0
  for index, row in train_df.iterrows():
    # Calculate the length of the current row
    row_length=len(row['source_text'])
    # Update the maximum length if the current row length is greater
    max_length=max(max_length,row_length)
  for index, row in test_df.iterrows():
    row_length=len(row['source_text'])
    # Update the maximum length if the current row length is greater
    max_length=max(max_length,row_length)

  print("Max length in dataset ", max_length)
  return max_length

In [34]:
def collate_fn(batch):
  sources, targets=zip(*batch)
  padded_sources=pad_sequence(sources, batch_first=True)
  padded_targets=pad_sequence(targets, batch_first=True)
  return padded_sources, padded_targets

In [91]:
class MultiHeadAttention(nn.Module):
  def __init__(self, embedding_dim, num_heads):
    super(MultiHeadAttention,self).__init__()
    assert embedding_dim%num_heads==0, "embedding_dim must be divisible by num_heads"
    self.embedding_dim=embedding_dim
    self.num_heads=num_heads
    self.dim_perhead=embedding_dim//num_heads
    self.W_q=nn.Linear(embedding_dim, embedding_dim)
    self.W_k=nn.Linear(embedding_dim, embedding_dim)
    self.W_v=nn.Linear(embedding_dim, embedding_dim)
    self.W_o=nn.Linear(embedding_dim, embedding_dim)
  def scaled_dot_product_attention(self,Q,K,V, mask=None):
    # Q,K,V Shape: [Batch Size X Num_Heads X Seq_len X Dim per head]
    K=K.transpose(-2,-1)
    attn_scores=torch.matmul(Q,K)/math.sqrt(self.dim_perhead)
    if mask is not None:
      attn_scores=attn_scores.masked_fill(mask==0, -1e9)
    attn_probs=torch.softmax(attn_scores, dim=-1)
    # attn_probs Shape:
    output=torch.matmul(attn_probs, V)
    return output
  def split_heads(self, X):
    batch_size, seq_length, d_model=X.size()
    X=X.view(batch_size, seq_length, self.num_heads, self.dim_perhead)

    X=X.transpose(1,2)
    return X

  def combine_heads(self, x):
    batch_size, _ , seq_length, dim_perhead=x.size()
    x=x.transpose(1,2).contiguous()
    x=x.view(batch_size, seq_length, self.embedding_dim)
    return x

  def forward(self, Q, K, V, mask=None):
    Q=self.split_heads(self.W_q(Q))
    K=self.split_heads(self.W_k(K))
    V=self.split_heads(self.W_v(V))

    attn_output=self.scaled_dot_product_attention(Q,K,V,mask)

    output=self.W_o(self.combine_heads(attn_output))
    return output

In [92]:
class PositionWiseFeedForward(nn.Module):
  def __init__(self, d_model, d_ff):
    super(PositionWiseFeedForward,self).__init__()
    self.fc1=nn.Linear(d_model,d_ff)
    self.fc2=nn.Linear(d_ff, d_model)
  def forward(self, x):
    return self.fc2(F.relu(self.fc1(x)))

class PositionalEncoding(nn.Module):
  def __init__(self, d_model, max_seq_length):
    super(PositionalEncoding,self).__init__()
    pe=torch.zeros(max_seq_length,d_model)
    position=torch.arange(0,max_seq_length,dtype=torch.float).unsqueeze(1)
    div_term=torch.exp(torch.arange(0,d_model,2).float()*-(math.log(10000.0)/d_model))
    pe[:,0::2]=torch.sin(position*div_term)
    pe[:,1::2]=torch.cos(position*div_term)
    self.register_buffer('pe',pe.unsqueeze(0))
  def forward(self,x):
    return x+self.pe[:,:x.size(1)]

In [93]:
class EncoderLayer(nn.Module):
  def __init__(self,d_model,num_heads, d_ff, dropout):
    super(EncoderLayer,self).__init__()
    self.self_attn=MultiHeadAttention(d_model,num_heads)
    self.feed_forward=PositionWiseFeedForward(d_model,d_ff)
    self.norm1=nn.LayerNorm(d_model)
    self.norm2=nn.LayerNorm(d_model)
    self.dropout=nn.Dropout(dropout)

  def forward(self,x,mask):
    attn_output=self.self_attn(x,x,x,mask)
    x=self.norm1(x+self.dropout(attn_output))
    ff_output=self.feed_forward(x)

    x=self.norm2(x+self.dropout(ff_output))
    return x


class DecoderLayer(nn.Module):
  def __init__(self,d_model, num_heads, d_ff, dropout):
    super(DecoderLayer,self).__init__()
    self.self_attn=MultiHeadAttention(d_model,num_heads)
    self.cross_attn=MultiHeadAttention(d_model, num_heads)
    self.feed_forward=PositionWiseFeedForward(d_model,d_ff)
    self.norm1=nn.LayerNorm(d_model)
    self.norm2=nn.LayerNorm(d_model)
    self.norm3=nn.LayerNorm(d_model)
    self.dropout=nn.Dropout(dropout)

  def forward(self,x,enc_output, src_mask, tgt_mask):
    attn_output=self.self_attn(x,x,x,tgt_mask)
    x=self.norm1(x+self.dropout(attn_output))
    attn_output=self.cross_attn(x,enc_output,enc_output,src_mask)
    x=self.norm2(x+self.dropout(attn_output))
    ff_output=self.feed_forward(x)
    x=self.norm3(x+self.dropout(ff_output))
    return x

In [105]:
class Transformer(nn.Module):
  def __init__(self,src_vocab_size,tgt_vocab_size,d_model,num_heads, num_layers, d_ff, max_seq_length,drop):
    super(Transformer,self).__init__()
    self.encoder_embeddings=nn.Embedding(src_vocab_size,d_model)
    self.decoder_embedding=nn.Embedding(tgt_vocab_size,d_model)
    self.positional_encoding=PositionalEncoding(d_model,max_seq_length)
    self.encoder_layers=nn.ModuleList([EncoderLayer(d_model,num_heads, d_ff, dropout) for _ in range(num_layers)])
    self.decoder_layers=nn.ModuleList([DecoderLayer(d_model,num_heads, d_ff, dropout) for _ in range(num_layers)])
    self.fc=nn.Linear(d_model,tgt_vocab_size)
    self.dropout=nn.Dropout(dropout)

  def generate_mask(self,src,tgt):
    src_mask=(src!=0).unsqueeze(1).unsqueeze(2)
    tgt_mask=(tgt!=0).unsqueeze(1).unsqueeze(3)
    seq_length=tgt.size(1)
    nopeak_mask=(1-torch.triu(torch.ones(1,seq_length,seq_length,device=device),diagonal=1)).bool()
    tgt_mas=tgt_mask&nopeak_mask
    return src_mask, tgt_mask

  def forward(self,src,tgt):
    src_mask,tgt_mask=self.generate_mask(src,tgt)
    src_embedded=self.dropout(self.positional_encoding(self.encoder_embeddings(src)))
    tgt_embedding=self.dropout(self.positional_encoding(self.decoder_embedding(tgt)))
    enc_output=src_embedded
    for enc_layer in self.encoder_layers:
      enc_ouput=enc_layer(enc_output,src_mask)
    dec_output=tgt_embedding
    for dec_layer in self.decoder_layers:
      dec_output=dec_layer(dec_output,enc_output,src_mask,tgt_mask)
    output=self.fc(dec_output)
    return output

In [106]:
src_vocab_size=len(source_vocab)
tgt_vocab_size=len(target_vocab)
d_model=512
num_heads=8
num_layers=6
d_ff=2048
max_seq_length=get_max_seqlen()
dropout=0.1
num_workers=2
num_epochs=10
model=Transformer(src_vocab_size,tgt_vocab_size,d_model,num_heads, num_layers, d_ff, max_seq_length, dropout)
print(model)

Max length in dataset  1982
Transformer(
  (encoder_embeddings): Embedding(27637, 512)
  (decoder_embedding): Embedding(27637, 512)
  (positional_encoding): PositionalEncoding()
  (encoder_layers): ModuleList(
    (0-5): 6 x EncoderLayer(
      (self_attn): MultiHeadAttention(
        (W_q): Linear(in_features=512, out_features=512, bias=True)
        (W_k): Linear(in_features=512, out_features=512, bias=True)
        (W_v): Linear(in_features=512, out_features=512, bias=True)
        (W_o): Linear(in_features=512, out_features=512, bias=True)
      )
      (feed_forward): PositionWiseFeedForward(
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
      )
      (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (decoder_layers): ModuleList(
    (0-5): 6 x DecoderLayer(
      (self_attn): MultiHeadAttention(
        (W_q): Linear(in_features=512, out_features=512, bias=True)
        (W_k): Linear(in_features=512, out_features=512, bias=True)
        (W_v): Linear(in_features=512, out_features=512, bias=True)
        (W_o): Linear(in_features=512, out_features=512, bias=True)
      )
      (cross_attn): MultiHeadAttention(
        (W_q): Linear(in_features=512, out_features=512, bias=True)
        (W_k): Linear(in_features=512, out_features=512, bias=True)
        (W_v): Linear(in_features=512, out_features=512, bias=True)
        (W_o): Linear(in_features=512, out_features=512, bias=True)
      )
      (feed_forward): PositionWiseFeedForward(
        (fc1): Linear(in_features=512, out_features=2048, bias=True)
        (fc2): Linear(in_features=2048, out_features=512, bias=True)
      )
      (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm3): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (fc): Linear(in_features=512, out_features=27637, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

Let's count the number of trainable parameters our Transformer has

In [107]:
trainable_params=sum(p.numel() for p in model.parameters() if p.requires_grad)
print(trainable_params)

86616565

Now we have the model, but we now need to define our loss function and the optimizer which will minimize the value of this loss function

In [108]:
criterion=nn.CrossEntropyLoss(ignore_index=0)
optimizer=optim.Adam(model.parameters(), lr=0.0001,
betas=(0.9,0.98),eps=1e-9)
scheduler=torch.optim.lr_scheduler.CosineAnnealingLR(optimizer,T_max=10,eta_min=0)

In [109]:
# Create Dataloaders
train_loader=DataLoader(train_dataset, batch_size=4,shuffle=True,collate_fn=collate_fn,num_workers=num_workers)
test_loader=DataLoader(test_dataset,batch_size=4,shuffle=False,collate_fn=collate_fn,num_workers=num_workers)

In [110]:
source_dummy,target_dummy=next(iter(train_loader))

In [111]:
print(source_dummy.shape,target_dummy.shape)

torch.Size([4, 258]) torch.Size([4, 140])

In [112]:
print(source_dummy[1])

tensor([    1, 14231,  6436, 11404, 19084,  6159, 18056, 26628, 19084,  6161,
          460, 10610, 19265,  1937,   504, 19195,  9184, 19123, 14231,  6436,
        21530, 26478,  3466, 21535, 17171,  7790, 11719,   757, 23773,  6159,
        27327, 11415, 12648, 19782, 25841, 14231,  6436, 25335, 23203, 26071,
        18611,   558, 12918, 26717, 21859, 19216, 11188,  4141, 14486, 15094,
        18056, 13657, 24344, 17935, 19265,  7693,  5008,  6641, 13916, 16927,
        18056,  5522,   442,  2854, 14348, 16205,  3466, 25025,  2102, 16644,
         1937,   504, 19195,  6159, 15024,  3787,  2437, 19084,   539, 16205,
         3466, 21344, 10512,  5216,  5674,  2448, 27338, 24432,  8727, 19088,
        14484, 22158, 15785,  2514,  4889, 27051, 12918,  6159, 14203, 21344,
        16221, 17935, 19265,  5885,  1666,  8728,  8623, 14608,  8543, 16205,
         3466,   290, 17083,  8801, 25219, 12768, 15093, 14231,  6391, 14025,
         4092, 13467, 15401, 15668, 25154, 25639,   558, 18164, 26607, 19854,
        17245, 16205, 13467, 26528, 15902, 21257, 21814, 17825, 11631, 14881,
         9940,  5144, 26148,  1242, 25223,  1456, 13793, 13793, 21530, 14231,
         6391, 26604,  5522, 14186, 25098, 25098, 21530, 14231,  6436, 27338,
        15393, 11395, 24485, 22881,  5703, 13996, 18791,  8396, 16205, 13467,
        25154,  4759, 13793, 14025, 25061,  2549,  5142, 14025, 15645, 11730,
        23515,  3561,   539, 16654, 10121,  7822, 27046,  8615, 11268, 15268,
        14237,  6414, 21530, 16829,  4358, 19596, 13793, 23013, 21814, 17808,
        23007, 26945, 25098, 23083,  2102, 26953, 11710, 23975, 16205, 13467,
        21344, 26091, 10121,  7822, 27046, 24969, 15268, 27338, 16221, 25983,
        17367, 19939,  8625,  3223, 13793, 23935, 26604, 17825, 27338, 15393,
        14194, 25098,  1758,  7279, 14564,  9634, 18999, 17779,  7824, 14237,
         6414,  6426, 14054,  5144, 23428, 24797, 18423, 18724, 10395,  6264,
        10512, 10426, 23645, 24789,  4766, 10121,  7822,     0])

In [113]:
print(torch.min(target_dummy),torch.max(target_dummy))

tensor(0) tensor(27479)

In [114]:
model.to(device)
source_dummy=source_dummy.to(device)
target_dummy=target_dummy.to(device)
print()

In [115]:
y_pred=model(source_dummy, target_dummy)
print(y_pred.shape,target_dummy.shape)

torch.Size([4, 140, 27637]) torch.Size([4, 140])

In [116]:
y_pred=y_pred.reshape(-1,len(target_vocab))
target_dummy=target_dummy.reshape(-1)
print(y_pred.shape,target_dummy.shape)

torch.Size([560, 27637]) torch.Size([560])

In [119]:
def train_loop(model,dataloader,loss_fun,optimizer,device):
  model.train()
  model.to(device)
  min_loss=None
  for epoch in range(num_epochs):
    losses=[]
    accuracies=[]
    loop=tqdm(enumerate(dataloader),total=len(dataloader),leave=True)
    for batch,(x,y) in loop:
      x=x.to(device)
      y=y.to(device)
      y_pred=model(x,y)
      loss=loss_fun(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
      losses.append(loss.detach().item())
      accuracy=check_accuracy(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
      accuracies.append(accuracy.detach().item())
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      scheduler.step()
      loop.set_description(f"Epoch [{epoch}/{num_epochs}]")
      loop.set_postfx(loss=loss.detach().item(),accuracy=accuracy.detach().item())
  moving_loss=sum(losses)/len(losses)
  moving_accuracy=sum(accuracies)/len(accuracies)
  checkpoint={'state_dict':model.state_dict(),'optimizer':optimizer.state_dict()}
  if min_loss==None:
    min_loss=moving_loss
    save_checkpoint(checkpoint)
  elif moving_loss<min_loss:
    min_loss=moving_loss
    save_checkpoint(checkpoint)
  print(f"Epoch {0} Loss{1}, Training Accuracy={2}".format(epoch,moving_loss, moving_accuracy))

In [121]:
def train_loop(model,dataloader,loss_fun,optimizer,device):
    model.train()
    model.to(device)
    min_loss = None
    for epoch in range(num_epochs):
        losses = []
        accuracies = []
        loop = tqdm(enumerate(dataloader), total=len(dataloader), leave=True)
        for batch,(x,y) in loop:
            # put on cuda
            x = x.to(device)
            y = y.to(device)

            # forward pass
            y_pred = model(x,y)

            # calculate loss & accuracy
            loss = loss_fun(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
            losses.append(loss.detach().item())

            accuracy = check_accuracy(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
            accuracies.append(accuracy.detach().item())

            # zero out prior gradients
            optimizer.zero_grad()

            # backprop
            loss.backward()

            # update weights
            optimizer.step()
            scheduler.step()

            # Update TQDM progress bar
            loop.set_description(f"Epoch [{epoch}/{num_epochs}] ")
            loop.set_postfix(loss=loss.detach().item(), accuracy=accuracy.detach().item())

        moving_loss = sum(losses) / len(losses)
        moving_accuracy = sum(accuracies) / len(accuracies)
        checkpoint = {'state_dict': model.state_dict(), 'optimizer': optimizer.state_dict()}
        # Save check point
        if min_loss == None:
            min_loss = moving_loss
            save_checkpoint(checkpoint)
        elif moving_loss < min_loss:
            min_loss = moving_loss
            save_checkpoint(checkpoint)
        print('Epoch {0} : Loss = {1} , Training Accuracy={2}'.format(epoch, moving_loss, moving_accuracy))

In [122]:
train_loop(model,train_loader,criterion,optimizer,device)

Epoch [0/10] : 100%|██████████| 445/445 [00:54<00:00,  8.18it/s, accuracy=47.2, loss=4.36]

Saving weights
Epoch 0 : Loss = 6.800713614131627 , Training Accuracy=23.92488934977001

Epoch [1/10] : 100%|██████████| 445/445 [00:53<00:00,  8.34it/s, accuracy=53.7, loss=3.11]

Saving weights
Epoch 1 : Loss = 3.758389205611154 , Training Accuracy=46.42243364741293

Epoch [2/10] : 100%|██████████| 445/445 [00:54<00:00,  8.10it/s, accuracy=45.5, loss=2.09]

Saving weights
Epoch 2 : Loss = 2.6266980854313027 , Training Accuracy=52.69144109661659

Epoch [3/10] : 100%|██████████| 445/445 [00:52<00:00,  8.55it/s, accuracy=77, loss=1.06]

Saving weights
Epoch 3 : Loss = 1.9957751365190142 , Training Accuracy=56.62758212143116

Epoch [4/10] : 100%|██████████| 445/445 [00:53<00:00,  8.39it/s, accuracy=79.4, loss=1.65]

Saving weights
Epoch 4 : Loss = 1.5867260103815057 , Training Accuracy=59.42858147781887

Epoch [5/10] : 100%|██████████| 445/445 [00:52<00:00,  8.46it/s, accuracy=50.2, loss=1.44]

Saving weights
Epoch 5 : Loss = 1.2906435876749875 , Training Accuracy=60.69630131239302

Epoch [6/10] : 100%|██████████| 445/445 [00:52<00:00,  8.51it/s, accuracy=73.5, loss=1.22]

Saving weights
Epoch 6 : Loss = 1.0676216000251555 , Training Accuracy=62.181980223066354

Epoch [7/10] : 100%|██████████| 445/445 [00:52<00:00,  8.52it/s, accuracy=71.9, loss=0.533]

Saving weights
Epoch 7 : Loss = 0.8927374453357096 , Training Accuracy=64.07732491653957

Epoch [8/10] : 100%|██████████| 445/445 [00:52<00:00,  8.53it/s, accuracy=46.4, loss=0.99]

Saving weights
Epoch 8 : Loss = 0.7516126555673192 , Training Accuracy=64.81063347720028

Epoch [9/10] : 100%|██████████| 445/445 [00:52<00:00,  8.45it/s, accuracy=54.1, loss=0.581]

Saving weights
Epoch 9 : Loss = 0.6372168241257078 , Training Accuracy=64.89657115721971

In [133]:
def test_loop(model,dataloader,loss_fun,device):
  model.eval()
  model.to(device)
  losses=[]
  samples,correct=0,0
  loop=tqdm(enumerate(dataloader),total=len(dataloader),leave=True)
  with torch.no_grad():
    for batch,(x,y) in loop:
      x=x.to(device)
      y=y.to(device)
      y_pred=model(x,y)
      print(x,y_pred,y)
      loss=loss_fun(y_pred.reshape(-1,len(target_vocab)),y.reshape(-1))
      losses.append(loss.detach().item())
      _,predpos=y_pred.reshape(-1,len(target_vocab)).max(1)
      samples+=len(y.reshape(-1))
      correct+=(predpos==y.reshape(-1)).sum().item()
      loop.set_postfix(loss=loss.item())
  print("Final Test Accuracy = ", 100*(correct/samples))

In [134]:
test_loop(model,test_loader,criterion,device)

  2%|▏         | 2/112 [00:00<00:14,  7.78it/s, loss=1.01]

tensor([[    1, 15621,  3436,  ...,     0,     0,     0],
        [    1, 27552,   198,  ...,     0,     0,     0],
        [    1, 16165, 18521,  ...,  4030, 21804,     0],
        [    1,  3007,  1187,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.9640, 21.4622, -0.9225,  ..., -2.3160,  0.2236,  0.3772],
         [-4.6590, -2.3413, -2.6235,  ..., -4.9298, -1.5565, -1.0562],
         [-8.0121, -4.0993, -3.5968,  ..., -7.8422, -4.1278, -2.4483],
         ...,
         [-3.0725, -2.1076, -1.7783,  ..., -2.4492, -1.8272, -0.5855],
         [-3.1469, -1.9724, -1.7727,  ..., -2.5929, -1.8340, -0.6003],
         [-3.2629, -1.8329, -1.7591,  ..., -2.7617, -1.8584, -0.6016]],

        [[-2.7334, 22.2736, -0.5765,  ..., -1.9299,  0.4186,  0.3950],
         [-5.4921, -1.0500, -1.5822,  ..., -4.7833, -1.8943,  0.1513],
         [-5.0544, -0.0852, -1.1057,  ..., -5.0418, -1.8213, -0.6250],
         ...,
         [-2.7977, -1.9028, -1.6926,  ..., -2.3516, -1.4934, -1.0119],
         [-2.8025, -1.7700, -1.6860,  ..., -2.4104, -1.4566, -1.0032],
         [-2.7773, -1.5363, -1.6372,  ..., -2.4515, -1.3946, -0.9569]],

        [[-1.9094, 22.8320, -0.2511,  ..., -1.2601,  0.7710,  0.4591],
         [-5.1368, -3.0757, -2.4659,  ..., -4.8956, -2.7310, -1.8735],
         [-4.6954, -2.7056, -3.1753,  ..., -5.4602, -3.0647, -1.3386],
         ...,
         [-2.2480, -2.6976, -0.6603,  ..., -2.1353, -1.8711, -0.9061],
         [-8.7789, -5.0992, -3.7931,  ..., -8.2372, -4.8262, -1.9303],
         [-1.3994, -0.9518, -1.3541,  ..., -1.3856, -0.7154, -0.9550]],

        [[-1.9218, 22.3563, -0.2104,  ..., -1.1823,  0.6911,  1.0223],
         [-3.1852, -0.8072, -1.3597,  ..., -2.8841, -0.4574, -1.1304],
         [-3.1507, -3.1805, -0.8545,  ..., -2.7591, -1.4140, -0.8712],
         ...,
         [-3.2336, -2.1540, -1.6621,  ..., -2.7481, -1.8258, -0.5608],
         [-3.2619, -2.0164, -1.6404,  ..., -2.8219, -1.7884, -0.5613],
         [-3.3371, -1.7973, -1.6014,  ..., -2.9535, -1.7710, -0.5465]]],
       device='cuda:0') tensor([[    1, 26161,  1932, 10232,  4359, 22899, 25314, 14290,  1031, 12590,
          1278, 15621,  2690,  4845, 17929,  2690,  2690, 15621, 23594, 20609,
         14795,  3789, 25314, 21365,  2690, 14795, 19136, 15621, 26161, 14029,
         12590,  4845, 19412, 10302,   130, 16221, 13918,  7096, 16603, 25122,
         16588,  1444,  2690,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 21269, 17117,  9260, 27552, 14283, 26161,  5569,  1537, 23624,
         21269, 10512, 21914, 13498, 19119, 25920,  5569, 11198, 27552,  1255,
         22513, 26161, 23857, 14496,  1926,   179, 26161,  5569,  5522,  6213,
          1934, 23624,  1576, 27544,  6660,  1926, 24432, 27552, 13998, 21344,
          7192,  1764, 23708,  3785,   914, 19533, 26986, 26161,  5569, 13319,
         21269,  4842, 16109, 17089,  6997, 27552, 14101, 27350, 15396, 14000,
         11768, 19814, 25025,  5569, 27552,  4384, 25265, 25593, 24703,  1926,
           179, 17205, 16626, 26161, 23857, 27552,  4199,  9184, 17084,  3207,
         15821, 16178, 26161,  7615,  6182, 22030, 27552, 26162,   219, 18581,
          6660,  1926, 12797,  3785, 23911, 27552, 27552, 14868,  9145,  1936,
         26161,  8966, 27338,    58, 21268,   525, 14484,  1278, 21269, 23440,
         10035,  9260, 10075, 16010,  2428, 27546, 27552, 25920,  9576, 13663,
         21344,  9260, 12613, 20227, 26161, 18930, 24887,  4038, 10210,  3785,
         11198, 26161,  5580,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 16165, 22496, 24364, 10456,  9973,  2436,  9984,  4030, 14036,
          9172, 18709, 16165,  2438,  4559, 19070,  4030, 14036, 25199, 19994,
          5036, 25290, 25076, 18483, 21344,  2245,  4158, 27338, 27115, 14036,
         21804,  8437,  1330,  9446, 23428, 21874, 16859, 14881,  4044, 15752,
         22008, 16852,  9973, 15561,  5049, 12125, 22893,  3563,  1330,  1089,
         21874,  5049,  7615, 12152,  4158, 19088, 18931, 27338, 23566, 18423,
         16010,  7711,  1330,  4030, 21804,  7615,  9984, 22654,  6288, 24322,
         27499, 27150,  9984, 23433, 14564, 17795, 22413,  9001,  4158, 21278,
         26258, 16752, 27338,  8437, 21323,  2374, 24990,  3563, 19377, 25015,
          1758, 10208,  6277, 18485, 25920, 16221,  5732,   558, 17828,  5940,
          2244, 19084, 14284,    78,  3563, 17471,  7759,  1330,  6277,  1330,
         16521, 20740, 19098, 27201,  3563, 10205,  4452, 22197,  2695,  4158,
           759, 25068, 10395,  8879,  4030, 14036, 20154, 25138,  1326, 18056,
         15270,  1128, 26818, 22473,  1758, 24364, 21344, 27150, 14874, 11608,
         11023, 24449, 16165, 14953, 14881, 27032, 14606,  7637, 10956,  1067,
          8613,  4750, 26818, 16165, 21530,  9973,  4892,  9293,  9634, 11514,
         21683,  9505, 21683, 10205, 20643, 14317,  9973,  6962,   759, 24824,
          5732, 11071,  8437, 24823, 21692, 10404,  5660,  4038, 11109,     0],
        [    1, 16626, 14115,  4049, 10303, 19048,  5678, 14352, 17936, 27294,
           168,   945,   372, 13947, 25211, 14813, 16626,  1936, 13988, 11286,
         20067, 23245,  6757, 12648, 19782,  1937,  8987,  2778, 17131, 13988,
          6078, 10061, 19048,  9266, 27294, 21827, 24482, 20734,  9179,  5678,
         14874, 20116,  3007,  1936, 13996,  1186,  5549,  5084, 16177, 11623,
          5915,  5492,  2856, 13988,   759, 14888,  6765,  4845,  6213,  1936,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1,    67, 18627,  ...,  8879,  8141,     0],
        [    1, 11186, 24435,  ...,     0,     0,     0],
        [    1, 27476,  8761,  ...,     0,     0,     0],
        [    1,  8385,  4226,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7823, 22.3833, -0.5537,  ..., -1.9315,  0.4523,  0.4594],
         [-4.6968,  0.6455, -1.0909,  ..., -4.0467, -1.2005, -0.8850],
         [-4.4203, -5.1682, -1.5754,  ..., -3.6221, -1.9700, -1.3706],
         ...,
         [-6.0957, -4.9704, -2.6717,  ..., -5.6772, -1.5277, -1.2596],
         [-8.1547, -5.0489, -3.9192,  ..., -8.3224, -2.8212, -2.3841],
         [-2.4810, -1.9230, -1.4382,  ..., -2.3957, -1.1070, -1.0138]],

        [[-2.1066, 22.4080, -0.2216,  ..., -1.4549,  0.4632,  0.5654],
         [-1.0435, -3.4786, -0.6988,  ..., -1.6515, -0.8644, -0.2843],
         [-3.8245, -0.2569, -2.1857,  ..., -4.3439, -2.3117, -1.0030],
         ...,
         [-2.4278, -1.8560, -1.5486,  ..., -2.4678, -1.1836, -1.0683],
         [-2.3890, -2.0378, -1.4266,  ..., -2.4360, -1.2065, -1.0275],
         [-2.2790, -2.1544, -1.3404,  ..., -2.3192, -1.1900, -0.9557]],

        [[-2.5347, 22.1131, -0.6085,  ..., -1.6670,  0.3902,  0.6062],
         [-8.7247, -2.8455, -4.7597,  ..., -8.3946, -4.5393, -1.8488],
         [-4.1203, -1.5645, -1.0707,  ..., -3.3966, -1.5971, -1.1884],
         ...,
         [-2.7515, -1.8464, -1.6345,  ..., -2.2983, -1.2663, -0.6553],
         [-2.8274, -2.1232, -1.5615,  ..., -2.3798, -1.3612, -0.6685],
         [-2.8294, -2.2800, -1.5106,  ..., -2.3762, -1.4215, -0.6520]],

        [[-3.9491, 21.7631, -1.2634,  ..., -3.1694, -0.2509,  0.0312],
         [-3.3550, -2.0909, -2.1874,  ..., -3.7309, -1.8429, -0.8283],
         [-5.3687, -1.6025, -2.4190,  ..., -4.8919, -1.7672, -1.3560],
         ...,
         [-3.9592, -1.7825, -2.2718,  ..., -3.6972, -1.7745, -1.0264],
         [-4.1309, -2.1173, -2.2552,  ..., -3.8689, -1.9085, -1.0472],
         [-4.1153, -2.2819, -2.2153,  ..., -3.8314, -1.9526, -1.0091]]],
       device='cuda:0') tensor([[    1, 23443, 21344,    67, 13498, 12918, 21533, 18611, 24041, 16205,
         11730, 17171, 27338,  4779, 26818,  9844,    17,    67, 16205,  2549,
         23203, 21344,  3844,  4306, 26919, 13663, 18724, 12918, 17171, 15024,
         12922,  3684, 15537, 24772, 21874,  5261, 16205,  2549, 13934, 27479,
          6443, 18447, 13181, 27064,  9634,  4216,  3844,  8816,  6600, 20188,
         24352,  4832, 21344,    67,  6765, 12918,  5490, 12702, 16205, 11730,
         21344,  2244,    67,  1666,  8461, 13988,  4046, 22096, 11570, 21835,
          6090,  6093, 21344, 25800, 16205, 11730, 22444,  5142, 10512, 27338,
           727,  4823, 26604, 12918, 16205, 13467, 21344, 19000, 26605, 26882,
         14348, 15434,   389, 15393, 13657, 27338,  1061,    67, 10711, 19072,
         14290,   715,  5080, 16205, 11730, 16626, 23385, 21344, 10395,  8879,
          8141, 25114, 14025, 24046, 20068, 14101, 14348, 26886, 21344,  5883,
         21229, 24411,    67,  6392, 19019, 15783, 23203, 22030, 16205,  2549,
         26440, 25076,  3844,  8111, 26669,  1768, 15645, 11730, 23385,    69,
         16205, 11730, 23713, 26448, 18149, 26448,     0],
        [    1, 11186, 25580, 11259,  5862, 27148,  2247, 13934, 23975, 15199,
          2438,  4559,  5260, 18481, 11186,   759, 18481, 10885,  1758, 18728,
          9844,  1758,  3690, 20744, 27136,  8111,  3654, 11186,  3654, 19043,
         27314,  5862, 10456,  9572, 24922, 20653, 21804, 14128, 27136,  1614,
         11186, 11630, 26170, 23975, 20701, 11259,  5862,  4422, 26776, 23253,
          8111, 19922, 22571, 16465,  9266, 11259,  5862,  7311, 11168, 13934,
         23975, 11186, 22709, 23387,  6373, 23991,  5754, 13528, 15139,  5471,
         21683, 24922, 24797, 25481,  3857,  5607,  8737,  5558, 18236, 11631,
         10205,  9844,  9605,  8437,  2896, 14951, 21683, 11186, 19923, 11186,
         12528, 24922, 16326, 23969,  6582,  6371, 13653,  2656,  7496, 21216,
         26368, 21023, 12000,  9266, 11186,  3545,  9326,   969, 21239, 21683,
         12461, 24938, 25481,  7618, 24922,  7400, 18904, 15448, 16894,  6307,
         23566,   818, 18475,  8111, 11186, 25025,  2102, 11765,   874, 21216,
         18481, 10609,  9973, 12797,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 18904, 22405, 16631, 25923,  8761, 25406, 21286, 18900, 14036,
         14027, 27476,  8750,  5862, 24797, 21135, 16924, 18904, 24512,  8761,
          6765,  1708,  9984,  4031, 22415, 26883, 13027, 24797, 18425,  8457,
         26526, 18551, 14451, 25313,  3375,  5811, 17660, 10395, 23977,  9843,
          8761,  3711,  5862, 21919,  9178, 26805,  2755, 15447, 12823,  1474,
         26463,  7406, 22200, 25923, 16796, 14036, 22405,  7400, 11428, 25923,
         11268,  3050, 10400,  7400, 23975,  5025, 22405,  8569,  4366, 13651,
          7256, 21490, 25313, 17131, 25229, 15447, 11538, 14958, 25923, 13027,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 16205, 23688, 21344, 26161, 10512, 24141, 16131,  5548, 27199,
          8385, 26716,  1897, 14301,  8385,  7916,  1293,  8683,  4226, 14323,
         14301, 16654, 22571, 16050,  6600, 26161, 16979, 25639,  9543, 21835,
         12958, 23688, 21344, 21344, 27381, 19452,  4226,  7916,  5548, 27611,
          3367, 21344, 14323,  1897, 27338, 14301,  3115, 24351, 18948,  8385,
         14716, 13295, 21344,  8385,  4624,  5015, 27338, 18989, 12249, 16924,
          1293,  8679,  5549,  6182,  8385, 18510, 27290, 25173, 14302,  1897,
         21344, 19849, 27499, 14301,  8047,  7760,  1293,  5319, 20271,  4226,
         26161, 17089, 21530, 21482, 15417,  8385,  4624,  5015, 21000,  8141,
         18989,   100,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')

  4%|▎         | 4/112 [00:00<00:10, 10.16it/s, loss=1.39]

tensor([[    1, 25639, 18901,  ...,     0,     0,     0],
        [    1, 26515, 21160,  ...,  8503, 24291,     0],
        [    1, 20925, 25639,  ...,     0,     0,     0],
        [    1, 23059, 11180,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1456, 22.6386, -0.4244,  ..., -1.4638,  0.5678,  0.7767],
         [-5.8600, -2.0244, -3.3632,  ..., -5.3517, -2.7237, -1.1551],
         [-4.4767, -0.9582, -2.3997,  ..., -4.1587, -1.5369, -1.4842],
         ...,
         [-1.3959, -0.5672, -1.2307,  ..., -1.0951, -0.6455, -0.7025],
         [-1.2330, -0.3832, -1.1101,  ..., -0.9779, -0.4912, -0.5687],
         [-1.1883, -0.4227, -1.1159,  ..., -1.0017, -0.3970, -0.4949]],

        [[-2.4575, 22.5686, -0.6201,  ..., -1.8031,  0.4739,  0.5110],
         [-7.9651, -1.7287, -4.1031,  ..., -7.3990, -3.9055, -2.3999],
         [-3.8599, -1.4827, -2.2035,  ..., -3.9757, -1.7746, -1.2933],
         ...,
         [-5.0981, -2.8737, -2.1590,  ..., -4.5997, -2.0820, -1.9298],
         [-7.8914, -3.1341, -3.9317,  ..., -7.4893, -3.9369, -2.3414],
         [-1.2516, -0.4088, -1.1843,  ..., -1.1317, -0.4451, -0.6040]],

        [[-2.6409, 21.9800, -0.7362,  ..., -1.8319,  0.3006,  0.4923],
         [-1.5312,  1.9928, -0.5870,  ..., -2.0455, -1.2263,  0.4436],
         [-1.6731, -0.1725,  0.2756,  ..., -1.7969, -0.9665, -0.6539],
         ...,
         [-3.1664, -1.7481, -1.8257,  ..., -2.5668, -1.7762, -0.9289],
         [-3.0620, -1.6259, -1.7150,  ..., -2.4915, -1.6433, -0.8007],
         [-3.0247, -1.7026, -1.7104,  ..., -2.5126, -1.5327, -0.7275]],

        [[-2.1717, 22.3046, -0.4949,  ..., -1.4929,  0.5519,  0.6644],
         [-6.6473, -2.8259, -3.8383,  ..., -6.2909, -2.7690, -2.9459],
         [-2.4565, -0.5821,  0.0819,  ..., -2.5195, -0.8585, -0.4950],
         ...,
         [-1.7533, -0.8575, -1.1762,  ..., -1.3908, -0.9421, -0.6267],
         [-1.5951, -0.6816, -1.0568,  ..., -1.2678, -0.7764, -0.5050],
         [-1.5945, -0.7449, -1.0882,  ..., -1.3394, -0.6905, -0.4357]]],
       device='cuda:0') tensor([[    1, 19115,  2219, 14586, 20906, 16311,    15, 18450, 18901, 22340,
         14542, 23945, 24747,  1666, 13657, 14606,  6878,  3118, 25032,  8872,
         11623, 21859, 22340, 14542, 10205, 14542, 24747, 24938,   290,  3118,
         19114, 19119, 11862, 24704, 18289, 24747, 16310, 23109, 16616, 19000,
         21874, 21540, 21344, 27314, 18901, 23340, 16311,  4585, 19113,  3573,
         24751, 12145,  6090,  7705, 15818, 24344, 18423, 25101, 19028, 26669,
         24747, 16654, 27479, 22340, 14881,  6163, 25101, 15044,  9626, 24840,
         26945,  8047, 24750, 23922,  3630,  2799, 25032,  2808,  9165, 11766,
         18673,  3572, 21344, 16205, 26684, 22325, 22453,  6129,  3572, 16311,
          8615, 14542,  6182, 16310, 22340, 27380,  2750,  4918,  1196, 19656,
          2219,   948, 14470, 26852, 26945,  8047, 16311,  2750,  7417,  5090,
          9227, 10711, 26286,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1,  6469, 27290, 18049, 23206, 21344, 16205, 22777, 11604,  1702,
         20112,   209,  4368, 22023,  3690, 19031, 12471, 20734, 23053, 27483,
         21044,  4199,  8552,  4207, 24040,   488, 22548, 13175, 10243, 11570,
         17083, 18115, 21835, 21335,  8054, 16205,  2673, 19570, 22548, 13175,
         14795, 18115, 21835,  1192,  9482,  4368, 22023,  3690,  6077,  1758,
         16205, 22777, 27040, 20676,  1017, 27290, 18049, 21835,   612, 22777,
         16894, 14795,  4771, 17278,  2063,  9581, 16474,  4199,  8552, 16205,
         26712,  6373, 17171, 25593, 14874, 20476, 16662, 25076,  4368, 22015,
          3951,  6090,  2673, 26515,   439, 13640, 16626, 27479, 11608,  3690,
         18156, 14086, 16924, 23890, 14874,  4044, 19155, 14237,  6414, 21344,
          2202,  2241,  9024, 17089,  5522, 20345, 14167,  3784,  1150, 12268,
         14071, 20327, 26935, 16205,  2673, 17083, 11162, 12073, 16462,  6469,
             0],
        [    1, 16924, 18056, 27290, 21100, 15731, 13934, 24840, 16050,  8437,
         18056,  8000, 24862, 16924, 18056, 27290, 12250, 15731, 11396,  9139,
         22513, 20001,  2200,  6600, 18056, 27290, 15021, 21844,  5272, 23915,
         27294,  1718, 13934, 19512, 19451,  8000, 21844, 19994, 14633, 15731,
          8047, 13934, 27479, 25639, 13157, 25122, 21100, 21827, 16048, 21160,
          6182, 17087,  9141, 22340,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1,  5998, 16293, 23059,   867, 24840,  3118,  1639, 14795, 22321,
         12191, 12668,  2800, 19070, 15331, 15060,  1572, 16794, 19000, 14857,
          2800, 19070, 12668,  1702, 23430, 20601,  5733,  2800, 19070, 17204,
          3118,  4824,  1639, 19070,  4781,  1628,  2720, 27290, 12560, 17171,
          2797, 15060,  1572, 21498,  2260,  9917, 10007, 15114, 10803, 10587,
         12907, 13347, 15707, 13760, 23401, 14136,  7291, 14182, 11900, 15331,
         16374, 14842, 25037,  7896, 15141, 13481, 17063,  5946, 17594, 18253,
         21120, 16293, 23059,  1078, 24309, 13175, 26096,    72,  1737, 27486,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0]], device='cuda:0')
tensor([[    1, 14542, 12845,  ...,  9895,  3179,     0],
        [    1,  4226,  5273,  ...,     0,     0,     0],
        [    1,   259,  9645,  ...,     0,     0,     0],
        [    1, 25488,  5492,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.7560, 22.9654, -0.1084,  ..., -0.9651,  0.7607,  0.7156],
         [-6.0663, -2.3018, -2.8020,  ..., -5.2815, -2.0740, -0.4614],
         [-4.3062, -3.2759, -2.8657,  ..., -4.2953, -2.3153, -1.5161],
         ...,
         [-3.8151, -2.5695, -2.2170,  ..., -4.2360, -2.0643, -1.1799],
         [-3.1978,  0.2624, -1.2488,  ..., -3.2612, -1.4475, -0.6935],
         [-1.3053, -0.3714, -1.1920,  ..., -0.9785, -0.4628, -0.5698]],

        [[-2.6369, 22.4523, -0.5835,  ..., -1.9171,  0.3616,  0.4367],
         [-5.4894, -1.5595, -2.3232,  ..., -5.2153, -1.5223, -0.9980],
         [-5.0902, -0.5139, -1.5476,  ..., -5.7875, -2.2866, -0.7693],
         ...,
         [-2.4420, -0.8439, -1.4661,  ..., -1.9906, -0.8945, -0.7548],
         [-2.5222, -0.7985, -1.5428,  ..., -2.0035, -0.9098, -0.6746],
         [-2.6060, -0.9501, -1.6695,  ..., -2.1290, -0.9973, -0.6362]],

        [[-2.3613, 22.3928, -0.3698,  ..., -1.5295,  0.6220,  0.6622],
         [-5.0339, -1.9396, -2.5189,  ..., -5.1579, -1.4405, -0.9854],
         [-6.1065, -3.1664, -2.0784,  ..., -5.3723, -3.7115, -1.2913],
         ...,
         [-2.8056, -0.6740, -1.2882,  ..., -1.9245, -1.0916, -0.2328],
         [-2.9010, -0.6485, -1.3715,  ..., -1.9676, -1.0967, -0.1381],
         [-2.9789, -0.7605, -1.5118,  ..., -2.0830, -1.1606, -0.0834]],

        [[-2.6200, 22.0927, -0.6396,  ..., -1.9504,  0.2633,  0.5460],
         [-6.6337, -1.2084, -3.4511,  ..., -6.3799, -3.6913, -1.9569],
         [-4.5574, -2.2640, -1.9938,  ..., -4.9391, -2.8432, -0.8287],
         ...,
         [-2.9938, -1.5393, -1.6445,  ..., -2.4712, -1.3492, -0.6684],
         [-3.0653, -1.5047, -1.7076,  ..., -2.4817, -1.3441, -0.5605],
         [-3.2395, -1.7271, -1.8882,  ..., -2.6998, -1.4628, -0.5363]]],
       device='cuda:0') tensor([[    1, 20458,  8453, 15030, 11519,  7751, 26971, 11110, 17634, 26258,
          6526, 26694, 23772, 13467,  6014, 10813, 20211, 16295, 26258, 10292,
         26619,  8290, 11496, 20985, 13578, 20824, 17937, 10630,  7335, 22180,
         19419, 11073, 20079,  5988, 25035, 26619, 18793, 12845,  6277, 26776,
         21827, 25481, 20823,  2495, 26935, 25718, 12845, 25238, 25593, 18588,
          3018, 10428, 21344, 15800, 14444,  2367, 10494, 10205,  1758,  9844,
         15800, 15089, 26258, 10292,   290, 18588, 12845, 20466, 24840, 18023,
         15089, 15030,  7458, 10397, 21700, 23400, 19714,  5166, 25481, 26776,
         18346, 18960,  1537, 10525,  9639, 25481, 27338, 21848,  2792, 18581,
          6443,  6596,  6285, 12845, 26776, 14795, 14308,    78, 22055, 12672,
         22536, 14542, 12845, 25405, 21827, 10885, 25387,  2019,  8453, 20456,
         15030, 13939,  9973,   290,  5340,  2169,  9639, 18904, 18482, 19829,
         18588,  1758, 21160, 18481,  8875, 21216,   290,     0],
        [    1, 17471, 12777,  9297,  1444, 23566, 11392, 18999, 27479,   770,
         26818, 17968, 21874,  9266, 19512,  6600,  1122, 19896,  7700, 17471,
         10721, 18318, 20331, 23760,  7699, 21344, 10721, 12334, 17437, 14857,
         24432, 10512,  7771, 12133,  5868,  5674, 12778, 18999, 27479,  4226,
          7700,  8602,  3025,  8918, 18869, 26919,  4226, 19681, 19782, 18075,
         18588,  9266, 11415, 16735, 27483, 17047,  4226,  7700, 10052, 23127,
         24736,  7230,  6392,   759, 22854, 21365, 17524, 17089, 18582, 12334,
         10721, 22720, 22024, 19303, 16221, 12105,  6600, 26156,  7634, 18003,
         17089, 12524, 14551, 26818, 19849, 14881, 22234, 15093, 22030, 19780,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 26161,   259, 13009,  9645, 10301, 25593, 16792, 10429, 10354,
          1705, 15584, 23702, 16082,  9735,  3831,  2560,   759, 19071, 10429,
         10355, 11561, 21827, 19183,  1705,  9266, 14874, 16792,  1017, 10429,
         10355,  3966, 24344, 18423, 13027, 17353,  9482,  8984,  4524, 17572,
          6090,  3739, 16448, 18708,   759,  1705,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 23308, 13898,  8764,  2690,  2448, 19990, 25488, 13558, 18056,
          3945,  1926, 21535,  9844, 19962,  7693,  5492, 23308, 13898, 25488,
          4457, 24938,  4750,   168, 16205, 15527, 10885, 12055, 24040,  5522,
          4750,  9742,  6159, 20440, 27338,  9724, 20584, 12063,  8357, 18894,
          1926, 10515, 23980, 15527, 25025, 20474,  5522, 20925,  1926,  2690,
         21253, 22030,  1396, 14142, 14636, 12648, 19780, 14604, 19219, 17171,
         22405,  7759,  6886, 26251, 21252, 20926,  9543,  9873,  9394,  5549,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 15922,  9987,  ...,     0,     0,     0],
        [    1, 19748,  9081,  ...,     0,     0,     0],
        [    1, 27315,  6846,  ...,     0,     0,     0],
        [    1, 16310, 14948,  ..., 24351,  6102,     0]], device='cuda:0') tensor([[[-2.3889e+00,  2.2034e+01, -5.1929e-01,  ..., -1.7676e+00,
           3.2084e-01,  4.7603e-01],
         [-3.7362e+00, -4.0397e+00, -1.8636e+00,  ..., -3.9141e+00,
          -2.3805e+00, -9.3791e-01],
         [-3.2746e+00, -1.2699e+00, -9.0020e-01,  ..., -2.6051e+00,
          -1.4678e+00,  1.7022e-02],
         ...,
         [-3.1766e+00, -1.9748e+00, -1.9090e+00,  ..., -2.9112e+00,
          -1.7113e+00, -8.5585e-01],
         [-3.1222e+00, -2.1535e+00, -1.9339e+00,  ..., -2.7842e+00,
          -1.7122e+00, -8.7592e-01],
         [-3.0181e+00, -2.2224e+00, -1.9133e+00,  ..., -2.6638e+00,
          -1.7044e+00, -9.0015e-01]],

        [[-2.6194e+00,  2.2297e+01, -4.6110e-01,  ..., -1.8448e+00,
           4.0010e-01,  6.2094e-01],
         [-2.9416e+00,  2.2283e+00, -1.2054e+00,  ..., -2.6144e+00,
          -1.1693e+00, -7.7899e-01],
         [-6.4008e+00, -3.2089e+00, -2.4567e+00,  ..., -6.2293e+00,
          -2.7763e+00, -2.7416e+00],
         ...,
         [-2.2953e+00, -1.4335e+00, -1.3548e+00,  ..., -1.9832e+00,
          -1.2118e+00, -6.6381e-01],
         [-2.2790e+00, -1.6785e+00, -1.3916e+00,  ..., -1.8991e+00,
          -1.2662e+00, -7.1733e-01],
         [-2.2106e+00, -1.7523e+00, -1.3926e+00,  ..., -1.7856e+00,
          -1.2633e+00, -7.4805e-01]],

        [[-2.3469e+00,  2.2278e+01, -5.2938e-01,  ..., -1.6631e+00,
           5.1336e-01,  7.2131e-01],
         [-2.0968e+00, -2.3722e+00, -1.6749e+00,  ..., -2.5320e+00,
          -1.3396e+00, -2.7307e-01],
         [-7.8945e+00, -1.4401e+00, -3.0973e+00,  ..., -7.2500e+00,
          -4.5754e+00, -2.0806e+00],
         ...,
         [-2.8603e+00, -1.6713e+00, -1.6957e+00,  ..., -2.5835e+00,
          -1.6337e+00, -5.4535e-01],
         [-2.8187e+00, -1.8842e+00, -1.7170e+00,  ..., -2.4767e+00,
          -1.6472e+00, -5.7393e-01],
         [-2.7096e+00, -1.9168e+00, -1.7002e+00,  ..., -2.3440e+00,
          -1.6288e+00, -5.9844e-01]],

        [[-1.8104e+00,  2.2797e+01, -1.4139e-01,  ..., -1.1949e+00,
           7.6501e-01,  6.3985e-01],
         [-3.0206e+00, -1.6921e+00, -8.5763e-01,  ..., -4.1976e+00,
          -1.9113e+00, -1.1241e+00],
         [ 2.7311e-01, -1.3576e-01,  1.0851e+00,  ...,  4.3711e-01,
           1.4868e-01,  1.1264e-01],
         ...,
         [-4.1031e+00, -3.7880e+00, -1.9098e+00,  ..., -4.1161e+00,
          -3.0228e+00, -1.8220e+00],
         [-4.3213e+00, -2.8098e+00, -2.7673e+00,  ..., -4.0431e+00,
          -2.4749e+00, -7.5983e-01],
         [-1.6393e+00, -1.7686e+00, -1.4518e+00,  ..., -1.5109e+00,
          -1.0273e+00, -1.0288e+00]]], device='cuda:0')

  5%|▌         | 6/112 [00:00<00:11,  9.22it/s, loss=0.863]

tensor([[    1, 12284, 15922,  9987, 15093,  3106,   168, 20470, 13027, 15731,
         15922, 23848, 12284, 12285, 15922,  9987, 15093,  8615, 10126,  8047,
           168, 15093,   914, 23438, 15388, 15922,  9987,  9854,   759, 20485,
         17171, 13498,  7846, 20822, 15922,  8172,  8625,  5218, 14669, 15093,
         17239, 12341, 18483,   168, 23438, 15388, 24969, 14881, 17171, 12126,
         15098, 16654, 26811, 15922, 16262, 10721, 14177, 12284, 25122, 18678,
         15922, 12284,  4850, 26919,  8397,  5548, 15922,  9987,  8615,  8653,
         10353, 16654, 27483,  5885, 12284, 22571,  2436,  9984,  6670,  9634,
         15922, 17227, 17077,  9984, 23848, 21344, 20470,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 14948, 22329, 24784, 17449, 16626, 27522, 11688, 23791,  3936,
           565,  3936,  1131, 23449, 25593,  6106, 13941, 21344,  9973, 14554,
         15499,  9913, 25920,  3936,  1131,  9973,  6163,   630, 16924, 17171,
         26161, 19628, 12702, 16005,  3936, 21344, 16633,  6986,  5056, 19757,
         26161, 19748, 23411,  3936, 21344, 24867, 19270,  9973,  9913, 25920,
          9993,  9081,  1123, 12797, 25593, 22300, 12702, 11688, 21490,  9973,
          6554,  3936, 20946,  9774, 21344, 27338, 25544, 25528, 22116, 22329,
          6119, 16438, 17171,  9774, 12977, 19867, 11585, 21344, 22299, 25062,
         18423, 17449, 23790, 12702,  8054, 19756,  8328,  3290, 21854, 18158,
          3936, 27040, 21827,   630, 20287,  6163, 14795, 17171, 11449, 11621,
          2438, 23426, 12797, 19939, 20944,  9024,  1356, 12226,  8921, 13165,
         16438, 12978,  3936, 21827,   630, 15173, 20287, 24884,  9293, 26886,
          9973,  6163,  7188, 26935, 16924, 17171,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 16205, 23958,   757, 18498, 10776,  9704, 21963,  9482, 16205,
          7667, 25364,  1132, 19245, 27204, 16205, 23958, 23147, 25593,  6106,
          5754,  8498, 14001,  9581, 27315,  4199,  8552, 16205,  7667, 16205,
          7667, 25364,  9704,  5176, 20271, 27315,  4677, 16205,  7667,   783,
         12525, 25699, 11381, 22320, 27315,  9183,  1559, 20211, 26900,  1538,
         18711, 16205, 23958, 14230, 24884, 19572,  6200,  4807,  9704, 15447,
           914, 19136,  8359,  9581,  9181, 17084, 21344, 16205,  7667, 13636,
         12164,   178,  8198, 14795,  4955, 22854,  8622, 12388, 20734,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  5263, 16577, 27347, 15997,  3545,  9266, 17353, 22340, 16311,
          6846, 15499, 17271,   647,  5522, 22762, 22780,  6846, 21535, 16310,
         17271, 18489, 24351, 14551, 22329, 10890, 13657, 25849, 16311,  6846,
          8536,  8646,  5263,  2448,  5263, 13155, 16311,  6846, 17353, 22340,
          8800, 11206, 22513,  5017, 17271, 25649, 18464, 23176,  1446, 17271,
         23734, 24944,  1674, 17353, 22340, 21530, 27148,  9293,  6759, 18326,
         16310,  9791, 26161, 21530, 16387, 18475,  1181, 17171, 12063,   309,
          5263, 13288, 20985,  3545,  1401, 10205, 19849, 18475, 16221, 21535,
          7439, 20315, 22340, 21535,  5263, 12063, 25025, 22340,  6846, 23428,
          5892, 21725, 24592, 10426,  6744, 22340, 16326, 22935, 10426,  4499,
         18397, 16315, 10426, 11570, 15800, 13657, 27149,  3410,  8438, 24351,
          3970,   874, 18914, 16310, 17275, 22597, 20207, 22340, 26186, 21859,
         18147, 23083, 15660,  5915, 15997, 24938,  2438,  1702,  5522, 18740,
         10205, 14290, 10945,  7803,  5313, 26713, 24731,  8461,  8447, 15602,
         15997, 23972, 21535,  4825,  6846,  3966, 16310,  6846,  1550,  1028,
         10515,  1866,  8853, 17171,  6745,  2436, 23645, 21581, 24938, 13960,
          5263, 17271, 17107,  3517, 26119, 18475, 27149, 19701, 14551,   125,
         23124,  6600, 25025,  3079, 22340, 19115,     0]], device='cuda:0')
tensor([[    1, 25538, 25556,  ..., 18620, 12567,     0],
        [    1,  5867,  6363,  ...,     0,     0,     0],
        [    1, 10303,  9184,  ...,     0,     0,     0],
        [    1, 13242,  7137,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.2409e+00,  2.2602e+01, -3.6003e-01,  ..., -1.5582e+00,
           4.9848e-01,  5.9681e-01],
         [-3.8840e+00, -1.7874e+00, -2.0753e+00,  ..., -4.8712e+00,
          -2.0226e+00, -1.8136e+00],
         [-1.7251e+00, -8.3683e-02, -4.3181e-01,  ..., -1.5190e+00,
          -2.6282e-02, -2.6938e-01],
         ...,
         [-3.6758e+00,  2.2509e+00, -1.7282e+00,  ..., -2.8934e+00,
          -2.2193e+00, -7.1575e-01],
         [-2.9337e-01,  1.0252e+00,  8.5840e-01,  ..., -2.3814e-01,
          -9.9630e-01,  6.1058e-03],
         [-1.1694e+00, -1.3624e-01, -1.1985e+00,  ..., -8.9113e-01,
          -8.0564e-01, -6.3122e-01]],

        [[-3.1501e+00,  2.1580e+01, -1.0308e+00,  ..., -2.7076e+00,
           1.4530e-01,  7.0565e-01],
         [-4.6319e+00,  3.0364e-01, -1.8564e+00,  ..., -4.2307e+00,
          -1.1751e+00, -5.6917e-01],
         [-3.8106e+00, -3.6592e+00, -1.2225e+00,  ..., -3.0227e+00,
          -1.5361e+00, -5.6679e-01],
         ...,
         [-1.8588e+00,  3.1036e-03, -1.1696e+00,  ..., -1.1137e+00,
          -1.1540e+00,  2.3744e-01],
         [-1.6652e+00,  3.2818e-01, -1.1215e+00,  ..., -9.6423e-01,
          -1.1229e+00,  3.0903e-01],
         [-1.6489e+00,  3.1552e-01, -1.1818e+00,  ..., -1.0322e+00,
          -1.1831e+00,  3.1735e-01]],

        [[-1.6051e+00,  2.2583e+01,  5.2288e-02,  ..., -8.3672e-01,
           8.6715e-01,  8.6497e-01],
         [-4.4553e+00,  8.7969e-03, -2.4023e+00,  ..., -3.4906e+00,
          -7.3943e-01, -1.7258e+00],
         [-1.1675e+00, -1.0458e+00, -7.6270e-01,  ..., -7.2028e-01,
          -4.3730e-01,  1.9066e-01],
         ...,
         [-5.4788e-01, -8.5852e-03, -5.5025e-01,  ...,  6.4222e-02,
          -2.9396e-01, -2.0372e-01],
         [-4.9309e-01,  2.3521e-01, -5.6982e-01,  ...,  8.2542e-02,
          -3.0414e-01, -1.5960e-01],
         [-5.1211e-01,  1.8531e-01, -6.3263e-01,  ...,  5.7379e-03,
          -3.8251e-01, -1.4562e-01]],

        [[-2.1350e+00,  2.2366e+01, -3.2987e-01,  ..., -1.4886e+00,
           5.0354e-01,  6.6017e-01],
         [-5.5321e+00, -8.5863e-01, -1.8823e+00,  ..., -4.9809e+00,
          -3.4355e+00, -6.3459e-01],
         [-7.4764e+00, -2.3170e+00, -4.4870e+00,  ..., -7.8402e+00,
          -4.2912e+00, -1.7630e+00],
         ...,
         [-1.4889e+00, -1.6796e-01, -7.3048e-01,  ..., -7.4141e-01,
          -9.5827e-01, -2.5192e-01],
         [-1.2745e+00,  1.2363e-01, -6.5777e-01,  ..., -5.8279e-01,
          -8.9795e-01, -1.6157e-01],
         [-1.1845e+00,  1.1146e-01, -6.5954e-01,  ..., -5.7517e-01,
          -9.2391e-01, -1.4022e-01]]], device='cuda:0') tensor([[    1,   353,  8385, 25538, 27338,  5303,   744,  2690,  8400,  3268,
           168, 19939, 12081, 23793,  5549, 23440, 18449, 17296,  5734, 12524,
         16221, 17256, 25538,  7693, 20961,  7776,  1258,   882, 20925,  5549,
          5883,   171,  6297,  2690,  9266, 16050, 27479, 25538, 10698,  7230,
         17437, 22030, 10715, 18068, 27479,  1674,  5307, 27338, 20925, 14177,
          2690,  8400,   744,  2690,  8400, 24840, 27483, 10724,  7693,  5717,
         25538,  7424,  7700, 12146, 11736, 25538,  1432,  5049,  3226, 12081,
         23789, 12266, 21530, 25539, 15501, 27338, 10456, 16644,  8385,  7700,
         13498,  8777,  8385,  6200, 14887, 26986, 25538, 15602,  7693,  5724,
         18581,  5354,  8396,  6200, 14887, 19783, 18243,  5504,  8561,  8385,
           732, 25538, 27338,  8774,  3106, 15178,  7693,  2296, 25538,  3340,
          8385,  3268,  5549, 15179,  6159, 12225,  2690, 17571, 12055,  2457,
          2854, 26390, 12668,  2773, 15098,   759, 20331, 14874, 17010,   817,
         13183,  8385,  5506, 19169, 26293,  7615, 27483, 25538, 15501, 23858,
           747,  8358,  8508,  2690,  8400,   168, 18872,  1876,  2690,  8400,
         10084, 25538, 10698,  6159,  7311,  9139, 25538,  6161, 13917,  1270,
          7771, 19449,  1932, 20116, 21239,  1937,  3860,  5549,  6665, 19946,
         25158, 12341,  2814, 20735, 26530,  7311,  2690, 24840, 27483, 16626,
         15499, 23446,  8397, 25914, 10698, 19349,  6159, 25611, 10698,  7230,
         19118, 21535, 20791, 15967,  1450,  6846, 12055,  8397,  6469, 11392,
         12443,  8622, 27338,  5559, 20933,  2296,  9309, 25538, 10512, 27338,
         16616,  6373, 21530,  9001, 25539, 19168, 22383,   770, 23440, 25538,
          7700, 12126, 17600, 20116,  9172,  6200,  6182, 24346, 18624,  5567,
         10763, 18620, 12567,     0],
        [    1,  5867, 21344, 27115, 24364, 16841, 12649, 23967, 14606,  8816,
         13208,  5867, 23832,  5732,  4096,  8872, 19940, 21344, 24787,  4559,
         10494, 19375,  6841, 24364,  4562, 25025, 10426, 16902,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 24772, 15268, 18878, 17761,  5303,  4207, 25474,  9862, 24482,
          9724, 10247, 20277, 24344, 25122,  1028, 14348,  6839,  6505,   171,
          4207, 25474,  9862,  9522, 24938,  4285, 20277,  5522, 12765, 10247,
         11395, 19780,  4216,  6505,   171, 26170,  8998,  9862,   171, 11541,
         16010, 10246,  9774, 20277, 17761, 12648,  7618, 21517,   171, 15268,
         22030,   728, 17761, 20277, 21516,  2211,  4207,  5151, 10301, 17207,
         21973,   179, 17171, 17761, 10247, 17171, 10247, 20277, 12648,  7618,
          4216, 23831, 12229, 24482, 24482, 21229,  6759, 17761, 21511,  2211,
          4207,   179,  6577, 23428,  4216, 21517, 10842, 17107, 17929, 11395,
         19780, 12648,  7401,  9184, 10247,  4216,  9935,    82, 20877, 16010,
           482, 17761,  5313, 23147,  5051,   171, 11537, 16796, 24491,   733,
         12648, 19934, 27201,  6242, 12229, 24482, 10512, 25483,  8038, 21516,
          7615,   482, 16626,  4207, 25474,  9862, 17761, 20277,    58, 25076,
          9862, 27479, 10715,  9724, 12229,  3637,  9940, 24482, 12648, 24482,
          9724, 15268,  8038,  4216, 21511, 23428,  9862,  5522,  5530, 25173,
         25932,  5506,  8501, 12648,  8511, 14200, 27032, 12648, 24484, 17757,
         18989, 17761, 11539,  3789, 21517,  4216, 16391, 24352,   392, 24482,
           729, 17757, 10744, 20606,  2778, 19933, 16866, 19412,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 14290, 13939, 13242,  7137, 22524, 11900,  5900, 14795,  9157,
          1017,  9157,  6839,  7566,  2847,  1076,  5412, 14795, 16310, 16185,
          6474, 15937, 25620,  9157, 18056, 24622, 15589, 25138, 16310, 11622,
         17171, 27308, 18450, 21973, 13242,  7137,  9157,  1017,  3601,  9157,
          9072,  7612, 27479, 19168, 10205, 10703,  8794, 10205,  1778,  5900,
          8853, 16205, 27106,   759, 12797, 13242,  7137, 23897,  1903, 16626,
         17278, 26919, 11003, 16006, 21344, 27338, 19783,  1128,  9157, 16205,
         27106, 20329,  9774,  5900, 27054,  6082, 16448, 21535,  1401, 12798,
         14881,  9157, 17087,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  3290, 10232,  ...,     0,     0,     0],
        [    1, 10695,   529,  ...,     0,     0,     0],
        [    1, 10637,  1531,  ...,  4088,  1124,     0],
        [    1,  2669, 22633,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.4977, 22.2952, -0.5906,  ..., -1.8403,  0.3955,  0.5056],
         [-3.9744,  0.2179, -2.9260,  ..., -3.9630, -2.2412, -1.3400],
         [-6.2179, -3.5976, -3.4330,  ..., -5.8228, -3.2219, -1.6664],
         ...,
         [-2.8101, -1.8836, -1.9109,  ..., -2.4283, -1.4999, -1.1417],
         [-2.5711, -1.5702, -1.6745,  ..., -2.1558, -1.3583, -1.0156],
         [-2.3200, -1.3260, -1.4967,  ..., -1.9396, -1.1373, -0.8298]],

        [[-2.3116, 22.4172, -0.5390,  ..., -1.7060,  0.5016,  0.5942],
         [-3.9220, -4.7189, -1.1849,  ..., -3.9666, -2.2741, -0.9448],
         [-1.1439, -2.1457, -1.1604,  ..., -1.1579, -0.3168, -0.7246],
         ...,
         [-2.4620, -1.0693, -1.6768,  ..., -2.0149, -1.3254, -0.6919],
         [-2.2130, -0.7765, -1.4103,  ..., -1.7212, -1.1702, -0.5548],
         [-1.9882, -0.6247, -1.2307,  ..., -1.5304, -0.9814, -0.3933]],

        [[-2.7053, 22.1724, -0.5553,  ..., -2.0756,  0.3025,  0.5366],
         [-2.5915, -0.3924, -0.5005,  ..., -2.6026, -0.3023,  0.4751],
         [-2.6127, -0.5231, -0.2447,  ..., -2.3004, -1.6368,  1.1097],
         ...,
         [-1.9021, -2.0793, -0.0621,  ..., -2.2473, -1.6500, -0.1449],
         [-6.1395, -3.1767, -2.0607,  ..., -5.3879, -2.7583, -1.8821],
         [-1.9612, -0.8914, -1.2773,  ..., -1.7699, -1.0031, -0.9077]],

        [[-2.6874, 22.1424, -0.7098,  ..., -1.9297,  0.3176,  0.4485],
         [-5.1750, -2.1652, -3.5245,  ..., -4.5684, -2.0370, -0.9027],
         [-6.2020, -2.5446, -2.7456,  ..., -5.4087, -2.6780, -1.0995],
         ...,
         [-2.1103, -0.8888, -1.5136,  ..., -1.5244, -1.1203, -0.7962],
         [-1.8970, -0.6051, -1.2759,  ..., -1.2751, -0.9797, -0.6892],
         [-1.7200, -0.4157, -1.1356,  ..., -1.1366, -0.8144, -0.5396]]],
       device='cuda:0')

  7%|▋         | 8/112 [00:00<00:09, 10.44it/s, loss=0.882]

tensor([[    1,  4845, 22030,  9862,  4864,  1368, 26417, 13941,   353,  9862,
         21247, 22311, 16010, 16177,  9483,   981, 19284,  9260, 21344, 18999,
          4866,  9862, 21247, 16010, 13876,  6129,  5522, 21859, 24828, 18056,
         23919, 14701,  6952,  3860,  1368,  4845, 14795, 19933,  4866, 11736,
          6129, 23566, 19933,  1183, 11024, 22150, 21982, 12500,  9626,  4845,
         15847, 19349,   874, 16010, 22030,  1396,  5586,  1368, 20268, 14221,
         23062, 20557,  4199,  8552, 18194, 14750, 11024,  5885, 14888, 20735,
         26161,  1616,  2438, 24035,  1368,  3290, 15213,  1617,  3290, 19123,
         10711, 13007, 11024,   525, 17929,  2690, 26417,  1368, 20268,  6952,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 13108, 10695,   525, 16177,  1508, 14803,  2497,  4366, 10695,
         24433,  2669,  8872, 21460,  1137, 24346,  8457, 13934, 16048,  2866,
         23541,  3207, 21344, 27338, 11003, 14186,  6037, 12668, 10395, 19003,
         20877, 27479, 17131, 27138, 23147,  9293, 16050, 23318,   949,  9482,
         16177,  4158, 13295, 18485,  6447,  8391, 24666, 15858,  6102, 25249,
         22932,  6082,  3190, 11570, 27338,  6364,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 10189, 10637,  5729,  3912,  2436,  3187,  3314, 11721, 19570,
         19864, 25564, 22340, 26604, 10189, 10637, 20877, 14071,  3912,  2436,
          3187, 18999,  2436,  3187, 11721, 14071, 24938, 23981, 22160, 21422,
          5855, 24797, 22007, 16796,  3912, 26368, 22340,   759, 21344,  9024,
         11721, 19357, 21868,   490,  9030, 27376,  3138, 21344,  2436,  3187,
          2213, 14317,  4207, 19783, 17757, 24475,  5256, 13175, 15319,  6461,
          4656,  7439, 10637,  7612,  8794, 18162,  5257, 23340, 16385, 19275,
          2436,  3187, 21344, 24010,  3314, 24322, 14317, 14891, 11721,  4658,
         11816,  5522,  8038, 18484,  3314,  7155, 14407,  1047, 17450, 17054,
         12964, 23374, 13182, 11713, 16005,   759, 17171, 14177, 18673, 11721,
         13809, 23203, 26761, 14712, 21344, 22007, 23566, 27044, 17204,   298,
         13934, 11712,   759, 21874, 21260,  2385, 15319, 22647, 17054,     0],
        [    1,  2497,  5049,  2536, 14795,  2428, 20977, 21506, 14957,  6846,
         13380,  2963,  3517,  6539, 14606, 21344, 27380, 21505, 24666,  2497,
          4366, 13934, 25593, 10885, 27483, 21344, 21506,  9905,  2497, 23001,
         23119, 22055, 26886,  8872,  5731, 18093,  4559,  7612, 21804,  2497,
         14953, 23541,  3207, 12528, 26713, 21909, 21506,  5769, 10061, 15179,
         23391, 17469,  3545, 21490, 16669, 21344,  2963, 25025, 23972,  2428,
         26779,  8955, 17725, 24938,  8875,  8437, 24823,  5729, 16924, 19939,
         26886, 21490, 22348, 16221, 15393, 21530, 25593,  4562,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 23786, 12351,  ...,  5186,  3115,     0],
        [    1, 13307,  6392,  ...,     0,     0,     0],
        [    1, 25136,  2428,  ...,     0,     0,     0],
        [    1, 13793, 18339,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.2642, 22.5830, -0.4864,  ..., -1.5682,  0.4843,  0.1705],
         [-3.4688, -0.5532, -1.9852,  ..., -4.1719, -1.4805, -2.2091],
         [-7.1051, -3.7640, -3.1551,  ..., -6.5446, -3.1209, -3.7735],
         ...,
         [-3.3933, -2.2551, -1.6547,  ..., -4.1917, -1.5228, -1.6642],
         [-7.0474, -4.2885, -3.3104,  ..., -6.8338, -3.2189, -3.6037],
         [-1.9082, -1.3302, -1.4423,  ..., -1.8121, -0.9462, -0.9110]],

        [[-2.6715, 22.1383, -0.4957,  ..., -1.9975,  0.2395,  0.5147],
         [-1.1456,  1.2291,  0.1833,  ..., -1.0758, -0.7195,  0.3069],
         [-5.5847, -3.7129, -2.6303,  ..., -4.8010, -2.7881, -0.3399],
         ...,
         [-3.0236, -1.6231, -1.5185,  ..., -2.8136, -1.3792, -0.7565],
         [-2.9571, -1.7902, -1.6132,  ..., -2.8009, -1.3806, -0.7479],
         [-2.9249, -1.9037, -1.7408,  ..., -2.7947, -1.3608, -0.8048]],

        [[-2.6366, 21.7858, -0.7329,  ..., -2.0410,  0.0564,  0.5901],
         [-5.8097, -4.2068, -1.2327,  ..., -5.4322, -2.9871, -2.1506],
         [-5.7201, -2.9205, -2.4018,  ..., -5.3960, -2.4567, -1.3901],
         ...,
         [-3.5255, -1.7402, -1.5938,  ..., -3.2189, -1.9949, -0.2880],
         [-3.4596, -1.8971, -1.7064,  ..., -3.2228, -1.9994, -0.3067],
         [-3.4636, -2.0080, -1.8452,  ..., -3.2733, -1.9906, -0.3989]],

        [[-3.3168, 21.4877, -0.9581,  ..., -2.5449,  0.1547,  0.2347],
         [-4.4770, -0.1212, -2.5475,  ..., -4.4550, -2.4641, -0.7023],
         [-4.9971, -5.4861, -1.8449,  ..., -4.1000, -2.1303, -1.2746],
         ...,
         [-3.9141, -2.3048, -1.9380,  ..., -3.5289, -1.8924, -0.6890],
         [-3.9337, -2.5352, -2.0801,  ..., -3.6141, -1.9556, -0.7417],
         [-3.9170, -2.6503, -2.2225,  ..., -3.6323, -1.9585, -0.8459]]],
       device='cuda:0') tensor([[    1, 11395,  7744,  9869,  5523,  8111, 21344, 18056, 26935, 25932,
         10711, 20485, 25932, 26403,  4037, 25931, 25639, 21344, 16626, 24291,
          6292,  9007,  8111,  7510, 23428, 10577,  3382, 18661, 23787, 27338,
          8038, 10395, 11395,  7744, 12560, 19832,  4838, 21639, 16221,  7612,
          8437, 19018, 21630, 14200, 18162, 25932,  7744, 22935,  5522,  1413,
         21344, 11395,  7744, 15783, 13571, 11735, 21344, 27299, 21639, 19680,
          1535,  1410, 27529, 18056,  6863,  1242, 24546, 26919,  1775, 22571,
         24944, 14323, 10395, 25932,  6519,  1242, 20470, 21535, 11247, 20470,
          7404,  4207,  2296,  6071, 21344, 24546, 20828,  1242,  5522,  8610,
          2387,  4035, 10426, 25932, 18662, 16556, 22096,  7744, 21835, 24935,
          4704, 21344,  4457, 20470,  4216,  6863,  1242,  8879, 14323,  8035,
         18660, 23389, 21828,  7744, 11395, 23389, 21639, 27338, 14023, 10610,
         17804, 11395,  7744, 21344, 24938, 25931, 25223,  6136, 19409,   493,
         13939, 20470,   759, 22348, 27248, 14323, 15516,  8160, 11395,  7744,
             0],
        [    1, 11093, 21535, 13307,  2890, 16626, 11570, 27338,  6597, 14317,
         23472,  3924, 21865, 16177, 14795,  4457, 26715, 13657, 12648,  3008,
          4559, 13657, 13307, 26713, 10395, 21344, 11093,  1530, 15675,   759,
          4386,  1778,  2866, 15139, 16560, 22513, 16177,  3924, 17768,  8774,
         26717, 23472,  3924, 13307,   491,  5049, 18482, 11631, 24369, 15139,
         16560,  3008, 15675,  4759,  4541,  6468,  3924, 27338,  1801, 16177,
         13307, 26717,  1468, 20701, 16560,  9266, 24509, 18450, 23713,  2102,
         23221, 13307, 27338, 18877, 20327, 21701,  4030,  2169,  9816, 13799,
          9266, 24509,   244, 22513, 16177, 15671, 23967, 11091, 14795,  4457,
         16177, 14958,  4366,  1807, 16521, 15674, 18475, 14886, 18737,  2873,
         15630, 17399, 20032, 22159, 26344,   759,  8691, 12648,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 20211, 20256, 16177, 23008,  9554,   127,  3789, 18547, 18483,
         17077, 23278, 14795, 18999,  2433, 27479, 17131,  9554,  4199,  8552,
         15089,  1343, 21344, 19934,  2428, 23278, 25593, 18483,  5154, 17077,
         23278, 21874, 18999,  2433, 20211, 20256,  4031,  4559,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 13793, 21344, 18746,  1061, 13121,  1061, 25114, 21344, 16859,
          7071, 13121, 18147,  1456, 18339, 21344, 24938, 13007, 20470, 19360,
         18343,  9444, 25114, 23971,   288,  3557, 17808, 12509,  4750, 24938,
         11565,  6102,  6765, 24938, 15024, 13121, 18056, 16205, 15530,   290,
         13793, 23203,  6443,  3557,  1061, 21925, 18746, 14891, 22008, 18581,
         21344,  5142, 17825, 23203, 21344,  5144,  4968, 12922, 15235, 18056,
         14636, 24485,  5315, 12073,  4457, 21859, 13793, 17825,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0]], device='cuda:0')
tensor([[    1,  3243, 17081,  9724, 16588, 18267,  3522,  3243, 17079,  5910,
          9724, 12675, 24575,  3522, 22441,  3135,  6182,  4285, 10298,  1708,
          8188,  5910,  9724, 24575,  3522,  1092, 25639, 26390, 12675, 26179,
         16521, 26170,  3243, 12675, 24579, 22887, 13663,  3243,  4831, 15660,
         23082, 11181, 17949,  3243, 13964, 19196, 22340, 18767,  3135,  5104,
          5910, 18056, 26716, 24344,   392, 17077, 16521,  3243, 25015,  9297,
         14367,  5909, 22441,  3135, 17181, 17077, 14351,  9266, 18056, 22441,
         14350,  9724,  3522, 12223,  3522, 15923, 16796, 10165, 16927, 18907,
         16927, 12668, 16927,  3243, 13437, 19297,  8715, 22024,  3135,  5910,
         18056,   757, 26183,  3243,  4831,  9626,  8879,  5328, 26818, 14891,
          3514, 17949, 21344,   948,  3365,  6846, 26251,   290, 22024,  3243,
         20658, 11581, 10205, 11392, 23127,   130, 19301, 12253, 17079,   288,
         17183,  4126, 16588,  3522,  3135, 24579,  1566,  5910,  3243, 26717,
         14881, 24062,  9266, 26811, 22024, 21344, 11900,  9462,   913, 13314,
         20525,  3243,  4831, 19552, 13963, 23967,  3243, 26817,  9307,  2514,
           290,  3243, 23774, 14865, 15093, 22147,  3135, 23848,  4881,  8160,
         15093, 20476, 21530,  3243, 14604,  1302, 15093, 22147, 13934, 27479,
         10885,  3135, 26179, 14177,  3243, 11631, 13943, 17077, 18162, 18056,
         13298,  3135,  1912,  5885, 15731,  3135, 23848,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1,   673, 13505, 17204, 26161, 23990,  2924, 19587,  1737, 23411,
           673, 13505, 17204,  8984, 23990,  2924, 22527, 22942, 19000, 18094,
         19814,  4092, 26411,  3738, 13505, 22522,   838,  2147,   156, 23787,
          9408, 21630,  6126,  2604,  4092,  6745, 13934, 27479,  1547, 21630,
          4207, 13505, 21344,  8533,  6556,  4092,  1353,   344, 15857, 20585,
         13657, 10426, 25143, 15508, 15997, 21344,  9266, 18092, 23990,  2924,
         26790, 15734, 26161,  8984, 22548, 17902, 15310, 19297, 10885, 24938,
          8172, 22707,  9154, 13021, 12968, 13934, 27479, 17301, 19187, 20444,
         16743,  1975, 12215, 23061, 24828,  4895, 26161, 25564, 26790,  3137,
         16456,  9505, 14036, 23203, 21344,  4761, 22340, 27338,   124, 15170,
          1582,  9973, 22340, 26790, 15731, 18056, 26161, 25579,  3884, 17576,
         25564, 23451,  9199,  5549, 25564, 20198,   488,  4895, 14795, 13021,
         12968, 26732, 14912, 22548, 17902, 21344, 16859,  2437,  1401, 18091,
         23990,  2924, 14566,  9612, 21016, 15734, 11570, 23335,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 11713, 19006, 23915,  9074,  8829, 25639, 11713, 19006,  9019,
          6182,   168,  9141, 17083,  6525, 19019, 15783, 16463, 11713, 19006,
         21100,  1028, 19780,  6182, 14177, 20925, 18999, 16048,  1674, 25639,
         11713, 19003,  9019, 16894, 20108, 19939, 13865, 20180,  9141,  5050,
         22718, 13939, 14874, 25639, 20169,  1101, 16829, 12838,  8626,  8829,
          1028, 10721,  6182,  6182, 25223, 19552, 16048, 11724, 15093,  4285,
          3909, 11736, 19939,  9141, 13865, 20180, 22352,  2436,  7458, 21365,
         13934, 19512, 18999, 27479, 23932, 22718,  5522, 21805,  2611, 26590,
         21365, 17047,  6182,  7460, 16506, 19512, 18104, 13865, 20180, 21344,
           770, 17083,  6525, 19019, 15783, 13865, 20180,  9141, 18581, 22718,
         15093, 19939, 24116, 16466, 10889, 12289, 15093, 15268, 25765, 20762,
         20172,  8837,  1758,  8047, 10889, 21344, 11713, 19006, 21100, 13027,
         16466, 20471, 20925,  9266, 16048, 27479,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 15783, 11481, 27552, 21364, 21268, 20378,  8086, 12341, 16528,
         20741, 21943, 10512,  9139, 26750,  7700, 15783, 10190, 10641, 25025,
         13682, 16650,  6837, 23440, 12798, 17117, 25935,  4792,  9479, 21364,
         16221, 17117, 10232, 27552,  5586,  1758, 24485,  6129,  7761, 25062,
          9260,  1444, 19349, 17579,  6182,  1042, 21943,  7693,   413,  3517,
         21364, 24223,  3958, 27546, 25920, 19113, 27552, 17437, 21890, 22899,
          6182, 14177,  2690, 19000, 25937,  9260,  3517,  1831,  1831, 19202,
         17841, 10964, 23440,  5315,  9260, 21108, 22325, 15563, 23440, 10035,
         10232, 10075, 26172, 21859, 23703, 11849, 13574, 24787,   947, 12007,
          7693,   413, 18949, 26552, 19453, 25025, 18955,  5025, 17089, 27199,
          6106, 23745, 20603, 16205, 10641, 26919, 13663, 17234, 16457,  4878,
         17824, 15093, 13437,  7066, 16205, 12004,  4792, 19059,  4842, 27552,
          1807, 10957, 21344, 23713, 10512, 16522, 10205, 17117, 24789, 21108,
         27546,  2169, 23440, 17576,  4845, 16326, 19064, 21344, 25008, 10512,
         12343, 23440,  4842, 20643, 17564, 17795, 12343, 26919, 26750, 26183,
          1758, 24485,  6129,  9265, 14317, 27552, 24526,  1152, 13726, 22055,
          9265, 15872,  9479, 14524, 16458,  3402, 21344, 15024, 13916, 21269,
          4842, 17808,  8086, 21844, 26170,  4904, 26865, 17098,  4842,  1690,
         24485, 16205, 10641,   759, 18783,  4658, 26795, 18949, 19453, 19188,
          7313,  7693, 10721, 27199,  6169,  1422, 27552,  1444, 27046,  2555,
         22718,  7693, 10721, 19939, 16050, 24449, 22496,  7311, 10084, 12560,
         26170, 10084, 19499, 12166, 18056, 14453, 16205, 10641, 25025, 13682,
         16521, 22496, 12249, 10084, 12166, 23769, 12560,  9455, 11172, 10721,
          9141, 21268, 16522,  9452,  2387, 12572,  7767, 14177,  5467,  5569,
         24291,     0]], device='cuda:0') tensor([[[-3.2272e+00,  2.1627e+01, -8.8866e-01,  ..., -2.6005e+00,
           1.1275e-02,  3.3985e-01],
         [-3.9696e+00, -1.8795e+00, -1.8619e+00,  ..., -3.3480e+00,
          -2.2053e+00, -4.3582e-01],
         [-3.3191e+00, -3.7819e+00, -8.0228e-01,  ..., -3.5240e+00,
          -1.9824e+00, -1.2143e+00],
         ...,
         [-3.1874e+00, -2.1222e+00, -1.9173e+00,  ..., -2.7637e+00,
          -1.6345e+00, -7.4867e-01],
         [-3.0564e+00, -1.8852e+00, -1.7375e+00,  ..., -2.5537e+00,
          -1.6178e+00, -7.7296e-01],
         [-2.9094e+00, -1.6661e+00, -1.5359e+00,  ..., -2.3734e+00,
          -1.5133e+00, -6.8937e-01]],

        [[-2.7542e+00,  2.2072e+01, -6.8407e-01,  ..., -2.0489e+00,
           3.2264e-01,  4.5425e-01],
         [-4.7188e+00, -2.3285e+00, -1.5645e+00,  ..., -4.3208e+00,
          -1.5877e+00, -8.6137e-02],
         [-3.7520e+00, -4.2658e+00, -1.0002e+00,  ..., -3.7565e+00,
          -1.6714e+00, -4.8239e-01],
         ...,
         [-3.6204e+00, -2.1163e+00, -2.2563e+00,  ..., -3.1721e+00,
          -1.8962e+00, -8.2416e-01],
         [-3.4826e+00, -1.8842e+00, -2.0743e+00,  ..., -2.9828e+00,
          -1.8774e+00, -8.5324e-01],
         [-3.2939e+00, -1.6124e+00, -1.8379e+00,  ..., -2.7519e+00,
          -1.7638e+00, -7.3418e-01]],

        [[-2.5165e+00,  2.2022e+01, -4.7455e-01,  ..., -1.6081e+00,
           3.0958e-01,  9.5625e-01],
         [-2.6942e+00,  1.5816e-01, -8.0881e-01,  ..., -2.0319e+00,
          -1.5864e+00,  1.5467e-01],
         [-3.9631e+00, -2.2864e+00, -1.9349e+00,  ..., -3.9185e+00,
          -8.8356e-01, -4.6639e-01],
         ...,
         [-2.5395e+00, -1.7417e+00, -1.5775e+00,  ..., -1.8194e+00,
          -1.2598e+00, -5.4453e-01],
         [-2.3279e+00, -1.4906e+00, -1.3638e+00,  ..., -1.5472e+00,
          -1.2066e+00, -5.2256e-01],
         [-2.0103e+00, -1.1224e+00, -1.0904e+00,  ..., -1.2018e+00,

 11%|█         | 12/112 [00:01<00:07, 13.11it/s, loss=1.05]

tensor([[[-2.5261, 22.0494, -0.4780,  ..., -1.6900,  0.4808,  0.6513],
         [-6.5299, -1.5449, -3.0568,  ..., -6.3269, -3.4033, -1.5573],
         [-6.4400, -4.1795, -2.2527,  ..., -6.5343, -2.9936, -1.9045],
         ...,
         [-2.7441, -1.9470, -2.1382,  ..., -2.4736, -1.7571, -0.9434],
         [-3.0684, -1.9390, -2.1322,  ..., -2.7512, -1.8593, -0.9297],
         [-3.1434, -1.7254, -2.0435,  ..., -2.7971, -1.7790, -0.8079]],

        [[-2.2486, 22.0537, -0.5036,  ..., -1.5802,  0.4943,  0.5540],
         [-4.7445, -1.7436, -2.1937,  ..., -5.0591, -2.2153, -0.2589],
         [-4.0040, -1.1793, -2.3064,  ..., -4.0108, -3.7093, -1.2832],
         ...,
         [-2.1906, -1.5689, -1.7837,  ..., -1.9699, -1.4794, -1.0545],
         [-2.4637, -1.5534, -1.7694,  ..., -2.1950, -1.5879, -1.0368],
         [-2.6225, -1.4681, -1.7272,  ..., -2.3344, -1.5802, -0.9428]],

        [[-3.7656, 21.4733, -1.1975,  ..., -3.1376, -0.2417,  0.1601],
         [-6.5635, -1.8552, -2.9255,  ..., -6.6225, -3.8222, -1.5740],
         [-5.4931, -3.1269, -3.6270,  ..., -6.2734, -3.4373, -1.3613],
         ...,
         [-3.4964, -2.0973, -2.5669,  ..., -3.5081, -1.9891, -1.4128],
         [-3.8132, -2.1096, -2.5577,  ..., -3.7797, -2.1136, -1.4054],
         [-3.8973, -1.8974, -2.4658,  ..., -3.8327, -2.0557, -1.2769]],

        [[-1.8572, 22.6389, -0.3180,  ..., -1.2550,  0.4970,  0.5440],
         [-2.3276, -0.1210, -1.5607,  ..., -2.5079, -0.7309, -0.2800],
         [-7.0134, -4.6210, -2.8196,  ..., -6.5372, -3.7269, -1.7084],
         ...,
         [-3.4419,  0.8740, -0.5852,  ..., -2.1655, -0.3651,  0.5951],
         [-4.3418, -0.6141, -2.4812,  ..., -4.3345, -2.0474, -0.1840],
         [-2.0596, -0.7970, -1.5614,  ..., -2.1291, -1.3934, -0.9707]]],
       device='cuda:0') tensor([[    1, 23760, 21365, 17449, 26947,  8396, 11287, 20382,  2821, 19143,
           770,  9260, 26750, 14636, 15068, 27479,  4003, 14615, 21655, 21344,
         10609, 27479,  9260, 20382, 21344, 17424, 12341,  8396, 27479, 23329,
         22742, 10721,  9533, 20169,  9260, 21344, 23760,  6392, 17449, 26947,
          8396, 10456, 18092, 15460, 19727, 14301, 20647, 13031,  3721, 16751,
         20382, 17581, 23358,  5304,  2690,  8400, 16588, 12229, 27479, 25122,
         21365, 17449, 26947,  8396, 20382,  5423, 15093, 21100,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1,  1330, 10945, 18767, 11570, 24912,  9024, 14545, 26945, 10913,
         19303, 10927,  4750, 20461, 22200, 25923,  2755, 26205,  6531,  9843,
         26945,  3171,   629, 25136, 26205, 16878,  9554,  8457, 26205, 14958,
         25923,  4096,  1495, 26205, 14128,  4366,  3375, 26205,  2536, 23008,
         26205,  3050, 11074, 16631, 26205,  4158,  1330, 26205, 26945, 10913,
         22200, 25923, 24918, 18481,  8984, 25923,  7406,  8457,  4158,  8761,
         25406, 16631, 16878,  9554,  2866, 10033, 15469,  5522,  8761, 25406,
          1758, 17131,  4559, 26945,  3167,  4750,  9639, 21135, 20461, 25136,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 11932, 22496, 22717, 23046, 22560,   209,  3557,  4845, 21344,
         14721,  8396, 14881, 14622, 23042,  3557,  2200, 13939, 16894, 24322,
         19294,  5320, 15024, 21854, 17297, 21344, 26179, 17801, 14721,  8396,
          3557, 16859, 23931, 14881, 14622, 23042,  3190, 22560, 24433, 21344,
         14881, 14622, 23042, 26867, 26179,  5522,  7348, 21732, 27338,  8062,
         20504,  6071, 16588, 22560, 15537, 15024, 13311, 14850, 15594, 16588,
         22023,  9265,  2200,  2625,   130, 14721,  8396, 22558, 19275,   244,
          5251,  3557,  3315,  1913,  2459, 23046,  9395, 22560,  6071,  7460,
         23443, 14721,  8396,  1021, 21717, 21608,  4845,  6443,  8938,     0,
             0,     0],
        [    1,  8111,  3656, 13040, 20989, 15857, 20609, 22571, 16465, 12461,
          8111,  1016, 23290, 15044,  9973, 12930, 21490, 14564,  9612,  1758,
          8111, 23290, 20989, 23387,  3656,    78, 13214, 27085,  7510, 14023,
          8111,  9172, 25593,  9984, 12930, 21697, 20989, 21344,  6879, 15398,
         15857,  8111, 13934, 25593,  9984, 22571, 16465, 25581, 25593,  9984,
          4559, 21364, 22159,  8111,  3656, 12065,  9139,  1661, 12672, 22571,
         16465, 14029,  8501, 24944,  9581,  8111, 22613, 13098, 10811, 25025,
          2102, 19628,  9293, 14442,  4241, 27338, 15233,  6099,  8437, 24823,
         11536, 20187, 23433, 18423, 25877,  8111,  3607, 20323, 14027,  9111,
         15997,     0]], device='cuda:0')
tensor([[    1,  2973,  3625,  5319,  4948, 24509, 26161, 20528, 22354,  5318,
          6677,  2969, 23515,  4541,  9634, 18056, 25593, 17815, 17745, 26974,
         26179, 23891, 16178,  4948,  5893, 26845,  3625,  7836, 18999, 20525,
         22354, 16026,  5313,  4948,  7836, 12108,  2969, 16626, 27522, 24509,
         20471,  9195, 19096, 16456,   113, 21660, 20647, 22340, 18056, 14059,
         26170, 21543, 19996,  7837, 20814,  5313, 19753,   193, 16179,  5893,
         25593,  6842, 21344, 13209, 27240,  6448, 15335, 20525, 24509, 16626,
         27522, 23440,  6469, 11188, 23440, 25932, 16626, 27522,   623, 21344,
         20525,  1042, 23515, 25173, 18056,  5318, 26975,  7839,  6677, 24824,
          9634, 18056,  8762, 13916, 26426, 21726, 26845, 23090,  3625, 15399,
         24081, 12107, 16522,  2969,   258, 19116,  7830, 22445, 19839,  7836,
          4904,   667, 25282, 22445, 12576,  6837,  4948,  2969,   258, 20509,
         26170, 16579, 16301, 18056, 23752, 23170,  5414, 12459,  5522, 26170,
          3625,  7761, 12153, 16796, 12750, 16256,  5313,   209, 18931, 23793,
         23936, 16796, 12750,  2969,  5313, 12652,  5522, 24040,  4513, 26173,
         17221, 20993,  1278, 16143, 26974, 16610, 21344, 20528,  9634, 26596,
           759, 22348,  5522, 10205,  2387,  5318,  5893, 24944, 25385,   770,
         25593, 17798, 17745, 18056, 18094,  2387, 17471, 20528, 21344,  5522,
          2971, 26172,   283, 22496, 16126,  9266, 24938, 20528, 22974, 23888,
          2969,  5313,  8633, 24512, 26172,  8737, 16123, 19999, 24527,  7612,
         27479, 24509, 15888, 15425, 13797,  8396,  6426, 27169,  3625, 19839,
          2969, 26816,  5313,  4948,  4067,     0],
        [    1, 26161,  3793, 25382,  8761,  1897, 25639,  5320, 16626, 25639,
          3794,  1939, 26183,   839, 25382, 25211,  8156, 22864, 20606, 23932,
          5848, 21835, 24679, 13241, 21344, 19232, 23990,  3794,  6759, 26161,
          5542,   838, 18246, 20472, 20287, 14762,  8038,   503,  9971,  4530,
         17107, 20371, 26691,  7790, 23990,  3794, 19232,  9971,  2448,  2170,
         13988, 16208, 13241, 21344, 14115, 27338,  1897, 19342, 25378, 25025,
         24944,  3118,  3794, 19567,  6759, 17524,   241, 22864, 20606, 26818,
         24931, 20191, 21239,   168,  3118, 21229, 22496,   727, 25382, 18056,
         23832, 25700, 12249, 20930, 19084,  9971, 17171, 24319, 26172, 26161,
         22503,  6105, 16709, 24938, 14689, 18483, 20330, 24301, 22707, 14762,
          3794,   759,  9755, 17077,  9724,  9494,  7439, 11691,   154, 13442,
         19407,  2389, 23203,  3118,  3793,  1458, 20485, 25639, 12341, 21344,
         10512, 25483,   696,  8971, 25639, 13927, 26311, 21344, 26818, 14264,
          1703, 15399, 25639,  9265, 15179,  6862,  9543,  4842, 27338,  3970,
         27115,  5288, 25639, 12341, 17171, 27314, 20588, 21344, 14639, 14200,
         19084,  9971, 27314,  3971, 26170, 18245, 25639,  9971, 12341, 25129,
          9812, 24938,  9543,  4842, 24344,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  7560, 14886, 23317,  1700,  9260,  2428, 25639,  5010, 14886,
         23317, 12668, 20139,  4783, 20476, 15268, 23831, 24348,  7615,  9184,
         24944, 20470, 21344,  3401, 12609,  9260, 10524, 25800, 23433,  7510,
          6787, 27290, 23317, 12668,  5444,  4490, 23203, 23317, 14888,  8856,
          7560,  2982,  5010, 27338,  4783, 15093, 23119, 11736, 16644, 21960,
         22153, 23317,   759, 14888, 21628,  9516, 18025, 17597,  9823, 21344,
         11392, 19134,  9260, 15687, 27261, 23317,   977,  7566, 11716, 19123,
         10711, 19957,  2284,  7791, 16050,   517, 19957,  2284,  3951, 21236,
         24348,  2428, 23317,  3545, 16859,  9265, 21874, 27338, 23952, 12223,
         13572,  4419, 13177, 13177, 19057,  8267, 12780,   914, 21874, 23317,
         24348, 24432, 27483, 22899, 24083, 10374,  1071,  3402, 14952, 24509,
         15268, 23317,  9580, 24840, 26818, 15565, 22035, 11189,  9516, 23095,
         21628,  5010, 14886, 14542, 12668, 10711,  2987, 12223, 24279,   905,
         15495,  5521, 15436, 21494,  4932, 11669,  6463, 19123, 15876,  1747,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 25515,  1128,  3506, 21239, 25593, 24938, 17154, 15623,  4028,
          6529, 25515,  5049, 24344, 17795,  3337, 10609,  3506, 21239,  7719,
         15268, 27479, 17131,  8376,  9266, 23411, 16387,  8160,  8441, 25515,
          2869, 14542, 25024, 15039, 26919, 27314, 24990,  6364, 21848, 22024,
         17171,  6226,  4881, 23221,  8447, 21874, 21344, 19596,  6846, 15238,
         25546, 19994, 23084, 27248,  7066, 21246, 27338,  6045,  4849, 17989,
         25515,   290, 15687, 16654, 16048, 23624, 27150, 17154,  3173, 15418,
         13934, 23967, 25653,  5161,  4032, 19599,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0') tensor([[[-2.3231, 22.4626, -0.3234,  ..., -1.5762,  0.6442,  0.5792],
         [-1.4565, -0.7388, -0.0849,  ..., -1.2521,  0.4842,  0.8056],
         [-3.1340, -4.2059, -1.4955,  ..., -3.1330, -1.2673,  0.1299],
         ...,
         [-4.4553, -2.2520, -1.1275,  ..., -4.0552, -2.6880,  0.6747],
         [-5.6163, -2.6897, -3.5387,  ..., -5.9173, -2.8809, -1.7282],
         [-1.7491, -1.3903, -1.4388,  ..., -1.7149, -0.8087, -0.8210]],

        [[-3.0163, 21.9538, -0.6307,  ..., -2.1948,  0.4411,  0.3628],
         [-6.7285, -2.4282, -3.8754,  ..., -6.0463, -2.6221, -1.4150],
         [-2.6665, -0.6678, -0.6623,  ..., -2.2616, -0.9837, -1.8646],
         ...,
         [-2.9349, -1.5538, -1.7069,  ..., -2.4692, -1.1186, -0.7485],
         [-2.6291, -1.4449, -1.5977,  ..., -2.2078, -1.1539, -0.8438],
         [-2.4118, -1.1777, -1.5028,  ..., -2.0101, -1.1578, -0.8733]],

        [[-2.5546, 22.1032, -0.5785,  ..., -1.6614,  0.2463,  0.5267],
         [-4.3850, -0.7296, -1.6814,  ..., -3.7559, -2.6429, -0.5573],
         [-2.0985, -2.0858, -0.4951,  ..., -1.9612, -0.7468, -0.1744],
         ...,
         [-2.1887, -1.3344, -1.3239,  ..., -1.7338, -1.1156, -0.3496],
         [-1.9726, -1.2651, -1.2553,  ..., -1.5734, -1.2018, -0.4800],
         [-1.8671, -1.0349, -1.1958,  ..., -1.4777, -1.2398, -0.5472]],

        [[-3.2629, 21.6444, -0.9494,  ..., -2.5684, -0.1109,  0.2826],
         [-4.0626, -4.2869, -1.8734,  ..., -4.0184, -1.9246,  0.1090],
         [-2.0731, -3.7898, -0.6196,  ..., -1.9037, -0.2095, -0.1258],
         ...,
         [-3.4792, -2.4519, -1.8887,  ..., -3.1337, -1.7781, -0.4786],
         [-3.1659, -2.2739, -1.7558,  ..., -2.8639, -1.8088, -0.5807],
         [-2.9446, -1.9337, -1.6418,  ..., -2.6717, -1.7883, -0.5935]]],
       device='cuda:0') tensor([[    1,   770, 25593, 17798, 17745, 18056, 18094,  2387, 17471, 20528,
         21344,  5522,  2971, 26172,   283, 22496, 16126, 24509, 26161, 20528,
         22354,  5318,  6677,  2969, 23515,  4541,  7612, 27479, 24509, 15888,
         15425, 13797,  8396,  6426, 27169,  3625, 19839,  2969, 26816,  5313,
          4948,  4067,  9634, 18056, 25593, 17815, 17745, 26974, 26179, 23891,
         16178,  4948,  5893, 26845,  3625,  7836, 18999, 20525, 22354, 16026,
          5313,  4948,  7836, 12108,  2969, 20525, 24509, 16626, 27522, 23440,
          6469, 11188, 23440, 25932, 16626, 27522,   623, 21344, 20525,  1042,
         23515, 25173, 18056,  5318, 26975,  7839,  6677, 24824,  2969,   258,
         20509, 26170, 16579, 16301, 18056, 23752, 23170,  5414, 12459,  5522,
         26170,  3625,  7761,     0],
        [    1, 23203,  3118,  3793,  1458, 20485, 25639, 12341, 21344, 10512,
         25483,   696,  8971, 25639, 13927, 26311, 25639, 12341, 17171, 27314,
         20588, 21344, 25639,  9971, 12341, 25129,  9812, 24938,  9543,  4842,
         24344, 21344, 26818, 14264,  1703, 15399, 25639,  9265, 15179,  6862,
          9543,  4842, 27338,  3970, 27115,  5288,  5848, 21835, 24679, 13241,
         21344, 19232, 23990,  3794,  6759, 26161,  5542,  5320, 16626, 25639,
          3794,  1939, 26183,   839, 25382, 25211,  8156, 22864, 20606, 23932,
          7790, 23990,  3794, 19232,  9971,  2448,  2170, 13988,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 25639,  5010, 14886, 23317, 12668, 20139,  4783, 20476, 15268,
         23831, 24348,  7615,  9184, 24944, 20470, 21344,  3401, 12609,  9260,
         10524, 25800, 23433,  7510,  6787, 27290, 23317, 12668,  5444,  4490,
          9823, 21344, 11392, 19134,  9260, 15687, 27261, 23317,   977,  7566,
         11716, 19123, 10711, 19957,  2284,   914, 21874, 23317, 24348, 24432,
         27483, 23317,  9580, 24840, 26818, 15565, 22035, 11189,  9516, 23095,
         21628,  5010, 14886, 14542, 12668, 10711,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 25593, 24938, 17154, 15623,  4028,  6529, 25515,  5049, 24344,
         17795,  3337, 10609,  3506, 21239,  7719, 15268, 25515,  2869, 14542,
         25024, 15039, 26919, 27314, 24990,  6364, 21848, 22024, 17171,  6226,
          4881, 23221,  8447, 21874, 21344, 19596,  6846, 15238, 25546,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  5928,  5703,  ...,  3679, 16927,     0],
        [    1, 13311,  7599,  ...,     0,     0,     0],
        [    1, 15663, 20288,  ...,     0,     0,     0],
        [    1, 16441, 18449,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.3685, 22.5334, -0.3776,  ..., -1.6438,  0.5973,  0.5167],
         [-5.2530, -2.5534, -2.3926,  ..., -5.1398, -2.7618, -2.0768],
         [-7.4476, -2.3626, -3.8677,  ..., -7.0235, -3.3486, -2.5461],
         ...,
         [-2.6176, -3.0102, -2.3177,  ..., -3.1759, -1.7853, -0.5893],
         [-1.9819, -1.0217, -1.6618,  ..., -2.7381, -1.3326,  0.3380],
         [-2.0672, -1.1842, -1.9615,  ..., -1.9333, -0.7059, -0.9506]],

        [[-2.2713, 21.8733, -0.3427,  ..., -1.5025,  0.4923,  0.7917],
         [-4.8222, -3.8335, -2.8947,  ..., -4.9672, -2.2738, -0.5503],
         [-5.3446, -5.1955, -2.1001,  ..., -5.3552, -3.2102, -2.0577],
         ...,
         [-3.5058, -1.9290, -2.0891,  ..., -3.0927, -1.6539, -0.6623],
         [-3.3252, -1.7704, -1.9530,  ..., -2.8950, -1.4787, -0.5903],
         [-3.0122, -1.2881, -1.7410,  ..., -2.5233, -1.2453, -0.4271]],

        [[-1.6342, 22.4196, -0.0590,  ..., -0.9393,  0.6510,  1.1541],
         [-5.8987, -1.9816, -2.3571,  ..., -5.6022, -3.4877, -1.4186],
         [-5.1368, -1.6816, -2.7122,  ..., -5.1036, -3.0119, -1.4456],
         ...,
         [-4.1176, -2.4463, -2.5321,  ..., -3.7809, -2.1283, -0.7991],
         [-3.9052, -2.2569, -2.4031,  ..., -3.5408, -1.9325, -0.7153],
         [-3.5715, -1.7716, -2.1877,  ..., -3.1501, -1.6963, -0.5646]],

        [[-2.5640, 22.0084, -0.5741,  ..., -1.8504,  0.2963,  0.4975],
         [-8.3500, -3.6303, -4.1592,  ..., -7.8957, -2.9489, -2.9102],
         [-4.9020,  1.1557, -1.4781,  ..., -4.2268, -1.6762, -0.1263],
         ...,
         [-3.5177, -2.2233, -2.1072,  ..., -2.9464, -1.7532, -0.5673],
         [-3.3612, -2.1027, -2.0049,  ..., -2.7556, -1.5812, -0.5202],
         [-3.1143, -1.6722, -1.8132,  ..., -2.4589, -1.3881, -0.3967]]],
       device='cuda:0') tensor([[    1, 17795, 19880,  2872, 16595,  2169, 18987, 21344,  7510,  2436,
          4044, 26818, 15024, 26513,  5658,  5294, 21344, 16205, 11527,  4624,
         26513,  9999, 23284, 19721,  4821, 11268, 15024, 10712, 27290, 19112,
         16626, 26275, 24938, 17171,  2438,  4049, 26711, 12395,  2933, 10852,
         13437, 14881, 16387, 27379,  8917, 23246, 26512, 21344, 13496, 11527,
         21943, 14953, 24256, 21854, 20601, 10711, 16205, 11527, 21344, 27318,
         27377, 12649, 20019, 17953, 24344, 17795,  2872, 16595, 26172, 21932,
         23042, 16157,  1531, 26868, 18729, 22405,  9227, 21854,  9260,  8749,
         21847, 21344,  2367,  8447, 27479,  3666,  1314, 21966, 26512, 27377,
          5709, 15754, 10852,  7946,  9266, 19216, 26512, 15922, 18270,   759,
         21874,   770, 24544, 26512, 27377, 23566, 18475,  1302, 14918,  4624,
         21344, 16205, 11527, 21525, 22450, 20925,  5705, 26170, 14918, 19157,
         25122,  7790, 26512, 27377,  1315, 15500,  3517, 26512, 27379, 10711,
         21963,  5530, 13663, 26513,  3158,  2008, 16924, 16626, 26513, 10652,
          1061, 18264, 27299, 10711, 20471, 16924, 18264,  1531, 16626, 24435,

 14%|█▍        | 16/112 [00:01<00:06, 14.60it/s, loss=1.37]

tensor([[[-1.8098, 22.3368, -0.1636,  ..., -0.9795,  0.5816,  0.9668],
         [-2.7498,  0.3822, -1.5643,  ..., -2.7659, -1.7262, -0.2882],
         [-7.3492, -4.8003, -4.5971,  ..., -7.2251, -3.7325, -2.8606],
         ...,
         [-2.8539, -1.8410, -1.5547,  ..., -2.3041, -1.4712, -0.4888],
         [-2.8940, -1.6221, -1.6004,  ..., -2.3574, -1.5530, -0.3632],
         [-2.9563, -1.6369, -1.7200,  ..., -2.4482, -1.6255, -0.3708]],

        [[-2.3915, 22.6785, -0.3484,  ..., -1.6472,  0.5131,  0.6573],
         [-2.7357,  1.4759, -0.5122,  ..., -2.2474, -1.2543, -0.2004],
         [-3.8413, -4.7006, -1.3639,  ..., -3.0325, -1.6967, -1.1445],
         ...,
         [-3.8351, -3.0394, -2.2767,  ..., -3.2929, -1.3101, -0.4088],
         [-6.9385, -6.6030, -3.7693,  ..., -7.2265, -4.1911, -1.6980],
         [-2.6671, -1.6363, -2.1875,  ..., -2.4539, -1.3026, -1.0094]],

        [[-3.4006, 21.9088, -1.2098,  ..., -2.8081, -0.1218,  0.1709],
         [-7.4361, -4.6364, -3.3508,  ..., -6.5969, -2.4318, -1.3938],
         [-3.4517, -2.4116, -1.1361,  ..., -3.6227, -1.4631,  0.2609],
         ...,
         [-3.3390, -2.2197, -2.1805,  ..., -2.9748, -1.6907, -0.8886],
         [-3.4797, -2.0618, -2.3109,  ..., -3.1416, -1.8182, -0.8246],
         [-3.5581, -2.0870, -2.4346,  ..., -3.2509, -1.9109, -0.8491]],

        [[-2.8709, 21.9671, -0.5239,  ..., -2.1237,  0.1010,  0.4390],
         [-3.8784,  0.0720, -1.0512,  ..., -3.4989, -2.1003, -0.5427],
         [-7.8760, -2.8159, -3.6321,  ..., -7.5797, -3.3886, -1.0506],
         ...,
         [-3.1468, -2.0479, -1.7575,  ..., -2.5891, -1.5402, -0.7054],
         [-3.3650, -1.9195, -1.9324,  ..., -2.8345, -1.7154, -0.6722],
         [-3.5560, -1.9629, -2.1284,  ..., -3.0567, -1.8555, -0.7425]]],
       device='cuda:0') tensor([[    1,   985, 23525,  6846, 26403,  4003, 12285, 18209,  5445, 16240,
         23202, 17579, 12922, 25593,  3189, 25062,  5313, 20298,  7991,  9482,
          6143,  8928, 13295, 12813, 17576, 20298, 12339, 25544, 21239, 16240,
         23119, 20864, 25390, 23387, 17000,  2557,   985, 18620,   818, 17367,
         11227, 12777, 16240, 20298, 15922, 18267, 26338,   985,   809, 27530,
         25593,  3189,  4079, 12284, 13919, 19057,  4845, 20559, 21247, 18209,
         23857,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 15398, 21344, 23330, 13201, 21943, 26403, 18949, 25564, 10762,
         25564, 10711, 26818, 18056,  9193,  5248, 26713, 26786, 22492, 25564,
         26443, 22030, 25076,  2931, 14317, 26161, 24996, 25639, 22622, 24291,
           727, 18056, 19994, 23633, 18475, 17909,  9612, 27117, 25564, 19155,
         26713,  8341, 24534,   733, 16221, 18152, 25564, 11570, 24747, 24294,
         18458, 11392,  6308, 25567,  6775, 26426, 19998, 16186, 14457, 21086,
         26818, 18056, 26786, 25564, 19624,  6759,  9293, 27483, 24938, 15398,
         16606, 26161, 24657,  4056,  5522, 24344, 14033, 10471,  2797, 21794,
          8104,  9905, 12560, 21605, 11286, 18056,  9193, 26713, 26786, 11392,
          6308, 25564, 22036,  8463, 15024, 16626, 15941, 14016, 25567, 13964,
          7576,  3627,  3294, 12560,  8709,  2931, 17171,  8501, 13964, 22340,
         11789, 12210, 14016, 25564, 11710, 24996,  7576,  7573, 19997, 17171,
         26161,  2438, 21474, 25564,  4842,  6852,  8437, 13964,  2983,  7576,
         22340, 11712, 19999,  3627, 12554, 20461, 21794,  9855, 20106, 12252,
         25352,  9730, 16262, 18056, 26786, 26713, 26713, 26161, 16606,  3466,
         21474,  4842, 27321, 15398, 24657,   408, 20735, 26919,  2982, 11949,
         26442, 14645,  4056, 26161, 14029, 25352, 19155,  5248,  6373, 26443,
         26390, 11570, 16606,  3466, 21474, 24567,  4842,  3135, 22023, 19301,
          9791, 21087, 18692,  6677, 18099, 26713, 16221,  4241, 19452, 10964,
         16205, 10979, 23932, 17171, 24366, 24532,  3978,  6775, 18149, 26426,
         19998,     0],
        [    1,  4274, 26909,  6846,  2933, 21344,  4049, 14795,  9157, 23790,
         16626, 14367,  8691,  4973, 16924,  4279, 26868,  1526, 25396,  6487,
          4306, 10412, 19376,  6443,  2808,  1061, 20308,  6846, 21735,  9157,
           277, 18253, 19376,  6051, 15213, 20370, 20091, 10412,  4306, 16183,
         26909,  6839,   839, 18323,  2933, 21344, 16626, 14367,  8966,  1061,
         20307,  9157, 27338, 14881, 19168, 26073,  9185,  2808, 24592,  2076,
          4306,  9131, 17550, 10412, 26909,   353, 27338, 15024, 18056,  9266,
          4241,  6837,  9165, 21344, 20154,  9157,   277, 12126, 27290, 14290,
          8691, 27323, 18737, 18072,  1061, 20307, 26909, 25025,  6051, 15213,
          8872, 26867, 26909, 21344, 26527, 19376, 25025,  1638,  5522, 20479,
          1209,  8348,  5896,  9727, 12315, 26986, 20308, 18620, 25123,  9865,
          4835,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1,  2106, 17256, 12280, 14029, 12295, 10084, 10721, 25593, 19514,
           539,  7712, 13027, 17047, 24787,  2603,  3401, 17256, 27479, 25716,
          1456, 10121,  7822,  2106, 21344, 25639, 14566, 23760, 10426, 10121,
          7822,  3402, 16521, 18917, 13203,   539,  1926,  8111, 19838, 10721,
         12391, 18962, 21344, 18194, 11295, 17816,  2106, 23651, 11147, 17256,
         11396, 22513,  3401, 19872,  2296,  5274, 20925, 19349, 23144, 21530,
         20528,  2106, 23651, 11147, 25639,  3402, 22030, 19253, 16654, 16050,
          5522, 25389, 12648, 19780, 20928,   168, 20470,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')
tensor([[    1, 21172, 23892,  ...,     0,     0,     0],
        [    1, 26330,  4226,  ...,     0,     0,     0],
        [    1, 13429, 20082,  ...,     0,     0,     0],
        [    1, 25076, 13264,  ..., 19349, 12499,     0]], device='cuda:0') tensor([[[-2.8275, 22.1926, -0.6627,  ..., -2.1210,  0.2608,  0.5403],
         [-5.0281,  0.5434, -2.4603,  ..., -3.8941, -2.5655, -1.1785],
         [-5.0733, -2.0968, -2.4643,  ..., -4.5598, -2.5912, -1.0454],
         ...,
         [-2.2041, -1.4127, -1.5648,  ..., -2.1279, -0.8535, -0.7100],
         [-2.1934, -1.2510, -1.4753,  ..., -2.0078, -0.8184, -0.6808],
         [-2.1367, -1.0352, -1.4084,  ..., -1.8112, -0.7346, -0.5313]],

        [[-2.6505, 21.9977, -0.7097,  ..., -1.9349,  0.2312,  0.7203],
         [-5.0009, -1.9032, -2.0651,  ..., -4.3487, -2.1924, -1.0626],
         [ 0.7021,  2.3088,  0.7822,  ...,  0.8845,  0.5906,  1.5842],
         ...,
         [-2.2275, -0.7110, -1.4600,  ..., -1.9665, -0.9578, -0.5884],
         [-2.1944, -0.4792, -1.3735,  ..., -1.8170, -0.8894, -0.5189],
         [-2.0762, -0.1984, -1.2800,  ..., -1.5792, -0.7543, -0.3500]],

        [[-2.4350, 22.0992, -0.5241,  ..., -1.7436,  0.4112,  0.5628],
         [-1.0846, -0.6826, -1.0957,  ..., -1.5324, -0.3086,  0.4950],
         [-1.4082, -0.6666, -1.0294,  ..., -1.7237, -0.6721, -0.9128],
         ...,
         [-2.1879, -1.0130, -1.1743,  ..., -1.7625, -0.9995, -0.2823],
         [-2.2158, -0.8414, -1.1340,  ..., -1.6865, -0.9745, -0.2676],
         [-2.2585, -0.6881, -1.1212,  ..., -1.6020, -0.9520, -0.1764]],

        [[-3.1732, 22.0678, -0.8656,  ..., -2.4260,  0.1658,  0.2557],
         [-4.2691, -3.6653, -1.9399,  ..., -3.6911, -2.5715, -1.5582],
         [-2.4445, -2.9701, -0.8666,  ..., -2.4090, -2.2785, -0.4813],
         ...,
         [-4.9485, -3.0473, -1.2303,  ..., -4.5366, -1.5275, -0.4833],
         [-4.6670, -5.0281, -1.8162,  ..., -3.9611, -1.8206, -1.3173],
         [-2.3494, -1.0152, -1.5881,  ..., -2.0427, -0.7655, -1.0165]]],
       device='cuda:0') tensor([[    1, 21226,  4044,  9905, 21344, 14586,  7501, 19057, 15499,  2448,
         17841, 18001, 27338, 26150, 16203, 17240,  4823, 10512, 20139,  1758,
         14586,  7501, 23892,  5774,  2448, 21533,  4904, 19681, 15024,  5193,
         12922,  4049, 19232, 14586,  7501,  4904,  5320, 25804, 19683, 14874,
          5193, 12922, 21344, 17235,  2448, 12226, 25114, 14586,  3563,   730,
          2509, 27116, 21187, 20713, 15645, 21700, 13244, 21344, 27338, 21973,
         23440,  4306,  8111,  4279,  8816, 14586,  8825, 21344, 15500, 21172,
          8853, 14367, 23892, 19026, 26669,  7867, 23883, 25680,   241, 14586,
          4036, 14586,  8825,   525,   241, 22042, 10517, 23892,  6943,   290,
         18810, 19433,  7763, 14351, 14586,  7501,   525, 27188,  2448, 21827,
         19846, 11713, 14587, 26151, 10512, 24789, 13941, 23340,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 26330,   759, 17078, 24038,  2004,  9829, 17117, 16048,  4226,
          4226, 16588, 12129, 17117, 22513, 15666, 24797, 17117, 10035,  5219,
          4766,    74,  4226, 19546, 10718,  7700, 16521, 17117,  5304, 19994,
         11392, 17117, 19006, 27479,   748, 18620, 26013, 15668,  7641, 24038,
          2885, 16205,  4124, 26528,  4226, 21344,  5549, 27338, 19452, 15024,
         17117,  8770,  7030,  4226, 26331, 18949, 11771,  4124, 17078,  4226,
         27044, 19733,   130,  5549, 17117, 20541, 17077, 14795, 17795, 25211,
          6129, 25593,  5548,   727,  4226, 17216, 17117,  9114, 26330, 12765,
         16626, 20102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 27483, 17131,  1401, 15996, 17121,   259, 20082, 21344,   259,
         13429, 20082,  2367, 13663, 21044, 15225, 16185,  1703, 23411, 18966,
         11561, 26671,  8847, 11561,  3520, 21344, 10494,  3670,  3118, 19604,
         10622, 26598, 11544,  9397,  3069, 11539, 21814,   259,  2847, 14075,
          3637,  2227,   759, 23200,  7460, 21630, 19438,   243,  3690, 27529,
         14948,  9844, 11630,  7417,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 14586, 27277,   759,   219, 11408, 25947, 14586,  4036, 27338,
          1156, 13264, 27180, 14586,  4199, 13326, 14586, 27277, 21344,  5883,
         21229, 27380, 12236, 18813, 14586,  4036, 27338, 17519,  4976, 27380,
          8469,  4813, 14586, 27277, 21344,  8879,  8794, 19829,   527, 14586,
          4036, 12918, 14586, 27277, 21344,  6648,  5883, 26384, 26986, 13264,
          4000, 12500,  5271, 10742, 13272, 12273, 14586, 27277, 14586,  4199,
         13326,  8111, 26669, 10303,  8469,  4823, 19349,   337, 21896,  4813,
         12500, 19349, 12499, 25025, 16203, 14586,  4036, 14586,  8825, 12527,
          9172, 21530,  3787, 10512, 21535, 14586,  4036, 27338, 25947, 10395,
         14586, 27277, 27180,  6469,  5193,   440, 23206, 21344, 14586, 27277,
         14586,  8825,   525, 10995, 18813, 21344, 12797,  4241, 14586, 11857,
         13988, 14586,  4750, 13319,  1402, 22567, 14586,  4036,  3607, 17015,
           527,  1159, 13264, 10994, 21344,     0]], device='cuda:0')
tensor([[    1,  2549,  2570,  ..., 22319, 18450,     0],
        [    1,  5814,  5522,  ...,     0,     0,     0],
        [    1, 25639, 27529,  ...,     0,     0,     0],
        [    1, 21362, 21552,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.8046, 22.2050, -0.6576,  ..., -2.0912,  0.3496,  0.2296],
         [-5.7301, -4.6264, -2.1133,  ..., -5.7003, -1.6857, -1.1976],
         [-2.0355, -2.4098, -1.6581,  ..., -2.4207, -1.2388, -0.6554],
         ...,
         [-4.1413,  0.6671, -2.2947,  ..., -4.2558, -1.0862, -0.2559],
         [-3.2223, -0.9490, -1.1857,  ..., -3.1768, -1.2059, -0.5843],
         [-2.1996, -0.5462, -1.8200,  ..., -2.0402, -0.9906, -1.0686]],

        [[-2.2114, 22.6639, -0.5818,  ..., -1.5512,  0.4588,  0.3779],
         [-3.6531, -4.1377, -1.4387,  ..., -2.7699, -1.5860, -1.0153],
         [-6.7722, -3.1637, -1.9331,  ..., -6.2287, -2.6119, -1.2266],
         ...,
         [-1.6995, -0.1820, -1.5156,  ..., -1.6216, -1.0433, -0.4795],
         [-1.6311,  0.1930, -1.4660,  ..., -1.4400, -0.9488, -0.4796],
         [-1.4513,  0.3288, -1.3419,  ..., -1.1670, -0.7977, -0.4605]],

        [[-2.4945, 22.1547, -0.5890,  ..., -1.7316,  0.2947,  0.6060],
         [-2.9024, -0.5657, -0.7010,  ..., -2.5084, -1.5138, -0.9769],
         [-4.0767, -1.2651, -1.6793,  ..., -3.7805, -2.5432, -0.5137],
         ...,
         [-2.6020, -0.3462, -1.6189,  ..., -2.3016, -1.4000, -0.1604],
         [-2.7151, -0.0845, -1.6472,  ..., -2.3022, -1.3931, -0.1965],
         [-2.8039, -0.1682, -1.6713,  ..., -2.3137, -1.3982, -0.2620]],

        [[-2.6078, 22.0022, -0.5541,  ..., -1.9881,  0.4186,  0.4108],
         [-4.1561, -3.3877, -2.0202,  ..., -3.7600, -1.9141, -1.1976],
         [-4.3101, -1.3608, -1.8459,  ..., -3.5814, -1.6518, -1.7495],
         ...,
         [-2.6331, -0.5343, -1.5787,  ..., -2.4330, -1.3499, -0.4859],
         [-2.5408, -0.1800, -1.5222,  ..., -2.2383, -1.2592, -0.4808],
         [-2.3870, -0.0742, -1.4260,  ..., -1.9950, -1.1318, -0.4487]]],
       device='cuda:0') tensor([[    1, 23123, 16205,  2549,  5295, 20118, 13793, 17825, 14060, 17034,
         18620,  3951, 10703, 11383, 25114, 17825, 21344, 27338, 25544,  4527,
          1758, 23144,  5921, 25114, 14025, 15645, 11730, 21344, 17825, 27338,
          5915,  2690, 26782, 23144,   727,  2690, 24482,  5921, 16205,  2549,
         21344,  5142, 24482, 23144, 19230, 27338, 19452, 20930,  3115, 11013,
          7693, 23328, 14639, 16107, 12390, 25841,  6170, 13498, 12777, 19349,
         22024,  4036, 21344,  5144, 18450, 27338, 21859,  2690, 23144,  5921,
         25098,  6460, 15401, 25114, 22096,  4036, 17141, 14195,   198, 16205,
          2549, 15856, 17825, 19230, 19533, 13793, 27338,  9862, 18450, 21490,
         25114, 22096, 11570, 21835,  6090,  6093, 21344, 25098, 27338,  9862,
          5921, 20372, 12345,  3351, 13793, 19019, 15783, 25025, 13793, 17825,
         10052, 25114, 18609, 27338,  3859,  7693,  8798, 20601,  6090,  6093,
         21344, 25098, 27338, 14881,  5921, 20372, 20168,  1427, 27338,  3106,
         18606, 17085, 15199, 13793, 23144, 11188,  7744, 16205,  6093, 21344,
         13793, 20606, 11765, 26779, 11765, 17538,  9800,  3346, 16205,  2549,
          4036,  8794,  1048, 19531, 14284, 11203,  7822, 24485, 19452,  9153,
          2690, 22319, 18450,     0],
        [    1, 21344, 20460,  5320,  5814, 27338, 16914, 17262, 15785, 27338,
         21226, 21717,  4207, 24040,   488,  8794, 12166, 27290, 18049, 21835,
           612, 13177, 26750,  4813, 21344, 16456,  1588, 17083, 12768,  7736,
         24291, 10447,  1807, 27381, 20470, 26151,  5814,  7400,  5267, 18450,
         12226,    17, 17262, 18935, 17777,  7644,  3785,  5813,  4948, 24291,
          5522, 14795, 27290, 24789, 21896,  4813, 27338,   523, 27338,    83,
          5355, 24291, 10426, 27290, 16203, 13964, 12500,  5814, 18092,  2156,
          4457,  6600, 12728, 22488, 24291,  3499, 14869, 17936, 16626,  3787,
          1782,  4386,  3290, 24773, 15268, 25114, 22096, 27290, 18049, 21835,
         21344, 10494,  9193, 26818, 10426,  8156, 17936, 10205, 18056,  7510,
          5814, 24106,  5323, 22513, 12728,  1436,  8089,  4207, 24040, 17936,
            80, 17761, 20470,  4823, 27290, 18049,  4813,  3517,   488, 27340,
         25944, 12167, 22023, 27199, 26886,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1,  4216, 25639,   493,  1028, 12229, 21344, 15093,   913,  6074,
         26170, 18188, 18791, 10205, 17761, 23802, 16506, 24797, 12229, 20470,
         21344,   168,  6074, 20470, 25352, 15090,  3118, 24546, 17808, 12126,
          5488, 15020, 14323,  8629,  2987, 19123,  9572, 14551, 24650,  2149,
         21154,  3118,  4216,  8123, 11396,  1674,  1028, 12229,  8396,  7311,
         23052, 12927, 27533, 20470, 23936,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,

 17%|█▋        | 19/112 [00:01<00:05, 16.66it/s, loss=1.82]

tensor([[    1, 15498, 22284,   480, 21827, 21860,   943,   480, 23916,  4927,
          6264, 13316, 15498, 19512,  9180, 21446, 17204,   480, 17107,  1896,
          1619,  7458, 22330, 21404, 13223, 14600,  6285,  4028, 25076, 21860,
           952, 21026, 19692,  2134, 24197, 24809,  8145, 26028,  5949, 21500,
          2134,  9639, 21860, 26478, 23036, 25043, 10838, 17477,  7792, 21860,
         15260, 15812, 15498,  2136,   480, 25593, 24840, 15449, 10456,  9973,
         18439,  8550, 18090, 21344,   783, 25147,  4750, 18475,   943, 26713,
         18475,  9973, 14888, 21239, 14317,  7201,  5569,   480, 15202, 18791,
         17234, 25593, 10945,  1776, 21344, 15498,  8501, 22055, 18483, 25154,
         27095, 24344,  4038, 14606, 10823,  3628, 21344,   839, 18481, 16221,
          2387, 24944, 17238, 14578,   480,   290,  5342,  2436, 18588,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  7311, 27115, 21774, 12515, 23052, 16183, 21774, 12515, 16388,
          2367, 18318, 23411, 13046,  1967,  2367,   259,  1919, 12668,  9157,
          9072,  2032, 25462, 23645, 17745, 14948,  2076,  8047, 14290, 21774,
         12515,  2367,  9543, 13894,  9157, 10429, 10354,  1705,  1009,  2301,
           901, 10103, 22148,  2367,   261,  1702,  1919,  9072, 27479,  8441,
         21541,  9482,  1394, 25488,  6886,  8833, 18227, 17214,  6846, 13166,
         21650, 14298,   210,  1702, 11600, 13685,  6846, 27256, 13376, 26652,
         11606, 19195,  1394,  4323, 10609, 11604, 26713, 22147, 11604, 24722,
          4685, 27256, 21344,  9746, 27376,  4288,  2000, 13697, 27376, 17768,
          4033,  4253, 22148,  2367, 21730,  1702, 14172,  4267, 17131,  2933,
         20592, 24797, 27479,  1919, 12668,  9157,  9072,  7253, 19143, 24900,
         21365, 25488, 20301,  9862,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 21365,  8793,  2821, 11392, 23703, 13027, 21365,  8794, 11286,
         25639, 11392, 23703, 20008, 18660,  4285, 21804, 24111,  9626, 23636,
         19934,  2821,  1971, 11821, 25219, 20744,  6182, 14203,  3118, 20658,
          5174,   176, 13717, 21344, 21365, 25223, 23760, 16048, 21100, 14317,
         14317,  2046,  4850, 27479,  7612,  5218, 20327,  3868,  3434,  2436,
         24900, 12932, 14317,  9890, 21344,  3010,  6846, 10121, 13496, 11133,
         11395, 12648, 19782, 25717, 11724, 15093,  5271, 24344, 25033, 20658,
         21844,  3010, 21344,  4551,  9516, 21365, 21344, 10125,  2387,  6182,
          6469, 23636,   759, 10456, 16048, 24840, 16050, 13027, 14317, 14317,
         21365, 22348, 10721, 19780, 24840, 16050,  6182,  3010, 21344,  9482,
         20276, 23760, 16626, 27479,  1926, 11545, 25219, 25062,  7363, 25544,
         21344, 16205, 11133,  8437,  8703, 19198,  6918, 17929,  6102,  2821,
         13941, 16048,  5522, 24612,  5910, 18999,  3010, 24111,  9626,  4285,
         27331, 27483, 20660,   168, 17083, 16456, 23455,  6071, 21365,  6182,
          8794, 15447,  8614,  5554, 27331, 22513,     0],
        [    1, 11570, 14484,  1184, 20929, 16924, 16107,  1186, 25639, 20926,
          9266, 24938, 22513, 15268, 13934, 27479,   168, 14145,  9141,  1926,
          8111, 16626, 14486,  6182, 21100, 22687, 11395, 16894, 16735, 27479,
         14633, 16106, 14145, 21100,  2690,  6182,  2690, 20925, 16894,  9141,
          5290, 24111,  3118,  1931,  1458, 21344,  1184,  9293, 27479, 14633,
           914, 21530,  9141, 22340, 15093, 15268, 23327, 23566, 18581, 11713,
         19003, 22886, 15956, 20925, 16106,  1184, 14145,  6182, 20229, 12150,
         11724, 15093,  5885, 22723, 23479, 19783, 22168, 21344, 10351, 12520,
           913, 11730,  1222,  4791,  2722,  9141,  2100,  2247, 19219, 15093,
          5274,  5371,  4049, 16106, 20194, 15268,  1351,  6515,  9141, 16894,
         24887,  9345,  6182,  9141,   914, 21344, 17047, 13934, 27479, 16626,
         21229,  3545,  9522, 15399, 14144,  9523, 27188, 16106, 19123, 24610,
         16894,  6290, 14145, 14795, 24062,  4911, 21229, 19217, 21975,  1926,
          8111, 21344,  5216,  5674, 21100,  2690,  6182,  2690,  8615,  2690,
         20471, 18999, 16048,     0,     0,     0,     0]], device='cuda:0') tensor([[[-1.9836, 22.2946, -0.3967,  ..., -1.2849,  0.7671,  0.4135],
         [-2.4859, -0.5960, -0.8164,  ..., -2.0833, -1.6801, -0.1021],
         [-7.4189, -4.3294, -3.3078,  ..., -7.2725, -3.7196, -1.9859],
         ...,
         [-2.3138, -1.5895, -1.6828,  ..., -2.1036, -1.0674, -1.1431],
         [-2.4405, -1.6607, -1.7544,  ..., -2.2515, -1.2191, -1.1864],
         [-2.4401, -1.5984, -1.7751,  ..., -2.2467, -1.3306, -1.2146]],

        [[-0.9437, 22.9771,  0.1923,  ..., -0.2449,  1.1794,  0.9155],
         [-5.6634, -0.5832, -2.2630,  ..., -4.2164, -2.4042, -0.0919],
         [-3.7488, -2.0341, -1.7805,  ..., -3.4038, -1.2404, -0.7958],
         ...,
         [-0.8747, -0.7490, -0.8485,  ..., -0.6562, -0.2776, -0.4820],
         [-0.9732, -0.8059, -0.9085,  ..., -0.7837, -0.4274, -0.5198],
         [-0.9627, -0.7429, -0.9356,  ..., -0.7604, -0.5352, -0.5389]],

        [[-3.4023, 21.8290, -0.8960,  ..., -2.4755,  0.0936,  0.2230],
         [-4.1723, -3.2219, -1.8088,  ..., -3.5721, -2.5256, -0.9893],
         [-4.6848, -1.0458, -1.7691,  ..., -3.9237, -2.5416, -1.7727],
         ...,
         [-1.5107, -1.7073, -1.3027,  ..., -1.8775, -0.4225,  0.3352],
         [-6.6033, -5.3702, -2.4358,  ..., -6.1823, -4.0198, -2.1745],
         [-2.4452, -1.2845, -1.7320,  ..., -2.0570, -1.2604, -1.0705]],

        [[-3.0182, 21.7530, -0.7608,  ..., -2.2140,  0.1833,  0.1781],
         [-6.7178, -4.1971, -3.5672,  ..., -6.9143, -3.6344, -2.6871],
         [-5.4169, -4.0830, -3.3172,  ..., -6.0264, -1.8927, -1.5443],
         ...,
         [-1.8769, -1.5114,  0.4028,  ..., -2.1846, -0.6046, -0.1923],
         [-2.4514, -1.5060, -1.7362,  ..., -2.1576, -1.2204, -1.0725],
         [-2.5723, -1.5453, -1.8199,  ..., -2.2864, -1.3805, -1.1253]]],
       device='cuda:0') tensor([[    1, 21827, 21860,   943,   480, 23916,  4927,  6264, 13316, 15498,
         19512,  9180, 21446, 17204,   480, 15202, 18791, 17234, 25593, 10945,
          1776, 21344, 15498,  8501, 22055, 18483, 25154, 27095, 24344,  4038,
         26713, 18475,  9973, 15498,  2136,   480, 25593, 24840, 15449, 17238,
         14578,   480,   290,   480, 17107,  1896,  1619,  7458, 22330, 21404,
         13223, 14600,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 23052, 16183, 21774, 12515, 16388,  2367, 18318, 23411, 13046,
          1967,  2367,   259,  1919, 12668,  9157,  9072,  1009,  2301,   901,
         10103, 22148,  2367,   261,  1702,  1919,  9072,  2032, 25462, 23645,
         17745, 14948,  2076,  8047, 14290, 21774, 12515,  2367,  9543, 13894,
          9157, 10429, 10354,  1705, 24797, 27479,  1919, 12668,  9157,  9072,
          7253, 19143, 24900, 21365, 25488, 20301,  9862,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 24840, 16050, 13027, 14317, 14317, 21365, 22348, 10721, 19780,
         24840, 16050,  6182,  3010, 21344,  4551,  9516, 21365, 21344, 10125,
          2387,  6182,  6469, 23636,   759, 10456, 16048, 23636, 19934,  2821,
          1971, 11821, 25219, 20744,  6182, 14203,  3118, 20658,  5174,   176,
         13717, 21344, 11395, 12648, 19782, 25717, 11724, 15093,  5271, 24344,
         25033, 20658, 21844,  3010, 21344, 18999,  3010, 24111,  9626,  4285,
         27331, 27483, 20660,     0],
        [    1, 16106, 14145, 21100,  2690,  6182,  2690, 20925, 16894,  4049,
         16106, 20194, 15268,  1351,  6515,  9141, 16894, 24887,  9345,  6182,
          9141,   914, 21344, 15956, 20925, 16106,  1184, 14145,  6182, 20229,
         12150, 11724, 15093,  5885, 22723, 23479, 19783, 22168, 21344, 10351,
         12520,   913, 11730,  1222,  4791,  2722,  9141, 21975,  1926,  8111,
         21344,  5216,  5674, 21100,  2690,  6182,  2690,  8615,  2690, 20471,
         18999, 16048,     0,     0]], device='cuda:0')
tensor([[    1,  3193, 18627,  3557, 16177,  6443, 10512,  6443, 20476, 10480,
          3193, 18921, 17379,   612, 15709, 13793,  7822, 24054, 27290, 18049,
         15783,   612, 13177, 21344, 27381, 23931,  4036, 27338, 26187, 16205,
         15709,   298, 27338, 27290, 24509, 20470, 23975,  3401,  4384, 16205,
          3193,  1401, 24344,  4079, 15425, 23682, 16205, 15709, 27338, 16177,
          2219, 21591, 21044, 13793,   783, 14866, 16205,  3193, 27338,  3945,
          3557, 21044, 15024, 13793,  1761, 21344,  7055, 26818,  7822,  3561,
         10447, 21344, 26715, 21859,  4036, 24344,  2437, 21044,  4789, 21530,
         25098, 10586, 12449, 19457, 13793,  1758,  9503, 20596,  5142, 18611,
          1019,  4386,  9479, 26282, 17230, 18633, 23931, 25098,  9939, 13793,
         17825, 23681,  2245, 26713,  3106, 16205,  3193,  3951, 23340, 21874,
         24040, 20925, 19057, 18630,  3268, 13934, 26882,  1042, 20470, 23975,
         24570,  4386, 16205, 15709, 26080,   727, 16626, 21044,  4036,  4750,
          8621, 16205, 13177, 25025,  2102, 16644, 10480,  3193, 18475,  3945,
         21044,  7822,  3557, 27381, 21344, 15709, 17381,  3193, 27381, 21533,
          3193, 17381, 15709, 27290, 24509, 16205, 15709, 20446, 21344,  4036,
         13498,  3557,  6997,  4386, 20869, 16563,  7345, 23703, 13793, 17825,
         27338,  4783,  6845, 20476,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 16295,  3213,  2076,  3514, 25147,  9973, 18289,  8801, 18475,
         12928, 14795, 26161, 27290, 11013, 26424, 17296, 10456, 19294, 10210,
          2387,  2387, 27483, 10395,  8879, 23763, 12927, 24509,  8762, 13636,
           748, 27338, 11765, 24833, 17808,  9266,  9973,  4031, 14317,  6106,
         10447,  5522, 10205, 21690,  2695,  7615, 27290, 22872, 25481,  3287,
         21690, 10541, 19867, 11013, 27290, 18483, 18515,  3319,  3212, 19293,
          1801, 17171, 25593, 17367,  9003,  2514, 16005, 16090,  1787,  9816,
         16626, 21204, 13996, 14437,  2514, 19086,  6759, 12682, 20086, 18483,
         14437,  6765, 14951, 10205,  1866, 10964, 10494, 25481, 16502,  8047,
          9266, 10885,   783, 10456, 21683, 10609, 27290,  3061,   783, 13636,
         21685,  8437, 24823, 26935, 26135, 26426, 20086,  7706,  3523, 10885,
         24938,  8437, 24823,   539, 23137, 16522,   422, 10210,  1866, 24669,
         16626, 21203, 13988, 14795,  2514,  6765, 10205, 10885, 18021, 14606,
          3019, 13531,  4038, 10397, 27338,  2219,  3018, 19867, 26935,  1758,
         18485, 24669,  9973, 22494, 24788, 17879,  1866,  8458, 17171, 14437,
          9973,  9482, 12459,  3061, 10480, 27499, 13657,  9844,  8708, 12459,
         10456,  9452, 21697, 22571,  6106, 20008,  2436,  1399,  3213,  8034,
         12147, 26818, 21698, 18481,  9746, 21490,  5522,  7639, 10447, 26818,
          5558,  6201, 12026, 10426, 25147, 26161, 15400, 21064,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 17810, 26750, 10654, 26604, 18620, 17810,  3607,   457, 24344,
         17132, 25639, 26607, 10575,  4766,  7822, 21535,   482,  4973, 24111,
          4088, 23936, 21530,   783, 26604, 10121,  7822,  4850, 27479, 17136,
          4088,  2866, 10480, 14410, 21344,  6202,  2656, 23767,  7822, 27338,
         17132, 26607,  5522, 20300, 25544, 25122,   385,   483, 12703, 23793,
         16205, 14410, 26151, 16654, 10512,  2821, 23440, 18046,   759,  3517,
         15409,  4739,   485,  3287,  7760, 19349, 22024, 24040, 26161,   484,
         22870, 17132, 18056, 26713, 21859, 14984,  4810, 14881,  6757, 14453,
         16205, 14410, 21344, 18620, 17810, 16326, 26662,  8774, 25944,   305,
          6395,  4976, 17132, 18056, 13442,  1561, 26604, 24111,  3744, 11919,
         20525, 18056,   483, 21344, 16616, 26605, 10121,  7824,   867, 21344,
         27338,  3970, 26604, 12062,  7822,  4850, 18056,   482,  4973, 21535,
         25923,  1302, 13498,  1242, 18611, 26713, 10512,  9452, 18049, 16662,
         13498, 12922,  7700, 12126, 24797, 24482,  5780,  1241,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 16626, 25642,  6272, 26359, 25639, 12273, 17825, 14604, 17171,
         25593, 14542,  1429, 15500, 20982, 13570, 22464, 16626, 18620, 17825,
          8615, 13963, 26876,  6000, 11515, 21344,  8487,  4118, 11678, 16205,
         13570, 22464, 27338,  6371,  2387, 14025,  8401, 17825, 21344, 16205,
         13570, 22464, 14795,  6525, 17825, 14025, 26359, 13947, 25479, 23003,
          4538, 16205, 11515, 21344,  1302,  7790, 15500, 14542, 25642,   759,
         18449, 13298, 22258,  6623,  4766, 26882,  8443, 10925, 15448, 16205,
         13570, 22464,  3257, 11570, 23975,  2102, 16644, 26867, 25025, 16644,
          3545, 25642, 24133,  3590,   702, 23933,  5709, 12504, 13558, 13175,
         11725,  7510, 23387,  7641, 13554, 21810, 13861, 16654,  7822, 23203,
         25642,  3517, 16205, 11515, 19566, 14542,  1429, 25642,  1434, 16205,
         11515, 16068, 16984, 14101, 17171, 23387, 16205, 11515, 15401, 25025,
          2102,  2244, 20982, 13570, 22464,  6371,  2387, 14025,  8401, 17825,
          5883, 14028, 25639, 12273, 17825, 24137, 16205, 11725, 25642, 21344,
         21897, 13636, 16859, 26448, 16205, 11725,   701, 21344, 17309,  5709,
         12504, 14795,  1666, 13988,    52, 15500,  4839, 19232, 14102,  7473,
         22063, 25211,  7186, 20472, 21344, 14566, 20657,  3118,  7991, 19088,
         11781, 19596,  8208, 17367,  6136, 10351, 21540,  3522, 19622,   715,
          8112, 23083, 16465, 25918,    58, 25642, 23203, 15089,  5766, 21344,
         14857, 12918, 27338, 16205, 11725, 20471, 26448, 18935, 25642, 18611,
             0]], device='cuda:0') tensor([[[-3.0289, 21.9118, -0.9457,  ..., -2.3401,  0.2047,  0.1735],
         [-3.6045,  0.1214, -2.2206,  ..., -3.7504, -2.1810, -0.5954],
         [-1.4929, -3.9195,  0.3161,  ..., -1.6799, -1.3788, -0.6660],
         ...,
         [-3.3648, -2.4727, -2.4095,  ..., -3.2842, -2.0597, -1.4860],
         [-3.5623, -2.3921, -2.3550,  ..., -3.4354, -2.1247, -1.4544],
         [-3.5784, -2.1789, -2.2410,  ..., -3.4266, -2.0394, -1.3156]],

        [[-2.6009, 22.3648, -0.5875,  ..., -1.8257,  0.5220,  0.3982],
         [-3.7827, -1.7457, -0.7809,  ..., -3.9644, -1.6268, -1.1778],
         [-3.0193, -0.2877, -1.9878,  ..., -1.8992, -0.5680, -1.0569],
         ...,
         [ 0.3711, -0.8096,  1.0699,  ..., -0.7856, -0.3462, -0.2833],
         [-3.8848, -2.7889, -1.4842,  ..., -3.7644, -1.6194, -1.7582],
         [-2.0686, -1.0419, -1.4727,  ..., -1.8512, -1.0279, -0.9881]],

        [[-2.8876, 22.0621, -0.6639,  ..., -2.1898,  0.3636,  0.4094],
         [-3.8195, -2.0613, -2.3468,  ..., -3.4334, -2.3047, -0.4284],
         [-4.4760, -5.2902, -1.5815,  ..., -3.8112, -1.8398, -1.0851],
         ...,
         [-3.5920, -2.3005, -2.4061,  ..., -3.4467, -2.0802, -1.1521],
         [-3.8575, -2.2630, -2.3754,  ..., -3.6641, -2.1620, -1.1340],
         [-3.8785, -2.0171, -2.2524,  ..., -3.6446, -2.0624, -0.9791]],

        [[-2.7256, 21.9092, -0.5128,  ..., -2.0099,  0.3804,  0.4257],
         [-6.2979, -1.0584, -2.5646,  ..., -6.3477, -2.5231, -0.8550],
         [-7.0946, -5.1696, -3.5957,  ..., -6.8159, -3.2703, -0.7449],
         ...,
         [-2.8883, -1.7073, -1.9756,  ..., -2.7372, -1.6147, -1.2071],
         [-3.1794, -1.6976, -1.9617,  ..., -2.9921, -1.7097, -1.1767],
         [-3.1426, -1.4530, -1.8132,  ..., -2.9287, -1.5941, -0.9984]]],
       device='cuda:0') tensor([[    1, 13793,   783, 14866, 16205,  3193, 27338,  3945,  3557, 21044,
         27290, 18049, 15783,   612, 13177, 21344, 27381, 23931,  4036, 27338,
         26187, 16205, 15709,   298, 27338, 27290, 24509, 20470, 23975,  3401,
          4384, 16205,  3193,  1401, 24344,  4079, 15425, 23682, 16205, 15709,
         27338, 16177,  2219, 21591, 21044, 16205, 15709, 20446, 21344,  4036,
         13498,  3557,  6997,  4386, 20869, 16205, 13177, 25025,  2102, 16644,
         10480,  3193, 18475,  3945, 21044,  7822,  3557,  1042, 20470, 23975,
         24570,  4386, 16205, 15709, 26080,   727, 16626, 21044,  4036,  4750,
          8621,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 14317,  6106, 10447,  5522, 10205, 21690,  2695,  7615,  8458,
         17171, 14437,  9973,  9482, 12459,  3061, 10480, 10609, 27290,  3061,
           783, 13636, 21685,  8437, 24823, 26935, 26135, 26426, 20086,  6759,
         12682, 20086, 18483, 14437,  6765, 19867, 11013, 27290, 18483, 18515,
          3319,  3212, 19293, 18289,  8801, 18475, 12928, 14795, 26161, 27290,
         11013, 26424, 17296, 10456, 19294, 10210,  2387,  2387, 27483, 10395,
         16626, 21203, 13988, 14795,  2514,  6765, 10205, 10885, 12147, 26818,
         21698, 18481,  9746, 21490,  7706,  3523, 10885, 24938,  8437, 24823,
           539, 19867, 26935,  1758, 18485, 24669,  9973, 22494, 24788, 17879,
          1866,     0],
        [    1,   867, 21344, 27338,  3970, 26604, 12062,  7822,  4850, 18056,
          4088,  2866, 10480, 14410, 21344,  6202,  2656, 23767,  7822, 27338,
         17132, 26607,  5522, 20300, 25544, 17132, 18056, 26713, 21859, 14984,
          4810, 14881,  6757, 14453, 16205, 14410, 21344, 24111,  4088, 23936,
         21530,   783, 26604, 10121,  7822,  4850, 27479, 17136, 18620, 17810,
          3607,   457, 24344, 17132, 25639, 26607, 10575,  4766,  7822, 21535,
           482,  4973,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1,  6000, 11515, 21344,  8487,  4118, 11678, 16205, 13570, 22464,
         27338,  6371,  2387, 14025,  8401, 17825, 23003,  4538, 16205, 11515,
         21344,  1302,  7790, 15500, 14542, 25642,   759, 18449, 13298, 22258,
         24137, 16205, 11725, 25642, 21344, 21897, 13636, 16859, 26448, 23203,
         25642,  3517, 16205, 11515, 19566, 14542,  1429, 21344, 16205, 13570,
         22464, 14795,  6525, 17825, 14025, 26359, 13947, 25479, 16205, 11515,
         15401, 25025,  2102,  2244, 20982, 13570, 22464,  6371,  2387, 14025,
          8401, 17825,  5883, 14028, 25639, 12273, 17825,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')
tensor([[    1,  9774,  8965,  ..., 27317,  8047,     0],
        [    1, 23007,   468,  ...,     0,     0,     0],
        [    1, 13696, 23144,  ...,     0,     0,     0],

 20%|█▉        | 22/112 [00:01<00:05, 17.84it/s, loss=0.536]

tensor([[    1,  5546,  8047,  6102,   943,   480, 12798,  1617, 17204, 19452,
          7317, 19374, 13691,  4429, 11449, 12461,  4761,  9003, 11449,  5627,
          5522,  5271, 21344, 27479, 17131, 21344, 19084, 11449, 12461,  9523,
         15857, 27112, 13934, 27479,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 25593,  4562, 15602, 23052,  8750, 16005,  1473,   290, 24824,
         10303,  9973,  4988, 24368,  8750,  6193, 18851,  2367, 24787, 18475,
         24938, 20330,  2341,  8416, 21683, 25593, 15800, 16816, 24938, 20330,
          9973, 19854, 22865, 18949, 13223, 14682,  1473, 21344, 24824,  2367,
         24787, 18475, 24938, 20330, 19854, 14803, 19854, 22866, 18475,  9172,
         22571, 15800, 15199,    15, 23975,  2758, 21570, 11808,  8872, 23696,
           240, 18398, 26818,  8593,  9973,  3517,   759, 14317, 24344,  4035,
         21530, 25044,  9973, 24344, 18423,  3416,  6214, 17809,  5278, 13782,
         18562,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  8397, 15437,   488,   759, 21344,  7184,  3868, 10303,  7473,
         17881, 20930,  8780, 11203,  6951, 10301, 16626, 12408,  4457,  3685,
         20930, 16998,  1185, 14888, 26503, 25917,  4426, 22478,  7473, 15094,
         26161, 16205, 13571,  8644, 26161,  9494,  7469, 20197,  6192,  9765,
         26986, 19977, 21364, 17639, 14382, 11392, 20930, 11203,  1526, 23752,
         19457, 26503,  1758, 22213, 14323,  2821, 19143, 15555, 14881,  7637,
         14101,  2083, 18056,  4381, 12458,  7469,   914, 21344,  8772, 23508,
          5732, 10961, 26503,  3785,  8963, 21344, 25503,  5657, 12274,  2720,
         17525, 21331,  7473,   757, 15093, 18423, 26503, 27192, 22309, 13934,
         27479, 15555, 21344, 27338,  5148, 21914, 10208,  8963,  1183,   613,
          2261, 21244, 20525, 16852,  3517,  1185, 22348, 20930, 11203,  1526,
         23752,  7313, 17881, 24352,  7469, 14070, 16050, 17639,  3517,  5604,
         12440, 22899,  2982, 16391,  3910, 26503,     0],
        [    1, 13934, 27479, 13021, 12968, 26732, 14912,  8039,  8962, 12133,
         25149, 21229, 26161,  5084,   324, 13934, 27479, 27201,   526, 16626,
         14200,  9202,  8170,  5522,   759, 14223,  9202, 19232, 14113, 26161,
         18617, 17089,  8987,  4830,  4801, 26161, 18624, 19234, 25147, 16626,
         13988,   558,  5616, 12263,  1801, 13894, 26161, 25564,  8689, 13021,
         12968,  3030, 13934, 27479, 23993, 13866,  3884,  9198,  5883, 15265,
          9198, 23396, 23451,  3884, 16603, 18021, 14181,   877, 12968, 12215,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  4088, 22528, 19489, 20301, 22525, 12226, 22548,  4492, 20823,
          2933, 10174, 19999,  4088, 22528, 11286, 19680,  9873, 26417,  1394,
         25488, 11622, 22942, 19680, 20301,  9862, 22942, 24991, 10658, 16616,
         10720, 17131,  6554, 15479,  1867, 27380, 19628,  7155, 15700, 19839,
          9581,  2942, 22524, 21078, 13431, 15268,   759, 24344, 17795, 23790,
          9626,  4538, 11546, 24235, 16310, 23426,  1178, 12223, 20987,  2019,
         10234,  2186, 10101, 13058, 21945, 13009,  5837,  4274, 19828, 17143,
         16653, 13175, 22548,  4492, 19996, 26555, 17795,  1953,  2933, 10174,
         19996, 16626, 27522, 19839, 27387, 22942,  2932,  6102, 25231, 24824,
         10361, 20286, 18450, 19996,  4689, 18664, 23426, 16387, 17171, 27314,
         19168, 16470, 11570, 18056, 13484, 21533, 10456, 22942, 21312, 22942,
         19839, 21344, 21344, 22942, 22717,  1867, 27338, 27290,  1302, 22525,
         19783, 22522,   748, 14317,  1903,   546, 22528, 19683, 16010,  8854,
         20301,   468,  1778, 25199,   757, 19996, 17301, 11622,  9215, 27199,
         16654, 26882, 10205, 19994, 22309, 22955, 18739, 19839, 26935,  6887,
          7948,  4813,  4585, 17286,  3118, 20301,  7769, 11932,  6102,  2932,
          6102, 25129, 22281,  8138, 23907,  6886, 24517, 21864, 17333,  4216,
         26705,   560, 21794, 17761, 21344, 19839, 21344,  9873, 19681, 19994,
         27338, 10395,  6168, 18505, 24657, 15399, 21365, 10494, 16924, 17171,
           290,  4088, 26914, 16644, 22528, 21344, 16010, 19681, 27338, 11286,
           487, 27299,   442, 20167, 19914, 24123, 14453, 14446,     0],
        [    1, 10621,  7551,  4459,  7289,  3785, 23263, 13708, 13473, 13406,
         24738,  4459,  7289, 17070, 12274, 25370,  7551, 19310, 24133, 11896,
           702, 15863, 24840,  7473, 24693, 12226, 17171,  8436,  1492, 17155,
         10621,  1498,  8989, 25370, 17557,  1947,  6200, 11896,  5255,  5569,
          1210, 23221, 17648,  9581,  4586,  4291, 25619,  1939,  9634, 27483,
         13473, 24738,  4080,  1693,  7469, 24693, 24557,  1689,  4194,  1492,
          8795, 16868,  1061,  7289, 17089, 26982, 17155, 27194, 17155, 15863,
          7473, 24680, 17154, 26464,  1600, 17648, 23147,  9634,  6106, 11674,
          4385, 12458, 16138,  5637, 12668, 17154,  4813,  6392, 11896, 12768,
           439, 14086, 11199, 10621, 25370, 11162, 25370, 13708, 17686, 21344,
         19295,  1494, 20139, 24344, 24680,  1492,  4079,  3607, 23866, 21344,
         26818, 12411,  1128,  7289, 24680, 10422, 24738, 13473, 14000, 10647,
         12804, 21344,  6200, 15398, 16205, 13473,  8595, 11408,  5997, 25878,
          4081,  8728, 11050,  3690,  5162, 14866, 12477, 23866,  8469,    58,
         23841, 25370,  9482,  6360, 13027,  8469, 22357, 16205, 13473, 16616,
          1401, 23841, 24680, 12668, 17154,  4813,  5522, 18740, 10776,  6358,
          1693, 17171, 22357,  3785,  1048, 16205, 13473, 10301, 17239,  6570,
         19914,  3690,  9844, 13660, 23353,  4067, 23916, 10612, 24862, 17277,
          8685,  8853,  8139, 18962, 11896, 21344, 24093, 26351, 23203, 16678,
          6092, 21344, 16852,  6200, 10621,  1637, 12648,  7289, 20746,  2695,
          5148,  8112, 26368,  6200,     0,     0,     0,     0,     0],
        [    1, 10195, 11003,   957, 14451,  3656, 23542, 10195, 20251,  6582,
         23472,   957, 27115, 25434,  4559, 27479, 17131,  8111, 15675,  6648,
         21859,  5282,  6600, 20471, 12648,  4158, 21344, 22448, 21804,  1042,
         25593, 22567, 14606, 23119,  4559,  3656, 26713, 11286, 26161, 10205,
          1758, 24299,  4030, 14036, 10195, 14565, 22030, 16177,  4158, 23967,
         23119, 24231, 23379,  3071,  1270, 13027, 25264, 27122,  1180, 19681,
          7323, 20063,  9905, 21344, 26715,  4559, 19293, 24990,  4019, 16502,
          9905, 15687, 14071, 14451,  2866, 19640,  2303, 12525, 10195, 19187,
         26717, 23472,   957,  2303, 21344, 21344, 23542, 24062, 26715, 23472,
         21344, 21344, 14564, 26713, 27115, 24992, 26713, 15422, 26713, 14451,
         24788, 10426, 16521, 11286, 19867, 24789, 26717, 23472, 16326, 14881,
         23290, 23762, 15401, 10195, 26151,   957,  2695, 22441, 19854, 14803,
         23732,  9048, 16085, 13027, 25264, 27122, 16085,   757,  8691, 27096,
          4750,  8111, 10195,   290, 10609, 18482, 21690, 10404, 14036,  5862,
          4877,   759,  4030, 14036, 24789,    58, 18475, 26161,  8396, 21804,
            58, 10205, 11536, 10210, 10609, 18482, 23052,  4588, 23052, 14953,
         10494, 24840,  9634, 23052, 18483, 11286, 22040, 19640,  2303, 13664,
         26717, 13664, 23708, 23290, 10494, 20877, 18483,  2169,  1666, 20877,
         19003, 24062, 23708, 27338,  3971, 16669, 21859, 16626,  8764, 13027,
          9758, 24788,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 27091, 21535, 16616, 19566,  6294, 15233, 27091, 21535, 19566,
         21697,  4586,  8437, 22405, 22729, 16626, 14633,  6264, 12930, 16297,
         27338, 14071, 21698,  8951, 27115, 27264, 23218, 21827, 27479, 21247,
         16616, 19566,  1089, 14290,  1101, 15270, 17645, 13611, 25025,  2102,
         23221, 24040, 10301, 16297, 27032, 24938, 27091, 27499,  8625, 19823,
         22571, 16465, 26424, 22049,  1540, 21697, 14604,  9984, 14028, 20256,
          4853, 14795, 15425, 23003,  2359, 26564, 19940, 21305, 21697,  9505,
         14953, 18660, 21239, 20647, 10190,  9505,  4586,  1617, 21216,  4586,
          1089,  4820,  1401,  2525,   907,    91,  2840, 11801, 27091, 12528,
         20731, 18960,  6600, 18737, 21827, 22571, 16465, 22007, 27201, 26424,
          2405, 19868, 18737,   353, 16859, 16221, 24512,  5522, 27115, 16654,
         24840,  9984, 14596,   265, 19867,  8123, 21864,  5388, 18960,  4586,
         11292, 24509, 10715, 11292, 10715,  4586,  5522, 17765, 13934,  9293,
         15800, 25593,  6268,  5038, 25593,  9266,  9984,  5038,  2134, 12930,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0') tensor([[[-2.5383, 22.1830, -0.6804,  ..., -1.8615,  0.3213,  0.4241],
         [-4.1795, -4.0860, -1.5226,  ..., -3.3424, -1.6753, -1.0770],
         [-5.1841, -2.4587, -2.0963,  ..., -4.8787, -2.3684, -0.7549],
         ...,
         [-2.1133, -1.1198, -1.5436,  ..., -1.8933, -1.2350, -0.8976],
         [-2.0859, -0.8238, -1.5672,  ..., -1.8632, -1.1775, -0.8341],
         [-2.2294, -0.6632, -1.7202,  ..., -1.9937, -1.1215, -0.7502]],

        [[-3.6114, 21.8601, -0.9996,  ..., -2.7655, -0.0666,  0.3094],
         [-6.4272, -1.8674, -2.1551,  ..., -6.5786, -2.8609, -0.5039],
         [-7.1405, -4.7901, -2.8766,  ..., -7.3173, -4.2457, -0.7583],
         ...,
         [-3.7676, -1.1963, -1.1141,  ..., -3.9065, -2.2824, -0.8449],
         [-5.5772, -4.0994, -1.7713,  ..., -4.9169, -1.7204, -1.7516],
         [-3.2864, -1.6318, -2.1614,  ..., -3.0714, -1.5046, -0.9487]],

        [[-2.7112, 22.3421, -0.5781,  ..., -1.9756,  0.5088,  0.4728],
         [-7.3157, -2.2827, -3.8761,  ..., -6.3540, -3.0120, -2.5168],
         [-2.1799, -1.1524, -1.7558,  ..., -2.1216, -1.0797, -1.5191],
         ...,
         [-2.4979, -1.3102, -1.8433,  ..., -2.4358, -1.3304, -0.9069],
         [-2.3950, -0.9561, -1.8105,  ..., -2.3380, -1.2350, -0.8200],
         [-2.5199, -0.7538, -1.9357,  ..., -2.4343, -1.1612, -0.7264]],

        [[-2.2991, 22.2137, -0.4851,  ..., -1.4311,  0.4162,  0.7468],
         [-0.9816,  0.4926,  0.1730,  ..., -0.7961, -1.0198,  0.9600],
         [-5.2552, -3.1091, -2.0054,  ..., -4.4218, -4.1403, -1.1652],
         ...,
         [-2.1872, -1.5118, -1.5584,  ..., -2.0022, -1.4137, -0.7745],
         [-2.1447, -1.1931, -1.5445,  ..., -1.9427, -1.3473, -0.7015],
         [-2.3096, -1.0383, -1.6825,  ..., -2.0918, -1.3026, -0.6269]]],
       device='cuda:0') tensor([[    1, 21344, 22942, 22717,  1867, 27338, 27290,  1302, 22525, 19783,
         22522,   748, 14317,  1903,   546, 22528, 19683, 16010,  8854, 20301,
           468, 11622, 22942, 19680, 20301,  9862, 19839, 27387, 22942,  2932,
          6102, 25231, 24824, 10361, 20286, 16470, 11570, 18056, 13484, 21533,
         10456, 22942, 21312, 22942, 19839, 21344, 19839, 21344,  9873, 19681,
         19994, 27338, 10395,  6168, 18505, 24657, 15399, 21365, 10494, 16924,
         17171,   290, 22548,  4492, 19996, 26555, 17795,  1953,  2933, 10174,
         19996, 16626, 27522,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 13473, 14000, 10647, 12804, 21344,  6200, 15398, 16205, 13473,
          8595, 11408,  5997, 25878,  4081,  8728, 11050,  3690,  8469, 22357,
         16205, 13473, 16616,  1401, 23841, 24680, 12668, 17154,  4813,  5522,
         18740, 10776,  6358,  1693, 17171, 26818, 12411,  1128,  7289, 24680,
         10621,  1498,  8989, 25370, 17557,  1947,  6200, 11896,  5255,  5569,
          1210, 23221,  5162, 14866, 12477, 23866,  8469,    58, 23841, 25370,
          9482,  6360, 13027, 23263, 13708, 13473, 13406, 24738,  4459,  7289,
         17070, 12274, 25370, 11896, 21344, 24093, 26351, 13473, 24738,  4080,
          1693,  7469, 24693, 24557,  1689,  4194,  1492,  8795, 16868,  1061,
          7289, 17089, 26982, 17155, 11162, 25370, 13708, 17686, 21344, 19295,
          1494, 20139, 24344, 24680,  1492,     0],
        [    1, 14451,  2866, 19640,  2303, 12525, 10195, 19187, 26717, 23472,
           957, 14451,  3656, 23542, 10195, 20251,  6582, 23472,   957, 27115,
         25434,  4559, 21344, 14564, 26713, 27115, 24992, 26713, 15422, 26713,
         14451, 24788, 10426, 16521, 11286,  4559,  3656, 26713, 11286, 26161,
         10205,  1758, 24299,  4030, 14036, 10195, 14565, 22030, 16177,  4158,
         23967, 23119, 24231, 23379,  3071,  1270, 13027, 25264, 27122,  1180,
         15401, 10195, 26151,   957,  2695, 22441, 19854, 14803, 23732,  9048,
         16085, 13027, 25264, 27122,  2303, 21344, 21344, 23542, 24062, 26715,
         23472, 21344, 10195,   290, 10609, 18482,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  6294, 15233, 27091, 21535, 19566, 21697,  4586,  8437, 22405,
         22729, 16626, 14633,  6264, 12930, 16297, 27091, 27499,  8625, 19823,
         22571, 16465, 26424, 22049,  1540, 21697, 14604,  9984, 14028, 27091,
         12528, 20731, 18960,  6600, 18737, 21827, 22571, 16465, 22007, 27201,
         26424, 10190,  9505,  4586,  1617, 21216,  4586,  1089,  4820,   265,
         19867,  8123, 21864,  5388, 18960,  4586, 16859, 16221, 24512,  5522,
         27115, 16654, 24840,  9984, 14596, 11292, 24509, 10715, 11292, 10715,
          4586,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  2335,  1138,  ...,     0,     0,     0],
        [    1, 17792, 19456,  ..., 14036,  9505,     0],
        [    1, 11486, 26658,  ...,     0,     0,     0],
        [    1, 26161, 21869,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.7276, 22.3828, -0.1792,  ..., -1.1934,  0.6580,  0.8693],
         [-2.2463,  0.9787, -0.0465,  ..., -1.8729, -1.1417, -0.5984],
         [-2.7304, -2.9421, -1.7783,  ..., -2.3992, -1.8675,  0.7931],
         ...,
         [-2.0523, -0.7766, -1.1270,  ..., -2.1427, -1.0235, -0.0872],
         [-1.7751, -0.9647, -1.1570,  ..., -1.9502, -1.0307, -0.2449],
         [-1.9945, -1.3800, -1.4450,  ..., -2.2401, -1.3934, -0.6003]],

        [[-2.3500, 22.7127, -0.4379,  ..., -1.5410,  0.7121,  0.5001],
         [-1.9225, -1.3373, -0.1641,  ..., -1.8819, -0.3605,  0.4467],
         [-7.0759, -5.6180, -2.9035,  ..., -6.5822, -2.7159, -2.3465],
         ...,
         [-3.5417, -1.6103, -1.7406,  ..., -2.5548, -1.8845, -0.0258],
         [-4.2446, -0.8572, -2.0728,  ..., -3.8377, -1.5401, -0.2804],
         [-1.7671, -1.2598, -1.8803,  ..., -2.1294, -0.9019, -1.3336]],

        [[-3.0532, 21.5221, -1.0529,  ..., -2.2449,  0.0513,  0.6414],
         [-9.4480, -4.2768, -3.9105,  ..., -8.5256, -4.0685, -2.6263],
         [-5.7455, -4.5090, -2.4102,  ..., -5.9297, -1.9380, -1.6203],
         ...,
         [-2.8657, -0.8933, -1.6746,  ..., -2.7324, -1.4930, -0.3056],
         [-2.4902, -1.0333, -1.6516,  ..., -2.4460, -1.4538, -0.4273],
         [-2.6026, -1.4406, -1.8820,  ..., -2.6139, -1.7549, -0.7216]],

        [[-3.0980, 21.9194, -0.9005,  ..., -2.2938,  0.1862,  0.4686],
         [-3.1919,  2.3141, -1.4847,  ..., -2.8898, -0.9332,  0.1103],
         [-4.6549, -2.3564, -2.9769,  ..., -4.2394, -2.6285, -0.1194],
         ...,
         [-3.1409, -1.1309, -1.7560,  ..., -3.0363, -1.5299, -0.4779],
         [-2.7230, -1.2604, -1.7143,  ..., -2.7224, -1.4881, -0.6029],
         [-2.8429, -1.6370, -1.9686,  ..., -2.9207, -1.7909, -0.9496]]],
       device='cuda:0') tensor([[    1,  4125, 13182,  ...,     0,     0,     0],
        [    1, 27338, 13442,  ..., 26713, 21909,     0],
        [    1,  1474, 26463,  ...,     0,     0,     0],
        [    1, 10512, 14001,  ...,     0,     0,     0]], device='cuda:0')
tensor([[    1, 25538,  6129, 11286, 27314, 17962,  6129,  3107, 25538, 23515,
          4541,  8385, 15501,  9863, 12125, 17962, 21854, 27314, 25061,  2549,
         21344,  6129, 23767,  8397,  5523, 13934, 26882,   759, 19294,  4386,
          4422, 16322,  4281, 27381, 16205,  2549, 21344, 20483,   210, 11467,
          3118, 16980,   290, 25114, 14025, 15645, 11730, 21344,  6129, 13833,
         20609, 23934,  8385,  1061, 12896, 25538, 12798,  8385, 27338, 19297,
         12746,  3071,  8396, 20609, 27314, 16205, 11730,   290, 25114, 14025,
          1255,  8385,  5192,  6577, 24344,  5549, 13916, 25538, 16205,  2549,
         14029,   421, 25539, 15501,  6600,  5323, 24107, 11932, 12525, 25539,
         14028, 14795, 10609,   389, 12171, 11781, 20882, 20001,  6129, 17204,
          9573, 24369,   998,  3545,  6600,  8385,  6392, 25538, 19970,  5948,
           525, 12918, 24315, 13941,  6075, 25539, 18900, 19941,  8279,   123,
         16548, 10737,  5549,  9844,  8385, 15501, 12671, 19971, 23013, 17795,
          5948,  8385, 15499, 25538, 17033, 16829,  5948, 19000, 12525, 27338,
          2917,  6395, 19970,  5549,  3520, 12918, 20032, 14367,  5522, 24344,
         27483, 25538,    58, 13181,  8200,  3607, 10738, 13184, 25538, 15268,
           123, 20636, 14348, 15694,  4362,  8385,   759,  1017, 23428,   136,
         24369,  5737,  1192, 11736, 24369,  2204,  5549,  4585, 17218,  9849,
         25669, 26719,  5704, 25370,  9581, 27548,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  8286, 21876,  7623, 12166, 24567,  8264, 24035,  8286, 18745,
         20925,  9639, 19512, 19143, 24736,  4491, 14317,  6660, 24571, 26099,
         16606, 17220, 19136, 24840, 16050,  6182,  2690, 13740,  2690, 13740,

 23%|██▎       | 26/112 [00:01<00:05, 16.69it/s, loss=0.871]

tensor([[[-2.5870, 22.3727, -0.5677,  ..., -1.7887,  0.4063,  0.7301],
         [-6.1610,  0.2175, -2.6837,  ..., -6.1501, -2.4572, -1.2887],
         [-6.0458, -2.6961, -2.6092,  ..., -6.3618, -2.1266, -1.4760],
         ...,
         [-2.3454, -0.8588, -1.6209,  ..., -2.1954, -1.2288, -0.8223],
         [-2.5068, -0.8768, -1.6524,  ..., -2.2865, -1.1121, -0.6538],
         [-2.5943, -0.9769, -1.6944,  ..., -2.3171, -1.0094, -0.5341]],

        [[-2.8031, 21.6021, -0.7217,  ..., -2.1029,  0.1634,  0.4481],
         [-6.8793, -3.1469, -2.5793,  ..., -6.0784, -3.9240, -1.4275],
         [-8.0204, -3.8340, -3.7936,  ..., -7.9825, -3.8022, -3.5703],
         ...,
         [-2.9785, -1.5496, -1.6505,  ..., -2.5479, -1.5300, -0.6564],
         [-3.2821, -1.6726, -1.7696,  ..., -2.7820, -1.4780, -0.5210],
         [-3.3505, -1.8069, -1.8045,  ..., -2.8076, -1.3933, -0.3781]],

        [[-2.7829, 22.3321, -0.7017,  ..., -2.0437,  0.3215,  0.3512],
         [-2.1378,  0.0502, -1.3598,  ..., -2.1157, -0.2424, -0.1305],
         [-6.5628, -1.2221, -2.9372,  ..., -6.2141, -4.2487, -1.9528],
         ...,
         [-3.6762,  0.1831, -1.4573,  ..., -3.6791, -1.9613, -0.9434],
         [-6.6698, -2.4638, -2.1914,  ..., -6.7976, -2.2004, -0.4178],
         [-2.5787, -1.3311, -1.7699,  ..., -2.4510, -0.9283, -0.7827]],

        [[-2.5365, 22.0130, -0.6559,  ..., -2.1157,  0.1331,  0.5592],
         [-6.2972, -3.0670, -3.8345,  ..., -5.4694, -4.0596, -0.7073],
         [-4.8244, -4.5031, -2.1105,  ..., -4.2316, -2.3814, -0.1049],
         ...,
         [-3.0252, -1.6512, -1.9447,  ..., -3.1408, -1.7529, -0.9757],
         [-3.2519, -1.7100, -2.0048,  ..., -3.2859, -1.6803, -0.8309],
         [-3.3205, -1.7934, -2.0243,  ..., -3.2938, -1.5841, -0.6990]]],
       device='cuda:0') tensor([[    1,  6129,  3107, 25538, 23515,  4541,  8385, 15501,  9863, 12125,
         17962, 21854, 27314, 25061,  2549, 21344,  6129, 17204,  9573, 24369,
           998,  3545,  6600,  8385,  6392, 25538, 19970,  5948, 25114, 14025,
          1255,  8385,  5192,  6577, 24344,  5549, 13916, 25538, 25114, 14025,
         15645, 11730, 21344,  6129, 13833, 20609, 23934,  8385,  1061, 12896,
         12671, 19971, 23013, 17795,  5948,  8385, 15499, 25538, 17033, 16829,
          5948, 19000, 12525, 27338,  2917,  6395, 19970,  5549,  3520, 12918,
         20032, 14367,   525, 12918, 24315, 13941,  6075, 25539, 18900, 19941,
          8279,   123, 16548, 10737,  5549,  9844,  8385, 15501,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 27032,  8286, 20702, 16588, 19136,  2690, 13740,  4850, 14601,
          2690, 13740, 17220, 19136, 24840, 16050,  6182,  2690, 13740,  2690,
         13740, 13934, 27479, 11736,  4845, 20329, 17257,  7623, 17424, 21365,
          9639, 19512, 21100,  2690, 13740, 21365,  4501,  2454, 13740,  2690,
         13740,  8286, 22153,  7460, 13740,  7615, 25219, 24884,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  8111, 16543, 26818, 25147,  7400, 27115, 21216, 27314,  5862,
         22050, 11600, 13685, 16654, 16048,  8111, 21394,  9673, 12930, 10177,
          4227, 24339,  8111,  9266, 21216, 27314,  5862, 22050, 22405, 12224,
         14327, 13995,  5988, 15233,  6099,  8111,    55,  6646, 27115, 27314,
          5862,  5657, 23223, 11471, 16455, 11536, 22050, 27314,  5863, 24938,
         21344,  8111, 22050,  4586, 15700,  9765, 25076, 25593, 22415, 18655,
         19496,  8111,  5522,  8761, 27149, 16626, 27584, 19512,  9180, 23798,
         21394,  8111,  8875, 19994, 11600, 13685, 13934, 24840, 27483, 27314,
          5862,  6759, 14200,  8111,  9266,  8441, 12668, 21216,  2695, 27314,
         22050, 22007,  7495, 22696,  9639, 24299,  8795,  3287, 26424,     0],
        [    1,  4789, 21530,  6129,  8394, 17581, 14299,  6540,  8526, 14542,
          4747, 17765,   895, 14408, 23594,  8529,  5522, 18768, 17077, 14650,
          5492, 21517,  6129,  6660,  2724, 17683,  8397, 23594, 15093,  8394,
          1178, 14542, 23594,  8526, 18739, 24348,  2428, 17077,  9483, 27053,
         15425, 23119,  8394, 27338, 14881, 17077, 14650, 11736,  8394, 21344,
          5522, 10737, 23340,  9260, 17077, 27338, 14795, 14650, 24369,  8397,
         23594, 15093, 20942,  2429,  6660,  2724,  5271, 14650, 21344, 26883,
         20470, 24570, 19580, 25959,  8552,  8394, 21533, 10711, 27338, 14881,
          3789,  2428, 25466,  6660,  2724, 17077,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 25639,  6163,  ...,     0,     0,     0],
        [    1,  5998, 13290,  ...,     0,     0,     0],
        [    1, 26161, 12648,  ...,  4766,  8047,     0],
        [    1,  2549,  5995,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1785, 22.5555, -0.4011,  ..., -1.4330,  0.6056,  0.6865],
         [-3.9413, -1.1936, -2.0185,  ..., -4.6775, -2.3691, -1.4309],
         [-6.6265, -4.8367, -3.6751,  ..., -5.5462, -2.1896, -0.2806],
         ...,
         [-2.7715, -1.4364, -1.8234,  ..., -2.4128, -1.1183, -0.5283],
         [-2.4376, -1.0855, -1.7111,  ..., -2.0811, -0.9149, -0.4967],
         [-2.2292, -0.9246, -1.5678,  ..., -1.8945, -0.8302, -0.5045]],

        [[-1.7634, 22.5371, -0.0954,  ..., -0.8756,  0.7306,  0.8900],
         [-5.5598, -0.6996, -2.7577,  ..., -4.6690, -2.7491, -1.1751],
         [-4.2767, -4.2129, -1.2708,  ..., -3.2275, -1.7667, -0.7155],
         ...,
         [-2.5860, -1.1472, -1.3650,  ..., -2.0877, -1.0743, -0.1378],
         [-2.3866, -0.8703, -1.3121,  ..., -1.8856, -0.9237, -0.1360],
         [-2.1430, -0.6728, -1.1455,  ..., -1.6702, -0.8058, -0.1048]],

        [[-2.3134, 22.5836, -0.4852,  ..., -1.5029,  0.5462,  0.3487],
         [-6.4491, -1.7907, -3.1072,  ..., -6.0691, -3.3546, -2.4966],
         [-6.4678, -2.4619, -3.2539,  ..., -6.2064, -3.2707, -0.7958],
         ...,
         [-3.5286, -2.6001, -1.8948,  ..., -3.8503, -1.0543, -0.5593],
         [-3.2752, -1.2788, -1.5938,  ..., -2.4800, -1.0379,  0.3910],
         [-2.9308, -1.7781, -2.0556,  ..., -2.7758, -1.2279, -1.2715]],

        [[-3.4793, 21.7356, -1.1042,  ..., -2.8249,  0.0680,  0.1843],
         [-3.0443, -1.3626, -0.5099,  ..., -2.6121, -1.1169, -0.9981],
         [-2.8015,  1.0894, -0.0784,  ..., -2.2432, -0.9881,  1.5224],
         ...,
         [-3.5558, -2.1374, -2.3009,  ..., -3.3248, -1.6758, -0.8841],
         [-3.4297, -1.9162, -2.2858,  ..., -3.1915, -1.5730, -0.9137],
         [-3.3079, -1.7986, -2.1720,  ..., -3.1058, -1.5269, -0.9214]]],
       device='cuda:0') tensor([[    1,  2709,  6048, 17171, 10611,  8170, 27314,  8447, 13663, 27499,
          6745, 27529, 13574,  9570, 21344, 23035, 18901, 23035, 27387,  6839,
         23424,  9157, 12540, 14290,  5749,  2709,  6048, 25372, 22932, 24789,
         20337, 24358, 21344, 23035,  6048, 22532, 22944,  9157, 22995, 13636,
            83, 16859,  2709,  6048,  9157, 11765,  8858, 21344,  2871,  1547,
         18901,  3118,  2936, 17328,  2648, 11561, 23426, 13496, 23035, 13405,
          2871,  1547,  3118, 18901, 16626,  9157,  2405, 21774, 14542, 14128,
         23294, 24884, 23035,  7311, 17352, 27148, 14551,  8908, 23645, 22524,
          2709,  6048,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 13459, 21344, 16580, 15448,  5998, 13290,    82, 11337, 15151,
         18669, 23411,  5998, 13290,   949, 26790, 11472, 23340, 26368,  4429,
          9157,  4088, 18092, 14542, 26945,  8047,  9266, 24938,  5998, 13290,
         22329,  8847, 16405,  7002, 16183, 21874, 16311, 23341, 19026,  7750,
         24747,  9943, 18092, 21525,  5998, 13290, 20701, 24747,  9266, 23425,
         21044, 18092, 11806,  7536,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1,  8986, 17204, 15093,  4813, 22036, 12648, 19780, 18611, 26161,
         26605, 25689,  8945, 19512, 18581, 20925, 26161, 12648, 19782, 20925,
          9639, 24938,  9293, 16050, 27046,  1065, 16177,  8986, 10541,  7640,
         19782, 22513, 23967, 19512, 18075, 18581, 20928, 13304,  1600, 21982,
         20925, 26161, 19782, 25947,  6837,  2129, 25639, 16008, 18611,  8987,
         20539, 19681, 13498,  8987,  9873, 19780, 19512, 18075, 18581, 14308,
         16163,  8469, 26161,  7700, 20149, 23485, 23443,  8986, 21344, 14551,
         24650, 12390, 18962, 20329, 26919,  5230, 26161,  7700,  1131, 10718,
         15944, 17600,  6600, 20925,  8086, 19006, 20470, 19360, 26876,  1926,
         21344, 19782,  5883, 14200, 12390, 27338, 20925, 24432, 27199, 25593,
         27483, 24789,  8987, 20539, 26713, 21010,  2703, 26183, 10540,  1177,
         19683, 12648, 19780, 21344, 23979, 22889,  4199, 26161,  7698, 26926,
          8891,  1926,  1926,  8111, 13484, 12648, 19782, 11536, 17857, 24840,
         16050, 14029,  4789,  1254, 19782, 15268, 17970, 19939,  8469, 18582,
         26143, 26161,  7700,     0],
        [    1, 25122, 18629, 21344, 24270, 16205,  2673, 21533, 16506, 10885,
         24112, 21344, 16205,  2673, 20701,  3463, 13793, 16654,  7822, 15400,
         21344, 16205,  2549, 10456, 19019, 15783,  6866, 24806, 18068,  3936,
         21344,   439, 22348, 16205,  2673,  5522, 25475, 15783,  6866,  9609,
         24840, 18068,  3936, 24824, 16205,  2673,  7257, 10456, 13155, 11570,
         21835,  6866, 21344, 16205,  2673, 22030, 10456,  8501, 26716, 24344,
         20604,  4207, 21535,  1768, 14101,   244,  4850, 24824, 25704, 24840,
         19514, 21344, 16205,  2673, 20877, 10395,  5569, 20877, 21859, 16207,
         19559, 22940, 21535,  8929, 26567, 24270, 16207, 19559,   744, 19512,
         18629, 23975, 24944, 21344, 20701,  3463, 23657,  7822,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 11765, 21260,  ...,     0,     0,     0],
        [    1, 15785, 16382,  ...,     0,     0,     0],
        [    1,  1399, 13074,  ..., 13074, 12517,     0],
        [    1, 24462, 14724,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7446e+00,  2.2066e+01, -5.7971e-01,  ..., -1.8321e+00,
           3.6982e-01,  7.0160e-01],
         [-9.1942e+00, -6.3158e+00, -5.5634e+00,  ..., -8.6771e+00,
          -3.1437e+00, -3.6723e+00],
         [-5.7633e+00, -3.9624e+00, -1.9751e+00,  ..., -5.6318e+00,
          -3.5659e+00, -2.1059e+00],
         ...,
         [-2.4926e+00, -9.7046e-01, -1.6549e+00,  ..., -2.0141e+00,
          -1.0545e+00, -2.7159e-01],
         [-2.4963e+00, -1.2610e+00, -1.6771e+00,  ..., -1.9950e+00,
          -1.1167e+00, -4.0398e-01],
         [-2.3405e+00, -1.2404e+00, -1.5488e+00,  ..., -1.8195e+00,
          -1.1234e+00, -4.9720e-01]],

        [[-2.3151e+00,  2.2601e+01, -5.7562e-01,  ..., -1.6712e+00,
           4.4651e-01,  3.7399e-01],
         [-3.7598e+00, -1.9613e+00, -8.7915e-01,  ..., -2.5912e+00,
          -1.1002e+00, -2.5520e-01],
         [-3.3132e+00, -2.2029e+00, -1.2218e+00,  ..., -3.1762e+00,
          -1.5906e+00,  5.0903e-02],
         ...,
         [-4.4099e+00, -3.4029e+00, -2.6413e+00,  ..., -4.4051e+00,
          -2.6052e+00, -4.3402e-01],
         [-4.0954e+00, -5.2290e+00, -2.4757e+00,  ..., -4.4511e+00,
          -3.0497e+00, -1.7319e+00],
         [-2.1612e+00, -1.0092e+00, -1.9066e+00,  ..., -2.0649e+00,
          -1.0949e+00, -1.1216e+00]],

        [[-3.1842e+00,  2.2201e+01, -9.1325e-01,  ..., -2.4909e+00,
           1.1250e-01,  2.6805e-01],
         [-5.2364e+00, -4.9152e-02, -2.0893e+00,  ..., -5.6108e+00,
          -1.6184e+00, -3.4010e-02],
         [-3.1322e+00, -2.6572e-01, -1.9312e+00,  ..., -2.7814e+00,
          -1.2722e+00,  2.2160e-02],
         ...,
         [-3.3269e+00, -1.1899e+00, -2.5918e+00,  ..., -3.1364e+00,
          -1.3819e+00, -1.1318e+00],
         [-3.2648e+00, -1.3987e+00, -2.5633e+00,  ..., -3.0432e+00,
          -1.4223e+00, -1.2369e+00],
         [-3.2365e+00, -1.4790e+00, -2.4853e+00,  ..., -3.0030e+00,
          -1.4966e+00, -1.3549e+00]],

        [[-1.7931e+00,  2.2334e+01, -1.4678e-01,  ..., -9.4420e-01,
           8.0065e-01,  9.3037e-01],
         [ 1.9412e-01, -7.7520e-02, -2.7194e-01,  ..., -2.1517e-01,
           3.2414e-01,  9.4712e-01],
         [-5.3344e+00, -3.4550e+00, -3.9391e+00,  ..., -4.9817e+00,
          -2.2818e+00, -1.3374e+00],
         ...,
         [-2.8013e+00, -1.6061e+00, -1.8960e+00,  ..., -2.3732e+00,
          -1.3618e+00, -4.6629e-01],
         [-2.7151e+00, -1.8012e+00, -1.8501e+00,  ..., -2.2562e+00,
          -1.3683e+00, -5.4962e-01],
         [-2.5164e+00, -1.7580e+00, -1.7015e+00,  ..., -2.0529e+00,
          -1.3452e+00, -6.0444e-01]]], device='cuda:0') tensor([[    1, 12285,   573, 13114,   585, 12443, 19349, 17079, 17546, 24944,
          1931, 21344,  9765, 13114,   585, 14633,  8885,   573,  9629, 14542,
          2032,  8487, 25313,   491, 16426, 10519,  5319, 12285,  7230,   573,
         15093, 12284,  2200, 17204,  7230,   573, 15093, 19000,  7235, 23440,
         21239,  3745, 12285,   576, 19003, 22153,  2204, 25219,   525, 26883,
          1931, 21344,  2433, 11395,  8047, 19003, 19727, 21253,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 13046, 22894,  8385,  9543, 18611,  4199, 21535, 18267, 24415,
          8469, 27308,  5580,  8397,  5548, 16205, 22894, 25025, 12939, 13209,
          6791, 19151, 18267, 24415,  8469,  5569, 27308, 16816,  7257, 27338,
         16382, 11570, 21835,  4092,  4420, 21535,  8469, 27338, 14881, 16221,
          6757,  3787, 11781, 20882, 10712, 25076, 18606, 17085, 15024, 16203,
         21530,   732,  8469, 27338, 20370, 16521,  6624, 24670, 24131, 27201,
          4079,  5734, 18267, 24415, 25367, 21530,  8469, 17107, 26827,  8684,
         15617, 21854, 22024, 10512, 16382, 20142,   727, 18267, 24415,  8469,
          5569, 21943,  8385, 18623, 21535, 22055, 24131,  6625, 18802,  8469,
          6247, 21955, 11198,  5569, 11570, 21835, 21535, 12641, 27338, 14881,
         16221,  6757,  3787, 24670, 24131,  9755, 20323, 13577, 24110,     0],
        [    1, 13134, 13905, 26403, 18949, 21794, 19218,  1399, 13074, 26161,
         21344,   227,  2634, 10205,  9511,  2628, 19364, 27314,  1399, 13074,
         21344, 18449,  4044,  2634, 27338, 26170, 15731,  1346,  1229, 21135,
         12280, 26850, 24823, 16205, 13905,   290,  1399, 13074, 27338, 11290,
         17298,  6072,  2628,  8198,  2634, 11541, 16588, 12283, 24534, 27338,
         12554, 24202,  4049,  2634, 21344, 16205, 13905, 27338,   759, 11286,
          7447, 12408,  8198,  2636, 18695,  1399, 13074, 17218, 16221,  1399,
         13074, 17635,  2634, 20721, 21344,  1399, 13074, 16221, 12649, 11290,
         18056,  9193, 12408, 14566, 19783, 11290, 27374, 16205, 13905, 21344,
           230, 27338, 22555, 26919,  1399, 13074, 22023, 14191, 18056,  5911,
         26850,  8625,  3287, 18149,  4689, 26173, 14385,     0,     0,     0],
        [    1, 27483, 21338, 23594, 19003, 22049, 27479, 11372,  9825, 17171,
          3115, 26329, 15020, 20702, 26301, 12280,  9520, 21344, 23928, 10711,
            80,  9825, 22049, 27483, 16205,  9046, 11287, 20701, 10721, 24462,
         14724,  4199,  8552, 16388,  8397,  3403, 27479, 14029,  3401, 14813,
         11899,  9046,  1703, 24990, 26161, 19350,  9520, 20703, 17171, 25639,
         26329, 15020,  5549, 25076,  4842,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 15312, 24435,  ...,     0,     0,     0],
        [    1,  2549, 16182,  ...,     0,     0,     0],
        [    1, 14541, 20314,  ...,     0,     0,     0],
        [    1,  9973, 14887,  ...,  9522, 21344,     0]], device='cuda:0') tensor([[[-2.4827e+00,  2.2279e+01, -4.0008e-01,  ..., -1.6145e+00,
           3.5482e-01,  6.1256e-01],
         [-4.7752e+00, -7.6402e-03, -1.3919e+00,  ..., -3.5476e+00,
          -1.0071e+00, -1.3969e+00],
         [-3.7195e+00, -9.2944e-01, -1.6264e+00,  ..., -3.1964e+00,
          -2.4149e+00, -1.0309e+00],
         ...,
         [-2.0825e+00, -6.8500e-01, -1.1000e+00,  ..., -1.6413e+00,
          -1.0303e+00, -4.1443e-01],
         [-2.0589e+00, -5.1199e-01, -1.0256e+00,  ..., -1.5034e+00,
          -9.8609e-01, -3.7873e-01],
         [-2.0808e+00, -3.7260e-01, -9.9328e-01,  ..., -1.4113e+00,
          -9.4622e-01, -2.7168e-01]],

        [[-2.3777e+00,  2.2370e+01, -5.1409e-01,  ..., -1.5669e+00,
           5.8011e-01,  5.5654e-01],
         [-1.9528e+00, -1.6028e+00, -1.7253e+00,  ..., -2.2321e+00,
          -1.1319e+00, -5.4028e-01],
         [-5.9403e+00, -4.7630e+00, -2.3103e+00,  ..., -6.2033e+00,
          -2.7742e+00, -1.6002e+00],
         ...,
         [-4.1101e+00, -2.1017e+00, -2.0727e+00,  ..., -4.0917e+00,
          -1.6526e+00, -1.1009e+00],
         [-6.4255e+00, -3.6766e+00, -3.3256e+00,  ..., -6.3156e+00,
          -3.1371e+00, -9.6356e-01],
         [-2.2929e+00, -1.0304e+00, -1.6349e+00,  ..., -1.9731e+00,
          -7.6655e-01, -1.0636e+00]],

        [[-2.6846e+00,  2.2117e+01, -4.8925e-01,  ..., -1.9948e+00,
           3.4655e-01,  4.7093e-01],
         [-6.7464e+00, -3.7218e+00, -1.4746e+00,  ..., -7.0711e+00,
          -3.7452e+00, -2.3237e+00],
         [-2.5857e+00,  1.5132e+00, -2.1513e-01,  ..., -2.2945e+00,
          -1.0599e+00, -1.4803e+00],
         ...,
         [-1.6901e+00, -1.1901e+00, -1.1928e+00,  ..., -1.5126e+00,
          -7.0813e-01, -7.8348e-01],

 25%|██▌       | 28/112 [00:02<00:04, 17.14it/s, loss=1.37]

tensor([[    1, 25135, 25556,  ...,     0,     0,     0],
        [    1,  6090,  2673,  ...,     0,     0,     0],
        [    1,  8397, 14602,  ...,     0,     0,     0],
        [    1, 26752, 25488,  ...,   307, 21932,     0]], device='cuda:0') tensor([[[-2.2382e+00,  2.2076e+01, -3.9275e-01,  ..., -1.3861e+00,
           4.1155e-01,  8.3672e-01],
         [-1.6832e+00, -4.4803e-01, -1.2457e+00,  ..., -1.8019e+00,
          -1.5394e+00, -2.1976e-02],
         [-2.1524e+00, -1.2461e+00, -9.9513e-01,  ..., -1.8108e+00,
          -5.2820e-01,  5.7720e-01],
         ...,
         [-2.4933e+00, -1.2914e+00, -1.1910e+00,  ..., -1.8019e+00,
          -1.1079e+00, -3.6697e-01],
         [-2.7216e+00, -1.1406e+00, -1.2057e+00,  ..., -2.0643e+00,
          -1.2111e+00, -3.2329e-01],
         [-2.8459e+00, -1.0430e+00, -1.2289e+00,  ..., -2.2473e+00,
          -1.3156e+00, -2.8932e-01]],

        [[-2.7878e+00,  2.1998e+01, -7.4135e-01,  ..., -2.1215e+00,
           2.6308e-01,  4.4871e-01],
         [-6.2589e+00, -2.0275e+00, -2.4449e+00,  ..., -5.7291e+00,
          -2.5065e+00, -7.6355e-01],
         [-9.6811e+00, -5.0020e-01, -4.3816e+00,  ..., -9.7410e+00,
          -4.3007e+00, -2.0469e+00],
         ...,
         [-3.3118e+00, -2.0243e+00, -1.6683e+00,  ..., -2.8085e+00,
          -1.5802e+00, -8.1339e-01],
         [-3.5501e+00, -1.9094e+00, -1.6727e+00,  ..., -3.0445e+00,
          -1.7046e+00, -7.6671e-01],
         [-3.7714e+00, -1.9468e+00, -1.7322e+00,  ..., -3.3259e+00,
          -1.8733e+00, -7.3999e-01]],

        [[-2.9026e+00,  2.1572e+01, -6.7946e-01,  ..., -2.1455e+00,
           1.1922e-01,  3.3207e-01],
         [-6.8839e+00, -2.9267e+00, -2.5368e+00,  ..., -6.0965e+00,
          -4.1352e+00, -1.4827e+00],
         [-7.3689e+00, -3.5710e+00, -3.1269e+00,  ..., -6.7919e+00,
          -3.6185e+00, -2.7525e+00],
         ...,
         [-3.7914e+00, -2.3319e+00, -1.6827e+00,  ..., -3.1185e+00,
          -1.9336e+00, -7.9024e-01],
         [-3.9672e+00, -2.2197e+00, -1.6630e+00,  ..., -3.3065e+00,
          -2.0198e+00, -7.2126e-01],
         [-4.0587e+00, -2.1232e+00, -1.6551e+00,  ..., -3.4593e+00,
          -2.1223e+00, -6.6086e-01]],

        [[-2.9756e+00,  2.2249e+01, -6.2806e-01,  ..., -2.1545e+00,
           3.0262e-01,  3.4717e-01],
         [-4.5957e+00, -4.7116e+00, -1.8507e+00,  ..., -3.8284e+00,
          -2.0302e+00, -1.4828e+00],
         [-5.0623e+00, -4.0368e+00, -2.1028e+00,  ..., -4.5919e+00,
          -9.6442e-01, -1.5205e+00],
         ...,
         [-2.9539e+00, -1.8264e+00, -6.6045e-01,  ..., -3.0814e+00,
          -1.7723e+00,  1.2298e-01],
         [-2.9805e+00, -1.4121e+00, -9.5986e-01,  ..., -3.3506e+00,
          -1.9210e+00,  1.5768e+00],
         [-3.8218e+00, -2.3036e+00, -2.0312e+00,  ..., -3.5959e+00,
          -1.7125e+00, -1.2960e+00]]], device='cuda:0') tensor([[    1, 25076, 18670, 25547, 23411,  7906, 18953, 16311, 12989, 21010,
         13939, 21010, 14107, 21673, 25639, 24718, 16924, 17171, 22528, 15083,
         13680, 18489, 18953, 21044, 23340, 22522, 17171, 16709,  9765,  2102,
         17171, 22340, 19115, 25672, 26170, 18953, 26426,  9504, 13680, 14323,
          1128, 22340, 16654, 26882, 16654, 18953, 20286,  9497,  5567, 10298,
         24797, 16924, 17171, 24840, 26886, 25076, 18670, 23205, 21344, 23090,
         16924, 17171, 25639, 24718,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 24789,  1088, 21530, 21344, 17171, 24787, 19349,  7257,  1042,
         19057, 27290,  9746, 10512, 11766, 23890, 21344, 16205,  2673,  6090,
          2673, 20559, 11570, 21835,  3294, 20501, 18435, 23083, 27525, 14948,
         27338,  6028, 24669, 18818, 18838,   783,   123, 20604,   783,   123,
          5138,   246,  9500, 24824,  3912,  7725, 27338, 20282, 16816, 25474,
         18435, 23083, 23657, 24368, 22935, 15237, 16221, 18623, 14948,  6193,
         26582, 20504, 12274, 20746,   699, 15886, 18724,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 27032, 10382,  7618,  2690,  2690,  1028, 20734, 21100,  2690,
         10382, 20735, 21100,  2690,  2690, 27479,  7612, 10121, 16147, 21525,
         16588, 19143,  8829, 13934, 19512,  5272, 11472, 14602,  8397, 17224,
         26161, 10232,  7618, 17047,  6182, 18104,  2690,  9639, 19512, 10382,
         21344, 19143,   759, 11472, 11395, 11189,  5506, 26161,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 21344, 23042,  7599, 14855,  6840, 18056, 22558, 23430,  4343,
         25593,  6106,   517, 22325,  7225, 16387, 22558, 20171, 21344,  6168,
         11623, 10205,  8820, 22558, 22384, 22955, 18739, 22558, 13943, 14551,
         14412, 21550, 25481,  3789, 10469, 10127, 25488,  6886, 17884, 21413,
         23206,  6886,  7948,  4813, 21344,  1706, 22558,  5224,  4948,  5703,
         25920, 21697, 27464, 11286, 10205, 22384, 16208, 21413, 21344,  6168,
          5224, 26161, 16588, 20176, 10956,  7225, 17579, 16588, 11685,  9260,
         13445, 22558, 26850,  6168, 10426, 19449,  3789,  7252, 26390, 22558,
         10945, 17087, 17296, 16798,  7599, 14850,   307, 24034, 22558, 27290,
         19854, 17577,  7225, 16994, 19358,  1666, 16588, 20001,  1540,  2102,
         16644, 26867,  5223, 18056,  2219, 22558,  8794,  3243,  6168, 11685,
          4845,   759, 14891,  7771, 10205, 22558, 22384, 21344, 26850,   305,
          8820, 22558,  6237, 17293,  5522,  4538,  8141, 17087, 27399,  6168,
         17293, 25639,   305,  5067, 18056, 13437,  7251,     0]],
       device='cuda:0')
tensor([[    1,  6015, 16310,  ..., 26748, 13657,     0],
        [    1,  4227, 27129,  ...,     0,     0,     0],
        [    1, 14587, 27381,  ...,     0,     0,     0],
        [    1,  4704,  3522,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6909, 22.4614, -0.4580,  ..., -1.9269,  0.4333,  0.3962],
         [-7.0875, -3.3294, -2.6733,  ..., -7.1895, -3.7521, -2.6268],
         [-3.5944, -2.9779, -0.8507,  ..., -2.9025, -1.7838, -1.6448],
         ...,
         [-5.1827, -2.4824, -1.4876,  ..., -4.9883, -2.4221, -2.5199],
         [-3.7873, -1.4480, -0.5758,  ..., -3.6151, -1.7303, -1.9321],
         [-0.9229,  0.2867, -0.9372,  ..., -0.6573, -0.4745, -0.5333]],

        [[-1.6799, 22.5504, -0.3381,  ..., -0.8975,  0.7989,  0.6720],
         [-2.9460,  0.9529, -1.7698,  ..., -3.8852, -1.8480, -1.6128],
         [-5.2889, -3.4039, -3.1006,  ..., -5.4557, -2.8828, -3.4920],
         ...,
         [-2.7766, -1.0531, -1.6109,  ..., -2.2957, -1.4352, -0.6284],
         [-2.4913, -0.6038, -1.4382,  ..., -1.9647, -1.2691, -0.5255],
         [-2.3348, -0.3745, -1.2951,  ..., -1.7869, -1.1715, -0.4736]],

        [[-3.2278, 21.9122, -0.8949,  ..., -2.5246,  0.1678,  0.3776],
         [-4.3970, -4.9264, -1.6948,  ..., -3.6680, -1.8567, -1.1611],
         [-7.1894, -3.5200, -4.3036,  ..., -7.2680, -3.2911, -1.9302],
         ...,
         [-2.3006, -0.7642, -1.6871,  ..., -2.1295, -1.1429, -0.7006],
         [-2.0234, -0.3288, -1.5508,  ..., -1.8075, -1.0288, -0.6296],
         [-1.8430, -0.0758, -1.4372,  ..., -1.6056, -0.9280, -0.5684]],

        [[-2.3931, 21.9699, -0.5975,  ..., -1.7518,  0.3614,  0.7898],
         [-3.3538, -1.4895, -2.4064,  ..., -3.1437, -1.0592, -1.0420],
         [-5.7447, -2.4937, -2.2720,  ..., -4.7545, -2.1904, -0.1745],
         ...,
         [-2.1703, -0.9267, -1.3164,  ..., -1.7639, -1.3045, -0.2345],
         [-1.9564, -0.4937, -1.2055,  ..., -1.5171, -1.1797, -0.1830],
         [-1.7066, -0.2416, -0.9980,  ..., -1.2411, -1.0398, -0.1102]]],
       device='cuda:0') tensor([[    1,  7155, 16819,  5365,   598,  8924, 22688, 21344,  6015, 16310,
          6119,   353,  5885, 10426,  8836, 17861,  5365,   219, 16221,  4044,
          6015, 27314,  9634, 27483, 22513, 13934,   630, 10887, 10821, 23426,
         23713, 15393,  6015, 21589, 18116,  8458, 26882, 14891,   630, 19846,
          1346,  6406,  6015, 16310, 17019,   446, 22938, 25025,  2102, 27314,
         22023, 24900, 19151, 24789,  5128, 23826, 19846,  8458, 26882,  6015,
         16310,  6119, 27338, 24789, 20877, 21746, 25199, 24305, 24787,  6765,
         24944,  5365, 21344,  5769,  2436, 26847, 16669,  1509,  8437, 10395,
         10456, 10887,  9266, 19994, 24789, 10494,  5365, 21344, 17807, 21344,
         23774,  5388, 24305, 12733, 24611,  3018, 15119, 19628, 17171, 18936,
         27617,  1866, 14382,  7155,  6012, 18061,  6674, 14023, 23931,  6015,
          9215, 18673, 16310, 10153,  4794,  8798, 13943,   631,  3115, 25593,
          2438,  6015,   263,  8924, 22688, 17676, 19111,   783, 17427, 16616,
         17406,  5559,  4547, 15024, 23995,  9469, 24840,  6015, 16310, 14814,
          9266,  6358, 13200, 25523, 18056, 24789,  6515,  8644, 21344,  6648,
         10995,  1866,   441,   630, 21344, 27617, 25199,  3517, 15166,  1747,
         26935, 14096, 15752,   630,  7573, 20912, 22030,  2438, 21912, 27479,
             0],
        [    1, 27459, 23440,  1443, 14952,  3345, 10512,   488, 16825,  7646,
          4366, 27459, 17581,  4053,  5222, 27129,  4226, 23566, 14633, 14436,
         18068,  3636, 21344, 26161,   531,  6469, 12930, 12033, 21466,   525,
          3429,  4053, 13919, 27129, 14886,  4226,  4227, 27129, 21365, 10718,
         26161,   531,  6469, 21344, 27129, 21365,  2690, 27540, 12927, 14399,
         14886,   227, 22153, 27459, 23440,  1443, 14952,  3345,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 21344, 13988, 14587, 21230,  7925, 10512, 14874,  4049, 16522,
         13988,  9543, 21835, 21344, 20877, 14290, 12126, 14255, 10512,  7570,
         19262, 18056, 24672, 16626, 11570, 21835,  4092,  4420, 26613, 16735,
         15516, 27338, 20327, 19051, 13988, 20747, 24884, 14586,  2465, 21943,
         13988, 14586, 21344, 21229, 12233,  8397,  5330, 11781, 20882,   731,
          6639, 26818,  6939, 10703, 16462, 12073, 23463, 13332,  6638, 27201,
         25364,  9543, 24131,  3123, 14586, 16675,  2494, 21230, 21344, 12268,
         12160, 27201,  4079, 25364,   922,  5549, 17001, 21226, 13988, 21344,
         11268, 20877,  1124, 23090, 12073,  1124, 25370,  6200, 11536, 24131,
         26105,  5569, 13988, 14587, 22496, 27381, 12122,  6200,  6624, 18056,
         26991,  3973, 11570, 21835, 25025,  2102, 19628, 25008, 19151, 13988,
         14587, 22496, 27381, 12122, 15516, 11268,  1208, 14237,  6409, 17999,
         14586,  3710, 10512, 12274, 20748,  1061, 24672, 13996, 21344, 18739,
          6627,  5522, 20287,  3785, 11198, 17700, 16735, 13988, 14587, 19783,
         26185,  9293,  5193, 12125,  3785,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 27314,  4028, 13571,  4704, 21535, 24133, 23262,  7577,  4024,
           731,  4867, 17155,  4704, 21535,  3118, 17154,  1458, 20740,  6200,
          1897, 17155, 14290, 11071,  4704, 25025, 19628,  9293, 14442,  4704,
           290, 10609, 10822, 16616, 19088,  4024,  1939, 25593, 27483, 24690,
         18729,   902, 23539, 24778, 24137, 21248, 16894, 27479,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0]], device='cuda:0')

 29%|██▊       | 32/112 [00:02<00:07, 11.39it/s, loss=0.974]

tensor([[    1,  7962, 21833,  ...,     0,     0,     0],
        [    1, 21136,  5273,  ..., 22124, 20332,     0],
        [    1, 19521, 20017,  ...,     0,     0,     0],
        [    1,  2142, 20701,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6720, 22.1799, -0.6452,  ..., -1.9608,  0.3896,  0.7101],
         [-4.6461, -2.2954, -1.5612,  ..., -4.9797, -1.6477, -0.6753],
         [-5.7282, -1.2038, -2.5546,  ..., -6.0322, -2.6597, -0.7106],
         ...,
         [-3.1775, -1.4422, -1.6534,  ..., -2.7863, -2.4637, -1.0329],
         [-3.2541, -1.1601, -1.6457,  ..., -2.8297, -2.4606, -1.0132],
         [-3.3419, -0.9111, -1.6359,  ..., -2.9391, -2.4537, -1.0109]],

        [[-1.7980, 22.6562, -0.2605,  ..., -1.1839,  0.8750,  0.5357],
         [-2.0082,  1.1537, -0.7851,  ..., -1.8567, -0.1789, -0.6238],
         [-1.3121, -0.9144, -0.5345,  ..., -1.6401,  0.1011, -0.6342],
         ...,
         [-1.2647, -0.2091,  0.5678,  ..., -0.9957, -1.6445, -0.5100],
         [-2.8253, -2.3554, -0.9125,  ..., -2.8806, -1.3000, -0.0300],
         [-0.2841,  0.4595, -0.6087,  ..., -0.2490, -0.5609, -0.7686]],

        [[-2.4916, 21.9925, -0.5319,  ..., -1.7602,  0.2992,  0.6017],
         [-5.7587,  0.1520, -3.4532,  ..., -5.9221, -2.9936, -1.2528],
         [-7.3481, -4.0001, -3.4574,  ..., -7.3834, -3.7875, -2.5821],
         ...,
         [-3.0874, -1.4517, -1.5885,  ..., -2.6492, -2.3512, -1.0310],
         [-3.2610, -1.2786, -1.6397,  ..., -2.7990, -2.3927, -1.0450],
         [-3.3301, -1.0504, -1.6135,  ..., -2.9125, -2.3893, -1.0332]],

        [[-2.9108, 21.5779, -0.7576,  ..., -2.1667,  0.1340,  0.8449],
         [-5.8567, -0.5187, -2.9776,  ..., -5.2034, -3.7234, -1.4580],
         [-3.9952, -2.0241, -1.7844,  ..., -4.2096, -2.2511,  1.0839],
         ...,
         [-3.1745, -0.8716, -1.7119,  ..., -2.6631, -2.3923, -0.7019],
         [-3.3329, -0.6935, -1.7394,  ..., -2.8102, -2.4387, -0.6910],
         [-3.5137, -0.5672, -1.7668,  ..., -3.0296, -2.4971, -0.7124]]],
       device='cuda:0') tensor([[    1,  9639,   630,  ...,     0,     0,     0],
        [    1, 17171, 19410,  ..., 17316, 11937,     0],
        [    1, 20330, 15500,  ...,     0,     0,     0],
        [    1,  2142, 24133,  ...,     0,     0,     0]], device='cuda:0')
tensor([[    1, 22524, 22582, 12988, 24191, 20162, 23411, 22582, 27040, 25639,
         25154,  3583, 19284,  1061, 10067, 14739, 12988, 13004, 24191, 23340,
         22524, 16326, 22018,  6106, 19051,  5162, 24243,  4977, 23318, 24809,
         13004, 13027,  6600, 26753, 18606,  4080, 13988, 19167, 12264,  7423,
          8694, 22582,  9293,  6075, 25639, 25154,  3583, 13934, 16894, 19284,
         10067, 20882,  3560, 22582, 27040, 19854, 16387, 15695,  4704, 20287,
           631, 22513,  5675, 24352,  6018, 16310,  1758, 20162, 17323, 15024,
         13005,  8170,  1131,  5580, 26170, 19126, 19939, 27483, 26186, 19933,
         26345, 26752, 24133, 21962,  4839, 22023, 22582, 25639, 25154,  3583,
         21697, 27464, 19602, 26500,  5703, 24451,  1017,  8500, 14739,  7790,
         20162,  1356, 27338,  5047, 22582,   867, 17171,  5320, 22944, 19383,
          5233, 13005, 17882, 14739,  9237,  9090,  6699, 14948,  6391, 26890,
         10395, 20850, 14948,  2219, 25283, 10067, 20882, 10711, 17439,  3368,
         15516, 22063, 15516,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 24546,   731, 16203, 24546,    58,  2169, 16203, 18450, 26070,
         15785, 27380, 23443,  5193,   440, 15783,  4289, 14175, 21344,  5883,
         15779,   482, 16197, 27338, 20065, 19230,  9479, 19978, 13934, 27479,
          7824, 26788,  7825,  4801, 10512, 12615, 14114, 17779, 24938,   733,
         14636,   482, 21344, 16205, 14175,  7821,   482,  8437, 16177, 10395,
           539, 25947, 18423, 16654, 10121,  7822, 27046, 18869, 15268,  1018,
         16205, 14175,  7821,  9582, 21323, 25114, 21810, 19200,  3522, 14638,
         26609,   482, 26608,   715, 21344, 10456, 24787,  8095, 18056, 14638,
          3589,   482,  1255, 14638, 26609,   482, 27338, 16221,  7760,  3589,
           446, 18624, 26609,   482,   446, 15734, 27530, 18056, 21344, 23203,
           651,  9473, 27338, 11622, 10512, 24299,  2448,  3134,  8141,   727,
           834,  3190, 24680, 24040, 20068, 26609,   482,  5885,  3591, 14496,
         16456, 26608, 16326, 26609,   482,   482, 14876, 20065, 13996,  6078,
          6647,  5883, 26609,   482, 23473, 18423, 12845, 20496,  2342,  6683,
         17171, 10950, 27479, 17136,  7821, 17777, 24718,  3958, 27150, 21810,
         27531, 25800, 25114,  7750, 25551, 11663,  7822,   483,  6106, 22019,
         17777,  5275, 27483, 13934,  1192, 20470,  7825,  4801, 21344, 23760,
          1258, 14074,   482, 23391,  7822,  4801,  9626,  4820,  1177,  1302,
         27314, 26609,   482,  3589,   482,     0],
        [    1, 15021, 20012, 22723, 25639, 15021, 10652, 22722, 17600, 17171,
         10885, 27483, 13027,   168, 24111,  4104, 12568, 19417, 24038, 21344,
         19417, 14953, 12280,  9019, 20754,  6182,  6600, 15863,  9537, 18555,
         16924, 20329, 12291,  8605, 21844,  4333, 21344, 23760, 18777,  6457,
          8683, 20929, 17117, 15607, 19006, 13484,  5506, 11392, 24111,   290,
         20929, 12495, 19006,  5373,  6392,  6650,  8781, 14955, 11455, 16626,
         27294,  7769,  5915,  5506, 25390, 21827, 23893, 16049,  8829,  4333,
          8000, 12280, 14639, 14200, 22513, 13304, 24111, 26090, 17087,  9141,
         23931, 15021, 19946,   914, 21344, 24111, 23931, 15021, 20012, 21247,
         23485,  1133, 25639, 25593, 24916,  7700, 21344, 18845, 27450,  7698,
         14141, 13681, 26833, 15021, 24789, 27338,  4973, 18614,  1926,  8111,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 10862, 10301, 18552,   817,  9581,  5142, 14025, 27090, 10862,
         21535, 23387, 14028, 10301,   817, 19019, 15783, 16205, 10862, 25025,
          5972, 24570, 27338,  9193, 14290,  7235, 18626,  2844, 25882, 16205,
         10862, 23525, 17825,  7822,  6264, 21226, 20701,  9791,  2279,   759,
         25025, 17725, 11630, 20327, 16197, 20833, 16825, 27524, 23428,  8853,
         27064,  9088, 16205, 10862, 19940, 19360,  2478, 27090, 18404, 27530,
           759, 21344, 26715,  5271, 27379,  2808, 23123, 27379, 25025, 16650,
         13657, 26986,  8447, 10395,  1758,  9791, 21260,  1401, 27338, 23387,
         14028, 16205, 10862, 20466,  6307,  6646, 23472,  1708,  3945, 21044,
          6877, 21943,  5142, 15500, 21530, 17825, 16528, 24935,  4704, 22096,
          7744, 21835, 21344, 13934, 26882, 27338, 11765,  2821, 17825, 16205,
         10862, 20702,  9791,  2279, 16205, 10862,  2156, 16197, 14025, 17245,
         21344,  9001,  9604,   482,  5626,  8181, 18620,  3690,  3463, 14025,
         17825,  2980, 24788, 14244,  9003, 16205, 10862,   290, 15268, 15843,
           817, 19019, 15783, 15270,  7449, 18626, 24824, 21344,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0') tensor([[[-2.1610, 22.0248, -0.2744,  ..., -1.2647,  0.4552,  0.8942],
         [-4.8436,  0.0503, -2.4322,  ..., -4.7627, -1.8861, -1.1471],
         [-3.7944,  0.3832, -2.0540,  ..., -3.6570, -0.9734, -0.2799],
         ...,
         [-1.6890, -0.5647, -1.0605,  ..., -1.1483, -0.9728, -0.3027],
         [-1.6561, -0.6509, -1.1101,  ..., -1.1335, -0.9783, -0.2980],
         [-1.8382, -0.9658, -1.2825,  ..., -1.3570, -1.1633, -0.3997]],

        [[-3.0505, 22.0795, -0.7558,  ..., -2.2044,  0.2734,  0.3666],
         [-4.5073, -1.7220, -2.5496,  ..., -4.4141, -1.9844, -0.4836],
         [-7.5882, -3.6653, -3.1679,  ..., -8.2033, -4.3184, -2.7598],
         ...,
         [-6.5711, -2.0258, -3.4703,  ..., -5.7817, -2.4789, -1.6262],
         [-2.3031, -0.3231, -0.6049,  ..., -1.5502, -1.1305, -1.7362],
         [-1.7775, -1.1002, -1.7091,  ..., -1.5129, -0.9610, -1.0082]],

        [[-2.1381, 22.1029, -0.3799,  ..., -1.3255,  0.5054,  0.5937],
         [-4.1914, -0.5046, -2.3684,  ..., -4.6289, -1.8075, -1.2947],
         [-2.4768,  0.2831, -0.0712,  ..., -2.6825, -0.4297, -0.4877],
         ...,
         [-1.2321, -0.4676, -1.1192,  ..., -0.8964, -0.8003, -0.3523],
         [-1.2430, -0.5805, -1.1943,  ..., -0.9228, -0.8302, -0.3739],
         [-1.5947, -0.9811, -1.4620,  ..., -1.3091, -1.1014, -0.5351]],

        [[-1.9906, 22.4095, -0.4136,  ..., -1.2923,  0.6243,  0.8634],
         [-1.6261, -2.2858, -1.4410,  ..., -1.9700, -1.1216, -0.3395],
         [-6.5199, -3.4833, -3.2842,  ..., -5.7233, -3.3937, -1.8359],
         ...,
         [-0.7031, -0.4291, -0.9284,  ..., -0.4689, -0.5324, -0.2026],
         [-0.7574, -0.5726, -1.0202,  ..., -0.5391, -0.5762, -0.2412],
         [-1.0500, -0.9043, -1.2401,  ..., -0.8649, -0.8104, -0.3794]]],
       device='cuda:0') tensor([[    1, 20162, 23411, 22582, 27040, 25639, 25154,  3583, 19284,  1061,
         10067, 14739, 12988, 13004, 24191, 23340, 22582, 25639, 25154,  3583,
         21697, 27464, 19602, 26500,  5703, 24451,  1017,  8500, 14739,  7790,
         20162,  1356, 22582,  9293,  6075, 25639, 25154,  3583, 13934, 16894,
         19284, 10067, 20882,  3560, 27338,  5047, 22582,   867,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 26608,   715, 21344, 10456, 24787,  8095, 18056, 14638,  3589,
           482,  1255, 14638, 26609,   482, 27338, 16221,  7760,   482, 14876,
         20065, 13996,  6078,  6647,  5883, 26609,   482, 23473, 18423,  4801,
          9626,  4820,  1177,  1302, 27314, 26609,   482,  3589,   482, 10512,
         12615, 14114, 17779, 24938,   733, 14636,   482, 21344, 16205, 14175,
          7821,   482,  1018, 16205, 14175,  7821,  9582, 21323, 25114, 21810,
         19200,  3522, 14638, 26609,   482, 13934,  1192, 20470,  7825,  4801,
         21344, 23760,  1258, 14074,   482, 23391,  7822, 26609,   482,   446,
         15734, 27530, 18056, 21344, 23203,   651,  9473,     0],
        [    1, 24111, 26090, 17087,  9141, 23931, 15021, 19946,   914, 21344,
         24111, 23931, 15021, 20012, 21247, 23485,  4104, 12568, 19417, 24038,
         21344, 19417, 14953, 12280,  9019, 20754,  6182, 25639, 15021, 10652,
         22722, 17600, 17171, 10885, 27483, 13027,   168, 24111,  4333, 21344,
         23760, 18777,  6457,  8683, 20929, 17117, 15607, 19006, 13484,  5506,
         11392,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 16205, 10862,  2156, 16197, 14025, 17245, 24935,  4704, 22096,
          7744, 21835, 21344, 13934, 26882, 27338, 11765,  2821, 17825, 16205,
         10862, 20702,  9791,  2279,  1401, 27338, 23387, 14028, 16205, 10862,
         20466, 16205, 10862, 25025,  5972, 24570, 27338,  9193, 14290,  7235,
         18626,  2844, 25882, 16205, 10862,   290, 15268, 15843,   817, 19019,
         15783,  9581,  5142, 14025, 27090, 10862, 21535, 23387, 14028, 10301,
           817, 19019, 15783,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 22692, 18491,  ..., 16205, 11706,     0],
        [    1, 22952, 26736,  ...,     0,     0,     0],
        [    1, 15605, 22726,  ...,     0,     0,     0],
        [    1, 11738, 11292,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1018, 22.6561, -0.4254,  ..., -1.2592,  0.7094,  0.4341],
         [-7.9641, -4.5296, -3.4405,  ..., -7.9003, -3.8924, -2.7923],
         [-5.2842, -2.2308, -3.0367,  ..., -6.4418, -2.6135, -1.3573],
         ...,
         [-2.3993,  0.1404, -1.1637,  ..., -1.4692, -0.8668, -0.6224],
         [-6.0077, -3.9877, -2.3877,  ..., -6.1647, -2.6522, -1.6087],
         [-1.5438, -1.1906, -1.5432,  ..., -1.2678, -0.6258, -0.8565]],

        [[-2.5163, 22.3665, -0.5540,  ..., -1.8292,  0.5720,  0.5220],
         [-4.8725, -0.1448, -2.3166,  ..., -5.1884, -1.8137, -1.0407],
         [-2.3241, -2.1653, -0.9897,  ..., -1.8016, -0.9578, -0.0411],
         ...,
         [-2.3628, -1.0911, -1.6201,  ..., -2.1716, -0.8708, -0.4770],
         [-2.3440, -1.2732, -1.7071,  ..., -2.1622, -0.8847, -0.5545],
         [-2.3141, -1.3723, -1.7650,  ..., -2.1308, -0.9832, -0.7244]],

        [[-1.7201, 22.6154,  0.0307,  ..., -0.9264,  0.9137,  0.8304],
         [-2.0431, -3.1903, -0.5873,  ..., -1.6411,  0.1429, -0.0345],
         [-6.0372, -2.6045, -2.3903,  ..., -5.2517, -2.5345, -1.1399],
         ...,
         [-1.6410, -0.6122, -1.1586,  ..., -1.2991, -0.5159, -0.2735],
         [-1.5851, -0.7578, -1.2308,  ..., -1.2564, -0.5086, -0.3420],
         [-1.5563, -0.8343, -1.2826,  ..., -1.2343, -0.5948, -0.4913]],

        [[-2.2836, 22.1854, -0.5001,  ..., -1.5402,  0.4470,  0.6053],
         [-4.1496,  0.2214, -0.8499,  ..., -3.4809, -2.5754, -0.6533],
         [-0.2258, -0.3530,  1.3373,  ...,  0.0743, -0.4525,  0.1439],
         ...,
         [-2.7954, -1.6129, -1.5679,  ..., -2.2495, -1.2540, -0.4351],
         [-2.7692, -1.7796, -1.6550,  ..., -2.2302, -1.2377, -0.4733],
         [-2.6833, -1.8288, -1.6836,  ..., -2.1354, -1.2936, -0.5892]]],
       device='cuda:0') tensor([[    1, 24990,  3158, 25639, 21365, 19994, 26426,  9984,  9266, 26883,
         20286,   770, 27411, 21365, 13934, 26882,   759,  4501, 19330, 21365,
          7311, 22952, 18491, 22692, 22141, 19294, 18673, 25639,  9983, 22899,
          9266, 26882, 21364, 21365,  9141,   759, 23931, 15268, 13917,   382,
          1582,  7453,  6392, 22513, 10733, 21404,   945,  3973, 27411,  9973,
         10902, 20287, 16894, 25639,   759, 27046, 24969, 17171,  2367, 21914,
          9984, 27479, 16927,   759,  2822, 20286, 19330,  9973, 10559, 24754,
          1642, 21404,   945,  9141, 15393, 22952, 19832, 22049, 15731,  2008,
         25639, 21365,  5167, 11472,  5780, 19003, 18588,  1302, 19867, 17204,
         16626,  5168, 16626,  1582, 18547, 20286, 25593, 19867, 12126,  9984,
         24657,  6672,   759,  7453, 21365, 21344, 16205, 11706, 15663, 27411,
         27150, 19596, 13934, 26882, 21365,     0],
        [    1, 17902, 25437, 16644,  8981,  7727, 17949, 19072, 21344, 22055,
         22952, 19123, 11287, 24344, 12483,  1702, 22952, 24346, 19070, 25076,
         12486,  1028,  1705, 17949, 19072, 14813,  1705,  6193, 17949, 19072,
         23337,  5310, 12224, 17171,  3609,  8224,  6775,  3548, 26715, 11030,
          3836, 16205, 25437, 21344, 22952,  4748,  4948, 21726, 13499, 26633,
         14323, 27046,  5393,  9905, 11570, 17953,  5028,  1702, 17949, 19072,
         23337, 18304, 22952, 17950, 27406, 17597, 26229, 13913, 23806, 18324,
          8108, 16205, 25437, 21344, 18056, 26605, 20296, 22023,  1705, 25580,
         15024,   783, 12754, 16626, 24534, 22952, 16616,   467, 12481,  1302,
         26282,  9579, 21344, 16205, 25437,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 24938,  2621, 24992, 17077,  9757, 14274, 17642,  8945, 19854,
         12483, 15605, 22726,  9757, 10039,   565,  8271, 27411,  8437, 25585,
          2448, 10045,  8737, 22496,  4254, 10728, 26637,  9293, 22405, 21744,
         14203, 11236, 26426,  9973,  2569,  8447,  8034,  8872, 20993, 10041,
         16852, 24990, 20097, 12560, 26293,  1312, 26316, 17077,  9973, 23797,
          2525, 11030, 10941,   989, 23266, 22405, 21744,  8437,  5153, 20695,
         20287,  1216,  9634, 27483,   517, 15559, 15605, 22726,  4126, 22678,
          9769, 23270, 14948, 21535, 14317,  7436, 21999, 17857, 15605, 22726,
         26662,  3514, 25008,  9983, 15992,  4623, 22680, 26539,  8865, 25400,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 13934, 21403, 23425, 25035,  5789,  2438,  9543, 16183, 11472,
         13030, 13934, 27479, 24352,  2690, 27491, 13031,  9165,   177, 13030,
          2929, 17083, 25122, 13934, 27479,  9543,  9165, 24352, 20330, 24076,
         14086,   989, 16183, 11738, 16186,  3804, 25062,  2690, 27491,  2169,
          2438,  9157, 13030, 13030,  2929, 17083, 19934,  2821, 13934, 27479,
         24900, 21365, 27332,  2690, 27491, 21365, 16185,  7573, 26426,   875,
          2690, 27491, 27479,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')

 30%|███       | 34/112 [00:02<00:06, 11.97it/s, loss=1.04]

tensor([[    1,  3679,  9707,  ...,     0,     0,     0],
        [    1, 15513, 15105,  ...,  4431, 24938,     0],
        [    1, 14214, 19458,  ...,     0,     0,     0],
        [    1, 11286, 12301,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7051, 22.2201, -0.7027,  ..., -2.1030,  0.3568,  0.4970],
         [-7.1245, -1.9856, -2.8593,  ..., -5.8161, -3.0257, -1.4445],
         [-6.1316, -5.4888, -3.2961,  ..., -6.6290, -3.8778, -2.2167],
         ...,
         [-3.3322, -0.4483, -2.4088,  ..., -3.6748, -2.1028,  0.3088],
         [-3.8066, -4.8594, -1.6005,  ..., -3.2387, -1.8094, -1.2827],
         [-2.3042, -1.4389, -1.7495,  ..., -2.3638, -1.1178, -1.1000]],

        [[-2.0445, 22.5662, -0.2470,  ..., -1.3599,  0.5717,  0.6041],
         [-4.8268, -1.0632, -1.9911,  ..., -4.4119, -1.3652, -0.3287],
         [-5.1281, -1.4425, -1.6262,  ..., -4.6627, -1.9762, -1.0388],
         ...,
         [-1.5028, -0.9059, -1.2250,  ..., -1.5197, -0.9405, -0.9291],
         [-1.4062, -0.8627, -1.1479,  ..., -1.4129, -0.8827, -0.9074],
         [-1.5454, -0.8455, -1.1524,  ..., -1.4971, -0.8238, -0.8173]],

        [[-2.0562, 22.2215, -0.3460,  ..., -1.2953,  0.6668,  0.6030],
         [-7.3210, -3.6311, -3.6355,  ..., -7.0577, -3.7656, -1.3102],
         [-6.8927, -3.2784, -3.4183,  ..., -6.2438, -3.7073, -0.2394],
         ...,
         [-3.0627, -1.6919, -1.7290,  ..., -2.7413, -1.8295, -0.7831],
         [-2.9999, -1.6806, -1.6841,  ..., -2.6844, -1.7700, -0.7632],
         [-3.1272, -1.6382, -1.6824,  ..., -2.7573, -1.6816, -0.6400]],

        [[-2.3021, 22.2167, -0.5126,  ..., -1.4851,  0.4402,  0.8116],
         [-3.9513, -1.3588, -1.6331,  ..., -3.7065, -1.9814, -2.1346],
         [-3.4907, -2.9357, -1.8797,  ..., -3.4760, -2.2605, -1.3216],
         ...,
         [-3.0876, -1.7170, -1.9589,  ..., -2.6927, -1.8488, -0.5998],
         [-3.1989, -1.7863, -2.0069,  ..., -2.8075, -1.8813, -0.6226],
         [-3.5241, -1.8727, -2.0996,  ..., -3.0732, -1.8862, -0.5529]]],
       device='cuda:0') tensor([[    1, 12728,  4229, 18359,  3686,   558,  5915,  5674,  3679,  9704,
         23636,  1402, 22307, 26356, 11949,  5039, 18149, 18359, 16924, 12560,
         22446, 11736, 21344, 19934, 20457,  3686, 16515,  4229, 24534,  3679,
         19301,  9894, 21344, 16798,  3686, 20456, 21344, 16626, 21327,  5674,
          6154,  3679, 17936, 22309, 14086,  9707,  9452, 12675, 18267, 17936,
          1061,  9704,   488, 21344, 20658,  6201,  4199,  8552,  3708,  4567,
         25025,  2102,  7317,  4229, 18359, 27338, 20064,  3679,  9704,  3679,
         18931,  8207, 12728,  4229, 18359,  3686, 24925, 21854, 25259, 11392,
         23703, 14857, 12918,  8461, 18372, 16521, 21344, 16205,  4567,  4392,
          3860,  9707,  4044, 24313, 20658,  6201, 21344,     0],
        [    1,  2707, 10456, 18482,  8047, 13934, 24938, 21525, 14542,  2707,
          7449, 12315,  2707,  8062, 17257, 26818,   468, 27338, 25544, 17171,
         13934,  6077, 14542, 20930, 23448, 17018,  8723, 22942, 27376, 23340,
           241, 18099, 10611,  8447, 21874, 12691, 20203,  2707, 17171, 15586,
         18056,  8447, 19065, 27290,  2438, 25157,  1564, 27314,  1530, 15674,
         18482, 26919, 27479, 25156,   468, 23546, 27249,   783, 23773,  5100,
          2530,   838, 21948,  3690, 10426, 10395,  7344, 23116, 11251, 18802,
         27483, 17131,  9172, 25519,  9172,   630, 20037, 22942, 17171, 12254,
          4431, 24938, 21470,  9791, 25564, 15800, 17018, 10426, 16177, 19858,
         23428, 14983,  6609, 27199,  2245,     0,     0,     0],
        [    1,  7449, 19452,  1866, 10703, 27010, 26935, 14186, 10395,  1866,
         26776, 27136, 12525, 10705,  1866,  3323, 14367, 21344, 20086, 13209,
         13372, 14795, 27381,  6200, 24789,  5522, 17100, 27201,  7317,  2219,
          1866, 21344, 21364, 18482, 16177, 18447, 24526,  5832,  5831,   759,
         19459, 25481,  6871, 13372,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  3118, 18273, 12341, 11943, 13799, 12274, 16310,  1666,  7348,
          3557, 13964, 11286, 12274, 13789, 10205, 16310, 17181,  2293, 10718,
         25352,  7352, 16310,  7348, 21365,  7510, 12245, 25639, 22530,  4101,
         13941, 27479, 17795,  3557,  2947, 21247, 22007, 21922,  8186, 10210,
         16310, 17181,  9455, 12274, 13789,  7933,  6775, 16310,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 17899, 22777, 11678,  1358,  9072, 21010, 23411, 17899, 22777,
         14795,  1354,  6846, 27479, 15492,  9072, 11268, 14542, 23007,  1926,
          3951, 13304, 19403, 18375,  9483, 16101,  6090,  2922, 16678,  3873,
          6840,  6106,  4979,  8443, 22777, 27499,  6192, 14367, 15492,  2207,
         13304, 26713, 25138,  1406,  5848, 18099, 19847, 10140, 11932, 13098,
         12855, 19839, 19292, 21344, 27479, 17131, 26161, 22524, 16709, 25025,
         16999, 16650,  9072, 27338, 20601, 15209,  8659, 10620, 24944, 12126,
          8665, 16626,   759, 21381,  2367,  1336,   435, 23183, 21344, 13934,
         27479, 15492,  9072,  6839,  8487, 22778, 23411, 16101, 12224,  1130,
         22524, 13018,  2496, 16400, 22512, 18493,   612,  2308,   759, 18163,
         19403,  1903, 16626, 27522,  7221, 20116, 20707, 22340,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 20495,  8761,  4226, 12930, 20495, 12838,  1308,  9772,  4226,
         12930, 24344, 18423, 13902, 20960, 15044,  1600,  3061, 13488, 22405,
          8761, 24718, 19737,  4227, 15044, 24840,  6106, 27314,  5862, 19494,
         12915, 24557,  1689, 12930, 26526,  1600, 26741,  9973,   539,  1661,
         27314,  5862, 19495, 13934, 15448, 12845,  2134, 12930, 27314,  5862,
          9180, 11736, 20495, 26424,  7790,  1540, 12928, 22049,  9984, 15044,
          9973, 21827, 24938, 20495, 18481,  4226, 18999,  8034,  1758, 13304,
         12845, 27150, 21452, 13030,  3061, 13488, 21344,  4226, 14795, 10609,
         19158, 13934, 27483, 19297,  6765, 17245, 27205, 18093,  1394, 24512,
         13934, 27314,  5862,  4226, 18475, 22478, 25606,  9505, 12930, 14881,
         26913, 20701,  7499, 15179,  1564, 17171, 10609, 25221, 18802, 27314,
          9973, 11933, 18914, 24840, 12126, 27314,  5862, 19495,  1661, 12838,
         21135, 27314,  5862,  3557,  9984,  9673, 21982,  5948, 17047, 24235,
         17047,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 12916,  4559, 14564,   468,  9634,   469, 18483, 12226, 27611,
         10398,  8086, 16285, 19849, 18475, 12916,  4559, 10993,  2691, 21355,
         25631,  5862,  2691, 21355,  9266,  1197, 22405,  8447, 18475,  8397,
          4876, 18475,  8112, 18904, 22405, 16631, 25923,  9266, 21135, 26764,
         10398, 16285, 14795, 16387,   469, 16465,  5862,  9180, 25525, 11287,
          2691, 21355, 17480,   621, 17814, 24974, 18999, 21135, 16285, 16178,
         12915, 19940,  3079, 23581, 23007,   469,  4559, 11278,  4559, 12916,
          5862,  9172, 13934, 21804,  2032, 21355, 16502, 10863,  4559, 23760,
          8371, 11392, 19134, 19193, 17962,  4585, 17221, 27199, 12915, 24840,
           470,  4559,  9581,  3551,  6283,  8294,  8367,  7369,  5078,   610,
         15196, 16704, 15675,  7723,   521, 23581, 25526, 22405,  8333,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1,  3193, 17420, 24797, 24650, 26524, 10480,  3193, 17419, 24792,
         13498, 24758, 16626, 13793, 16654, 10121,  7822,  2428, 21344,  8159,
          8458,  4207,  3115,  2367, 23428, 14290,  5522, 14100, 15199, 16662,
          5661,  4036, 19000, 18447, 17825,  7822, 23682, 24938, 21044,  9154,
           612, 15709, 13498,   739, 25061,  2549, 18900, 12525, 16205,  3193,
         13498, 21044, 13793,  3557, 18826, 10961,  7700, 27379, 10744, 16650,
         16205,  3193, 17419, 26440,  6841, 16626, 13793, 24352, 14984, 19151,
          4766,  6169, 14881,  4457, 13793,   817, 22496, 24318, 11960,  6375,
          9844,  8000,  1530, 11992,  6951, 23292, 19195, 14294,  7744, 10456,
         11188, 24146,  4838,  2102, 18620,  7727,   948, 15116, 21344, 16205,
          3193,  1345, 26752, 22329, 16205,  2549, 25481,  5915, 14984, 27379,
         19098,   783,  4625,  3693,  8182,  6357, 16205, 15116,  1440, 19019,
         15783,  1401, 16205,  3193,  1345,  7822, 21044,  1131,  2102, 19628,
         25008, 19151, 16205,  2549, 21344,  6200, 27499, 24346,  7822, 27338,
         21239,  4036, 21044, 27338,  3945, 16205,  2549,  1255, 16626, 13793,
          5549,  4046,  2387, 17795, 16205,  3193, 14952,  7700, 18510,  4209,
         27338,  3953, 13793, 14984,   759, 18869, 16654, 10121,  7822, 25147,
         25147,  9131, 16626, 13793, 19019, 15783, 12525, 13657,  6075, 18627,
         27338, 24344, 18423,  6600, 23119, 15268, 16205,  2549, 21344, 24352,
         16859, 10575,   539, 26604, 26752, 25114, 23682, 27115, 18791, 26390,
          1758,  7279, 11446,   559,  5915, 13793, 14876, 12560, 11631, 17444,
         27115,     0]], device='cuda:0') tensor([[[-2.8556, 22.0010, -0.5788,  ..., -2.0703,  0.3862,  0.6642],
         [-4.9528,  0.2097, -1.2827,  ..., -4.9366, -1.0604, -0.8221],
         [-4.1785,  0.2814, -2.1676,  ..., -4.0972, -0.7915, -0.4325],
         ...,
         [-3.4817, -1.6473, -1.7931,  ..., -2.9641, -1.6633, -0.5349],
         [-3.2762, -1.5978, -1.7222,  ..., -2.7982, -1.5640, -0.5554],
         [-2.8958, -1.4905, -1.6097,  ..., -2.4996, -1.4302, -0.6070]],

        [[-2.2717, 22.2982, -0.4247,  ..., -1.4945,  0.5367,  0.4239],
         [-4.3728, -3.2832, -1.5139,  ..., -4.1100, -1.1454, -0.4681],
         [-8.9323, -6.9792, -3.8677,  ..., -7.9631, -4.4797, -1.3992],
         ...,
         [-3.5522, -1.7799, -1.8523,  ..., -3.1049, -1.6685, -0.8179],
         [-3.4947, -1.7887, -1.8899,  ..., -3.0930, -1.6487, -0.8734],
         [-3.2140, -1.7476, -1.8353,  ..., -2.8951, -1.5776, -0.9526]],

        [[-1.6871, 22.4127, -0.2463,  ..., -1.1953,  0.5294,  0.6720],
         [-4.3052, -3.7496, -1.7134,  ..., -4.3941, -2.3599, -0.7498],
         [-7.1255, -2.3637, -2.6541,  ..., -6.7882, -3.7685, -2.4005],
         ...,
         [-2.7991, -1.5049, -1.5035,  ..., -2.3211, -1.6696, -0.2657],
         [-2.5992, -1.4175, -1.4460,  ..., -2.1743, -1.5959, -0.2859],
         [-2.2191, -1.3492, -1.3260,  ..., -1.8806, -1.4947, -0.3348]],

        [[-2.4092, 22.5298, -0.5397,  ..., -1.7086,  0.7034,  0.7287],
         [-3.6677,  0.5322, -1.5634,  ..., -3.2604, -1.7291, -0.3548],
         [-4.9330,  0.9868, -2.5005,  ..., -4.4228, -2.0258, -1.2201],
         ...,
         [-5.4005, -3.3777, -2.5127,  ..., -4.8834, -2.0503, -0.1959],
         [-3.4306, -1.0758, -1.0290,  ..., -2.5538, -0.5071, -0.4349],
         [-2.3534, -1.0470, -1.7908,  ..., -2.3414, -1.1209, -0.7941]]],
       device='cuda:0') tensor([[    1, 21010, 23411, 17899, 22777, 14795,  1354,  6846, 27479, 15492,
          9072, 11268, 14542, 23007,  1926,  3951, 13304, 13934, 27479, 15492,
          9072,  6839,  8487, 22778, 23411, 16101, 12224,  1130, 22524, 13018,
          2496, 16400, 22512, 18493,   612,  2308, 12126,  8665, 16626,   759,
         21381,  2367,  1336,   435, 23183, 21344,   759, 18163, 19403,  1903,
         16626, 27522,  7221, 20116, 20707, 22340,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 12930, 26526,  1600, 26741,  9973,   539,  1661, 27314,  5862,
         19495, 13934, 15448, 12845,  2134, 12930, 27314,  5862,  9180,  9973,
         11933, 18914, 24840, 12126, 27314,  5862, 19495,  1661, 27205, 18093,
          1394, 24512, 13934, 27314,  5862,  4226, 18475, 22478, 25606,  9505,
          3061, 13488, 22405,  8761, 24718, 19737,  4227, 15044, 24840,  6106,
         27314,  5862, 19494, 12915, 24557,  1689,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1,  9634,   469, 18483, 12226, 27611, 10398,  8086, 16285, 19849,
         18475, 12916,  4559, 10993,  2691, 21355, 25631,  5862,  4559, 12916,
          5862,  9172, 13934, 21804,  2032, 21355, 16502, 10863, 16285, 16178,
         12915, 19940,  3079, 23581, 23007,   469,  4559, 11278,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1,  2102, 18620,  7727,   948, 15116, 21344, 16205,  3193,  1345,
         26752, 22329, 16205,  2549, 25481,  5915, 14984, 27379, 19098, 16205,
          2549,  1255, 16626, 13793,  5549,  4046,  2387, 17795, 16205,  3193,
         14952,  7700, 16205,  2549, 21344,  6200, 27499, 24346,  7822, 27338,
         21239,  4036, 21044, 27338,  3945, 19019, 15783,  1401, 16205,  3193,
          1345,  7822, 21044,  1131,  2102, 19628, 25008, 19151, 18900, 12525,
         16205,  3193, 13498, 21044, 13793,  3557, 18826, 10961,  7700, 16205,
          2549, 21344, 24352, 16859, 10575,   539, 26604, 26752, 25114, 23682,
         27115, 18791, 26390,  1758,  7279, 11446,   559,  5915, 13793, 14876,
         12560, 11631, 17444, 27115,     0]], device='cuda:0')
tensor([[    1,  5265, 15268,  ...,     0,     0,     0],
        [    1, 12284, 17211,  ...,     0,     0,     0],
        [    1, 22548, 17902,  ...,     0,     0,     0],
        [    1, 27248, 25544,  ..., 16456, 23455,     0]], device='cuda:0') tensor([[[-2.3696e+00,  2.2345e+01, -5.6456e-01,  ..., -1.5636e+00,
           5.5498e-01,  4.7919e-01],
         [-3.9166e+00,  1.2309e-01, -1.7852e+00,  ..., -4.2944e+00,
          -1.7384e+00,  2.4278e-02],
         [-6.7325e+00, -2.8056e+00, -2.2359e+00,  ..., -6.2370e+00,
          -3.6283e+00, -2.4042e+00],
         ...,
         [-1.7807e+00, -1.4139e+00, -1.1367e+00,  ..., -1.4678e+00,
          -8.0337e-01, -3.0636e-01],
         [-1.4449e+00, -1.1082e+00, -1.0458e+00,  ..., -1.1116e+00,
          -5.7604e-01, -1.9503e-01],
         [-1.0919e+00, -6.9439e-01, -9.5593e-01,  ..., -7.6468e-01,
          -3.1026e-01, -5.9134e-02]],

        [[-2.3306e+00,  2.2239e+01, -4.1064e-01,  ..., -1.4565e+00,
           5.5186e-01,  8.3817e-01],
         [-3.3458e+00, -3.5838e+00, -1.5170e+00,  ..., -3.1821e+00,
          -2.1554e+00, -7.4365e-01],
         [-3.2369e+00,  9.0750e-02, -6.6636e-01,  ..., -2.8014e+00,
          -2.4530e+00, -1.1848e+00],
         ...,
         [-1.8317e+00, -1.5300e+00, -8.8860e-01,  ..., -1.4220e+00,
          -8.7643e-01, -2.1875e-02],
         [-1.6337e+00, -1.2795e+00, -8.5825e-01,  ..., -1.1918e+00,
          -7.1792e-01,  4.4168e-03],
         [-1.2146e+00, -8.6118e-01, -7.3295e-01,  ..., -7.8464e-01,
          -4.4215e-01,  1.3869e-01]],

        [[-2.4516e+00,  2.2359e+01, -3.7240e-01,  ..., -1.6932e+00,
           5.3275e-01,  4.7783e-01],
         [-7.3386e+00, -1.9009e+00, -3.0787e+00,  ..., -6.7737e+00,
          -2.9537e+00, -2.0431e+00],
         [-4.1604e+00, -9.8786e-01, -2.0429e+00,  ..., -4.3063e+00,
          -1.6350e+00, -8.3199e-01],
         ...,
         [-2.3028e+00, -1.7281e+00, -1.3679e+00,  ..., -1.9503e+00,
          -9.8431e-01, -6.1060e-01],
         [-2.0519e+00, -1.4181e+00, -1.3033e+00,  ..., -1.6746e+00,
          -7.9515e-01, -5.4609e-01],
         [-1.6059e+00, -9.6742e-01, -1.1534e+00,  ..., -1.2451e+00,
          -4.9087e-01, -4.1208e-01]],

        [[-2.8351e+00,  2.2439e+01, -5.7503e-01,  ..., -1.9915e+00,
           3.1821e-01,  4.1792e-01],
         [-6.4784e+00, -4.3033e+00, -3.3130e+00,  ..., -5.5713e+00,
          -2.5580e+00, -1.4551e+00],
         [-4.8979e+00, -2.4027e+00, -2.3065e+00,  ..., -4.3371e+00,
          -3.0105e+00, -1.5101e+00],
         ...,
         [-3.8051e+00, -4.6928e-01, -3.6986e-01,  ..., -3.3510e+00,
          -2.6483e+00, -3.7007e-01],
         [-2.8597e+00, -1.5461e+00, -1.4288e-01,  ..., -2.6958e+00,
          -1.1092e+00, -1.6850e+00],
         [-2.1012e+00, -1.1509e+00, -1.5235e+00,  ..., -1.8020e+00,
          -8.8770e-01, -8.7411e-01]]], device='cuda:0') tensor([[    1, 27201, 20068, 26642,  2293,  5506, 19881, 19249,  9905, 19137,
          2244,    55, 19680,   302, 16010,  9189, 27338, 25715,  5265, 21344,
          9150, 26161, 21853,  8526,  4801,  9150, 26161, 20197,   573, 26750,
         12185, 14404,  8797, 20064, 26642,  5506,  8047,  8984, 25593, 26886,

 34%|███▍      | 38/112 [00:03<00:07, 10.19it/s, loss=1.25]

tensor([[    1, 25564,  9905,  ...,     0,     0,     0],
        [    1, 16644,  5442,  ...,     0,     0,     0],
        [    1, 13570, 13966,  ..., 26359, 24262,     0],
        [    1, 18125, 24348,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6817e+00,  2.2078e+01, -5.7592e-01,  ..., -2.0293e+00,
           2.2361e-01,  5.4587e-01],
         [-3.3812e+00,  1.0987e+00, -2.5531e-01,  ..., -2.8427e+00,
          -2.2421e+00, -3.4593e-01],
         [-4.8439e+00, -2.4342e+00, -8.1250e-01,  ..., -4.4665e+00,
          -1.9769e+00, -2.0108e+00],
         ...,
         [-1.7859e+00, -2.0723e-01, -7.6711e-01,  ..., -1.1445e+00,
          -1.3656e+00, -4.8085e-01],
         [-2.0746e+00, -3.7091e-01, -9.3723e-01,  ..., -1.3355e+00,
          -1.4611e+00, -5.8949e-01],
         [-2.4120e+00, -5.6872e-01, -1.1561e+00,  ..., -1.6411e+00,
          -1.6208e+00, -7.1826e-01]],

        [[-2.2013e+00,  2.1938e+01, -4.7256e-01,  ..., -1.5266e+00,
           6.0220e-01,  9.2991e-01],
         [-3.8315e+00, -6.4484e-01, -1.0691e+00,  ..., -4.0046e+00,
          -2.5912e+00, -4.1119e-01],
         [-7.4686e+00, -3.4162e+00, -2.9893e+00,  ..., -6.0291e+00,
          -2.8358e+00, -2.2947e-01],
         ...,
         [-2.3208e+00, -3.1158e-01, -9.5291e-01,  ..., -1.6228e+00,
          -1.6190e+00, -4.4892e-01],
         [-2.3966e+00, -3.8670e-01, -1.0210e+00,  ..., -1.6121e+00,
          -1.6494e+00, -5.0448e-01],
         [-2.6551e+00, -5.2439e-01, -1.1609e+00,  ..., -1.8251e+00,
          -1.7690e+00, -6.2886e-01]],

        [[-1.4402e+00,  2.2533e+01,  1.4639e-02,  ..., -8.0253e-01,
           9.9564e-01,  6.0404e-01],
         [-3.4611e+00, -1.8699e+00, -1.4009e+00,  ..., -3.4705e+00,
          -2.0863e+00, -1.0221e+00],
         [-4.1340e+00, -3.6856e+00, -1.4020e+00,  ..., -4.4874e+00,
          -2.8451e+00, -8.9950e-01],
         ...,
         [-2.3763e+00, -3.0574e+00, -5.2373e-01,  ..., -1.6061e+00,
          -9.9227e-01, -6.8770e-01],
         [-4.0763e+00, -3.5157e+00, -1.2149e+00,  ..., -3.6094e+00,
          -1.9980e+00, -3.1153e-01],
         [-2.7243e-01,  3.9725e-01, -5.1554e-01,  ...,  1.8859e-01,
          -4.2955e-01, -7.2638e-01]],

        [[-3.2722e+00,  2.1631e+01, -1.0615e+00,  ..., -2.6349e+00,
           1.0065e-02,  5.1909e-01],
         [-5.2537e+00, -3.3419e+00, -1.4111e+00,  ..., -4.4871e+00,
          -2.2252e+00, -5.4410e-01],
         [-6.7402e+00, -7.2183e+00, -3.2940e+00,  ..., -6.8508e+00,
          -2.9993e+00, -2.2107e+00],
         ...,
         [-3.3143e+00, -1.0565e+00, -1.4388e+00,  ..., -2.6160e+00,
          -2.1139e+00, -7.1943e-01],
         [-3.4405e+00, -1.1047e+00, -1.5322e+00,  ..., -2.6366e+00,
          -2.1513e+00, -7.7723e-01],
         [-3.7210e+00, -1.2168e+00, -1.6897e+00,  ..., -2.8728e+00,
          -2.2807e+00, -8.9400e-01]]], device='cuda:0') tensor([[    1, 13934, 27479,  ...,     0,     0,     0],
        [    1, 24657, 17077,  ...,     0,     0,     0],
        [    1, 20337,    55,  ...,  8141,  9479,     0],
        [    1, 18125, 20065,  ...,     0,     0,     0]], device='cuda:0')
tensor([[    1,  3135, 25639,  ...,     0,     0,     0],
        [    1,  1685,  5667,  ...,     0,     0,     0],
        [    1, 14568, 16310,  ...,  2075, 14290,     0],
        [    1,  8394, 18591,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.2910e+00,  2.1638e+01, -8.7874e-01,  ..., -2.5647e+00,
          -7.7891e-02,  3.4630e-01],
         [-7.1810e+00, -3.3955e+00, -2.6709e+00,  ..., -7.4384e+00,
          -3.8009e+00, -2.9714e+00],
         [-7.4909e+00, -5.5141e+00, -4.0744e+00,  ..., -7.3152e+00,
          -3.7984e+00, -2.4443e+00],
         ...,
         [-3.6148e+00, -1.5466e+00, -1.8091e+00,  ..., -3.2671e+00,
          -2.0113e+00, -7.7740e-01],
         [-3.8156e+00, -1.9605e+00, -1.9820e+00,  ..., -3.4349e+00,
          -2.1418e+00, -8.4121e-01],
         [-3.7019e+00, -2.0921e+00, -1.9614e+00,  ..., -3.2624e+00,
          -2.1296e+00, -8.5343e-01]],

        [[-2.4388e+00,  2.2243e+01, -4.1016e-01,  ..., -1.7431e+00,
           4.3950e-01,  8.4948e-01],
         [-5.0456e+00, -3.4989e+00, -1.7953e+00,  ..., -4.7652e+00,
          -2.8929e+00, -8.4706e-01],
         [-6.5743e+00, -3.6505e+00, -3.5175e+00,  ..., -6.3785e+00,
          -3.2540e+00, -1.1160e+00],
         ...,
         [-2.7025e+00, -9.3741e-01, -1.4259e+00,  ..., -2.5012e+00,
          -1.4469e+00, -5.4187e-01],
         [-2.9248e+00, -1.3929e+00, -1.5885e+00,  ..., -2.6953e+00,
          -1.5795e+00, -6.4093e-01],
         [-2.8562e+00, -1.5558e+00, -1.5812e+00,  ..., -2.5665e+00,
          -1.5779e+00, -6.7407e-01]],

        [[-2.4812e+00,  2.2447e+01, -5.7696e-01,  ..., -1.9259e+00,
           4.4748e-01,  2.9221e-01],
         [-6.0310e+00, -2.1843e+00, -2.1791e+00,  ..., -5.8168e+00,
          -3.1819e+00, -4.6551e-01],
         [-3.9483e+00, -5.0161e+00, -1.5923e+00,  ..., -3.3956e+00,
          -1.9405e+00, -1.4260e+00],
         ...,
         [-2.5225e+00,  2.7392e-01, -5.5653e-01,  ..., -2.8178e+00,
          -1.0073e+00, -1.3128e+00],
         [-1.3516e+00, -9.4477e-01, -1.8812e-01,  ..., -1.3642e+00,
          -9.0002e-01,  4.5700e-01],
         [-1.9659e+00, -1.7953e+00, -1.6520e+00,  ..., -1.9221e+00,
          -1.1342e+00, -1.1344e+00]],

        [[-2.8193e+00,  2.2088e+01, -7.1810e-01,  ..., -2.1319e+00,
           1.3939e-01,  4.5596e-01],
         [-4.5856e+00,  2.3747e-02, -1.1050e+00,  ..., -3.9960e+00,
          -2.9724e+00, -5.2706e-01],
         [-3.7476e+00, -2.2176e-02, -1.2220e+00,  ..., -2.7616e+00,
          -1.7092e+00, -1.1836e+00],
         ...,
         [-3.4791e+00, -1.7633e+00, -1.8748e+00,  ..., -3.1499e+00,
          -1.9235e+00, -7.9253e-01],
         [-3.5893e+00, -2.1105e+00, -1.9906e+00,  ..., -3.2191e+00,
          -2.0016e+00, -8.5573e-01],
         [-3.5318e+00, -2.3074e+00, -1.9905e+00,  ..., -3.1053e+00,
          -2.0142e+00, -8.8043e-01]]], device='cuda:0') tensor([[    1, 24567, 10232, 21344, 16924, 18056,  3135, 26390, 24575, 14367,
         24088,  9634, 15731,   168,  3243, 25639, 11581,  3402, 19933,  3135,
         18267, 14367,   759,  8358, 15731,  3466,  3135,  5910, 25639, 22453,
          3135, 12223, 10205, 22023,  6837,  3243, 26390, 15024,  4842, 21909,
          3243, 14373, 16387, 12226,  5101, 26390,  3466,   744, 22571, 15731,
         18056,  8917,   783,  5104, 13934, 15731,  5105, 14795, 17857,  9634,
         16050, 24828, 18056,   290, 25122,  8458,  6102, 26882,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 24840, 19115, 16388, 18068,  9157, 23791,  2219,  1685, 15731,
          7218,  1747,  8794, 25397,  5679,   113, 16123, 18320,  1358, 21660,
          7257, 10429, 10355, 16205,  8431, 16388,   867, 27149,  9157,  2367,
          7391,  9157,  8420, 21854, 10742, 18274, 24346,  6727,  6846, 15139,
         21694, 16205, 14995, 16205, 13578, 17353, 17301, 18304, 25593,  1685,
          9634, 19115, 16789,  2367,  9157, 14412, 19115, 27115,  2367,  9157,
         17352,  7510, 14348, 16924, 16794,   879,  6193, 14348, 16924, 19115,
          5522, 16789, 22112, 14622, 26424, 21525,  9293, 19115,  4686,  1705,
          1685, 16789, 19115, 15645, 14995, 10549, 13578, 16205,  8431, 21422,
          4496, 16205, 14995,  9581,  6525, 14096,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  1140, 21344, 16626, 12938, 16310, 18482, 27338,  2169, 16146,
         23388, 16310,  1150, 16310, 18270, 24797, 10130, 15923,    55, 10956,
         13916,   877,  6071, 25264, 14317, 26426,  5522,  7447, 18056, 26103,
         18270, 16208, 15708, 21344,  6765, 21530, 19550, 27338, 10994, 10456,
          6573, 14564, 15922, 26919, 16626, 22024, 16310,  7353,  5522, 10395,
         26818, 19451, 21365, 21344,   914, 13295, 13934, 27479, 16146,  1140,
          1017, 26368, 12938, 17181, 16310,  7352, 22023, 27338, 20287, 27338,
          4859, 16146, 15922, 18270,  4016,  1855, 23632,  3630,  2075, 14290,
         15922, 16310, 11630,  4867,  6775, 16310, 18483, 14317, 12818, 22952,
          8286, 20287, 26677,  2983, 15922, 18267, 26633,  4747,  6775, 16310,
         18482, 11712,  2075, 14290, 25593, 15461,  3548, 15398, 15922,  4842,
         24789,  3694, 17079, 16626, 15941, 18056, 21859,  4863, 19880, 26099,
         21344, 10031, 18267,  9859, 21344, 17577,  5522, 22685, 22718, 21365,
          8397, 26161, 15098,   168, 10031, 18056, 26654, 21859,  4759, 16654,
         15922, 24534, 27338, 21260, 19112, 25593, 24840, 15461,  3548, 18270,
         19880, 15922, 17578, 26099, 16208, 15708, 21344, 15941, 27338, 14323,
         20287,  4766, 27479, 11013,  7452, 14323,  7447, 21365, 27338,  1551,
          6573,   436, 26919, 16310, 22024,     0],
        [    1, 13934, 26882, 14650, 20256, 24348, 19229, 10190, 20942,  6660,
          2724, 18025, 22147, 17077, 26252,  8526,  2690,  8394,   757, 18930,
         14542,  7510,   230, 14542,  2032, 17263,  9908,  8526, 14299, 13934,
         26882, 14650, 21344,  2428, 25808,   412,  1467, 25258,  5522, 23891,
         12112, 25217, 14650,  4459, 26390,  4464,  8394, 19512, 23358, 17683,
          8397, 10711,  8394, 18591, 13963,  2428, 14542, 23594,  8526, 25639,
         15425, 20476, 21530,  8394,   759, 17218,  8526, 14408, 13934, 26882,
          1157, 25628,    59,   893,   302,   418, 16205, 21887, 23932, 15564,
          4845, 27338, 21239, 14542, 15279,  9690, 19681,  4976, 16177,  5522,
          5492, 10190, 13159,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 12845,  4845,  ...,     0,     0,     0],
        [    1, 15783,  6286,  ...,  6443, 12714,     0],
        [    1,  2870, 17257,  ...,     0,     0,     0],
        [    1, 15968, 27106,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.4882e+00,  2.2016e+01, -3.4369e-01,  ..., -1.6406e+00,
           4.2041e-01,  7.5240e-01],
         [-7.3225e+00, -3.2658e+00, -3.8321e+00,  ..., -7.3083e+00,
          -3.4485e+00, -2.2158e+00],
         [-3.6070e+00, -1.2006e+00, -1.5986e+00,  ..., -3.2244e+00,
          -1.0474e+00, -1.7405e+00],
         ...,
         [-2.6068e+00, -1.5732e+00, -1.5077e+00,  ..., -2.1638e+00,
          -1.3654e+00, -6.2723e-01],
         [-2.8917e+00, -1.7123e+00, -1.5232e+00,  ..., -2.4018e+00,
          -1.3551e+00, -6.7666e-01],
         [-3.2140e+00, -1.6985e+00, -1.5532e+00,  ..., -2.6812e+00,
          -1.4274e+00, -6.6765e-01]],

        [[-2.6279e+00,  2.2360e+01, -4.6636e-01,  ..., -2.0301e+00,
           2.8899e-01,  4.2902e-01],
         [-8.5517e-01,  1.5215e+00,  7.9497e-01,  ..., -1.1463e+00,
          -5.3042e-01, -4.3001e-01],
         [-4.3821e+00, -4.1283e+00, -1.2906e+00,  ..., -4.5862e+00,
          -2.8644e+00, -9.1615e-01],
         ...,
         [-6.9102e+00, -5.5349e+00, -2.7858e+00,  ..., -6.5110e+00,
          -3.5105e+00, -2.0257e+00],
         [-3.9381e+00, -3.4344e+00, -1.5155e+00,  ..., -3.8114e+00,
          -9.8373e-01, -1.5056e+00],
         [-2.5152e+00, -2.0537e+00, -1.5940e+00,  ..., -2.4918e+00,
          -1.1952e+00, -1.0913e+00]],

        [[-3.5630e+00,  2.1503e+01, -9.3197e-01,  ..., -2.6783e+00,
          -1.4497e-01,  4.9000e-01],
         [-1.9172e+00, -4.3859e-01,  7.3906e-02,  ..., -1.8097e+00,
          -1.4297e+00, -2.2635e-01],
         [-6.9340e+00, -1.3261e+00, -3.0572e+00,  ..., -7.0235e+00,
          -2.6264e+00, -1.7526e+00],
         ...,
         [-3.2713e+00, -2.3235e+00, -1.7006e+00,  ..., -2.6173e+00,
          -1.7069e+00, -4.4125e-01],
         [-3.4358e+00, -2.4295e+00, -1.6407e+00,  ..., -2.7059e+00,
          -1.6621e+00, -4.3646e-01],
         [-3.7186e+00, -2.3996e+00, -1.6298e+00,  ..., -2.9204e+00,
          -1.7203e+00, -3.9774e-01]],

        [[-1.5904e+00,  2.2581e+01,  3.5948e-03,  ..., -8.2017e-01,
           6.8200e-01,  9.1315e-01],
         [-3.1743e+00, -3.1129e+00, -1.4676e+00,  ..., -3.1864e+00,
          -1.2664e+00, -8.5884e-01],
         [-6.7014e+00, -3.2861e+00, -2.3691e+00,  ..., -6.5729e+00,
          -3.1656e+00, -1.5291e+00],
         ...,
         [-1.3744e+00, -1.5572e+00, -1.1728e+00,  ..., -1.0705e+00,
          -8.3778e-01, -6.4156e-01],
         [-1.5567e+00, -1.5974e+00, -1.1380e+00,  ..., -1.1853e+00,
          -7.9258e-01, -6.5142e-01],
         [-1.8794e+00, -1.5921e+00, -1.1556e+00,  ..., -1.4824e+00,
          -8.6366e-01, -6.4325e-01]]], device='cuda:0') tensor([[    1, 20712, 16644,   488, 20471, 12833, 17117, 15787,  1703,  9266,
         18741, 26719, 17119,  5288,  3573, 25539,  4845,  5282,  6667, 23824,
         14680,  9111, 27499,  1703, 12833, 17117, 15787, 23794, 17081, 22153,
         12845, 17117,  4845, 18205, 20584, 14604, 26251, 20470,  9260,  8794,
         27115,  5282, 12833, 12833,  3463,  1187, 17117, 15787,  4241,  4842,
          9266,  6129, 12833, 22448,  9543, 17117,  4845, 12852, 17117, 10035,
          6443, 20712,  4845, 19531,  3573,  4845, 16388, 12808, 20471,  5282,
         21239, 11427,  9111,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 18056, 25547, 22340,  8012, 15176, 11822,   241,  1801, 13988,
         21344,   298,  9644,   987, 13558, 14106,  8879,  1706, 13988,  1941,
         11822,  7206,  8111, 26669,  8090,  4457,   778, 15645, 21344, 18056,
         25385, 21239,  4335,  1302, 13988, 17388, 27338, 24925, 21344, 24828,
         11818, 24043, 25547, 11824,   240,  8111, 26669,  9266,  6102,  1897,
          1061, 11818, 10712, 21936, 16024,  4137, 13988,  3159,  9634,  1317,
           701, 11822, 11037, 27109,   770,  4457, 26986, 14795, 11822,   241,
         16205, 12968,  2424, 11818, 17586,  6443, 12714,   308,  4386, 16626,
         13988, 25843, 16205, 15645, 25025,  2102, 19628, 25008, 19151, 14606,
         23169, 24040, 11822, 21257,   440, 15783, 21344, 27338,  2169, 17018,
         18056,  9418, 13988,  3545,  9522,  9765, 18975, 21344, 12714, 21871,
         27053,  3517, 11824, 23624, 24043, 12713,  1061, 11818,   256, 26428,
         11824, 15700, 11511, 14036,  5787, 23224, 21344, 26426,  8469, 13988,
          3159, 27338, 17841, 17189, 18606,     0],
        [    1, 19187,  1048, 27199, 16654, 16048, 26658, 21859, 21344, 26051,
         11337, 21344, 13436, 14958,  4366, 17902,  2870,  9193, 27199, 16048,
         26986, 17078, 16626, 17171, 27479,  6129, 27479, 17131,  7566, 15675,
          5282, 23967,   770,   482, 15268,  5530,  9005, 18475,  1042, 21804,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 25061, 27106, 16310, 15968,  8346, 12398,  8781, 20001, 13963,
         16626, 13786,  5355,  6925, 24797, 14874,  1903, 27106,  2247, 19811,
          5522,  8749, 13242,  7137,  8781, 20001, 27106,  2247, 19748,   241,
         19811, 22448,  8749, 13786,  9639, 12203,  8781,  4897, 11101, 25376,
         27106, 23713, 12274, 16310, 21589, 20329, 12126, 13789,  8781, 21131,
         25211, 19176, 27106, 25580, 25385, 20655,  8781, 13935, 27483,  9469,
          4960,  7771,  6602,  6988,  8627, 23906, 19811,  3545, 14290, 19858,
         24797, 14874,  1903, 25025,  2102, 27314, 22023, 16310,  2524, 19151,
         23645,  8781, 20001,   759, 17576, 14108, 10847,  4559, 14958, 25025,
         15645, 27157,  9157, 11710, 17825, 18056, 27106, 18481, 23541,  5364,
         27106,  8644, 22940, 18163, 10395, 21859, 19811, 12444, 20322, 21533,
          6654, 27529,  3118, 18056, 19758,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  3243, 17081,  ..., 16654, 16050,     0],
        [    1,  8917, 14303,  ...,     0,     0,     0],
        [    1, 16588, 20194,  ...,     0,     0,     0],
        [    1,  1980,  9283,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7970, 22.3246, -0.4729,  ..., -2.0543,  0.3385,  0.2846],
         [-4.1861,  0.0874, -2.2662,  ..., -4.5507, -2.0243, -1.4628],
         [-7.8391, -6.0059, -2.7112,  ..., -7.8612, -3.9352, -1.9810],
         ...,
         [-8.4927, -3.3732, -3.7796,  ..., -8.4062, -4.0641, -2.7720],
         [-3.4515, -4.5197, -1.2634,  ..., -2.7591, -1.6162, -1.1981],
         [-1.7207, -0.4540, -1.2051,  ..., -1.5082, -0.7738, -0.8128]],

        [[-2.8878, 22.0511, -0.7017,  ..., -2.1406,  0.3589,  0.3383],
         [-4.5873, -2.4078, -2.9131,  ..., -3.6088, -1.6415, -1.4694],
         [-3.1131,  1.2314, -0.9235,  ..., -3.0563, -1.5921, -0.9481],
         ...,
         [-2.4526, -0.3196, -1.4918,  ..., -2.0087, -1.0363, -0.8026],
         [-2.5141, -0.4815, -1.4629,  ..., -2.0999, -1.0645, -0.8218],
         [-2.8614, -0.9673, -1.6196,  ..., -2.4914, -1.2493, -0.8975]],

        [[-2.6208, 22.5023, -0.4745,  ..., -1.8903,  0.3984,  0.4147],

 36%|███▌      | 40/112 [00:03<00:06, 11.49it/s, loss=1.06]

tensor([[    1,  3945, 19230, 18450,  3243, 17077, 17227, 14636, 27035, 19006,
          8918,  3135, 22024, 25295, 11408, 20191,   130,  3243, 14496, 16603,
          9581, 16032, 21344, 23443, 20352, 17065, 14551,  3243,  4044,  7593,
         27032,  3135, 15093, 19098, 17207, 25639, 14496, 24575, 16603, 12414,
         12777,  4876, 20331,  9656, 23203, 21344, 25923, 13579, 17239,  5657,
          8536, 12485, 24567, 15093, 27314,  3243,  4199,  8552,  2277, 26375,
         21344,  3243,  5726, 21044, 18475, 25008, 14891, 22030,  8879, 19832,
         19230, 25173,  9666, 21344, 16177,  4759, 24564, 20196, 17065, 21344,
         16894,  9260, 16326, 17077,  4881, 19854,  8251,   130, 18267, 14373,
          3243, 16178, 18837,  8005, 18739,  3018,  3401, 17079,  5915, 27035,
          3135, 19006, 17204, 16603, 20946, 24789,  9266, 19121, 24787,  3243,
         21344, 15447, 10718,  6392, 10610,  1913,  3243, 21344, 27338,  2204,
         25367,  1192, 26440, 13967, 11395, 23127, 22024, 16463,  1661,  2436,
         19531, 26986, 12341, 17808, 17065,  9005,  3243, 19230, 10395,  8879,
          8141, 19854, 16547,  2207,  6846, 24567, 20525, 25061, 13983, 21344,
          3243,  4017, 18475,  8801, 18450, 12724, 14200, 18485,  9111, 21587,
         26919, 18056,  8549,  3401, 18450, 22023, 19300,  4199,  8552, 14092,
         23655, 21344,     0],
        [    1, 14303, 24344, 21831, 27004, 17843, 25076, 24371, 24715, 25175,
         24339, 24341, 23990,  8917, 14303, 23127, 17843, 24968, 25175, 21831,
          1373, 25199, 10780,  2797, 20001,  6214, 18068, 21827, 23127, 25593,
         14303, 24219,  7630,  5876, 14303, 24344, 14554,  6549, 23143,   744,
         27032, 15799, 20703, 10703, 14200, 25076, 24715, 25175, 25076, 23127,
         14303, 25284, 16201, 13498, 16626, 24532,  1152, 27314,  8919,  7857,
         12223, 18960,  5313, 24291,   332,  1510, 18960, 12515,  3670, 26183,
         23902,  6893,  2657, 18993,  7610, 18668,   251,  5313, 24291, 25387,
          1852, 14300,  9201, 20370, 23003, 26400, 23699,  3755, 20064, 27014,
         16777, 19113, 21247, 14303, 11392, 23127, 12515, 16432, 22103,  3975,
          7857, 27314, 19994, 11538,  1636, 10780, 27314, 20001, 10609, 11604,
         26161, 21344, 15157, 22246, 18949, 15019, 25116,  7856,  3290, 24294,
         12547, 14303,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1,  2678,  2902, 25564, 12675, 19682, 19538, 20194, 26788, 17065,
         21344,  6600, 20357, 20194, 16588,  5248,  7043, 12250,   867, 12675,
         22023, 19301, 23124, 14795, 17065, 19939, 16050, 11445, 20194, 15687,
         17262, 12189, 16588,  5248, 17019, 18688, 26441,  4216,  5273,  7234,
         11174, 12675, 20194, 20331, 18620, 12918, 21344, 16197, 20823,   691,
         14237,  6409, 23203,  8774, 21344,  5248, 20505,  5218, 10447, 14150,
          7348, 15270,  8182, 20194,  9724,  8774, 12560, 21864, 20194,  3190,
         17181,  9905,  5522,  3106,  8047, 20194, 13657, 25564,  5248,  5248,
         25564, 12675, 22030, 16177,  4541, 27479, 25564, 19501, 26426, 17181,
          2170, 16814, 12675, 22023, 19301, 15425,  4842, 23697, 26426,  5248,
         26850, 11765,  4049,   465, 18869,  4842,  2102, 17077, 25564,  5248,
         16588,   364, 21229,  5885,  8585, 20190, 25564,  5248, 21904, 20194,
          5885, 18813, 16588, 12341,  6948, 26802, 16588, 21344, 16205,  3365,
         23789, 23931, 15024,  7790, 15731, 11719, 25639,  5522,   362,  3135,
          8047, 24534, 17211,  7279, 25564,  5248,  6373, 16588,  6149, 17299,
         12675, 22023, 19301,  1458, 14586,  5887, 21226, 18737, 20194,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1,  2251,  8980,  8111, 22405,  2134,  9673,  6106,   517,   290,
         19970, 10494,  8111, 23290, 12459, 26410, 22413, 14070, 22571, 26886,
         13289, 27017, 16517, 12461,  2251,  5522, 14881,  8111,  6163,  8111,
          4586,   952, 20989, 16391, 24509, 26876,  3517,  2063, 19211,  7538,
          2251,  9482, 18248, 26410,  3159,  1278, 22222,  8952, 14577, 22405,
         21751, 14323, 21587, 25713,  2251,   867, 25481, 21689,  8111,  2134,
          9673, 16735,  6106,   517,  7374,  8111,  4586,   952, 20989,  5522,
         24344,  9969,  3514, 12359, 21364, 22159, 19211,   948, 22222,  9791,
         21160,  8111,  3951, 17146,  1980, 17841,  9283, 23975, 22571, 16465,
          4422, 12838, 13902, 20960,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]], device='cuda:0')
tensor([[    1, 14393,  2656,  ..., 11421,  2703,     0],
        [    1, 22777, 14599,  ...,     0,     0,     0],
        [    1,  9094,  4199,  ...,     0,     0,     0],
        [    1, 20996, 15044,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1504, 22.7846, -0.3091,  ..., -1.3693,  0.6138,  0.6419],
         [-7.8794, -3.3596, -3.7684,  ..., -7.6108, -2.9549, -1.9100],
         [-4.9278, -0.8583, -2.0001,  ..., -4.9116, -2.2867, -1.6151],
         ...,
         [-3.8349, -1.9548, -1.0539,  ..., -3.4850, -1.6563,  1.2870],
         [-6.1085, -3.8997, -3.3710,  ..., -5.7380, -2.7879, -1.5292],
         [-2.1904, -1.6088, -1.4132,  ..., -1.9224, -0.8683, -0.8790]],

        [[-2.3881, 22.3679, -0.5265,  ..., -1.7638,  0.5271,  0.5821],
         [-7.8395, -5.2801, -3.7284,  ..., -7.1708, -3.5451, -2.2886],
         [-5.8068, -2.2437, -2.8902,  ..., -5.3626, -2.5187, -1.9538],
         ...,
         [-2.0887, -1.6202, -1.3403,  ..., -1.7037, -0.9841, -0.6352],
         [-2.3019, -1.7063, -1.3309,  ..., -1.8646, -0.9555, -0.6778],
         [-2.6293, -1.7174, -1.3582,  ..., -2.1651, -1.0111, -0.6998]],

        [[-2.4511, 22.1718, -0.3681,  ..., -1.6708,  0.3018,  0.5766],
         [-2.1910, -2.3413, -1.7810,  ..., -2.4949, -1.4004, -0.5358],
         [-4.5280, -3.9548, -1.6747,  ..., -3.4158, -1.6691, -0.7039],
         ...,
         [-2.3550, -1.9754, -1.5762,  ..., -1.9821, -1.3476, -0.8330],
         [-2.4880, -1.9910, -1.5071,  ..., -2.0507, -1.2723, -0.8224],
         [-2.8191, -1.9662, -1.5240,  ..., -2.3387, -1.3335, -0.8150]],

        [[-3.0305, 22.0525, -0.7561,  ..., -2.2395,  0.1573,  0.4311],
         [-6.7491, -1.9440, -3.5700,  ..., -6.5062, -3.3195, -1.6583],
         [-5.0799, -2.4905, -2.2837,  ..., -4.5771, -1.9408, -1.0550],
         ...,
         [-2.6618, -1.6251, -1.6143,  ..., -2.2654, -1.3590, -0.5947],
         [-2.9408, -1.7277, -1.6217,  ..., -2.4807, -1.3445, -0.6394],
         [-3.3235, -1.7300, -1.6819,  ..., -2.8330, -1.4460, -0.6732]]],
       device='cuda:0') tensor([[    1, 27272,   290, 13498, 24787, 26713, 23712, 12612, 26170, 22571,
         16465, 18483,  1666, 12668, 21216, 13498,  2281, 27338,  4945, 19880,
         18303, 18482,  1666, 12668, 21216,  8458, 18482, 14565, 15572, 22485,
         24493, 17459, 18482,  7323, 10208,  1758,  9844,  9285, 25406, 24789,
            83,  5726, 11471, 14393, 10494, 24344, 18483, 18485,  9634,  5548,
          3118, 12845, 14393,  4586,  4524, 27272, 21535, 25947, 21896, 18483,
         12797, 16654, 27479, 19823, 22571, 16465,  4031, 20643, 27272, 23713,
         14393, 10711, 15687,  7235, 18483,  8111, 12838, 11268, 11622, 23777,
         21698, 25025,  1758, 18485, 15044, 18515, 24938, 19293,  9285, 14393,
         18483, 14317, 20823, 11421,  2703, 18485, 12668, 21216, 23566, 23515,
         24680, 21216,  9482,  2543, 12153,  7027,  8396, 19939, 26886, 12226,
         11797,  9673, 27272,  2247, 24840, 24680, 22007, 16626, 27584, 19297,
         25649, 21216,  4016,  5988,  1758, 13177, 20674, 12668, 21216, 13934,
         16050,  5271, 23411,  4559, 22415,     0],
        [    1, 25083,  4101, 25593,  5130, 26886, 22777, 21062,  4756, 11474,
          7460, 21827, 18423, 24353, 16626,  4756,  6721, 14790,  2530, 27245,
          8054, 22777, 20213, 25076, 16825,   839,  2929, 17083,  2032, 18475,
         25600, 18134,   759, 23426, 10791, 25133, 10566,  9157, 25062,  9266,
         24840,  6106, 20286, 18134, 17171,   838,  2367, 13663,  2530, 18494,
         16633,  9157, 14633,  3268,  8979,  6721, 14790,  2530, 27245, 23426,
         13572,  7874, 27245, 24867, 23704, 18250, 11839, 13429, 20082, 24018,
         24848,  5182,  7460, 18423, 24840,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 16205, 15050, 13182,  4845, 13934, 27479, 21344,  9094,  1642,
         19029,  9452,  1551, 22002, 15050, 20456, 11319,  6399,  4199,  8552,
          9094,  1642, 16205,  6399, 14074,  4845, 16205,  6399,  3670, 12341,
         26381, 25062, 11283, 16894, 20018,  9581,  9094,  4199,  8552, 10297,
         16077,  4199,  8552,  9094,  5077, 24346,  6102,  6102,  5313, 23777,
          3670,  3401,  7769, 25544,  1302,  3670,  3401, 14795, 17220, 14601,
          9293, 13934, 22571, 27483,  9523, 19449,  1758,  3018,  8437, 24432,
         21365,  8615,  8829,  9094, 21344, 26882,  8593, 25988,  1242, 20417,
          3670, 15093,  9094, 25781, 15093,  8396, 13934, 27479, 21864,  9338,
         21365, 10382, 17929,  9094,  2690, 17795, 22042,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,   989, 16183, 20996, 17205, 25076, 26161,  3572,  2929, 17083,
          4101, 24352,  9266, 26883, 20286, 16183,  5492, 20471, 14881, 24346,
         26161,  8879, 24346,  8879,  3335, 17207, 16924, 17171, 25639, 13934,
         26883, 23890, 21239, 10193, 11736, 20027, 26368, 15477, 10239, 17847,
          4276,  8980, 14177, 26499, 13934, 27479, 17316, 16183, 25062,  6600,
         17207,  4326, 15401, 22777,  4756, 11474,  2169, 25076,  9157, 10351,
          2929, 17083, 24352,  8358, 26883,  4326, 17449, 16825,   838,   168,
         12341, 26867, 21726,  5972,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  9921, 15093,  ..., 19714, 13027,     0],
        [    1,  6102, 14213,  ...,     0,     0,     0],
        [    1, 25905, 22109,  ...,     0,     0,     0],
        [    1,  8321, 19052,  ..., 15325,     0,     0]], device='cuda:0') tensor([[[-2.0442e+00,  2.2826e+01, -2.4843e-01,  ..., -1.3352e+00,
           5.6563e-01,  5.5079e-01],
         [-4.9543e+00, -3.3019e+00, -2.7561e+00,  ..., -4.9237e+00,
          -1.9521e+00, -1.9121e+00],
         [-5.7252e+00, -3.2763e+00, -1.9161e+00,  ..., -4.4376e+00,
          -2.7829e+00, -2.3485e-01],
         ...,
         [-2.5856e+00, -4.9492e-01, -1.5292e+00,  ..., -2.3322e+00,
          -1.0030e+00,  3.9384e-01],
         [-1.4522e+00, -2.6516e+00, -3.0132e-01,  ..., -1.3062e+00,
          -8.6237e-01, -3.3997e-01],
         [-2.8201e-01, -2.4526e-01, -7.4918e-01,  ..., -4.4169e-01,
          -4.5445e-02, -5.9875e-02]],

        [[-1.2739e+00,  2.2597e+01, -1.1102e-02,  ..., -5.9647e-01,
           9.5465e-01,  1.1542e+00],
         [-3.7900e+00, -1.4123e+00, -1.0239e+00,  ..., -3.0212e+00,
          -2.8990e+00, -4.5102e-01],
         [-6.9891e+00, -3.4590e+00, -3.5537e+00,  ..., -7.2905e+00,
          -3.5495e+00, -1.1941e+00],
         ...,
         [-7.5821e-01, -2.1973e-01, -3.9684e-01,  ..., -4.1499e-01,
          -1.7152e-01,  4.6633e-01],
         [-6.6450e-01, -1.2914e-01, -3.7265e-01,  ..., -4.0062e-01,
          -1.5761e-01,  6.1056e-01],
         [-9.2665e-01, -2.8266e-01, -5.1306e-01,  ..., -6.7912e-01,
          -3.7822e-01,  5.5229e-01]],

        [[-2.9618e+00,  2.2130e+01, -6.2141e-01,  ..., -2.3112e+00,
           2.7703e-01,  2.4129e-01],
         [-4.1848e+00,  4.4791e-01, -2.8728e+00,  ..., -3.8999e+00,
          -2.2450e+00, -1.4050e+00],
         [ 3.3946e-01,  1.5468e+00,  1.0331e+00,  ...,  4.5956e-01,
           4.5571e-01,  1.1266e+00],
         ...,
         [-1.3478e+00, -7.8990e-01, -1.2090e+00,  ..., -1.3432e+00,
          -3.3010e-01, -5.5886e-01],
         [-1.4031e+00, -8.0158e-01, -1.2672e+00,  ..., -1.5076e+00,
          -4.1251e-01, -5.0299e-01],
         [-1.7075e+00, -1.0261e+00, -1.4119e+00,  ..., -1.8560e+00,
          -6.4985e-01, -5.8001e-01]],

        [[-3.1948e+00,  2.2090e+01, -7.9606e-01,  ..., -2.5099e+00,
           7.8930e-02,  1.6613e-01],
         [-4.2761e+00, -1.2849e+00, -1.5042e+00,  ..., -3.7166e+00,
          -1.9163e+00, -1.5893e+00],
         [-1.7974e+00, -2.0448e-01, -2.4874e-01,  ..., -1.7491e+00,
          -1.7921e+00, -5.9662e-01],
         ...,
         [-7.8604e-01, -4.8189e-01, -8.8662e-01,  ..., -7.6391e-01,
          -1.6664e-01, -4.4600e-01],
         [-8.7183e-01, -5.1417e-01, -9.3926e-01,  ..., -9.5495e-01,
          -2.4811e-01, -3.8754e-01],
         [-1.1923e+00, -7.5111e-01, -1.0929e+00,  ..., -1.3163e+00,
          -4.8096e-01, -4.6526e-01]]], device='cuda:0') tensor([[    1,  8670,  5216, 24534,  5271,  6346, 27314, 13919,  9921, 22340,
         13927, 26311, 25025,  5216,  7841, 22340,  8980, 18303, 19123, 18692,
         24532, 22340,   759, 20107, 17171,  3443,  3978, 24938, 18423, 22236,
         16262,  5248,    58, 26786, 14414, 26426, 16310,  1092, 24938,  1042,
          6881, 13799,  8689, 22952, 16626, 18692,  9984,  6676, 19334, 22340,
         22952, 20481, 25025,  2102, 16644, 26867, 22952,  5148, 17795,  5216,
         24534, 17079, 26070, 16626, 26822, 14194, 18056, 24344, 25564, 22357,
         19996, 18149, 26426, 19998, 26786,  1758, 18692,  6677,  8462, 10426,
          6775, 13602, 18222,  5216,  7841,  1458, 25025,  2102, 16644, 26867,
         11862,  6677,  4745, 16924, 16262,  9861,   759,  8469, 22340,  9397,
         26919, 22340,  9397, 22346,  8462, 24967, 26843, 16197, 18483, 10232,
         11392,  6308, 25567, 22055, 13502, 23124, 14795, 12341, 14027, 15663,
          4199,  2448, 10045, 19123, 22340, 19867, 22348,  3017,  6522, 12341,
          9139, 24088, 20925, 18676, 18692,  6775, 16310, 18483, 18149, 26426,
         19998,  6775,  3549,  5216,  7841, 15093, 14795,  9028,  3433,   168,
          3890, 20525,     0],
        [    1,   259,  6033,  6102, 14213, 18935,  1702,  3690,  9157,  2335,
          9157,  9072,  6102, 14213,  4868,  9634, 24944,  2335,  9157,  9072,
          9165, 16387,  8928,  5782,  2930, 15139, 21694,  9995, 16626, 27522,
         13030, 17133,  9157, 23790,   759, 11606,   748,  6102, 14213, 22278,
          9157, 23791,  9629, 27483,   517,  2169,  9266,  4327, 12570, 19933,
          2336,  3548,  1702,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1,  4845,   759, 21344, 18447, 23143,  8400, 27479,  3434,  1758,
         22153, 21365, 11913,  5656,  9812,  9494,  6833, 26161, 13934, 27479,
         20734, 10652,  6600,  6879, 21365, 22689,  4845, 21344, 25905, 21344,
          8397, 21365,  9019, 13934, 27479,  7379, 17795, 21365,  2393,  7137,
         20735,  6833,   744,  4845, 21344, 17305,  4049, 27338, 23127,  6200,
         14891,   759, 15268, 14881,  4049, 25905, 17581,  2987, 12226,  7331,
         22849, 21344,  1028, 18837, 24482, 19136,  9019,  2690,  8400, 14566,
           539, 25905, 21344, 17257, 19251, 22693, 19123, 21533,  6392, 26708,
         20942, 14633,  3676,  6754,  3971,  3785, 15098, 25149, 17857,  7791,
         16050,  8615,   759, 14604, 15093, 22147, 21344, 16205,  3982,  4845,
           759,  4355,  6765, 25219,  5008, 13799,  6392, 10468, 22689, 19727,
          2367, 17795, 16644, 16090,  4845,  1017, 23769, 22491, 21344,  1273,
         24204,   913, 18196, 25905, 25062,  2690,  8391, 17171, 24938,  4079,
          9639, 19512, 12226,  8391, 27374, 22689,  6751,  9495,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1, 21701,  8552, 21344, 15785, 27338, 16867, 27338,  4820, 18813,
         22441,  1183, 21344, 21701,  8552, 21871, 12288, 27497,  8320, 16205,
          9046, 15235,  3759, 21344, 25794,  8552,  3785, 12315, 15783, 22448,
          1183, 15645,  9046, 20287, 25847,  3759, 16208,  2989, 21344,  9266,
         15783,  3517, 20746, 10995, 16521, 24364, 23440, 11674, 16521, 20106,
         18606, 21344,  9046, 18721,  6027, 19349, 21344, 15785, 25025, 16867,
         27338,  4820, 18813, 22441, 23466, 20604,  4820, 18813, 18056, 27290,
         17880,  2367, 13660, 20930, 27338, 14881,  6200,  8552,  4961, 21701,
         15785, 14101, 20604,  1188, 22974, 14071, 21530, 21153, 23092, 17089,
         14881,  6200, 22496, 12403, 15785, 24346, 21701,  5142, 14025,  6090,
         15366, 21344,  7612,   744,  2405,  2241,   731, 10994,  8552, 23203,
         21344, 11188,  6469, 23440, 11674, 27338, 27290, 25015, 18921, 20470,
          8552, 23206, 21344, 19978, 14071,   525, 19340,   417,  5091, 17089,
          2211, 15785,  9266, 15783, 12958, 15314, 17279, 20470,  6200,   727,
         17749, 21616, 13637,  1528, 10395, 26526, 25885,     0,     0,     0,
             0,     0,     0]], device='cuda:0')
tensor([[    1, 22952, 19334,  ...,     0,     0,     0],
        [    1, 17352, 16794,  ...,     0,     0,     0],
        [    1, 14678, 15268,  ...,     0,     0,     0],
        [    1, 15922,  9984,  ...,  7349, 15032,     0]], device='cuda:0') tensor([[[ -2.3251,  22.1645,  -0.3407,  ...,  -1.5620,   0.3939,   0.7382],

 39%|███▉      | 44/112 [00:03<00:05, 13.42it/s, loss=0.732]

tensor([[    1, 17580,  9923, 22030,  9921, 14628,  1758, 18692,  9923,  7234,
         14412, 12226, 22162,  9913, 15922, 18267, 18054, 17261, 24158,  6775,
          3548, 21400, 27495, 27502, 26426, 13285, 27479,  8342, 22357,  9923,
          4128, 22067, 12312,  8447,  4128, 13934, 27479, 14412,  7510,  8833,
         15021,  5506, 14891,  9923,   459, 16654, 27479, 21859, 16626, 22030,
         24532,  3669, 12043,  9921, 14629, 23796, 18873, 22952, 18491, 18692,
         25076,  9921,   168, 21135, 25649, 10305,  4885, 23796, 14813,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 17352, 16794, 24174,  9645,   867, 27149, 21726,   260, 10769,
          1705, 26883, 17171, 15024,  3965, 11268, 21239, 17353, 15024, 16789,
         17353, 12226,  6727,  9645, 23469, 17352, 16793, 18092, 26343,  7390,
           759, 16789,  1816, 14166,  6727, 13009,  9645, 11418, 24174,   867,
          7510,  1542, 27479, 17352, 16794, 14697, 16005, 27479, 17352,  3966,
         11268, 23975,  8984,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 10190,   573, 14678, 15268, 23910,  8987,   487,  5996,  1319,
         26161, 18949, 10174, 26633,  3396,  7050,  9380,  3945, 19084, 12560,
         10885, 11710,  1319, 18949,  3396, 10190, 14099,  8397, 25154, 25062,
          2367, 17795, 11710, 14678, 21344,  6600, 19088, 16205, 13846, 21344,
          3970, 14678, 27338, 24344, 14101,   244, 16205, 13846, 21344, 17404,
          9380, 12229,  9380,  6342,  1674, 11710,  9482, 18949,  3396,  1319,
           443,   744, 17843, 14678, 21344, 15268, 14596, 15734,  8400, 20643,
           565,  9522, 17171, 13870,  9690,   580, 16205, 13846,  8644,  4845,
         18439, 19438, 10193,   565, 25226,  5317, 17296,   580,  1638, 26715,
         12560, 21859, 18739, 23910, 10190,  8987,   487, 10061, 17282,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1,  8437, 16780, 16363,  9928,  9973, 18267, 13964, 13939, 15024,
         15922, 17227, 19859,  1582, 14566, 22935, 18475, 10965, 15922,  9984,
          4750, 14551, 26818, 22311, 24938,  9973, 14191, 18475, 26390,  2670,
         17367, 19727, 16924, 10966, 18475,  9984, 10719, 11766, 25593,  8981,
         11286, 18581,  6841,  9973, 14887, 10298, 11932, 14564, 10205, 18485,
          9973, 14887,   759, 23433, 24344,   392,  8715,  3626, 15922,  2102,
         16644, 26867, 24351, 14564,  9984, 15922, 18270, 15244,  9984,   759,
         14186, 24344, 18056, 19854, 24938, 26390, 16603, 22564,  4538, 26390,
          2670, 22311, 19727, 19628, 24534,   759, 11287,  9984, 15923, 24851,
          8774,  7637,  8447, 10205, 11536, 24736, 24534, 13663, 26718, 19449,
         19101, 18791, 10966, 15398, 18292, 15922,  9984, 10210,  5357, 10582,
         12171, 21936, 24704, 15590,  9973, 14886, 24990,  7350, 10965,  1582,
         12225,  4840, 26716, 22935,  9153, 24938, 26818, 11570,  9973,  8872,
         14566,  2514, 26280, 11013,  5423,  9983, 14317, 18475,  8458, 15997,
           744, 10885, 18270, 13044, 17169, 15394, 18475, 12253, 22959,  9984,
          1666,  8437, 17174, 26170, 10582, 19764,   244, 16183, 13963, 27201,
         15922,  9973, 24912, 15779, 24534, 23103, 18270,   318, 10210, 22959,
         15398,  9984,  9973, 20784, 20461,   386,  4897,  8458, 21842, 27199,
         24938, 14348, 20704, 18982, 10456,  5148,  9984,  5492, 22296,  7908,
         26127,   395,  9984, 23682, 24992, 15024, 16889,  9984,  9626, 10966,
             0]], device='cuda:0')
tensor([[    1, 10902, 21915,  9293, 15731,  5394, 15663,  3907,  3317, 21365,
         27411, 21658,  9090, 22297, 10902,  9973, 22899,  9293, 15731,  5394,
         27317, 22513, 26935, 21364, 15666, 16894,  4845, 21344, 10902, 19294,
         18673, 17181,  9983, 16851, 19994, 15731, 11712, 18485,  9973, 27411,
         14442,   168, 15663, 16735, 27411, 14442, 15500, 18481,  9973,  1674,
         15800, 18068, 22028, 21983,  2367, 21914, 16521, 23127, 25768, 12211,
           539,  4876, 24344, 25076, 22707, 17087, 25639,  9984,  4107, 19604,
          9973, 16178, 17171, 23232,  9266, 18423, 16918, 10733, 21404,   945,
         21827, 18423, 10902,  7460, 17171, 18423,  9293, 10885, 14290,  9019,
         16924, 16735, 13934, 26882, 16626, 20288, 10430, 21038,   491, 13563,
          8794, 14881, 25076,  6166, 16924, 20592, 19994, 16927, 26724,  8872,
         22045,  9984, 17181, 27314, 17207,  6102, 27314, 26724, 15179, 16254,
         18482, 17181,  9973, 18483, 22448, 18475,  8438,  9266,  6102, 18483,
         27314,  9528,  2617,   288,  1042, 22021,  5388, 12399, 17181,  9973,
         25556, 23387,   747, 26724,  9984, 18143, 27314, 18483, 12432, 26526,
          8396,  9983,  5522, 26658, 13027, 11197, 10205, 15897, 16740, 10951,
          6676, 16740,  7487, 21535,  9986,  2524,  6090, 27467, 16740, 25639,
         10121, 14953, 25025, 18955,  5025, 14564,  6623, 16626, 27479, 26161,
         13963, 23975, 10422, 21364, 13030,  6182, 16740, 22147, 10951,  9987,
         15093, 21344,  8615, 21909,  1302,  9293, 15731,  7487, 15044,     0],
        [    1, 15319,  2436,  3187, 22340, 19604, 19394, 13175, 15319,  2169,
         13943,  5256,  8466,  3912,  2436,  3187, 16789, 14071,  4054, 22340,
          9024, 11721,   749, 11003, 16006,  6019,  2406, 17171, 24938,  2406,
           867, 18673,  5257, 22513,  2169, 27192,  1259, 15319, 17279, 14071,
         11713, 16005,  9482, 12964, 23374,   259, 24254, 16117,  9266,  8466,
          2406, 19834,  1807, 16644, 16789,  9293,  9024, 11721, 26990, 13175,
         19934,  9634, 26608, 24254, 23374,  8487, 27064,  3100, 16697, 16789,
         13175,  2406, 21344,  2406,  6765, 11781, 22935, 27381,  8437, 24823,
         14891,  7769, 11003,  9581, 11534,  4366,   259, 13098,  7751, 21344,
         16789,  2406,  2156,   511,  9765, 16709, 24366,  8323, 26681, 10395,
          4560, 21344,  2406, 14575, 23713,   168,  2804, 13809, 13175, 15319,
          8950,  8466, 16005,  2406, 15319,  8762, 19349, 26604,  9765, 19934,
         26604, 13442, 11713, 26990, 12964, 23374,  8466,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 13467,  3522, 12833,  8591, 18450, 25061,  2549, 22030, 19216,
          8591, 23682, 12833, 26662, 16654, 23975,  7824,  5549, 14231,  6391,
         14025,  4092, 13467, 21344, 23123,  9455, 12922,  1271,  7822, 10174,
         26633,  3396, 16205, 13467, 21344, 12833,  2169,  5782, 15720, 24672,
         26717, 21859, 18235, 27189, 25639, 25433, 22955, 22567,   733, 21344,
         14542,  8591, 23682, 16326,  1598, 24040,  6410, 19098, 17230, 15559,
         18930,  3118,   839, 25433, 12833,  9000, 12594, 21344, 25479,  8332,
         12443, 15875, 14795, 11227, 10947, 17224, 14317,  8838, 26919, 19353,
         12553,    97, 10964,  4594,  9525, 16205, 13467, 18582, 16592, 18718,
          5951, 20495, 25433, 17220, 23013, 21844, 12833,  1017, 12074, 27189,
         20156, 22567, 10703,   198, 16205,  2549, 10512, 14177, 23658, 18450,
         16654, 26882, 19019, 15783, 14881, 23443, 20155,  7824, 12833, 16205,
         13467, 21344,  4366, 14542, 23123, 22030, 19216,  8591, 23682, 12226,
         18235, 27189,  3118, 25433, 21854, 22567,   733, 16205, 13467,   759,
          1255,  3118, 25433,  6495, 12833, 20456,  9525,  5548,  8332, 12896,
          5548,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  8457, 26903,  5375,  8391, 11630,  8457,  6283,  6090, 26903,
         18481, 24364,  8397,  9505,  6600, 24509, 14723, 21827, 18423, 18904,
          2137, 14451, 26903, 25025,  2102, 19628,  9293, 14442, 26713, 20609,
         13973, 21530,   209,  1089, 27499, 24789, 23428, 24352,  8737,  1866,
         14881, 23444, 14564,  8879,  9905, 23428, 14891, 18872, 22955,  8829,
          1758, 25438, 24787, 15237, 16654,  9973, 21344, 14566, 11013, 27290,
         10422, 14551, 26818, 14036,  6307, 22354,   759, 12459, 24138,  5492,
         26161,  1807, 14606, 21904,  2241,  1302, 18423,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0') tensor([[[-2.2951, 22.4926, -0.5193,  ..., -1.5171,  0.5628,  0.4726],
         [-4.7597, -4.1418, -2.5240,  ..., -4.5509, -2.5078, -1.1709],
         [-3.3806, -2.8948, -1.2474,  ..., -3.8520, -2.1548, -1.3088],
         ...,
         [-3.7455, -3.8749, -1.5299,  ..., -3.9254, -1.6813, -0.6758],
         [-4.2697, -1.9054, -3.6992,  ..., -5.0430, -2.5298, -1.8956],
         [-1.5310, -1.2656, -1.8056,  ..., -1.5674, -0.9155, -1.0352]],

        [[-2.0963, 22.3970, -0.1319,  ..., -1.1817,  0.5453,  0.8466],
         [-4.0110,  0.6013, -0.6155,  ..., -3.4986, -2.3016, -1.4734],
         [-6.5240, -3.7221, -1.9439,  ..., -6.4032, -3.4536, -1.3899],
         ...,
         [-1.7531, -0.9968, -1.2844,  ..., -1.2982, -1.0420, -0.4182],
         [-1.7780, -1.1089, -1.3761,  ..., -1.3571, -1.0657, -0.4396],
         [-1.9970, -1.4324, -1.5595,  ..., -1.6297, -1.2621, -0.5395]],

        [[-2.3683, 22.4267, -0.6170,  ..., -1.7975,  0.6436,  0.4840],
         [-2.3015, -1.8840, -1.9880,  ..., -2.9007, -1.2979, -0.6077],
         [-4.6768, -2.5780, -2.4511,  ..., -5.1728, -1.8108, -0.7161],
         ...,
         [-1.6046, -0.6617, -1.6403,  ..., -1.7563, -0.7079, -0.7469],
         [-1.6496, -0.7598, -1.7386,  ..., -1.8336, -0.7552, -0.7813],
         [-1.9765, -1.1141, -1.9751,  ..., -2.1904, -0.9976, -0.9193]],

        [[-2.4578, 22.2600, -0.6884,  ..., -1.8588,  0.3773,  0.4752],
         [-7.4605, -2.3966, -3.1854,  ..., -7.5018, -3.4198, -3.2304],
         [-7.5984, -4.9748, -3.2279,  ..., -7.0243, -4.1548, -2.7354],
         ...,
         [-1.8707, -0.5460, -1.5264,  ..., -1.5595, -1.0231, -0.3994],
         [-1.8168, -0.6339, -1.5783,  ..., -1.5243, -1.0403, -0.4109],
         [-2.0588, -0.9929, -1.8104,  ..., -1.8081, -1.2763, -0.5337]]],
       device='cuda:0') tensor([[    1, 19994, 16927, 26724,  8872, 22045,  9984, 17181, 27314, 10902,
         19294, 18673, 17181,  9983, 16851, 19994, 15731, 11712, 18485,  9973,
         27411, 14442, 17181,  9973, 25556, 23387,   747, 26724,  9984, 18143,
         27314, 18483, 12432, 26526,  8396,  9983,  5522, 26658, 13027, 11197,
         10205, 15897, 16740, 10951,  6676, 16740,  7487, 21535,  9986,  2524,
         17207,  6102, 27314, 26724, 15179, 16254, 18482, 17181,  9973, 18483,
         22448, 18475,  9973, 22899,  9293, 15731,  5394, 27317, 22513, 26935,
         21364, 15666, 16894,  4845, 21344,   168, 15663, 16735, 27411, 14442,
         15500, 18481,  9973,  1674, 15800, 18068, 22028,     0],
        [    1,   168,  2804, 13809, 13175, 15319,  8950,  8466, 16005,  2406,
         21344,  2406, 14575, 23713, 16789, 14071,  4054, 22340,  9024, 11721,
           749, 11003, 16006,  6019,  2406, 15319, 17279, 14071, 11713, 16005,
          9482, 12964, 23374,   259, 24254, 16117,  9266,  8466,  2406, 19834,
          1807, 16644, 16789,  9293,  9024, 11721, 26990, 13175, 19934,  9634,
         26608, 17171, 24938,  2406,   867, 18673,  5257, 22513,  2169, 27192,
          1259,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 16205, 13467,   759,  1255,  3118, 25433,  6495, 12833, 20456,
          9525,  5548,  8332, 12896,  5548, 25061,  2549, 22030, 19216,  8591,
         23682, 12833, 26662, 16654, 23975,  7824,  5549, 14231,  6391, 14025,
          4092, 13467, 21344, 16654, 26882, 19019, 15783, 14881, 23443, 20155,
          7824, 12833, 16205, 13467, 21344,  4366, 14542, 23123, 16205, 13467,
         18582, 16592, 18718,  5951, 20495, 25433, 17220, 23013, 21844, 12833,
          1017, 12074, 27189, 20156, 22567, 10703, 23123,  9455, 12922,  1271,
          7822, 10174, 26633,  3396, 16205, 13467, 21344, 12833,  2169,  5782,
         15720, 24672,     0,     0,     0,     0,     0,     0],
        [    1,  8457,  6283,  6090, 26903, 18481, 24364,  8397,  9505,  6600,
         24509, 14723, 21827, 18423, 18904,  2137, 14451, 24789, 23428, 24352,
          8737,  1866, 14881, 23444, 14564,  8879,  9905, 23428, 14891, 18872,
         22955,  8829,  1758, 25438,   759, 12459, 24138,  5492, 26161,  1807,
         14606, 21904,  2241,  1302, 18423,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 23972, 17081, 19101, 11710, 23972, 15664, 13964, 17929, 10395,
         22023,   727,  5910, 20514, 11765,  4953, 18791, 20415, 11710, 23972,
         10656,  5506, 26179, 11710, 27332, 19101, 23632, 18791, 24294, 14866,
         23972,  3517, 10656,  4953, 13943,  3437, 18286,  4845,  2247,  4953,
          3630, 12126,  4818, 11030, 22887, 23972, 14325, 10656,  4953,  6672,
          7833, 24291,  5522, 15242, 26818, 26194,  7833, 26795,  6668, 21344,
         23972,  4199, 17220, 17084, 13209, 21652,  3287, 10656, 26170,  3251,
         11710,  1401, 26855, 13967, 23972, 19513, 16603,  4953,  8441,  3510,
          4845, 18162,  6071,  3951, 14955,   361, 16626, 15938, 21344,   757,
         12648,  5910, 17117, 10035,  9184, 22024, 12339, 26713,  2797,  4953,
          3630, 19103, 23972, 21344, 16205, 21652, 19714,  6429, 22023, 22352,
          6071,  5522, 19099, 19272,  9469,  8629, 11808, 22021, 26172, 22508,
         27299, 19084, 21831,   770, 25062, 21831,  8629,  5492, 26172, 11710,
         27332,  4953, 18791, 23972, 10656, 20302, 22898, 17220, 24291, 17576,
         23972, 12444, 11713, 10656,  8589, 18906, 26170, 11959, 22021, 24680,
         22887, 22264,  5910, 21344, 16221, 24291,  5492,  6667,   757, 20942,
         11907,  1256,  3630,  6392, 22023,  4128, 17078, 23972,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 23426, 17929, 25372,   259,  6093, 11561, 23426, 12226, 23161,
         14092,  3388, 20790, 17352, 16793,   612,   638, 17635, 25372,   259,
         17359,  6093,  9874, 16626, 27522, 26381, 23411, 17359,  6093, 26919,
         13663,  4368, 20882,   255,  6745, 15640,   482,  8984,  9774,  8853,
         12226,   261, 21202,  6243, 27064, 27483, 10050, 20950,  4306, 21490,
           759, 18931, 22023,  9581, 26161, 18949,  2448,  4516, 22524, 11070,
          2232, 10061,  8388, 27338, 10456, 18949, 25923, 23446, 21344, 16205,
          4516, 14317, 10061, 10061, 27479, 17131,  9626,  6119, 13934, 26883,
         11691, 21086,  9408, 14891,  9157, 18606, 21344,  1131,  6745, 16470,
          3861,  6093, 14795,   243,  6163, 26818, 23425, 22424, 18595,  9755,
          4669,  6846, 23161, 14092, 23425, 22049, 14092,  9165, 12226, 13305,

 43%|████▎     | 48/112 [00:03<00:04, 15.20it/s, loss=1.04]

tensor([[    1,  3193,  4759,  ..., 16654,  7822,     0],
        [    1,  9046,  8971,  ...,     0,     0,     0],
        [    1, 26161,  7700,  ...,     0,     0,     0],
        [    1,  2549,  2673,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.8698e+00,  2.2761e+01, -2.1067e-01,  ..., -1.2075e+00,
           7.7221e-01,  6.7725e-01],
         [-2.2080e+00,  1.4569e+00, -1.4069e+00,  ..., -2.2771e+00,
          -1.3038e+00,  8.8002e-02],
         [-1.4146e+00, -1.1383e+00, -9.6232e-01,  ..., -1.1902e+00,
          -7.8264e-01,  5.1387e-04],
         ...,
         [-4.8919e+00, -1.3416e+00, -1.4512e+00,  ..., -4.6242e+00,
          -2.9122e+00, -3.5696e-01],
         [-3.0628e+00, -5.9981e-01, -9.8821e-01,  ..., -2.6657e+00,
          -1.2851e+00, -5.2960e-01],
         [-1.0655e+00, -4.5170e-01, -9.8450e-01,  ..., -7.7526e-01,
          -3.0286e-01, -4.6031e-01]],

        [[-3.6708e+00,  2.1827e+01, -1.1453e+00,  ..., -2.9740e+00,
          -1.3515e-01,  1.2996e-01],
         [-4.8254e+00, -7.0345e-01, -1.6333e+00,  ..., -4.9185e+00,
          -3.2484e+00, -1.0652e+00],
         [-2.9101e+00,  4.1356e-02, -2.0569e+00,  ..., -3.2177e+00,
          -1.6222e+00, -1.2083e+00],
         ...,
         [-2.9252e+00, -1.3410e+00, -1.9604e+00,  ..., -2.8181e+00,
          -1.1687e+00, -1.0422e+00],
         [-2.8858e+00, -1.1238e+00, -1.9162e+00,  ..., -2.6495e+00,
          -1.1059e+00, -9.1722e-01],
         [-2.9049e+00, -1.0599e+00, -1.9649e+00,  ..., -2.6128e+00,
          -1.1014e+00, -8.3533e-01]],

        [[-2.4899e+00,  2.1999e+01, -6.6627e-01,  ..., -1.5916e+00,
           2.3113e-01,  8.6188e-01],
         [-3.7965e+00, -1.6827e+00, -8.7736e-01,  ..., -3.3020e+00,
          -1.5221e+00, -5.3283e-01],
         [-3.2205e+00, -1.8509e+00, -9.6754e-01,  ..., -2.5573e+00,
          -2.3514e+00, -3.4843e-01],
         ...,
         [-2.8543e+00, -1.7409e+00, -1.4893e+00,  ..., -2.2754e+00,
          -1.4754e+00, -5.4321e-01],
         [-2.8678e+00, -1.5710e+00, -1.4501e+00,  ..., -2.1787e+00,
          -1.4237e+00, -4.2085e-01],
         [-2.9983e+00, -1.5555e+00, -1.5447e+00,  ..., -2.2663e+00,
          -1.4489e+00, -3.3498e-01]],

        [[-2.8318e+00,  2.2340e+01, -7.7301e-01,  ..., -2.0826e+00,
           1.9583e-01,  2.2491e-01],
         [-2.5146e+00, -2.2609e+00, -1.9900e+00,  ..., -2.8568e+00,
          -1.4914e+00, -6.5727e-01],
         [-1.6308e+00, -1.7022e+00,  9.3602e-02,  ..., -1.7849e+00,
          -9.4349e-01,  7.0016e-01],
         ...,
         [-2.8655e+00, -1.5617e+00, -1.8062e+00,  ..., -2.5597e+00,
          -1.3453e+00, -1.1876e+00],
         [-2.8396e+00, -1.3392e+00, -1.7650e+00,  ..., -2.4207e+00,
          -1.2902e+00, -1.0677e+00],
         [-2.8753e+00, -1.2781e+00, -1.8123e+00,  ..., -2.4002e+00,
          -1.2758e+00, -9.6594e-01]]], device='cuda:0') tensor([[    1, 13793, 15268,    63, 11822, 23624,  4036, 10480,  3193, 26183,
          3268,  9237,  2004, 17245, 17810,  5423,  7822,  9644, 13793,  4335,
         25826,  1258, 10456, 19019, 15783, 10480,  3193, 14881, 18581, 16654,
          7822, 17019, 12249, 16456, 12590,  5308,  7822,  3557, 18510, 12249,
         12229, 24482,   783,   198, 10370,  8782,  2530, 11543,  3951,  9183,
          4381, 27338,  8156, 24482, 12251,  7822, 13793, 16203,  8501, 25826,
          8095,  6149,  8492, 20055, 14625, 17131, 13793, 27285,  4036, 19867,
          5558,  4216, 18047, 17880, 27532, 22935, 19374, 16205,  3193, 20032,
          2929,  1537, 18162, 23552, 24231, 16626, 13793, 10512, 25114, 14025,
         15645, 11730, 21344,  4036, 17131, 25376,  6358,  3803,  9537, 10298,
         12025,  8462, 25335, 13915,  9757,  6102,  9266, 23634,  1708,  9905,
         26170, 23101, 21525,  1539, 22653,  5523, 24482,  7822, 12918, 24514,
         14343, 14343, 27051, 18609, 18048,  8852,     0],
        [    1, 14601,  5522, 27326, 19501,  3106,  9046, 21344, 12623,   276,
         18475, 18475,  9973, 21344, 15707,  2134, 13340, 18024, 22301, 24912,
         17131, 25229,   926, 21344, 11003, 20701, 18475,  4030, 14036, 10298,
         26161, 10609, 16129,  3106, 22001, 18475, 25038, 21344, 14958, 25923,
         14953, 22548,   651,  9046, 21344, 22405, 24449,   106, 15707, 27338,
         14795,  7637,    78,   951, 22229,   926, 21344,  1706, 24833, 25923,
         18721, 11630,  4030, 14036, 10367, 26440, 22148, 21088,  2247, 10205,
         17857, 15707, 10609,  4035, 15707,  4586,  3714,   926, 21344, 24509,
         14566,  9612, 20703, 26340, 14301,  8396, 18966,  4559, 24990, 25593,
         21809,   517,  9046, 21344, 15707,  9791, 14367, 27338, 23566, 20479,
          9584,  4016,  6284, 13264, 26986, 23773,  7615, 17600, 14551, 21344,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 10721,  1028, 19780, 24797, 19512, 27479,  3545,  2367,  9139,
          9293, 27483,  9172, 19512,  3402, 12250, 23144,  3637,  8264, 22887,
         24797, 19512, 13027, 15044, 19512,  7700,  8615, 10715,  1028, 19780,
          7699,  9533, 26161,  7700, 10719,  8615,  8603,  1028, 19780, 13934,
         19512,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 16205, 11730, 21344, 16205,  2673,  4891, 12438, 10232, 15589,
         25062, 11570, 17083, 12958, 23688,  9543, 21835,  7345, 23703, 23713,
         16205,  2549, 24040, 11570, 21835, 26876, 19019, 15783, 19538, 25114,
         14025, 15645, 11730, 26935, 17076,  4792, 16205,  2673,   701, 14795,
         16626,  2478, 13934, 26882, 16205,  2673,  9266, 21135, 11392,  5569,
          2076, 16207, 19559,   130, 22940, 25061,  2549, 13181, 11570, 21835,
          6090,  2673, 26526, 22200, 24884, 11570, 21835,   757,   353, 27381,
         10298, 25593,  9266,  4426, 24904, 10301, 16197, 16207, 19559, 22513,
         17635,  1758, 16205,  2673,  6218,  4783, 18724, 21533, 12500, 26818,
         11392,  5569, 23713, 20877, 19056,   441, 13155, 12171, 21854, 23328,
         26526, 22200, 21874, 22340, 25927, 16205,  2549,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 19158, 16626,  ...,     0,     0,     0],
        [    1, 20989,  1051,  ...,     0,     0,     0],
        [    1, 18606, 18825,  ..., 23613, 12932,     0],
        [    1, 13473,  6444,  ...,     0,     0,     0]], device='cuda:0') tensor([[[ -3.1879,  21.6486,  -1.0744,  ...,  -2.5768,   0.1637,   0.5469],
         [ -2.4334,  -0.1695,  -0.6285,  ...,  -3.3845,  -1.3287,  -0.9856],
         [ -1.9913,  -0.3573,  -0.2404,  ...,  -2.6764,  -0.6198,  -0.2998],
         ...,
         [ -2.7689,  -1.3337,  -1.8099,  ...,  -2.3680,  -1.0358,  -0.3594],
         [ -2.6355,  -1.2789,  -1.7334,  ...,  -2.3041,  -0.9791,  -0.3174],
         [ -2.3750,  -1.1254,  -1.5888,  ...,  -2.1611,  -0.9374,  -0.2348]],

        [[ -2.6446,  22.1878,  -0.5221,  ...,  -1.8646,   0.2953,   0.6159],
         [ -6.7093,  -2.4599,  -3.1621,  ...,  -5.7557,  -3.3584,  -2.8141],
         [ -4.8577,  -4.8221,  -1.6984,  ...,  -4.0086,  -2.0825,  -0.9534],
         ...,
         [ -2.7639,  -0.9514,  -1.6433,  ...,  -2.3021,  -1.2483,  -0.2272],
         [ -2.6452,  -0.8407,  -1.5790,  ...,  -2.2554,  -1.2134,  -0.1684],
         [ -2.4950,  -0.7380,  -1.4915,  ...,  -2.2305,  -1.2267,  -0.1201]],

        [[ -2.5573,  22.5666,  -0.5094,  ...,  -1.7879,   0.5540,   0.1756],
         [ -0.9445,   1.8537,  -0.9740,  ...,  -1.2767,  -0.5353,  -1.0139],
         [ -3.4481,  -3.8056,  -0.0253,  ...,  -2.8901,  -1.4633,  -0.3375],
         ...,
         [ -4.2701,  -3.5112,  -1.0904,  ...,  -4.0665,  -1.7019,  -0.5529],
         [ -4.9365,  -3.0267,  -2.0992,  ...,  -4.9285,  -1.9923,  -1.9778],
         [ -1.4506,  -0.6181,  -1.3842,  ...,  -1.3370,  -0.4182,  -0.8887]],

        [[ -2.9069,  22.0254,  -0.8628,  ...,  -2.0467,   0.0609,   0.5792],
         [-10.3747,  -5.8775,  -5.6364,  ...,  -9.6133,  -4.8636,  -2.3293],
         [ -8.4980,  -2.3993,  -4.5654,  ...,  -8.7084,  -4.4496,  -1.7828],
         ...,
         [ -2.9972,  -1.3458,  -1.8346,  ...,  -2.3375,  -1.2772,  -0.4902],
         [ -2.8404,  -1.2472,  -1.7438,  ...,  -2.2628,  -1.2331,  -0.4329],
         [ -2.6518,  -1.1231,  -1.6271,  ...,  -2.2044,  -1.2357,  -0.3631]]],
       device='cuda:0') tensor([[    1,  7615, 16588,  5522, 25593, 16626,  7225, 16391, 16391, 25593,
         25122, 19232,  7226,  5153, 12675,  5445,  1445, 16391, 16927, 11911,
         11911,  1186, 22049, 16626,  7226, 26288,  6329, 23888, 19232, 16391,
         12223,  7225, 18688,  1393, 15922, 18270,  1061, 23042,  7225, 17171,
          3815, 13894,  5848, 11911, 21344,  7615,  6200, 25593,  7226, 20601,
          6621, 24523,  4794, 12408, 17297,  2219, 16391, 23842,  6600, 12443,
          1183, 11911,  3866, 10737,  7226, 27338,   265, 10395, 22023, 25122,
          8522,  7225, 16391, 14876, 16465, 18741, 25313, 16588,  7226, 10301,
         18894,  1183, 16588,   339,  2720,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 20989, 21344,  3971,  6217, 27285, 15219, 21344, 20989,  8111,
          3656, 13040, 20989, 21194, 23935, 27314,  4030, 24509,  6217,  9844,
          1758, 20989,  2247, 16626, 14564,  8111, 24509, 23624, 21116,  9673,
          8111,  2136, 26669, 22571, 16465, 17206,  3683, 13934, 26882,  8761,
          5883,  4030,  9673, 25581, 23975, 20989,   759, 27288,  4760, 27479,
         17131, 16631,  3951, 15219, 24340, 14795, 12668,  6163, 26669,  6434,
         23290,  8761,  9673, 23566, 10494, 24509, 10395,  2134,  1088,  6102,
         18091, 14596, 25593, 18588, 24062, 18475, 26919, 26882, 10205, 27115,
         16521,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  5522,  1807, 12458, 22329,  1089, 17350, 21344, 27064, 22161,
          3517, 18606, 21344, 26872, 20906, 24346,  2183, 24299, 22675, 17596,
          3545, 16669, 17795,  2497,  8462, 10494, 27292,  1334,  5980,  3996,
         16518, 24718,  1014, 18931,  9683, 16249, 26786, 22161, 21344, 17171,
         14795,   759, 23613, 18606,  6554, 12731, 26919,  3294, 24371, 21344,
         26845, 22598, 15162, 14308,  4726, 12962, 25248, 26990, 21898, 12932,
         13120,  3356,  7106, 17596,  5565, 24315,  3356, 19439, 11713, 21344,
         21010, 23411, 17596, 17350, 18826, 18606,  5565, 24318,  3356, 23612,
         13120, 11713, 17596, 21344,  4766, 10680, 10995, 17230, 25639, 14637,
         20276, 25438,  9724, 27483, 26161,   242, 12176, 17350, 21344,  6634,
         12535, 17902, 15729, 24730, 26246, 18606, 21344,  1131, 14948, 26172,
         13810, 10205, 11713,  9266,  9397,  2180, 27122, 11227, 15605, 23411,
         21344,  5522, 15602,  8925, 13939,  2139, 10174, 11067, 20446, 23320,
          3018, 21344, 27179, 27320, 16709, 26713,  1088, 10205, 12458, 22524,
         10526, 12731, 13299,  9823,  9266,  9397, 27122, 23411, 10061,  4109,
          3257, 11570, 16005, 24731, 10412, 17171, 10494, 12458,     0],
        [    1, 10621, 23262, 13708, 13473,  6443,  4386,  8821, 16135,  5637,
          1690,  7289, 24680,  6106, 23428, 17155, 13473, 12525,   139, 10995,
         13473, 23083, 10618,   762, 24587, 23449,   759,  4384,  1401, 24682,
          1939, 23863, 11674,  5637, 13473,  5269, 19280, 12477, 23975,  2555,
         10621, 17154,  4813, 17089,  9581,  4586,  4291, 25619,  8795, 12403,
         24680, 13473, 10621, 11337, 27150, 10428, 17155, 24247,   759,  5049,
          7510, 14308,  9320,  1492, 17207,  3966, 13473,  9024, 23262, 13406,
         24738, 22030, 14059,  8761,  5705,  4081, 26882,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 18491, 19102,  ..., 26183, 27123,     0],
        [    1, 15325,  2866,  ...,     0,     0,     0],
        [    1, 10190,  7700,  ...,     0,     0,     0],
        [    1, 22078,  1700,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6820, 22.2588, -0.3343,  ..., -1.9347,  0.3941,  0.2872],
         [-5.6280, -2.4291, -2.7117,  ..., -5.2142, -3.1535, -2.5030],
         [-7.2015, -4.0677, -2.7232,  ..., -6.7576, -3.0237, -2.0629],
         ...,
         [-6.5691, -6.6089, -2.0943,  ..., -6.8505, -3.5575, -1.1062],
         [-6.6042, -5.8024, -3.3468,  ..., -6.8259, -4.0364, -2.0241],
         [-1.7492, -1.1803, -1.2903,  ..., -1.5667, -0.6842, -0.6520]],

        [[-1.6253, 22.7882,  0.0586,  ..., -0.8820,  0.8658,  0.9596],
         [-1.4076, -1.5473, -1.2943,  ..., -1.7859, -0.8829, -0.0993],
         [-7.2862, -3.4662, -2.7711,  ..., -7.0082, -3.1488, -1.4682],
         ...,
         [-1.3845, -0.5126, -1.0348,  ..., -1.1123, -0.4957, -0.2325],
         [-1.4211, -0.6203, -1.1242,  ..., -1.1602, -0.4329, -0.1716],
         [-1.3517, -0.7703, -1.1928,  ..., -1.0983, -0.4236, -0.2453]],

        [[-2.4321, 22.2654, -0.3817,  ..., -1.6162,  0.4841,  0.5959],
         [-6.6293, -4.7980, -3.3994,  ..., -6.6066, -3.1355, -0.2516],
         [-3.0570, -0.4355, -0.7905,  ..., -2.1874, -0.9126,  0.2100],
         ...,
         [-3.0265, -1.2162, -1.6061,  ..., -2.4495, -1.3405, -0.4169],
         [-3.1071, -1.3453, -1.7363,  ..., -2.5637, -1.2989, -0.3511],
         [-3.0420, -1.4936, -1.8239,  ..., -2.5157, -1.2763, -0.4167]],

        [[-2.5251, 22.4545, -0.4908,  ..., -1.6666,  0.4231,  0.3818],
         [-4.1221, -0.7529, -2.4123,  ..., -3.6282, -2.5821, -0.7383],
         [-4.1575, -2.2476, -1.1068,  ..., -3.8492, -2.0955, -0.8400],
         ...,
         [-1.8853, -0.7123, -1.3022,  ..., -1.3448, -0.8278, -0.4672],
         [-1.9599, -0.8163, -1.4230,  ..., -1.4514, -0.7969, -0.4348],
         [-1.9194, -0.9730, -1.5111,  ..., -1.4383, -0.7969, -0.5104]]],
       device='cuda:0') tensor([[    1,  3916, 19102,  7447, 22952, 18491, 21239, 24944,  8918,  5883,
         17949,  4233,  6579, 21344, 11907, 21344, 21909, 27312,  4229, 23433,
         13941, 27479,  4229, 21239, 23132, 10610, 10224,  9265, 21344, 18491,
         14323,  9266, 15170, 15093, 19118, 26170,  3916,  4229,  6579, 21344,
          9371,  1227, 15398, 27338, 26173, 27044, 19727,  1151, 22021, 15922,
         18270,  3916,  4016, 12605, 19727,  4233, 15097, 16521,  9193, 12515,
         17953, 18874, 21239, 26183, 27123, 22952, 11907, 25116, 27299,  3916,
         19102, 24840, 27483, 26070,  4229, 16005,  6577, 26170, 10582, 27313,
         16626, 18491,  5167,  6554, 23996,  4229,  4853, 20942,  4229, 14886,
         12605,  8919, 19102, 21248, 10224, 11907, 21344,  3916, 17345, 16615,
         27338, 24040, 16265, 17220, 24294, 22508,  6579, 27338,  5047, 15663,
         27123,   867, 24682,  4229,     0],
        [    1, 16205,  2251, 25062,  4199,  8552, 18863,  3959, 13134,  3613,
          6745, 23906, 11203,  1526,  1192, 16205,  2251, 14073, 27064,  6082,
         27292,  4540, 16205,  3613,  3545, 20676, 25544, 15325,  1302, 16205,
          2251,  9453,  2823,  6392,  8589, 20618, 19783,  9479, 18611, 19753,
          8605,  4093,  2251, 23657, 24368,  9581, 11162,  8917,  9494, 10232,
         15325,  6745,  3586,   483, 16205,  2251, 17523, 15325, 14631,   408,
          3557, 12725, 23889, 15304,  2438,  4634, 22303,  2982,  1616, 16626,
         27584, 13183,  4845, 27479, 17131, 17795, 24938, 27293, 16205,  2251,
         19550, 16178, 19743,  2171,  1616, 27531, 23633, 14953,  4685, 21344,
         16205,  2251, 19290, 11792,  2206, 11290,  2219,  3789, 24934,  4462,
         24301, 26528, 20618,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 10193,  7700,  2438,   867,  5548, 22155,  8391, 10652,  8919,
         19780,  9634, 27483,  7449, 23760,  8683, 10698,  7230, 19118, 21100,
         13934, 27479, 23453, 17083, 21344,  8683, 26828,  7230, 10721, 20331,
         18660,  3607,  8610, 16221, 19139,  8774, 27314,  7700, 23760, 21344,
         23500, 21614,   913, 11751, 25404,  3366,  7700,  5283,  4976, 20327,
         11736, 23707,  8391, 26827,  7230,  6392, 22727, 13793, 15093,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 13657, 15024, 20032,  3686, 22354, 21344, 22078, 23443, 19731,
         23732,  5959, 19324,   759, 21960, 12215, 19934, 21827, 27489,  3679,
         27365,  1866,  1708,  5624, 10480, 14074, 11212, 13443, 10703, 18056,
         10494, 24344,   171, 12205, 27587, 24789, 11768, 17262, 11212,  2866,
         13175, 20986, 21344, 15704, 24867,  4184,  1450, 20086,  4184, 10494,
         20032,  3679, 21960, 26500,  5015, 24718, 15799, 13657, 22935,  7897,
         27010, 19324, 21960, 25593,  3867, 17171, 15199, 24137, 19731,  2866,
           651, 15364,   127, 20086,  5990, 17262, 21932, 19324,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  7348,  4101,  6163,  6342, 12227,  7350, 16310, 17087, 22530,

 46%|████▋     | 52/112 [00:04<00:03, 16.09it/s, loss=1.46]

tensor([[    1, 15279, 20683,  ...,     0,     0,     0],
        [    1, 16203, 12919,  ...,     0,     0,     0],
        [    1,  5115,   561,  ...,     0,     0,     0],
        [    1, 24521, 11292,  ...,  8458, 14200,     0]], device='cuda:0') tensor([[[-2.2946e+00,  2.2381e+01, -4.0166e-01,  ..., -1.5992e+00,
           5.1407e-01,  6.0478e-01],
         [-5.2974e+00, -3.7492e+00, -2.0875e+00,  ..., -4.2210e+00,
          -1.3020e+00, -9.4919e-01],
         [-6.8310e+00, -4.2172e+00, -3.7036e+00,  ..., -6.9234e+00,
          -3.2258e+00, -1.8851e+00],
         ...,
         [-1.9584e+00, -1.5614e-02, -1.1034e+00,  ..., -1.5683e+00,
          -1.0415e+00, -3.6857e-01],
         [-2.2254e+00, -4.4735e-01, -1.2328e+00,  ..., -1.8635e+00,
          -1.1927e+00, -4.4453e-01],
         [-2.6367e+00, -9.9305e-01, -1.4748e+00,  ..., -2.2938e+00,
          -1.4162e+00, -5.7426e-01]],

        [[-1.6765e+00,  2.2441e+01, -1.4169e-01,  ..., -7.4426e-01,
           7.9987e-01,  1.0632e+00],
         [-3.8683e+00, -7.1927e-02, -1.6209e+00,  ..., -2.9375e+00,
          -1.1254e+00,  2.2546e-01],
         [-4.5519e+00, -2.2094e+00, -2.1809e+00,  ..., -4.0611e+00,
          -2.1168e+00, -7.1949e-01],
         ...,
         [-2.0363e+00,  4.0838e-01, -9.8782e-01,  ..., -1.1766e+00,
          -1.0159e+00, -2.4139e-02],
         [-2.3561e+00, -9.7527e-02, -1.1560e+00,  ..., -1.5515e+00,
          -1.1930e+00, -1.3307e-01],
         [-2.7363e+00, -6.0546e-01, -1.3861e+00,  ..., -1.9499e+00,
          -1.4049e+00, -2.4660e-01]],

        [[-2.3466e+00,  2.2136e+01, -4.5378e-01,  ..., -1.6530e+00,
           4.3626e-01,  7.0614e-01],
         [-6.6235e+00, -3.6033e+00, -2.3810e+00,  ..., -5.2829e+00,
          -3.2669e+00, -1.5378e+00],
         [-7.0465e-01, -2.9557e-01, -3.2627e-01,  ..., -1.2778e-01,
          -6.7608e-01,  5.4973e-01],
         ...,
         [-1.8055e+00, -3.6351e-01, -9.9414e-01,  ..., -1.4085e+00,
          -9.7973e-01, -1.9417e-01],
         [-2.0547e+00, -8.1135e-01, -1.1176e+00,  ..., -1.6935e+00,
          -1.1259e+00, -2.6293e-01],
         [-2.5184e+00, -1.4203e+00, -1.3977e+00,  ..., -2.1731e+00,
          -1.3842e+00, -4.2373e-01]],

        [[-1.9253e+00,  2.2919e+01, -2.2890e-01,  ..., -1.2838e+00,
           6.9432e-01,  5.6381e-01],
         [-1.1784e+00, -1.3773e-01, -2.3046e-01,  ..., -1.6888e+00,
          -9.6166e-01, -8.7412e-01],
         [-2.5166e+00,  4.7073e-01, -1.1783e+00,  ..., -2.5254e+00,
          -1.4023e+00, -5.8419e-01],
         ...,
         [-3.1438e+00, -2.7595e+00, -8.2356e-01,  ..., -3.2804e+00,
          -1.7704e+00, -6.5515e-01],
         [-4.6953e+00, -1.9681e+00, -2.9755e+00,  ..., -4.6087e+00,
          -2.5323e+00, -5.7036e-01],
         [-6.9870e-01, -6.9683e-02, -8.4630e-01,  ..., -6.1261e-01,
          -3.6311e-01, -4.3497e-01]]], device='cuda:0') tensor([[    1, 14542, 15279, 13464, 14459, 20139, 20683, 16488, 12586, 14795,
         13121, 20473, 18791, 24133,  1952, 17083, 16205, 14459, 21344, 16326,
         12553, 14317, 13934, 27483, 25503, 15279, 21344, 27338, 14891,  9844,
         27380, 20601,  4003,  1429, 15279, 21344,  4792, 27338,   441, 17154,
          2428,   290,  6646, 23387,  2245, 15268, 12146,  2428,  4201,  1322,
         14542, 25503, 15279, 21344, 20002,  1429, 16924,  8502, 12733, 13237,
          8853, 19057, 14290, 26885, 18955,  5025, 25503, 21344,  4792, 19606,
         20139,  1113, 15279, 21535,   538, 20877, 26919, 15687,   265, 14317,
          4969,  3555, 10742, 17635, 13793, 16205, 14459, 21535, 23391, 20340,
           198,  8438, 23388, 13235, 14317,  4969,  3555, 10742,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 16203, 24867,  4823, 26170,  2532,  4023, 23080, 15645, 15139,
         21227, 26170,  7839,  6677,  4823,  4023, 14551,  9810, 23080,  4006,
          6151,  4823,  4080,  8159, 17278,  4023,  8094, 21229,  5332, 11713,
         10951,  4952, 26172, 18267, 17631, 21932,  7599, 14855,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1,  5115, 27150, 24797,  3625, 14891,  6163, 26424, 23007,   468,
         13934, 16894, 16799,  5115,  5885,  4974, 14891, 12150, 27150, 24797,
          3625, 26776,  9327, 20459,  6445, 14044,  5115, 13664, 16283, 14948,
         19451, 11013, 19922,  9482,  9973,  8111, 11662,  5568, 21899, 19867,
         21344,  5115,  5115,   290, 12650, 21859, 22568,  6204, 20098, 16626,
         13996,  4750,  5115,  3905, 24718,  2499, 26876, 25167, 26776,  6846,
         21216, 26761, 10055, 18739, 14393, 24680, 17212,  8879,  1758, 13934,
         21982,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 16148,  8053,  4559, 11631, 19457, 24532,  7024, 20643,  6861,
         18056,  2171, 12797,  1242, 23221,  8458, 14200, 16138, 19599, 21171,
         24409,  6531,  6668,  7839, 21988, 10086,  4048,  9482,   139, 20645,
         17795, 14096, 14099,   887, 16522,  9193, 26818,  4051, 10086, 10125,
         14096, 14099, 16205, 24409, 25025,  2102, 16644, 26867,  1042,  8573,
         16148,  8053, 23387, 23825, 12155, 19694,  3670,   279,   151, 26280,
          6858, 16148,  8053,  4559, 14096, 23433, 10656, 27497,  1660, 12668,
         22340,  2497, 16513, 22055, 24532,   276, 26316,  7024, 17296, 13964,
          8038,  6861, 18056, 10205, 12797,  1406, 16148, 12253, 18739, 24736,
         24530, 12484, 16205, 11133, 17750, 21535,  5910, 12224, 20877, 14096,
          1278,   890, 19483, 18056, 23754, 27245,  9634, 14345,   887, 16205,
         24409, 12755, 19072, 22234,  6577, 27290, 11364, 10088, 27046, 26172,
         16138, 19604,  3670,  7024,  9287,  7504,  4574, 24231, 10086, 23552,
         26172, 12560,  4574, 17982,  4876,  3670,  8462, 20877, 14596,  1852,
          3670, 21344,   301, 11290,  6861, 20851,  4867, 16205, 24409, 19963,
         19072, 22234, 21515, 14070, 21831, 18068, 13906,  4874, 12902, 14948,
         25492, 26180, 17283, 20960,  3670, 19457,  8706, 17983,  5903,  2219,
          1758, 19683, 21810,     0]], device='cuda:0')
tensor([[    1,  3652,  1617,  ...,     0,     0,     0],
        [    1,    21, 20708,  ...,     0,     0,     0],
        [    1, 12334, 20762,  ...,     0,     0,     0],
        [    1, 18331, 10302,  ...,  9973, 22357,     0]], device='cuda:0') tensor([[[-2.6327e+00,  2.1493e+01, -6.9640e-01,  ..., -1.9909e+00,
           7.9095e-02,  6.5163e-01],
         [-5.1524e+00, -1.4994e+00, -1.9942e+00,  ..., -4.4936e+00,
          -3.7273e+00, -1.1351e+00],
         [-1.2170e+00,  1.5218e+00, -2.4718e-01,  ..., -7.7282e-01,
          -7.4722e-01,  1.0843e+00],
         ...,
         [-2.3304e+00, -6.7764e-01, -1.3987e+00,  ..., -1.8161e+00,
          -1.2153e+00, -1.4917e-01],
         [-2.3592e+00, -5.6744e-01, -1.3858e+00,  ..., -1.7514e+00,
          -1.1672e+00, -6.5222e-02],
         [-2.4745e+00, -6.0754e-01, -1.4660e+00,  ..., -1.8223e+00,
          -1.1943e+00, -1.9046e-03]],

        [[-2.2787e+00,  2.2629e+01, -4.5596e-01,  ..., -1.4339e+00,
           5.9981e-01,  5.4584e-01],
         [-3.3249e+00, -4.1592e-02, -5.4504e-01,  ..., -2.8837e+00,
          -1.7819e+00, -7.5982e-01],
         [-1.7582e+00, -1.5052e+00, -1.1833e+00,  ..., -2.0352e+00,
          -7.7998e-01, -1.0844e+00],
         ...,
         [-2.3429e+00, -9.3513e-01, -1.3629e+00,  ..., -1.9308e+00,
          -9.8527e-01, -8.1110e-01],
         [-2.3824e+00, -7.9179e-01, -1.3256e+00,  ..., -1.8627e+00,
          -9.4443e-01, -6.9395e-01],
         [-2.4715e+00, -7.5406e-01, -1.4078e+00,  ..., -1.8917e+00,
          -9.7387e-01, -6.0284e-01]],

        [[-1.9270e+00,  2.2589e+01, -2.1163e-01,  ..., -1.1480e+00,
           7.2258e-01,  8.5926e-01],
         [-4.6238e+00, -2.3106e+00, -2.0134e+00,  ..., -4.3580e+00,
          -2.0446e+00, -8.0929e-01],
         [-4.6772e+00, -2.1259e+00, -2.8552e+00,  ..., -5.1520e+00,
          -2.4514e+00, -1.0191e+00],
         ...,
         [-2.3880e+00, -9.4766e-01, -1.4366e+00,  ..., -1.9789e+00,
          -9.7183e-01, -6.3668e-01],
         [-2.3381e+00, -7.1835e-01, -1.3660e+00,  ..., -1.7924e+00,
          -8.7790e-01, -4.8128e-01],
         [-2.4095e+00, -6.8926e-01, -1.4327e+00,  ..., -1.8099e+00,
          -8.8722e-01, -3.7084e-01]],

        [[-2.4832e+00,  2.2596e+01, -3.7543e-01,  ..., -1.8354e+00,
           4.2800e-01,  3.7025e-01],
         [-4.0022e+00,  8.9311e-01, -1.5217e+00,  ..., -3.6066e+00,
          -2.0063e+00, -6.3174e-01],
         [-6.3929e+00, -5.4482e+00, -3.5098e+00,  ..., -6.2817e+00,
          -3.4833e+00, -1.9414e+00],
         ...,
         [-3.9819e+00, -3.4908e-01, -1.4806e+00,  ..., -3.6758e+00,
          -2.1277e+00, -5.3654e-01],
         [-4.7906e+00, -4.5046e+00, -2.0933e+00,  ..., -5.2212e+00,
          -2.5849e+00, -2.5315e+00],
         [-2.2120e+00, -5.6327e-01, -1.4179e+00,  ..., -1.8362e+00,
          -6.9081e-01, -8.8223e-01]]], device='cuda:0') tensor([[    1, 13090,  3652,  2169, 24797, 14029, 13816, 27188,  1617, 17204,
         12461,  3652, 25593, 24938,  4028, 15481, 27151,  3652,   759,  6193,
          4875,  1617, 17204, 26741,  8441, 24247, 12668,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 17316,    21, 15499,  2529, 25655, 22030, 25285, 16311,  1903,
         16117, 25051,  3905, 11572,   749, 24199,  1353, 16726, 23759, 16311,
          2169, 10351, 18244, 18094, 24199,  9266, 24938,   744,    21, 17316,
         22944, 22899, 15731, 20001, 27317, 27380, 19996,  8112, 18901, 15103,
            21,  9266, 19349, 20707, 22513, 14108,  1903,   236,  3018,  7615,
         17316, 23426, 24199, 18664, 19515,    21, 20709, 11570, 18901, 11472,
         16311, 14944, 15639,  9266, 24938,   744, 27483,  9634,  2529, 25655,
          2310,   938,   515,  8846,  1010,  9764, 14728, 15602, 19358,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 12334, 17437, 21100,   328, 24938, 27479, 13027, 16048,  7612,
         26831,  8683, 16818,  8104, 13030,  7700,  8761, 26827,  7230,  6392,
         11287, 25389,  5285,  9172, 24840, 16050, 13934, 27479, 25593, 18999,
         19514, 22368, 10084, 26161, 10721,  2387,  8615, 18318,  8683,  7615,
          5522,   759, 17171, 24147,  6392,  7841,   759, 17171, 13505, 12167,
          7230, 15093, 19123,  9338, 21726, 25567, 11392,  6392, 13027, 27199,
         17471, 12334, 17437,  9139, 22455, 19373,  8678, 22718, 24938, 20658,
         21365, 18304,  8918, 24938, 22513,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  2102, 23221, 26072, 16626,   912, 25063, 18331, 26669, 26205,
          8111, 21216, 25914, 15199, 21490,  2102, 23221,  9266,  4490, 23428,
         26183, 24291,  2102, 23221, 16626, 25063, 18331,  5522,  8047,  6949,
         15800,  3549, 26183, 18331,  2387,  6620, 18739,  8047,  6071, 25547,
         15941, 24534,  5658,  2102, 20525,  6672,  2102,  3137,  2102, 17449,
          3141,  2102,  3137, 11630, 24534, 22899, 24797, 17810, 12649, 26183,
         16924,  6759, 26822, 23221,  3140,  8172,  9973, 22357, 17278, 13442,
          1583, 10718, 10718, 16521, 27290,  4540, 18056,  5657, 24534, 12483,
          3106, 23221, 14290, 21344,   948, 24810,  2102, 11162,  6672, 16626,
         15425, 23224, 16644, 26443,    58, 21859, 18856,  1866, 24867, 10303,
         10610,  6522, 10718, 26835,   912,  1666, 23224,  3141,   733, 26161,
         24592, 23645, 17837, 18475, 25204, 12315, 18483,   240,  9111, 14566,
         24322, 21344,   952, 25183,  2102,  3137,     0]], device='cuda:0')
tensor([[    1, 27552, 21869,  5569,   244, 21364, 27552, 20701, 26161,  5569,
         26876, 21865, 21409,  1831,  9181, 10711, 14437, 13663,  9260,  2890,
         14857,  1443, 27552, 21344, 23910,  1831, 17367, 12797, 21364, 27545,
          2690,  5996, 27552, 26161, 14001,  1537,  1831,  1444,  9812, 21269,
         10512, 11995, 26161,  5569, 17278, 13934, 26882,  2625, 21364,  1831,
          1774, 16131,  3434, 25920, 23566, 25725, 21269, 16651,  4384,  1831,
          2890, 27545, 19119, 25920,  2690, 23975, 23440, 19317,  1576, 23760,
         14385, 24085, 21268,  9639,  2438, 17117, 19114, 15024, 17000,  2244,
         25920, 19116, 27552, 17117, 17437,  5522, 25650,  8829, 10964, 24085,
          8437, 10075, 23440, 10035,  9260, 17252,  1576, 21269, 10512,  9523,
         21364, 27552, 14669,  1443, 17795,   244,  8089,  2690,  1758, 24482,
          2448, 21535,  4845, 17574, 27552, 26161, 14001,  4381,  1576, 12008,
          9260,  9145,  1936, 24772,  1444, 19265, 26161,  1936, 13988, 27317,
         13319, 26876, 27552,   759, 21865, 14101, 20343, 18989,  3018, 10711,
          2244,  1576, 12008, 12612, 19438, 14101, 20007,  1666, 26161, 27552,
         23203, 15700, 13837, 25025,   486,  9673, 18955,  8683, 17117, 15096,
         23613, 19118,   290,  9905, 17579, 27543, 20331, 25725,   853, 27053,
         23935,  1831,  8346,  9791, 12651, 23083, 25503, 18949, 19453, 21344,
          1831, 17576, 12315, 12780, 18447,  3287, 20274, 21269,  8086,  9265,
         12649,  6672, 27545, 18949, 19453,   759, 23932,  4226, 16456, 18211,
          5445,  5522, 18475, 21044, 25920,  9905, 22453,  4794,   527, 10075,
         27290, 13185,  8086, 19174, 27552,  4384, 21364, 14857,  1443, 14023,
          4677,  4845,  4789, 27552,  4381,  9260, 24432, 10512,  3557,  6611,
         18620,   818,  9630, 15702, 13520,     0],
        [    1, 16203, 12919,  2533, 24833, 16203, 24867,  4823, 26170,  2532,
          4023, 23080, 15645, 15139, 21227, 10951,  4952, 26172, 18267, 17631,
         21932,  7599, 14855,  6677,  9936, 16626, 19182, 26882,   619,  3563,
         26172,   141, 21932,  8649, 13812, 15590, 16648, 13235, 16205, 15139,
         20721, 16203, 26183,  2532,  6151,   759,  3866, 15500, 26183, 11381,
          7627, 26170,  7839,  6677,  4823,  4023, 14551,  9810, 22987, 15922,
         18267, 17631, 20643, 23760, 19918,  7803, 23080,  6523, 23080,  4006,
          6151,  4823,  4080,  8159, 17278,  4023,  8094, 21229,  5332, 11713,
           783, 16197,  4273,  4685, 16789, 10302, 17825, 18620,   705,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  4495,  5522, 18475,  1610, 17204, 13571,  4495,  6443, 20476,
         19374, 13027,  1617, 17204, 18143, 27371, 12461, 17204,  4199, 17902,
         15374, 21344, 13571, 27371, 17019, 10426, 20200, 23203, 12525, 22496,
          6342, 23843,  8200,  7184,  1439, 12461, 26885,  2046, 20930,  5522,
         18475, 14070, 20930, 23472,  1708,  6600,    80, 27394,  8200, 14412,
         25161,  2207, 13027,  4495, 27338,  3970, 10205, 27076,  3679, 20505,
         17171,  4495, 23566, 19737, 16496, 27314,  6600, 18485, 10950, 15203,
         13934, 21804,  2236, 17221, 14096, 27371,  7615, 21804, 12458, 20701,
         25154, 15401, 13082,  7211, 26172,  4867,  1616, 17252,  9266, 10559,
         22633, 21804,  7211, 18481,  1617, 17204, 22513, 14604,  9266, 21135,
         27479, 17131, 27338, 20323, 27076,  3679, 16654, 21804, 19739, 25517,
         24718,  9634, 24938,  4028, 16019, 21903, 18481, 22513, 13934, 27479,

 50%|█████     | 56/112 [00:04<00:03, 16.30it/s, loss=1.15]

tensor([[    1,  5667,  9266,  ...,     0,     0,     0],
        [    1, 21160, 24838,  ...,     0,     0,     0],
        [    1, 11212, 16958,  ...,     0,     0,     0],
        [    1,  2549,   539,  ..., 18791,   290,     0]], device='cuda:0') tensor([[[-2.1535, 22.4169, -0.2630,  ..., -1.4839,  0.6983,  0.6616],
         [-2.3623, -2.4841, -1.8900,  ..., -2.8091, -1.2400, -0.4456],
         [-3.6011, -3.1970, -2.3118,  ..., -4.0152, -1.9072, -0.8258],
         ...,
         [-2.9819, -1.9384, -2.0473,  ..., -2.7389, -1.1983, -0.8377],
         [-2.9135, -1.7995, -2.0087,  ..., -2.6386, -1.2590, -0.9827],
         [-2.7586, -1.5173, -1.8210,  ..., -2.4183, -1.2179, -0.9934]],

        [[-2.5826, 22.0828, -0.6689,  ..., -1.8344,  0.3860,  0.5943],
         [-2.1708,  0.5350, -1.3638,  ..., -1.5696, -1.0359,  0.4089],
         [-4.9948, -2.3338, -2.4290,  ..., -5.2749, -2.1205, -1.6689],
         ...,
         [-2.0988, -1.6881, -1.7875,  ..., -1.7451, -0.9907, -0.5001],
         [-2.0765, -1.6161, -1.7505,  ..., -1.6894, -1.0793, -0.6490],
         [-1.9581, -1.4052, -1.6019,  ..., -1.5076, -1.0629, -0.6605]],

        [[-1.8716, 22.3564, -0.0695,  ..., -1.2341,  0.5381,  0.8021],
         [-3.0705, -0.6900, -1.3570,  ..., -3.0010, -1.2460, -0.4818],
         [-7.0573, -1.9424, -4.3186,  ..., -7.4355, -4.2746, -1.3509],
         ...,
         [-2.0012, -1.3408, -1.3832,  ..., -1.7353, -1.0274, -0.4121],
         [-1.9912, -1.2608, -1.3543,  ..., -1.6909, -1.1111, -0.5714],
         [-1.8500, -0.9988, -1.1623,  ..., -1.4905, -1.0889, -0.5909]],

        [[-2.7692, 22.2440, -0.5328,  ..., -2.0490,  0.4116,  0.3344],
         [-3.6980, -2.6738, -1.8550,  ..., -3.2502, -1.5714, -1.1520],
         [-2.8801, -0.1092, -1.1848,  ..., -2.2474, -0.9896, -1.5355],
         ...,
         [-6.3702, -5.5446, -3.3897,  ..., -6.1175, -3.5638, -1.9079],
         [-8.9714, -4.3872, -4.6999,  ..., -8.1660, -4.3430, -1.2916],
         [-1.6804, -0.8826, -1.3552,  ..., -1.4174, -0.8603, -1.0535]]],
       device='cuda:0') tensor([[    1, 16205, 19773, 17171,  9266,  7996,  1140, 14795, 15024,  6573,
          6201, 14795, 14744,  7077,  9266, 20287, 14765, 20503, 16388, 16205,
         19773,  8950,  1140, 24823, 16387,  4046, 22687,  9482, 25213,  7038,
          1042,  4845, 11736, 19452,  4079, 22742, 24509,  6573,  4948, 14444,
         11932, 14760,  4126,   558,  5218, 19783,  4948, 19131,  7651, 26170,
           770, 16205, 19773,  7465, 24509,  5658, 14765, 23472,  1140, 21859,
         20287,   125, 12652, 25465,  2204,  4970,  6668, 26170,  1140, 18377,
         14407,  4948, 16205, 19773, 14096,  1140,  8182, 16205, 19773,  6705,
          6182, 17692,  3586,  6745,  8984, 11570,  3510, 13075, 19773, 11162,
         24509,  2219,  9266, 14765,  4948,  6745,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 13022, 11300, 10784, 23528, 21344,  8853, 23566, 11631, 10784,
         27338, 11606, 20960, 16388,  9627, 16178,  3290,   607, 11300, 14444,
         13865,  3294,  6668, 11724, 16205, 10434, 21344,  1638, 19187, 11713,
          5522, 20327, 16626, 22558, 25547, 15512,  4839,  3951, 15279, 10426,
         10395, 15279,  6612, 13135, 11300, 11713, 21344, 19814, 19637, 15129,
         13007, 15129, 11300,  9627, 11300, 27046,  5153, 17171, 12126, 10785,
         24938, 11300, 24043, 11623, 25544, 11570, 16304, 10784, 16205, 10434,
          3520,  1638, 17929, 16177,  3290, 21815,  3945,  7100, 11300, 10652,
         21815, 17089, 21344,  6129, 17078,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 14437, 13939,  3552, 11212, 11268, 27115,  9973, 18423,  9172,
         11212, 16958, 23430,  9973, 16523, 27115, 19496,  9172,  5511, 16522,
          1690,  6264, 10395, 11212, 16958, 22030, 10215,  5023,  5862,  9172,
         27115,  3551,  5511, 10025,   181, 23975, 10711,  1737,  9973,  3551,
          2134, 23007,   468,  7310, 16563, 22405,  5522, 19493,  9172, 27115,
         11212, 15398, 18475,  1367, 13710, 25593, 14099,  9172, 13759, 24509,
         19493, 10711, 21490,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 19019, 15783, 21344,  5549, 26659, 10395, 18633, 18740, 15235,
         26886, 26986, 23566, 22935, 17077, 21344, 13266, 18056, 14881, 23083,
           853,  9437, 18837,  7822,  3561, 19019, 15783, 21344, 12918,   783,
         21344,  3115,  6027, 16526, 17702, 19349, 21331, 12922, 16205,  2549,
         21344, 10512,   759, 14566, 14881, 24062, 14101,   546,    98,   246,
          7184, 17367, 17795, 20746,  3744, 14586,  4036,  6469,  1401, 27338,
         19566, 14025,  9027, 14317, 14222, 13793, 21344, 12126,   783, 13155,
         25944,  9001, 22935,  5303, 25025, 16999, 10512, 14290,  5181,  1998,
          1526, 21344, 27338, 23472,  4079,  9027, 25672,  5303, 16205,  2549,
         21344, 14060, 22007, 24944, 25147,  8037, 15500, 19349, 19531,  1048,
         22029,   240,  5549, 19939, 26886, 16205,  2549,   759, 23200, 15448,
         15024, 18056,   240,  5549,  4976,  4866,  5848,     0]],
       device='cuda:0')
tensor([[    1,  9247,  3203,  ...,     0,     0,     0],
        [    1,  2636, 24344,  ...,  4759, 10456,     0],
        [    1, 25663, 19143,  ...,     0,     0,     0],
        [    1, 17204, 23001,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.2217, 22.5575, -0.3241,  ..., -1.4807,  0.5658,  0.5307],
         [-5.8501, -1.9560, -2.4105,  ..., -5.4823, -3.3964, -1.7902],
         [-3.0065, -1.7726, -0.9080,  ..., -3.8621, -1.8383,  0.0499],
         ...,
         [-1.5489, -0.4107, -1.2435,  ..., -1.2909, -0.7540, -0.7182],
         [-1.8914, -0.9772, -1.4229,  ..., -1.6675, -0.9374, -0.8182],
         [-2.1317, -1.4885, -1.5743,  ..., -1.9054, -1.0967, -0.9539]],

        [[-1.9557, 22.7363, -0.1592,  ..., -1.2631,  0.6943,  0.5970],
         [-1.4197, -1.7122, -1.4364,  ..., -1.8577, -0.8669, -0.3058],
         [ 0.3875,  2.0633, -0.0503,  ...,  0.0667, -0.0835, -0.3863],
         ...,
         [-4.2948, -2.5584, -2.6370,  ..., -4.4535, -2.4206, -1.1304],
         [-7.1878, -4.3579, -2.9206,  ..., -7.0004, -2.1561, -2.0660],
         [-2.3943, -1.7654, -1.7035,  ..., -2.2718, -1.2005, -1.1603]],

        [[-3.0656, 22.0315, -0.7871,  ..., -2.2493,  0.1423,  0.3600],
         [-3.7769, -0.3245, -1.4115,  ..., -3.2236, -2.1653, -0.5681],
         [-2.8812, -0.8345, -1.1537,  ..., -2.7789, -1.1267, -0.5304],
         ...,
         [-2.5912, -0.8572, -1.3666,  ..., -2.2009, -1.3458, -0.7037],
         [-2.9893, -1.3862, -1.6311,  ..., -2.6060, -1.5622, -0.8062],
         [-3.1957, -1.8215, -1.8140,  ..., -2.7906, -1.7068, -0.8800]],

        [[-2.5987, 21.9022, -0.5831,  ..., -1.8774,  0.2870,  0.5234],
         [-5.2654, -2.3822, -1.5513,  ..., -5.1640, -2.7093, -0.6359],
         [-2.6333, -2.5943, -1.3028,  ..., -2.7344, -1.8806, -0.9222],
         ...,
         [-2.5570, -0.6945, -1.3991,  ..., -2.1652, -1.2892, -0.6096],
         [-2.9050, -1.2070, -1.6135,  ..., -2.5347, -1.4770, -0.6998],
         [-2.9587, -1.5847, -1.6952,  ..., -2.5689, -1.5310, -0.7224]]],
       device='cuda:0') tensor([[    1, 15663, 12675,  8667, 22008, 20942, 14551,  1698,  9247, 26850,
          3203, 20287, 12675, 16023,  9260, 26866,  4102, 10718, 18678, 18056,
         26183,  9247,  3203, 21535, 20606, 22724,  8299, 23673, 11971,  9247,
         19307, 18673, 15997,  8879,  9085, 21854, 11544, 12675,  8667, 12484,
         13802, 15663, 19149,  9247,  5658, 16196,  9627, 23430,  9581,  3203,
         14886, 16596,  1758, 16196,  9627,  4386,  9247,  7350,   744,  7790,
         15731, 24944, 19358, 21344, 27338, 11003, 10022, 27123, 26183, 16588,
          3206, 18678,  9247, 26172,  3517,  9240, 18266,   759, 10718, 16924,
         26555, 16588,  2032,  8872, 20286,  9247, 16894, 15687,  8437,  3859,
         11180, 25544, 15663, 19149, 23479, 27150, 18056,  1708, 22887, 10232,
         12675,  8667,  3203, 20286,  9266,  9844, 26368,  9247, 14951,  7475,
         20587,   874, 18837, 13963,  9069, 24617,  6106,  3557, 18056, 22448,
         19681, 22513, 22887,  9939, 18825,  5346, 14070, 13916, 16924, 21854,
         19088,  4750, 14308, 15663, 12675,  8667,  3557,  4585, 17285, 23245,
          9247, 26867,  1538, 19680, 16522,  9844, 17630,   402, 16626, 27522,
         24944, 16221,  6672, 27290,  7257, 22513, 10447,  9247, 14795,  9266,
          1129, 16387,  8984,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 16205, 16366,  1256,  2636,  2169, 12274, 23003, 12040, 11937,
          4346, 25221, 23003, 16644, 12408, 16651, 25564, 19628,  2628,   912,
          9260, 24536,  8359, 16924,  2636,  8587,  3517,  2635,   757,  8509,
          9293, 15731, 10718,  8675, 14203,  5883, 16924,  2636, 14323, 13442,
         10718, 26850,   757, 17504, 12408, 11736,   529,  8637, 14317, 14378,
         18620,   913, 16761,  4250, 14864, 15425, 14604, 25221, 21044, 16644,
         10043,  2636, 13498, 17795, 25269,  2636, 15268, 22742, 19844,  4829,
          8637, 21530, 19298,  1672, 18056, 21530, 27314, 18626, 17367, 14317,
          9746, 16650, 14021, 16007,  1152,  6759, 23682, 17079,  2636, 17795,
          5248, 27479,  9452,  2636,  3798,  5726,  8737, 16644,  8443, 17107,
         27379, 12922, 11995,  2436, 15425, 17079,  8737, 27204,   171,  8443,
         26161, 20525, 24789, 24400, 18220, 12675,   839, 14290, 21535,  2628,
          5658,  8458, 21831,   770, 14177, 25122, 26093, 14070,  8458, 25593,
         16050, 26850, 14531,  2636,  8463, 14070,  8358,  9293, 15731, 26850,
         16924, 22030, 10715, 19128, 13237, 16521,   147,  8207, 15024,  5310,
          6922, 21535, 16205, 16366, 25279, 22870, 25279, 21535, 16205, 16366,
         25068, 10471,  2630, 16176, 19940, 13964,  2375, 26368, 16212, 23034,
         14891,  7637, 21239,  2628,     0],
        [    1, 25639, 23227,  9260, 25663, 18745, 20925,  1028, 19136, 21365,
         20463,  8111,  9505, 13613,  2822,  8391, 25161, 25663, 19940, 14604,
         23211,  6135,  4158,  3924, 21344, 24884, 22448, 16626,  9634, 27479,
           527, 21701,  4559, 19731, 13027, 25663,  1017, 23211,   527,  4158,
         10061, 25663, 14669, 20877, 14881, 20463, 22276, 27338,  8047,  9293,
         27483,  7612,  8615,  9260, 20475,  9266,  1028, 20647, 22513, 14421,
         14542, 23594,  8526, 13304, 21344, 25639, 15093, 21874, 21365, 10721,
         13934, 27479,  4199,  8552, 18194, 15344, 21344,  9260, 18450, 10715,
         21365, 25639, 12671,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 17700,  6948, 14388, 23968,  3510, 16205, 25112, 21344, 22887,
         17872, 19084, 17204, 23001, 16179, 20171, 22887, 17872, 26161, 17204,
         23001,  6670,  1254, 15024, 16616, 10575, 12341, 20593, 17204, 23001,
         16179,  8774, 15024, 15500, 20479, 26170, 17204, 23001, 24291,  6667,
         22887, 24789, 12126, 18581, 14881,  4842,    58,  4254, 17872,  5408,
         17204, 23001, 25339, 12607,  6926,  9523, 26183, 17171,   290,  8879,
         12606,  4974, 17204, 23001, 17872,  4585,  8586, 15024, 27483, 27201,
         19088, 21344, 23206, 13132, 24151, 26719, 27288, 15663, 17204, 23001,
         16179, 11215, 26882, 14388,  9630, 14387, 25112, 14086,  1526, 22887,
         17872, 17700, 15500, 27321, 15663, 27338, 12918, 22007, 17868, 13999,
          9905,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 22854, 17117, 11481, 27314,  7700, 22854,  5492, 17117, 11472,
         10351,  7693, 10721,   770, 27314, 14874,  7697, 26847, 23640, 19003,
         20928,   168, 17064, 13943,  2414,  1028, 20470, 17064,  5915, 10721,
         18872, 27314, 14857, 12335, 20169, 26161, 10721, 27338, 19829,  8829,
         16654, 27479, 18999,  8357, 17064, 21344, 11736, 17765,  2032,  7696,
         24789, 24400, 21344,  2245, 10351,  7700,  5522, 23566, 20147, 16000,
          9537, 13031, 10721,   759, 21541,  1758, 27479, 17424, 27331, 15499,
          8407,  2618,   757, 22727, 10721,  9537, 22697, 27479, 17064, 21344,
         17471, 20470,  9533, 25122, 10721, 15499,  5548, 17064, 22697, 16654,
         27479, 20010, 16799, 10456, 19885,  2244,  6600, 19939, 17117, 19003,
         25532, 27314,  7700, 20147, 16000,  7070,  9905, 21344, 13062, 18254,
          5510, 17064,  4199,  7698, 19003,  5784, 11395, 23428, 19994, 11392,
         22030, 13939, 17047,  6826, 17117, 19006, 12171, 13159, 19251, 27338,
         12166,  5216,  5036, 23144, 17064, 21344, 17117, 22280,  8139, 11468,
         23389, 21874, 27326, 22053, 17117, 19003, 20925, 24789, 22280,    86,
         27199, 16654, 19514, 26478, 13672, 21943,  7698, 17064, 25025,  2102,
         27314,  3401, 20470, 20012, 25812, 12691,  2514, 17117, 22280, 27479,
         27338, 20147, 16000,  5567,  4226,  2814,  7700, 23110,  4751, 13030,
           625, 17171,  8844, 19939, 16050, 27338, 11286, 27314,  7693, 20012,
         17064, 21344, 24041, 23760,  1852, 22197, 11392, 19143, 20012,  3401,
         12777,  5271, 16825,   838, 23428,  7621,  8396,   290, 11736, 20470,
         26750, 20331, 21874, 26986,  5265,  8396, 18475, 23760, 24045, 21044,
         15090, 26138,  9172,  7230,  6392, 17064, 11405,  5883,  6515, 11716,
          8620, 10193,  8407, 20298,  8678, 14086, 10721,     0],
        [    1, 26161,  1926, 21823, 22042,  9293,  1926,   838, 23856,   525,
         17929, 25122, 22040, 12772,  9708, 25219, 22147, 18814, 26161, 21853,
          8526,  4801,  1017, 22043, 13943, 12341, 27044,  4452, 26161, 16339,
          9873, 21823,   759, 21344,  3190,  9704,  4081, 25593,  8487, 21943,
          8553,  4730,  7098,  4730,  7098, 17795,  9364,  2890,  2694, 13934,
         27479, 24840,  8487,  4730,  8553,   525, 22043, 21823, 21823, 22030,
         24449, 23382, 16339,  9873, 26170, 15093, 24951,  9572, 19546,  9237,
         22311, 24650, 22147, 25219, 11056, 12651, 22742, 12780, 16339,  9873,
         17808, 18673, 13934, 25593, 27483, 12134, 18023, 25128, 16506,  2690,
          9873, 21823, 26070, 25593, 21973, 22043, 17171,  5589,  2694,  6837,
         23856,  1042,  3402, 17795,  9364, 24938,  3787, 21344, 21833,  6135,
          8095, 15093, 24951, 16339,  9862, 22153, 21823,   525,  6129, 25128,
          1900,   838,  3637, 14952,  1753,  7099,  1900,   838, 21853, 14795,
         17929,  1758,  9940, 15093, 24951, 18023, 17635,  5995,  9873, 22150,
         21975, 21823, 21344, 19830,  6129,  8253, 23194, 18023,  4866, 19079,
          4730, 14952,   418,  4730,  9873,  7098, 24840,  8487,  4730,  8553,
          3402,  2156, 17795,  2694, 22805, 20942,  1926,  9364,  2690, 15565,
         13934, 15044, 21823,  9145,  4368,  9704,  4081,  2869,  8987,  5569,
         13007, 24379, 21535, 11167,  3986, 21365, 17224,   701, 21827,  4767,
         20982, 11846, 21823, 18959, 11396, 24916,  9184, 18023, 17648, 16265,
         26496, 20439, 18149,  9940, 12455, 18989,  9905,  3013, 23206, 21823,
          2869, 17083, 25025,  2102, 12062,  4783, 15516, 14001, 21823, 22042,
          3534,  3986, 12224,   528, 24840,  8487, 14955, 18194, 15139,  8288,
         10812, 13226, 17675, 17635, 18149,  9184, 18023,     0],
        [    1,  7218, 11729,  1302, 19994, 14642, 26161,  7218, 11727,  4538,
         19994, 14642,  8391,  9765,  4973, 10720, 22578, 26161,  3268,  6297,
           914, 18867,  7218, 20327, 26827, 12780, 27323, 23440, 26161,  7700,
          3396,   337,  1122, 26081, 12697, 24040,  7218,  3860,  4973, 11736,
         25219, 26576, 17857, 26882, 24523,  1651, 25219, 14308,  6392,   882,
         19837, 16644,   914, 21344,   298,  8610, 15098,  2169, 14177, 13303,
         13027,  7218, 25219, 26370,  8391,  9765, 16090, 11484,  9757, 19994,
         14633, 24884, 17171,  7218,  2890, 27491,  6879,  3401,  9141,  4194,
         25390, 26161,  5882, 26833, 24884, 16456,  1458, 19417, 14952,  4194,
         21344, 15021, 12280,  7460,  2437,  8829,  8615,  7218,  3433,  8332,
          4194,  6071, 27497, 21344,    59,   893, 17902, 14769, 24938, 10190,
          4036, 10186, 21644, 12927, 19019, 15783, 22476,  2337, 26567,  4976,
         23707,  8391, 16205,  2337, 21344,  8391, 23707,    83, 27324, 12927,
          8683, 16205, 21644, 21344, 16650,  1345, 23328,  9543,  8526, 15098,
         20510,  5453, 10351,  7693, 12052, 12780, 14564, 25173,  8984, 15448,
          9181, 15785,  9913, 12335, 16465, 14542,  4565, 26986,  3945,  1937,
          4745,  9525, 23508,  7218,  6217,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 23088, 21869,    66, 25154, 17935, 22524,  3120, 23088, 23941,
          7790, 12590,  4842, 20139, 20220,  3584, 27314, 25154, 18664, 23411,
          3583, 17195, 11691, 25154, 13934, 13304, 23919, 13633, 12461, 26426,
         22296, 21868, 20221, 25154,  5506,  4381,  9145, 16626, 27522, 23440,
         24052,  5569, 22049, 14542,  2032,  4842,  7792, 17765,  9260, 10301,
          6106, 20596,  4894, 27479, 17131, 23411, 12444, 15858, 16924, 22357,
          6075, 25154, 12460, 13633, 22340, 12015, 13934, 15044, 21263, 11674,
         16522, 24081, 13941, 12215,  9161, 26426, 22942, 17441, 14029,  3580,
         20609, 25154, 12226,  6077,  4226, 17019, 25062, 27381, 23515,  2598,
         13633, 13143, 23206, 21344, 24938, 17131,  6015, 12461, 14101, 23839,
          6554, 23088, 17171, 19971, 18096, 12341, 17195, 11691, 25154,  4355,

 54%|█████▍    | 61/112 [00:04<00:02, 18.41it/s, loss=0.814]

tensor([[    1, 15630, 26161,  ...,     0,     0,     0],
        [    1,  2663,  2134,  ...,     0,     0,     0],
        [    1, 20989, 26717,  ...,     0,     0,     0],
        [    1, 21697, 26205,  ..., 13716, 20986,     0]], device='cuda:0') tensor([[[-3.3962, 21.6563, -1.0862,  ..., -2.5784, -0.0817,  0.1623],
         [-3.7420,  0.1918, -0.8371,  ..., -2.9901, -2.4388, -0.5501],
         [-5.4138, -2.9381, -1.1463,  ..., -4.8206, -2.2823, -2.5486],
         ...,
         [-3.7293, -2.4211, -2.6434,  ..., -3.4147, -2.1800, -1.2986],
         [-4.0572, -2.5437, -2.7052,  ..., -3.7168, -2.4128, -1.3554],
         [-4.3504, -2.5600, -2.6893,  ..., -3.9580, -2.5153, -1.3178]],

        [[-2.2518, 22.1173, -0.3824,  ..., -1.3423,  0.6274,  0.6630],
         [-4.7778, -1.8771, -2.5942,  ..., -4.8553, -1.3303, -0.8310],
         [-6.3726, -3.8643, -2.5627,  ..., -5.8359, -3.4118, -1.7105],
         ...,
         [-1.9779, -1.0391, -1.5575,  ..., -1.6318, -1.1519, -0.4424],
         [-2.5266, -1.2766, -1.7264,  ..., -2.1438, -1.4794, -0.5683],
         [-2.8794, -1.3000, -1.7378,  ..., -2.4436, -1.6237, -0.5412]],

        [[-1.9031, 22.5252, -0.3048,  ..., -1.1974,  0.6074,  0.7890],
         [-5.2924, -1.4505, -2.8019,  ..., -4.4699, -2.8309, -2.5142],
         [-2.7331, -2.1012, -1.0281,  ..., -3.1409, -1.3659,  0.6219],
         ...,
         [-2.2033, -1.1332, -1.9736,  ..., -2.2323, -1.3840, -0.9921],
         [-2.5297, -1.2728, -2.0330,  ..., -2.5308, -1.6124, -1.0553],
         [-2.8609, -1.2956, -2.0396,  ..., -2.8273, -1.7307, -1.0463]],

        [[-2.6721, 22.3841, -0.5968,  ..., -1.8932,  0.4275,  0.3593],
         [-5.0514,  0.3440, -3.1699,  ..., -4.5747, -2.1861, -0.7576],
         [-4.0464, -3.4559, -1.4426,  ..., -3.6100, -1.6134, -0.0981],
         ...,
         [-0.5959, -1.8311, -0.3653,  ..., -1.2521, -0.6001, -0.2856],
         [-5.1390, -2.7339, -2.7412,  ..., -4.7862, -2.9119, -1.6966],
         [-2.7459, -1.7476, -2.0385,  ..., -2.5304, -1.5031, -1.1837]]],
       device='cuda:0') tensor([[    1, 13934, 27479, 15731, 25259,  1674, 26251, 18068, 20358,  1926,
         21344,  1926, 15632, 21344, 20359, 10652, 13934, 27479, 20479,  5549,
         21827,  2438, 23001, 12229, 17117, 20358,  4081,  8358,  7460, 20476,
         26161, 25335, 12628,   839,  6672,  1926, 21344, 12628,   839,  6672,
          1926,  8359, 20359, 13947,   838,  3704, 19830,  2690, 15630, 13795,
         14457, 26161, 21960, 19994,  2690, 11570, 13934, 27479,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 26161,  1903, 15110, 16388,  2367, 16626, 12668,  1353, 25062,
          2367, 12668, 22942, 24990, 14622, 25620, 19934, 23090,   210, 19070,
         16905, 16310,  1705,  2663,  2134, 12668, 10711,  1702, 22524, 13087,
           759, 25062, 11570, 25593,  1705,  2367,  9746,  9028, 22524,  2367,
          9746,   630, 26161, 18664,   241,  2530,  8740, 17975, 18304,  2367,
         12668,   630, 10448,  7854,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 20989,  9581, 21216, 14036, 12668, 24234,  4630, 14031,  8111,
          1616, 25581, 10389, 10609, 17239, 13865, 25435, 27338, 15179,  2821,
         21216, 14036,  5549, 21344, 20989,  2137,  1611,  9984, 27338, 15179,
           210,  8332, 14036, 21344, 20989,  2134,  1616, 27338,  8047, 10609,
          1661, 22007,  8111, 10389, 10609,  3115, 21216, 14036, 24509, 24344,
          1616,  9172, 25363, 16465, 25161,  8111, 21216, 25914,  3656, 13040,
         20989, 24433,  7492,  4624, 23888,  1616, 21490, 20989, 14600, 22435,
         24449,  8772,  8111, 22405,  9172,  1661, 12668,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 18960, 21697,  4586, 15233, 27091, 21869,  9266, 22571, 16465,
         26424,  7792,  1537, 12930, 14604, 17207,  9984, 11570, 12838, 26669,
         25313,  7719, 11392, 11630,  6600, 19994, 25593, 26421, 24693, 27091,
         12528, 20731, 18960,   265, 19867,  8123, 21864,  5388, 18960,  4586,
         21344, 17257,  6600, 17207,  6268,  9673, 12838,  6264, 26669, 24472,
         26161,  1089, 14200, 14881, 15875, 13604, 21344,  4586, 13175, 13604,
         26750, 22405, 16326,  8273,  8310,  2602, 14601, 26669, 11736, 20930,
         23919, 24797, 23893,  6264,  5038, 25593,  9266,  9984,  5038,  2134,
         12930,   290, 22571, 16465,  8458,  8309, 14881,  4750, 11392, 19003,
             0]], device='cuda:0')
tensor([[    1,  4285, 22942,  9587, 26070,  9587, 25649,  4285, 22528, 20721,
          4101,  2419,  3118, 11472, 22530,   631, 19952, 12225, 20090,  8928,
          4285, 22673,  2261,  4216,  4243,  4088,  7846, 22942,   759, 12223,
          4285, 24990, 27180, 17962,  7630, 14608,   579, 17083, 17810,  4820,
         16311,  7848, 14384, 16506,  2436,  4285, 16924, 17174, 19939, 24944,
         21344,  7727,  6090, 20985,  2797,   914,  4802,  4101, 18830, 10711,
         16066,  5657,  9266,  4285, 22528, 26183, 27032,  9587, 22942,  3517,
         10450,  4285, 16066, 26622, 21435,  8459, 21535,  4285, 16924, 17174,
          9588, 10450, 16924, 17171,  4285,  9266, 22942,  5612,  9587,  4745,
          7848, 17171, 25649,  4285, 25199, 21344, 16205, 20985, 24096, 21435,
         14413,   867, 25076,  4101, 18096,  2797,  4035, 11286, 21435, 20879,
         18423,  3118, 19999, 11471,  2436,  9074, 11481, 27483, 12223,  1903,
           546, 13657,  4285, 22630, 15580,  4285,  8459, 26965, 13934,  4285,
         22548,  4492, 20824, 15878, 27129,  1903,   546, 20332, 13657,  4285,
         22030,  5049, 16924, 17171,  4107, 23975,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  4172,   198,  1530,  3396,  4172,  2549,   198,  5731, 10174,
         26633,  3396, 18609, 19057,   305, 10061, 25923, 23446, 14082, 25154,
         19019, 15783, 27064, 21344, 18826, 24052,  5569, 17520, 27017, 11713,
         14101, 20882, 10736,  2092,  6627, 25098, 21344,  3158,  5330,  3118,
         18620,  9141,   241, 17812, 26818,    74,  7345, 23703, 21344, 23083,
          3630, 14000, 21344,  8693, 18620, 17231, 16207,  2549, 20340, 21344,
         14795, 23123, 13988, 23787, 15171, 21344,  6200, 26161, 24052,  5569,
         10298, 14101, 19265, 25593,  3123, 11268, 10736,  2092, 22450, 26424,
         11781, 20882, 12668, 21226, 13988,   759,  6554, 26161, 14101,  4624,
         17391, 10563,  4527, 26914,  6200, 24864, 13988,  1768, 16205,  3396,
         20270, 22877, 24703,  2102, 16644,  5460, 10033,  7270, 21344, 16207,
          2549, 14323,  8761,  3522, 20631, 22513, 26161,  7822, 12074, 16979,
         18056, 19882,  4538,  3396,   337, 14891,  4792,  1799, 25593,  6106,
         18950,  7822, 21344,  5144, 14795,  9004,  4457,  4172,  2827,   783,
         20154, 12274,  3690,  5272, 18815, 14874, 11781, 20882, 14000,  5580,
         26067, 14881, 22977,  5733,  4457,  7924,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  8917, 16186, 18267, 26513,  1128, 21854,  9265, 26752, 22055,
         15922, 18267, 26513, 23245, 16221,  8918, 22478,  3283, 16626, 23661,
          3465, 15922, 18267, 26512, 26170, 22311, 19727, 19628, 24534, 14052,
         26628, 18267, 22955, 19727,  3465, 26512,   446, 11392,  8047, 10966,
         21247, 24257, 22007, 18267, 17220, 24291,  6600, 26753,  8879, 20476,
         18270, 12367, 16626, 26275,  3465, 17316,  3465, 27318,  3545, 14308,
         15666, 13304, 21960,  1061, 26512,  9265, 19210,  4970, 19149, 15872,
         26818, 17316,  3465, 27380, 15399,  8437,  8321, 13792,  3281, 27338,
            58, 12366, 17171, 18267, 24938, 11736, 16626,  3465, 23661, 15872,
          5451, 23245, 26390, 22311, 19727,  2670, 24534, 26628, 18267, 19727,
          2670,  7760, 19727, 24635, 15623, 20930, 12367,  3465, 14633, 26179,
         16326, 10298, 14918, 19149, 18117,  7348, 10965, 16326, 15015, 12544,
         26179, 19262,   765, 22038, 24257, 18270,  4958, 10965,  2670, 26183,
          6677,  9227, 21854,  9260,  8749, 21847, 12919, 26752, 16626, 23661,
          3465, 21344, 26513,  5994, 18267,  2619, 16816,  2670,   258,  7386,
         18267,  2075,  1061, 26512,  9260, 22961, 21344, 23001,  4624,  3465,
         18745, 16588,  3008, 19153, 15687, 14023,  8437, 26275, 19149,  5658,
          8879, 22049, 26369,  3465, 13657,  8585, 17171, 12515, 14918, 22621,
         19149,  9626, 13939, 16894, 24257, 22007, 22887, 14263, 16780, 14219,
          7841, 14158, 17687, 21400, 21938, 22427,     0],
        [    1, 27389, 19233, 21804, 17492, 26927, 21216, 25914, 26717, 20639,
         16829, 11296, 21804,  9634, 21973,  2626, 21804, 27338, 23428,  3924,
         14036, 17047,  9480, 11259,  5862,  8984, 15044, 22571, 16465, 16178,
          1192, 15268, 16735, 26882,  3018, 27389, 19233, 25593, 16048, 18104,
          1708, 11570, 12668, 15203, 27389,  4003,  6090, 18306, 21344, 23769,
         27338,  8047, 19088, 18482,  1665,  4559,  5549,   290,  9001, 24062,
         23112, 12648, 27338, 20596, 12105, 11392, 12620, 21216, 18481,  5276,
         19783,  9660, 24947,  5885, 17221,  8253, 24129, 23210, 27338, 18877,
         24147, 12648,  5275, 25161, 11625,  3139, 27338,   759,  8123, 12250,
          8689, 16186, 22571, 16465, 25221,  8984,  2205,   759,  8156,  2387,
         26847,  5008, 23574, 10610, 12648,  9984, 10125, 19297, 12250, 22606,
          4876,  1561, 10610, 23112, 26445, 18306,  1255, 18439, 19452, 12668,
         21216,  2695, 16654, 16048,  9634, 18450,  7406, 12274,  5207, 10351,
         12601, 21804,   759,  6946, 18306,   290,  7615,  6106, 16924,  3875,
          1456, 14070, 20734,  3139,  8728, 12126, 10494, 10456, 18439, 17171,
         13265, 15572,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0') tensor([[[-2.2380, 22.4796, -0.3200,  ..., -1.4494,  0.5613,  0.7310],
         [-4.1854,  0.3931, -2.1721,  ..., -4.0683, -2.0345, -0.3713],
         [-5.6854, -4.1631, -2.8531,  ..., -5.0091, -2.9515, -0.3820],
         ...,
         [-3.0435, -1.8489, -2.1781,  ..., -2.8441, -1.7178, -1.0589],
         [-2.6317, -1.6202, -1.9456,  ..., -2.4090, -1.5090, -0.9587],
         [-1.9927, -1.2178, -1.5828,  ..., -1.7350, -1.2026, -0.7675]],

        [[-2.9190, 22.2015, -0.8505,  ..., -2.0369,  0.3364,  0.3834],
         [-4.6315, -4.9719, -1.9759,  ..., -3.7972, -2.0131, -1.2332],
         [-3.0966, -0.3269, -1.8443,  ..., -3.2603, -1.7562, -0.6167],
         ...,
         [-3.1550, -1.9087, -2.5188,  ..., -2.9814, -1.6623, -1.2850],
         [-2.7672, -1.6894, -2.3090,  ..., -2.5630, -1.4704, -1.1762],
         [-2.1225, -1.2749, -1.9533,  ..., -1.8772, -1.1437, -0.9794]],

        [[-2.3556, 22.2947, -0.5849,  ..., -1.6214,  0.6110,  0.6596],
         [-2.7912, -0.6059, -1.1701,  ..., -2.5017, -0.1596, -0.9409],
         [-2.1716, -0.9202, -1.0283,  ..., -1.5902, -0.6667,  0.2672],
         ...,
         [-1.0622,  0.3960,  0.1941,  ..., -1.5524, -0.4777,  0.4955],
         [-2.7552, -3.8644, -1.2448,  ..., -2.5650, -0.4624, -0.2164],
         [-2.3096, -1.1738, -1.9023,  ..., -2.2293, -1.0248, -0.9717]],

        [[-2.7774, 22.1319, -0.8935,  ..., -2.0923,  0.0779,  0.5529],
         [-4.6780, -1.7352, -1.2421,  ..., -3.9939, -2.7536,  0.1671],
         [-7.2006, -3.7493, -3.8006,  ..., -6.6262, -3.9224, -0.3449],
         ...,
         [-3.1434, -1.9559, -2.3570,  ..., -3.1214, -1.7289, -1.1609],
         [-2.8654, -1.7835, -2.1858,  ..., -2.8067, -1.5887, -1.0834],
         [-2.4083, -1.4570, -1.9267,  ..., -2.3169, -1.3588, -0.9324]]],
       device='cuda:0') tensor([[    1,  8459, 21535,  4285, 16924, 17174,  9588, 10450, 16924, 17171,
          4285,  9266, 22942,  5612,  9587,  4745,  7848, 17171, 25649,  4285,
         25199, 21344, 16205, 20985,  2436,  9074, 11481, 27483, 12223,  1903,
           546, 13657,  4285, 22630, 15580,  4285,  8459, 26965, 13934,  4285,
         22548,  4492, 20824, 15878, 27129,  2797,   914,  4802,  4101, 18830,
         10711, 16066,  5657,  9266,  4285, 22528, 26183, 27032,  9587, 22942,
          3517, 10450,  4285, 16066, 26622, 21435,  1903,   546, 20332, 13657,
          4285, 22030,  5049, 16924, 17171,  4107, 23975,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 21344,  6200, 26161, 24052,  5569, 10298, 14101, 19265, 25593,
          3123, 11268, 10736,  2092, 22450, 26424, 11781, 20882, 12668, 21226,
         13988, 21344,  8693, 18620, 17231,  7345, 23703, 21344, 23083,  3630,
         14000, 16207,  2549, 20340, 21344, 14795, 23123, 13988, 23787, 15171,
          2102, 16644,  5460, 10033,  7270, 21344, 16207,  2549, 14323,  8761,
          3522, 20631, 22513, 26161,  7822, 12074, 19019, 15783, 27064, 21344,
         18826, 24052,  5569, 17520, 27017, 11713, 14101, 20882, 10736,  2092,
          6627,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 16626, 23661,  3465, 15922, 18267, 26512, 26170, 22311, 19727,
         19628, 24534, 14052, 26628, 18267, 22955, 19727, 11736, 16626,  3465,
         23661, 15872,  5451, 23245, 26390, 22311, 19727,  2670, 24534, 26628,
         18267, 19727,  9227, 21854,  9260,  8749, 21847, 12919, 26752, 16626,
         23661,  3465, 21344, 26513,  5994, 18267,  3465, 26512,   446, 11392,
          8047, 10966, 21247, 24257, 22007, 18267, 17220, 24291,  6600, 26753,
          8879, 20476, 18270, 12367, 16626, 26275,  3465, 15872, 26818, 17316,
          3465, 27380, 15399,  8437,  8321, 13792,  3281, 27338,    58, 12366,
         17171, 18267, 24938,     0],
        [    1, 18439, 19452, 12668, 21216,  2695, 16654, 16048,  9634, 18450,
          7406, 12274,  5207, 10351, 12601, 21804,   759,  6946,  8253, 24129,
         23210, 27338, 18877, 24147, 12648,  5275, 25161, 11625,  3139, 27338,
           759,  8123, 12250,  8689,   290,  9001, 24062, 23112, 12648, 27338,
         20596, 12105, 11392, 12620, 21216, 18481,  5276, 19783,  9660, 24947,
          5885, 17221, 21804, 27338, 23428,  3924, 14036, 17047,  9480, 11259,
          5862,  8984, 15044, 22571, 16465, 16178,  1192, 15268,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 22548, 17902,  ...,  2924, 23340,     0],
        [    1, 16644,  5442,  ...,     0,     0,     0],
        [    1,  3510, 22036,  ...,     0,     0,     0],
        [    1, 19143, 23371,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.3960, 22.5126, -0.3920,  ..., -1.6162,  0.6425,  0.4081],
         [-7.1247, -1.8781, -3.0284,  ..., -6.6063, -2.7611, -2.0691],
         [-4.3294, -1.0653, -2.0381,  ..., -4.5290, -1.6372, -0.8927],
         ...,
         [-2.4996, -0.0405, -1.5087,  ..., -2.4763, -1.3245, -0.1118],
         [-1.5423, -1.9708, -0.7430,  ..., -1.8493, -0.2956,  0.9856],
         [-2.0309, -0.9847, -1.6245,  ..., -1.8426, -0.9333, -1.0451]],

        [[-2.1499, 22.2838, -0.3481,  ..., -1.3482,  0.6126,  0.5499],
         [-4.4221, -0.2890, -0.9208,  ..., -4.0402, -2.3669, -2.0289],
         [-5.2358, -2.8377, -3.1794,  ..., -5.3220, -2.7854, -2.0419],
         ...,
         [-1.4562, -1.5612, -0.9778,  ..., -1.3575, -0.8793, -0.6208],
         [-1.3817, -1.3215, -0.9443,  ..., -1.3031, -0.9394, -0.6779],
         [-1.3015, -0.9994, -0.9138,  ..., -1.2141, -0.8454, -0.5931]],

        [[-3.0515, 22.0292, -0.6986,  ..., -2.2663,  0.1872,  0.6955],
         [-5.2326, -1.2570, -1.8936,  ..., -4.9091, -2.0002, -2.6165],
         [-4.1683, -2.4557, -1.8491,  ..., -3.9913, -1.0263, -1.1523],
         ...,
         [-3.4825, -2.2918, -2.2354,  ..., -3.3389, -1.7791, -0.9582],
         [-3.3875, -2.0842, -2.1969,  ..., -3.2610, -1.8289, -1.0106],
         [-3.4136, -1.8422, -2.2340,  ..., -3.2871, -1.8049, -0.9629]],

        [[-2.7862, 22.2382, -0.5749,  ..., -1.9458,  0.3107,  0.3975],
         [-6.0297, -0.4470, -3.6435,  ..., -5.3087, -1.5170, -1.6679],
         [-4.1047, -2.1558, -1.8236,  ..., -3.8878, -2.2592, -1.0491],
         ...,
         [-2.1062, -1.3104, -1.4700,  ..., -1.8200, -1.2043, -0.8199],
         [-1.9960, -1.0656, -1.4138,  ..., -1.7204, -1.2470, -0.8441],
         [-2.0184, -0.8151, -1.4410,  ..., -1.7293, -1.1984, -0.7817]]],
       device='cuda:0') tensor([[    1, 17301, 27046,  5153, 18485, 21323, 27479,  2802, 27479, 17131,
         22548, 17902, 21827, 23990,  2924, 22340,  5323, 13934, 27479, 21525,
          3884,  9199, 19994,  8987, 20197, 23990,  2924, 17301, 25547, 19114,
         15824, 17525, 27479, 10885, 24938, 22340, 24840, 27483,   517, 12790,
         18091,  9266, 23990,  2924, 21982,  1531, 18094, 23097, 27380, 22942,
          9727, 22548, 17902, 15310, 27345,  8872, 14442, 15770,  4977,   839,
          9505, 23990,  2924,  1692, 13021, 12968, 23818,  5322,  9179,  4539,
         22340, 21146, 26368, 11368, 13263, 27479, 17131, 21423, 11368, 13263,
          2140, 22944, 15799, 22030, 10885, 24938,  9973,  9408, 22524, 20371,
          2530, 12962, 10887, 22340,  8872, 11631, 21827, 16743, 10042,  6878,
         13484, 20032, 24194, 25779,     0],
        [    1,   168,  9184, 24944,  4199, 17220, 17084, 18194,  4179, 21344,
         16644,  5442, 13534, 24977, 18982, 16221, 26426,  9984,  4842, 26426,
          9984,  2436,  3401, 17725, 19580, 16205,  4179, 21533, 16644,  5442,
         15425,  4845,  5315,  1617,  2455, 21254, 16292,  8741, 16177, 26426,
          9984, 15093, 19003, 24329, 20108, 11227, 12777,  6672,  4842, 26426,
          9984, 19307,   744, 19138,  9854, 23888, 19123, 22952, 18491, 15663,
         27406,  2929, 16740,  9973,  5823,  2822,  6392, 26426,  9984,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 13027, 16626, 13988, 12725, 19262,  4948, 26179, 22887, 13663,
         23287, 17171,  9572, 23287,  3517,   424,    55,  4686, 12408,  4948,
         26177, 26850, 24074, 23440,  5216, 19265, 23287,   241,  1947, 12545,
         22887, 24351,  5313,  1042,  4948, 22887,  3363,  4952,  4686, 27044,
         19727, 12408, 14887,  4948, 19157, 21837, 23283, 18056, 11570, 17953,
          5522,  8761, 11248,  9202,  3510, 23287,  5153,  4948,  8637, 17171,
          2438, 16920, 21854, 24839,  8772, 17949, 26179,  4766, 27479,  5885,

 56%|█████▋    | 63/112 [00:04<00:02, 18.48it/s, loss=1.65]

tensor([[[-3.8513, 21.5243, -1.3423,  ..., -2.9768, -0.2459,  0.1701],
         [-3.2228, -1.2068, -1.7843,  ..., -3.5933, -1.7167, -1.1094],
         [-5.1600, -5.4084, -1.9839,  ..., -4.1836, -2.3136, -1.2848],
         ...,
         [-3.9860, -2.0578, -1.9959,  ..., -3.3172, -1.8593, -0.8902],
         [-4.1179, -2.0120, -2.0135,  ..., -3.5058, -1.9859, -0.8669],
         [-4.1407, -2.1260, -2.0778,  ..., -3.6121, -2.0634, -0.8340]],

        [[-2.6560, 22.2724, -0.5053,  ..., -1.9694,  0.3691,  0.2916],
         [-4.1835, -1.7841, -2.3290,  ..., -4.5399, -1.7752, -0.2522],
         [-2.6837, -0.8289, -0.7732,  ..., -3.0222, -1.7347, -0.9849],
         ...,
         [-2.8905, -1.8933, -1.5322,  ..., -2.4537, -1.2008, -0.8217],
         [-3.0347, -1.8586, -1.5536,  ..., -2.6463, -1.3234, -0.7789],
         [-3.0964, -1.9633, -1.6142,  ..., -2.7630, -1.4098, -0.7562]],

        [[-2.1673, 22.2417, -0.4528,  ..., -1.5333,  0.4025,  0.5889],
         [-7.3683, -0.6520, -3.6113,  ..., -7.5335, -3.9436, -2.1524],
         [-0.4502, -1.3994,  0.2568,  ..., -0.5015, -0.0946,  0.8321],
         ...,
         [-1.3839, -0.4392, -0.7602,  ..., -0.9794, -0.3879, -0.2075],
         [-1.3818, -0.2577, -0.7253,  ..., -1.0253, -0.4464, -0.1306],
         [-1.2876, -0.2444, -0.7267,  ..., -0.9916, -0.4714, -0.0660]],

        [[-1.6284, 22.9614, -0.0388,  ..., -0.8780,  0.8978,  0.6288],
         [-3.3400, -1.0652, -1.0393,  ..., -4.2947, -1.9446, -0.9402],
         [-5.7785, -5.4292, -2.8797,  ..., -5.8189, -2.7731, -0.1338],
         ...,
         [-5.1584, -4.5985, -1.9828,  ..., -4.2175, -2.5504, -0.0747],
         [-6.1802, -2.2480, -2.2951,  ..., -5.7492, -2.7832, -1.2485],
         [-2.3597, -1.3857, -1.3495,  ..., -2.2669, -1.0788, -0.9161]]],
       device='cuda:0') tensor([[    1, 10085, 21344, 17282,  9639, 19512, 11395, 18104, 10721,   240,
          2695,  9639, 19512, 16735,  3402,  6373, 14070,  7311,  6774,  7623,
         10721, 21344, 16205, 12064, 13934, 27479, 10085,  2890, 26547, 25928,
         15568, 16493,  9572, 16493, 25928, 15213,  9184, 12334, 21845, 18311,
         21344, 23541, 21134,   913,  9862, 14953, 15225,  1443,   418, 22153,
         10085, 10085, 16588, 19143,  2690,  9172, 24840, 16050, 21365,  3545,
          2690,  2295, 10721, 12450,  8515, 10351,  7700, 21344, 10085,  4199,
          8552, 13076, 12064,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 14907,  5492, 19990,  5522, 27161,  7693, 10721,   168, 10512,
         23203, 16455, 18100, 21344,   542, 22105,  4199, 10512, 23203,  8614,
         23760,  5444,  7623,  7465, 12320, 23594,  8526, 12997, 19994, 11392,
         26876, 23308, 13898,  7699, 21344, 16221,  1028, 10721, 15268, 14604,
         12320, 12285, 11600, 13685, 23594, 15098, 19830, 19994, 11409, 24095,
          5492,  8511, 10084, 21344, 22105, 16857, 12777, 22528, 25159, 20578,
          7693, 14863,  5522, 21239,  8358,  7693,  5492,  6886, 11808, 15734,
          7219, 24723, 15268, 14596,  2690,  1830,  7623, 25158, 16654, 24840,
         16050,   168, 25158, 15783, 22951, 13762,  3502, 26654, 21344, 12055,
         17087,  3083, 26876, 11736, 15024,  8637, 12226, 27314,  1926, 18582,
         23566,  6765,  1436, 14836,  6886, 14323,  7693, 12081,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  5678, 27338, 21865, 23760,  9184, 21409, 14219, 10711, 14219,
          3679, 14401, 21344, 27519, 13127,  4043, 10515, 13697,  6672,  1926,
         17171,  3679,  9260, 14874,  5678, 14219,  3679,  5678, 10301, 14219,
         10711, 26876, 22441,  2690, 20520, 17610, 14219,  3679,  5678, 24836,
         17757, 10711, 14219, 10711, 18023,  8797, 20596,  6395, 14219, 10711,
         13664, 12081,  5216,  6392, 16456,  7700, 14403, 14219,  3679, 21344,
         13571, 27554,  8267, 23680,  7258, 12777, 25474, 14952, 14219, 10711,
         21344, 19303, 11286,  5674,  3679, 12920,  5522, 11836,  5444,  5672,
          5522, 23059, 22149, 13999, 14219, 10711, 21344, 17610, 20106,  9260,
         16626, 17579,   123, 25851,  3340,  5678, 23007, 13696, 25076,  5674,
          3679,  9260, 21344, 19452,  4845, 14403,  8487, 17757,  9260,  8797,
          1758,  1832,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 22153, 10193, 24892, 25639,  5477,  9673,  1235,  9019, 13030,
         16744, 23492, 22681,   525, 17929, 12850, 17289,  4226,  1950, 12850,
         23492,  4585, 21344,  6343, 22147, 21364, 26827, 15093,  5008,   298,
         27338, 19680, 23492, 19006, 17095, 17289,  5506, 26233, 20912,  7213,
         26882, 14951,  2821, 19003, 12850, 17289, 13498,  4915, 23492, 22153,
         23492,  9265,  7460, 27317,   853,  4976, 11395, 12850, 17289,  5506,
         11472, 19136, 10721,  1950, 23594,  4501, 16644,  6341,  6200, 12249,
         19003, 23492, 23492,   913, 18194,  9275,  6846, 22200,  2032,  5212,
         10711, 15547, 21344,  8708,  5926, 19003, 20925, 25721, 24669,   298,
         23492, 12341, 21874, 12249, 14836, 19077, 27483, 23492, 19006, 21100,
         10353, 13027,   747,  4226, 22147, 19003,  8829, 12444, 25390, 16644,
         25593, 27314,  2438, 12850, 17289, 24036, 16544,  5288, 16221, 11395,
         19006, 16644, 25390, 22147, 19003, 26833, 13030,  2438, 23492,  4845,
         16744, 23492, 14604, 27491,  4543, 20942, 13125, 11540,     0]],
       device='cuda:0')
tensor([[    1, 27572,  5038,  ...,     0,     0,     0],
        [    1, 21497, 15787,  ...,     0,     0,     0],
        [    1, 14231,  6436,  ..., 16205,  3193,     0],
        [    1, 20973, 22413,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.5793, 22.0387, -0.5029,  ..., -1.9411,  0.3899,  0.7340],
         [-6.1411, -1.2568, -1.9245,  ..., -6.0517, -1.9129, -0.5910],
         [-5.2087, -3.6949, -2.2354,  ..., -5.3472, -2.2206, -0.0595],
         ...,
         [-2.2486, -0.5451, -1.1414,  ..., -1.7067, -0.7259, -0.2256],
         [-2.4057, -0.5607, -1.2365,  ..., -1.8116, -0.7665, -0.1571],
         [-2.5139, -0.7498, -1.3940,  ..., -1.9689, -0.8545, -0.1237]],

        [[-2.4103, 22.3288, -0.4393,  ..., -1.4665,  0.3883,  0.4796],
         [-3.7201, -0.9534, -1.4639,  ..., -3.3660, -2.1639, -1.9256],
         [-4.8164,  0.2831, -2.1450,  ..., -3.9697, -2.9001, -1.6184],
         ...,
         [-3.2167, -1.2797, -1.5105,  ..., -2.3856, -1.3747, -0.7121],
         [-3.4660, -1.3510, -1.6509,  ..., -2.5746, -1.4714, -0.6728],
         [-3.6014, -1.5320, -1.8319,  ..., -2.7470, -1.5666, -0.6400]],

        [[-3.0314, 22.0911, -0.6708,  ..., -2.3360,  0.2525,  0.3240],
         [-2.5219, -2.3899, -1.9446,  ..., -2.9813, -1.4225, -0.7550],
         [-5.1533, -1.7311, -2.2621,  ..., -5.6010, -2.1337, -1.2515],
         ...,
         [-6.1993, -5.4844, -1.3769,  ..., -5.6972, -2.9729, -2.1990],
         [-4.9747, -5.0191, -3.1502,  ..., -5.0778, -2.0333, -0.3842],
         [-2.3008, -1.1731, -1.5831,  ..., -2.0080, -0.8403, -0.7724]],

        [[-2.1203, 22.4238, -0.3776,  ..., -1.4773,  0.5786,  0.7724],
         [-2.0657,  0.0302, -0.2088,  ..., -2.2399, -0.4494,  0.5251],
         [-7.9103, -4.0000, -3.4403,  ..., -6.7520, -4.0654, -0.8842],
         ...,
         [-2.2257, -0.8789, -1.3947,  ..., -1.7789, -0.8931, -0.3901],
         [-2.2799, -0.7951, -1.4555,  ..., -1.7796, -0.8962, -0.3096],
         [-2.3203, -0.9004, -1.5651,  ..., -1.8524, -0.9524, -0.2582]]],
       device='cuda:0') tensor([[    1, 26424,   978,   759, 15090,  9266,  6264, 27483, 27572, 14710,
         12273, 23335, 21490,  9973, 18481,  3444, 21344, 16859, 22311, 26424,
         11736,  3444, 26750, 22405,  4889, 18992, 24797, 23657, 27115,   978,
         13651, 27574, 21919,  9172, 23340, 27572, 22354,  6646, 27115,  9172,
         19924, 16735,  9543,  2032, 18483, 27572, 24523,  6846, 13361,  3444,
          5038,  3868,   539,  5480,  5862,  9172,   978, 21490, 14710,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 27248,  7994, 21497,  1198,  9543, 15787,  9266, 24938, 27479,
          9543, 15783, 19026, 21496,   607,  8814, 20471, 21533, 16650, 21344,
         15024, 21497, 27248,  9626,  8647, 18402,  8546,  7999, 27248, 19290,
         15536, 27479, 22119, 27248, 27299, 15787,  9543,   440,  9266, 24938,
          7745, 20120,  5658, 16626, 10130, 11408,  7741, 19130, 25245, 21497,
         27248,   229, 20879, 18724, 21497, 22870,  1197, 16644, 19580, 19026,
         21496, 21533,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 16205,  3466, 21344, 18048, 17934, 15064, 24482, 19782, 20256,
         18999, 14231,  6391, 19230, 21717, 16626,  6129,  3115,  7700, 23890,
          4384, 16205,  3193, 16205,  3466, 21344, 18056, 13657, 26986,  2244,
          4036,  5134,   867,  8637, 21344, 21226, 27338,  3159, 16205,  3193,
          7616,  2690, 11286, 13442,  5523, 24482, 20928, 16654, 27479, 16205,
          3466,   759,   198,  4036,  7505, 25147,  4242, 16205,  3193,  5049,
         22038,  1396,  1042,  5056, 12833,   461, 14231,  6391, 23203, 26477,
          3466, 21344, 19349, 13657,  2244, 16456,  1588, 17083, 13264, 19994,
          1401, 15785,  1527, 14231,  6391, 18450, 16626, 24482, 19780, 20822,
          7622, 27479, 20599, 18837,  3268, 20470, 16205,  3466,   759,  1527,
         13793, 25851,  4910, 24485, 19349, 25474, 10961,  7700, 20626, 10480,
          3193, 17211,  2808, 25707, 12533, 21530, 14231,  6436, 20601, 16205,
          3193, 23713, 12833, 16010,  3545, 20539,  9873,     0],
        [    1,  4158, 27138,  1274, 20973,  3159, 25593, 15609,  2781,  9503,
         14070, 22571, 26886,   290,  9027,  6759, 13934, 23967, 12461,  9503,
          4158, 18293, 15700,  1937, 11624, 20973,  5522, 20701, 18581, 15044,
         20973, 13498, 17795,  2669, 19449,  9634, 25434,  4386, 13636, 12557,
         22935, 27381,  9021,  2536, 15675,    12, 15980, 25221, 15609,  2169,
          8856, 22513, 13934, 27314,  5862, 13484, 21700, 17771, 25593, 16050,
          9027, 23657,  1708, 15980, 11472, 27076, 13528, 14096,  9503, 20973,
         16206, 21551, 12461, 24147, 18904, 27115,  2536, 16005,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1,  1526, 19203,  ...,  5909, 26868,     0],
        [    1, 22718, 11481,  ...,     0,     0,     0],
        [    1,  2750,  7407,  ...,     0,     0,     0],
        [    1,  1955, 16626,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6949, 22.3138, -0.6749,  ..., -1.8546,  0.3486,  0.3488],
         [-5.2739, -3.9931, -2.9404,  ..., -5.5976, -2.7993, -2.0412],
         [-4.6167, -4.1066, -1.9645,  ..., -4.2058, -3.0061, -0.9494],
         ...,
         [-6.6830, -3.7327, -2.5956,  ..., -6.6500, -3.5707, -0.7371],
         [-4.4578, -2.4592, -1.2076,  ..., -4.9574, -1.7396, -1.3927],
         [-2.8669, -2.1920, -1.9602,  ..., -2.7205, -1.4605, -1.0827]],

        [[-1.9911, 22.5270, -0.2002,  ..., -1.0340,  0.5670,  0.7683],
         [-2.1534, -1.5825,  0.5928,  ..., -2.7236, -1.4660,  0.9302],
         [-1.8653, -1.4991, -0.0415,  ..., -1.5389, -0.5663, -0.0829],
         ...,
         [-2.5960, -1.4335, -1.4547,  ..., -2.1654, -1.3337, -0.3912],
         [-2.8415, -1.7711, -1.4823,  ..., -2.4189, -1.5045, -0.4522],
         [-2.8734, -1.9650, -1.4477,  ..., -2.4364, -1.5688, -0.4300]],

        [[-2.2512, 22.6051, -0.3535,  ..., -1.5197,  0.5369,  0.6906],
         [-2.3419,  0.2389, -0.5789,  ..., -2.0524, -1.0153, -1.6654],
         [-2.9269, -1.5308, -1.1309,  ..., -3.0184, -1.6154,  0.2757],
         ...,
         [-2.0133, -1.0684, -1.3351,  ..., -1.9668, -0.8223, -0.8791],
         [-1.8229, -1.1863, -1.1365,  ..., -1.7728, -0.7749, -0.7797],
         [-1.7141, -1.3221, -1.0610,  ..., -1.6503, -0.7649, -0.7326]],

        [[-2.6763, 22.2416, -0.5351,  ..., -1.8151,  0.2976,  0.6982],
         [-3.4239, -3.0136, -2.1022,  ..., -3.0715, -2.1503,  0.2812],
         [-6.0289, -4.7158, -3.3432,  ..., -6.4306, -2.7235, -2.6185],
         ...,
         [-1.7016, -0.8746, -1.0264,  ..., -1.4105, -0.8286, -0.2578],
         [-1.8210, -1.1634, -0.9735,  ..., -1.5407, -0.9433, -0.2818],
         [-1.8255, -1.3485, -0.9430,  ..., -1.5439, -0.9958, -0.2672]]],
       device='cuda:0') tensor([[    1, 14070, 24840, 27299,   767,  7226,  3396,  4166,  3557, 14186,
         26850, 26179, 17449, 26161, 26526, 22558,  6071, 10050, 16590, 17896,
         25226, 22558, 22357,  2625, 20643,  1042,  6441, 22023,  1526, 17087,
          7822, 22558, 18949, 10174, 26633,  3396,  2625, 26531, 17524, 26179,
         21854, 19885, 22558,   759, 21874, 26183,  1040, 19322, 22024,  2032,
         26161,  2625,  2200,  7615, 16005, 17449, 26161, 25483, 26440, 22558,
         10494, 15590, 21533,  1632, 26440, 26850, 26179,  3572,   759, 20470,
          3201, 22558, 14957, 25226,  5522,   759, 10456, 26818,  8156, 22558,
         23475, 27299,  4546,  6106,  7822,  3557, 18611, 25483, 23624, 17524,
         26530, 26445, 22558, 24824,   362, 20601,  1526, 10176,  4734, 26867,
           839, 22901, 23450, 17524,    58, 21859, 22558, 26170, 26161, 15721,
         18703, 16588, 15024,  9626, 22558, 23566, 26441, 17524,  3204, 26390,
         22055,   767, 16588,   307,  5294, 16590,  9634, 16023, 23451, 26161,
         14951, 26440, 22558, 19088,  7615, 17047,  3517,  6441, 22023,  1526,
         16162, 22558,  2760,  6071, 24828, 17953,     0],
        [    1,  8984,  1042, 10456, 16048, 15021, 21844, 21344, 12906, 24111,
          4003, 16809, 17289, 17471, 19780, 10721, 22723, 17471, 18318, 12171,
         19003, 12251, 22313,  2171, 14177, 19084,   770, 12280, 14636, 13027,
          8774, 11268, 22357,  5272, 10721, 21844, 15021, 21845, 24112, 12906,
         20471, 10721, 12568, 24038, 14952, 12280,  9019,  8984,   328, 13027,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  3118,   261,  1077,  2346, 14891,  6163, 13606, 26763, 18577,
         15100, 10718, 25352, 16796, 12285, 23426,  1128,  2750,  9165,  6839,
          2750, 26381, 23829, 10213,  9157, 22030,  3118, 19686,  2346, 18489,
          1295, 10121,  6082,  8837, 14622, 21257,  2933, 13606,  2750, 25465,
         10447, 10351, 21535, 24427,   286,  7727, 12285,  9157, 13233, 25211,
         10762, 15024,  2750, 23426,  8743, 22030, 11561,   259, 19114,     9,
         13515,  9598, 26338, 20929, 22030,  1766, 12285, 16336,  3118,   259,
         25007, 23522, 13498, 21044, 13606, 22329, 22508, 11433,  8112,  8112,
         19036, 22316, 11710,   151, 26947,  1582, 11561,  2750,  2929, 17083,
          6649, 26986, 22935, 17846, 18234, 25352, 21535,   286,  3798, 13606,
           759, 12225,  3118,   260, 15645, 14934,  3732, 13892, 18638,   274,
         12174, 19567, 14606, 21535,  2346,  8437, 17081, 27290, 13606,  4898,
          9157,  8437, 22942,  4917,  8112,  1196, 19656,  6846, 18673, 26945,
          8047, 16311,  2764,  7417, 26170,  8397,   839,   260, 26441, 23515,
          6841, 21535,   286,     0,     0,     0,     0],
        [    1, 20842, 10086, 19714, 25593,  2543, 22049, 25387, 18874, 21827,
         23736, 14367, 14064, 17132, 18483, 26818, 24735, 10823, 15541, 25154,
         15199,  2602,  5323, 15999, 13941, 13333, 15129,  9021, 11392, 24314,
         13136,  5596, 16626, 27584,  4586, 10549, 11310, 21344, 19501, 18092,
          8626, 22405, 16924, 27529, 10823,  3545, 26919,  3353, 19940,  5775,
         18482, 27479, 18001, 12668, 21216,  2695, 23774,  9572, 19939, 26886,
         15143, 11532, 10494,  2543, 17186, 26818,  9127, 15799, 25481, 21260,
         11472,  1758, 15999, 13941,  9266, 27479, 14200, 18242,  8047, 23013,
         11296, 21804, 14478,  4316, 22902,  8397,  1955,  3323, 25481,  3085,
          5895,  6297,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 26258, 10424,  ...,     0,     0,     0],
        [    1,  3115,  2822,  ..., 26424,  6163,     0],
        [    1, 13210,  7289,  ...,     0,     0,     0],
        [    1, 15819, 22284,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.0772, 22.4427, -0.3788,  ..., -1.2542,  0.6294,  0.7405],
         [-3.8083, -0.7626, -0.8454,  ..., -3.6155, -1.3669, -0.2276],
         [-2.9356, -1.3740, -0.7554,  ..., -2.8245, -1.7766, -1.0808],
         ...,
         [-3.3806, -1.9989, -2.1761,  ..., -3.0081, -1.8096, -0.5697],
         [-3.3803, -2.2211, -2.1881,  ..., -3.0030, -1.7442, -0.6141],
         [-3.1856, -2.0760, -2.0620,  ..., -2.7952, -1.5608, -0.5415]],

        [[-1.5443, 22.8508, -0.0404,  ..., -0.7728,  0.9747,  0.7492],
         [-6.9061, -4.3137, -4.0874,  ..., -6.7601, -4.5952, -2.3744],
         [-2.5563, -2.6695, -0.2396,  ..., -2.6593, -0.7397,  0.3831],
         ...,

 58%|█████▊    | 65/112 [00:04<00:02, 16.72it/s, loss=0.973]

tensor([[    1, 16287,  6846, 24759, 26258, 10424,  5320,  9157, 23839, 19374,
         21127,  9157,  9072, 21854,  8971,  9072, 17211,  9746,  9157, 24718,
          7100,  5569, 15999, 25367, 14795, 19816,  6466, 25593, 26258, 10424,
          9165, 22354, 18447, 12226, 24751, 27314, 18901, 13934,  8979,  9072,
          6846, 21419,  6438, 10918, 21344,  9072, 20112, 10998,  1302, 26161,
         27199,  4323, 17171, 24840, 27308, 22354, 17795,  9727,  8694,  8441,
         25372, 13939,  9157, 14886, 14290,  6102,  7566,  9072,  2207, 26876,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 11564, 14096,  1492, 23411, 24509, 10077, 19619,  3744,  8614,
          1600,  9984,  9266, 24938, 27483,  3122,   209, 17154, 15668,  7066,
          7311, 13459, 11564,  9179,  9840, 18767, 23642,  7311, 10428, 25199,
         17154,  9984, 10010,   290, 17154, 20283,  5774, 27314, 12322, 24990,
         14317, 11564,  9179, 14444, 19186, 17154,  3287,  4554, 21904,  7317,
         19294, 25878, 17493, 20942, 15071, 16337, 27115,  9266, 10351, 24990,
         11564, 23430, 27479,  6879, 23818,  8833,  9172, 27314, 12322,  4032,
          8950, 19515, 11268,  8951, 26162, 27115,  3115,  9266, 20283, 15418,
         22513, 21831,   839, 13458, 27017, 24133, 23745, 27314, 24992,  8795,
          7473, 24680,  3115, 27406, 24509, 25062, 10428, 27201, 22024,  7577,
          4024, 10945, 25593, 27479,  1897,  8984, 24690, 18729, 23539, 24778,
          3115, 15516, 27406, 20283, 24509,   759,  2514, 24352, 22280, 10428,
         24823, 17903, 19619, 14542, 15038, 18515,  7391, 13479,  8431, 21277,
         15060, 17123, 25062, 24992, 11564, 11287,  8275, 10359, 10972, 24509,
         10077,  2438, 15418, 11622, 17903, 19619,  7460, 15038, 27406, 24509,
         10526, 13934, 10039, 10367,  3118, 15516, 17154, 23290, 18660, 23428,
          9984, 27479, 17131, 15038, 27314, 19994, 11537, 26935,  1492,  8441,
          8950,  8571, 19619,  7460, 15714, 24517, 21871, 24823,  1492, 27338,
          9266,  9984, 15516, 27338,  8793, 27115, 15418, 15645,  7641, 12315,
         25199,  9177, 13459, 22980,  4898, 24509, 10077,  1498, 15418, 11117,
          1492, 24092,  3173, 11315,     0],
        [    1, 13210, 21535, 12478,  5522, 14596, 17154, 15422,  5236, 21344,
         10061, 18092,  8119,  7473, 24247, 17155, 24247, 17155,  8054,  9634,
         27483,   517, 27314,  1061,  7289,   488,  4199,  6728, 18777, 21344,
         21226, 15268,  1154,   699,  4766, 12772,  7289,  4386, 15084, 13210,
         17205, 12668, 17154,  4813, 26418,  5236,   699, 25462, 25479, 20721,
         27314, 21859, 14101, 19098, 16182,  9612, 21344,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 25147,  9266, 21135, 15199, 10307,  4750, 21344, 10990, 15819,
         16522,  1551,   999, 12461, 21827,  9973, 13770, 19867,  8610,   999,
         25544, 21344, 15819, 18481, 10609, 15199, 24789, 15819, 22574, 23657,
         26424,  9482,  9266, 27394, 25161, 27115, 11866, 13934, 16048, 22026,
         26919, 21425, 15819,  5272, 20337, 20925, 26424, 26161, 17204,  4028,
         24163, 13770,  7495,  4032, 25503, 15819, 18489, 22475,  8893,  7864,
         13082, 13024, 16654,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 27277, 16286,  ...,     0,     0,     0],
        [    1, 18791, 18056,  ..., 25488,  6886,     0],
        [    1, 10190, 13157,  ...,     0,     0,     0],
        [    1, 13281, 25088,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7022, 22.1568, -0.6174,  ..., -2.0036,  0.3896,  0.6543],
         [-8.8469, -4.1008, -4.4363,  ..., -8.9013, -4.8200, -1.6258],
         [-7.8481, -5.8510, -2.9572,  ..., -7.9112, -3.9513, -1.8999],
         ...,
         [-2.2436, -1.0416, -1.5182,  ..., -2.0360, -0.8703, -0.5825],
         [-2.2100, -1.1421, -1.3974,  ..., -2.0385, -0.9023, -0.5901],
         [-2.2374, -1.3915, -1.2978,  ..., -2.0602, -0.9585, -0.5632]],

        [[-2.0952, 22.7434, -0.3115,  ..., -1.4824,  0.6596,  0.5824],
         [-3.9249, -4.4006, -1.6022,  ..., -3.2331, -1.6719, -1.2846],
         [-8.0834, -2.0430, -3.2196,  ..., -7.4519, -3.5875, -1.2866],
         ...,
         [-5.2306, -1.6116, -3.2316,  ..., -6.0453, -2.9777, -2.0316],
         [-3.9517, -1.8566, -2.5677,  ..., -4.7662, -1.4347, -1.8571],
         [-1.8463, -1.3492, -1.3536,  ..., -1.8404, -0.8608, -0.8137]],

        [[-2.3518, 22.2074, -0.6342,  ..., -1.7076,  0.3753,  0.7168],
         [-2.1579,  0.4827, -1.1591,  ..., -2.0575, -0.9314,  0.1948],
         [-5.3402, -2.9929, -2.3549,  ..., -4.7317, -2.4345, -0.5137],
         ...,
         [-2.7288, -1.4918, -1.6970,  ..., -2.4754, -1.2738, -0.5667],
         [-2.6722, -1.5495, -1.5753,  ..., -2.4444, -1.2811, -0.5766],
         [-2.7658, -1.7707, -1.5180,  ..., -2.5457, -1.3682, -0.5683]],

        [[-1.9263, 22.1103, -0.4095,  ..., -1.2886,  0.7772,  0.7723],
         [-5.3829, -2.5324, -2.0958,  ..., -4.7590, -3.4349, -1.2459],
         [-3.8094, -2.8780, -2.1590,  ..., -3.8474, -1.5138, -1.2313],
         ...,
         [-2.2157, -1.2107, -1.4411,  ..., -2.0418, -0.8634, -0.3612],
         [-2.2004, -1.3443, -1.3395,  ..., -2.0521, -0.8998, -0.3793],
         [-2.4033, -1.6792, -1.3412,  ..., -2.2533, -1.0434, -0.4228]]],
       device='cuda:0') tensor([[    1, 20754, 19230, 21966, 10765,  5523, 21842, 16286, 21344, 18739,
         20069, 27338, 26893,  3694, 13264, 14023, 12190, 22311, 21962, 10765,
         19970, 16521, 23056, 26417, 27206, 25310, 10426,  5569, 18739,   732,
         14310, 21965, 10776, 18501,  4585, 17221, 21344,  6846, 19349, 19246,
         13464, 14750, 19477, 22563, 22082, 21344, 19033,  6917, 21965, 17074,
          7615, 10776, 18501, 22030, 17777,  1181, 20064, 15779, 24650, 20153,
         18496, 10776, 15265, 20068, 27338, 17171, 22574, 16616,  8508,  9293,
         27483, 21344, 24938, 14586, 27277, 14586,  4199, 13326, 21344, 17171,
         24797, 20068, 27338,  8723,  4345,  8501, 18056, 10061,  5703,  8437,
          6631, 16626, 10764, 20065, 21965, 10776, 18501, 12249,  4038,  5351,
         10776,  3107,  4418, 19098,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 21344, 10397, 14881, 18056,  3951, 24534,   867, 16626, 19123,
         22344,  6775, 15425, 11755,  2436, 26099, 11743,  6775,  8172,  3951,
          6775, 20769,  9453, 14194, 18056, 24592, 22147, 23638,   168,  3720,
          9234,  4199, 24534, 10232, 11365, 17614,  6775, 20769,  6412, 24534,
          8627, 14888, 18739, 25025,  6346, 16208,  9234, 17171, 22055, 13502,
         23082,   759, 12224, 15663,  4199,  2448, 10045, 22030, 14874, 24534,
          4842, 24789, 18056, 24532,  9923, 16654, 16050, 13155,  9265, 11743,
         21344, 23123,  5216,  7841, 22340,  8156,  6775, 18289, 27316,  9849,
          5334, 15425, 11756,  6577,  8038, 18056, 17298, 17171,  2929, 20769,
           783, 10303, 18791, 18056, 17795, 10303, 18056,  5313,  9730,  5248,
         12040, 26426, 16310, 16208,  9234, 24364,   759, 25167, 26818, 24534,
          6577,  9452, 14296,  8913, 18150, 22935, 21876, 13498, 18056, 26713,
          6577,  5229, 11716,  6775, 15425, 18837, 19996, 25564, 22357, 18320,
         26430, 16310, 14951, 17171, 18423,  6775,  3549,  7510, 10395, 21364,
         26161, 23967,  2032, 11743, 15938,     0],
        [    1, 12034,  2032,  9141,   759, 23931, 16626, 16588, 13159,  5658,
         16048, 24352, 16924, 18056,  7994, 15731, 26183, 12671,   127, 15616,
         12668, 13793, 17296, 10193, 15731, 18056, 27290, 13027,   328, 21805,
          4049, 17471, 25841, 19780, 15731, 18056, 18075, 18588, 18999, 16048,
         15731, 10192, 27290,  8984, 16626,  9141, 22340,  9139, 15731, 18056,
         27299,   482, 18678, 11396, 13157, 19780,  8396,  2438,  7700, 22513,
         22854, 17087, 25841,  9139,  9483,  4044, 15616, 19450, 13157, 19780,
         13027,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,   259, 10182, 13281, 23411, 17352, 16789,  9157,  4271,  2136,
         10182,  6465,  2169,  9673,  2367, 17635,   259, 13281, 14795,  8400,
         13934, 27479,   168, 24299,  7406,  9673, 14021,  9130, 16650, 21490,
          4867, 24990,  2367,  9157,  9024, 16793, 14551,  8097,  9673,  3979,
          9157,  1705,  6600, 23425,  9293,  9165,  6465, 14795,  8400, 19457,
         24797, 18423,  4101, 10420, 23411, 13062, 20410,  9673, 21827,  2367,
         17635,   259,  7622,  8400,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')

 62%|██████▏   | 69/112 [00:05<00:03, 13.79it/s, loss=0.835]

tensor([[    1,  4108, 22030,  ...,     0,     0,     0],
        [    1, 22523, 10721,  ...,     0,     0,     0],
        [    1, 20165, 10711,  ...,     0,     0,     0],
        [    1, 16368, 19456,  ..., 11536, 22018,     0]], device='cuda:0') tensor([[[-2.5384e+00,  2.2041e+01, -4.3378e-01,  ..., -1.7654e+00,
           2.7926e-01,  6.0991e-01],
         [-6.8660e+00, -4.2696e+00, -3.1800e+00,  ..., -6.4431e+00,
          -4.0862e+00, -2.0090e+00],
         [-6.7577e+00, -2.2305e+00, -1.9171e+00,  ..., -6.0215e+00,
          -3.2672e+00, -2.1761e+00],
         ...,
         [-2.0056e+00,  5.2507e-02, -1.0184e+00,  ..., -1.7799e+00,
          -1.3179e+00, -1.7623e-01],
         [-1.8769e+00, -2.1062e-02, -9.5195e-01,  ..., -1.6000e+00,
          -1.2177e+00, -1.1914e-01],
         [-1.8103e+00, -1.2966e-01, -9.4511e-01,  ..., -1.5105e+00,
          -1.1581e+00, -7.4529e-02]],

        [[-2.3502e+00,  2.2306e+01, -4.2018e-01,  ..., -1.4555e+00,
           3.4908e-01,  7.3158e-01],
         [-3.3493e+00,  1.8254e-01, -1.8694e+00,  ..., -3.4722e+00,
          -1.7161e+00, -2.4180e-01],
         [-5.4157e+00, -2.0161e+00, -2.2612e+00,  ..., -4.4486e+00,
          -2.3795e+00, -2.2749e+00],
         ...,
         [-2.7912e+00, -7.0289e-01, -1.3698e+00,  ..., -2.4992e+00,
          -1.5722e+00, -4.1234e-01],
         [-2.6464e+00, -7.8248e-01, -1.2974e+00,  ..., -2.3048e+00,
          -1.4693e+00, -3.7965e-01],
         [-2.6172e+00, -8.9174e-01, -1.3063e+00,  ..., -2.2371e+00,
          -1.4311e+00, -3.6690e-01]],

        [[-3.1220e+00,  2.1924e+01, -7.9508e-01,  ..., -2.3804e+00,
           1.8188e-01,  4.8299e-01],
         [-2.6882e+00, -1.6658e+00, -1.4950e+00,  ..., -2.8857e+00,
          -9.3339e-01, -1.5297e+00],
         [-3.7851e+00,  1.5258e+00, -2.0204e+00,  ..., -3.4075e+00,
          -1.6555e+00, -2.0048e+00],
         ...,
         [-1.9152e+00,  2.2282e-01, -1.1772e+00,  ..., -1.6945e+00,
          -1.0309e+00, -1.9008e-01],
         [-1.8824e+00,  1.0749e-01, -1.1613e+00,  ..., -1.6134e+00,
          -9.8116e-01, -1.7046e-01],
         [-1.9166e+00, -6.5471e-02, -1.1929e+00,  ..., -1.6351e+00,
          -9.6294e-01, -1.6637e-01]],

        [[-2.9318e+00,  2.2245e+01, -7.2868e-01,  ..., -2.0730e+00,
           4.0587e-01,  3.5536e-01],
         [-7.0576e+00, -4.9888e+00, -2.0610e+00,  ..., -7.3011e+00,
          -3.5806e+00, -2.3548e+00],
         [-4.5093e+00, -3.5865e+00, -2.1022e+00,  ..., -4.8724e+00,
          -1.7320e+00, -7.9767e-01],
         ...,
         [-4.0282e+00, -1.5008e+00, -2.2277e+00,  ..., -4.7120e+00,
          -1.6304e+00, -8.1892e-01],
         [-5.8026e+00, -3.7485e+00, -3.3692e+00,  ..., -5.7398e+00,
          -2.3797e+00, -1.3383e+00],
         [-7.5581e-01,  7.2857e-02, -9.5192e-01,  ..., -6.8021e-01,
          -2.1307e-01, -6.8460e-01]]], device='cuda:0') tensor([[    1,  9327,  4667,  ...,     0,     0,     0],
        [    1, 11736, 22721,  ...,     0,     0,     0],
        [    1, 26919,  7822,  ...,     0,     0,     0],
        [    1, 16368, 19456,  ...,  3018, 18581,     0]], device='cuda:0')
tensor([[    1,  3401,  5036,  ...,     0,     0,     0],
        [    1, 26161, 25211,  ...,     0,     0,     0],
        [    1, 27314, 14027,  ...,  8879,  1101,     0],
        [    1, 15635, 21157,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.0957, 21.7830, -0.7932,  ..., -2.4072,  0.2020,  0.4282],
         [-6.4924, -2.8526, -3.6049,  ..., -6.0345, -2.6095, -1.0124],
         [-4.8196, -4.5893, -1.1495,  ..., -3.9076, -2.5709, -1.3299],
         ...,
         [-4.4107, -2.6871, -2.3761,  ..., -4.3660, -2.4019, -0.9648],
         [-4.3814, -2.3954, -2.3709,  ..., -4.3288, -2.3876, -0.8882],
         [-4.1772, -2.0654, -2.3124,  ..., -4.1069, -2.2611, -0.8515]],

        [[-3.2533, 21.7784, -0.8963,  ..., -2.4338,  0.1418,  0.3382],
         [-6.5087, -0.3848, -3.6236,  ..., -6.1258, -2.8639, -2.0842],
         [-9.2330, -4.2518, -4.6795,  ..., -8.6152, -4.6013, -3.0029],
         ...,
         [-3.9857, -2.5340, -2.2048,  ..., -3.7592, -2.1598, -0.8766],
         [-3.9345, -2.2467, -2.1764,  ..., -3.6977, -2.1220, -0.8141],
         [-3.5435, -1.8052, -2.0297,  ..., -3.2825, -1.9182, -0.7504]],

        [[-2.2156, 22.6423, -0.1714,  ..., -1.3453,  0.6164,  0.5869],
         [-4.5964, -1.9595, -2.6892,  ..., -4.0796, -1.6978, -0.4213],
         [-3.6967,  1.7064, -1.5586,  ..., -3.0941, -1.4468, -0.9159],
         ...,
         [-5.5300, -4.1063, -3.1071,  ..., -5.6472, -2.1872, -1.3777],
         [-7.8587, -1.9817, -2.9020,  ..., -7.7879, -2.9174, -1.6357],
         [-2.3527, -1.6018, -1.7274,  ..., -2.4131, -1.1965, -1.0652]],

        [[-3.3043, 21.8633, -0.8833,  ..., -2.4879,  0.0988,  0.2976],
         [-6.0379, -3.8377, -3.3878,  ..., -6.2026, -2.9394, -2.3294],
         [-5.2669, -5.3118, -1.9685,  ..., -4.4528, -2.1867, -1.3968],
         ...,
         [-4.0476, -2.3254, -2.2638,  ..., -3.9746, -2.1689, -1.0097],
         [-3.9549, -1.9675, -2.2346,  ..., -3.8649, -2.1139, -0.9322],
         [-3.8196, -1.6550, -2.2205,  ..., -3.7075, -2.0149, -0.9151]]],
       device='cuda:0') tensor([[    1,  3401,  5036,   867, 13031, 15020, 26829,  9266, 24938, 22513,
         15044, 19513, 24401, 24111,  9626,  7700, 17909, 25947,  8829,  7700,
         15783, 21344,  1926, 13030,  6182, 24111,  1852,  2436, 15020, 21533,
          3401,  5008,  2387, 15797, 21533, 27326, 21982,  5036,   867, 16796,
         15020, 25719,  9172, 19512,  9533,  7458, 17171, 18581, 15044, 24111,
          9001,  2514, 22721, 27479, 10721, 15268,  2514, 10156, 22567, 20012,
          5271, 21344,  7700, 15783, 11267, 24347,  6182,  5036, 14200, 21874,
         21982,  1926, 13030, 21344,  4842, 20471,  8610, 12765, 27479, 15044,
         18999, 27479,  8614, 12249, 21982, 24401,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1,  4793,  6469, 21344, 25211,  6297, 13934, 27479, 18999, 19994,
         12051,  2690, 10000, 26161,  8683, 12132, 11472, 24938, 11392,  2690,
         13943,  9141, 22340, 11736, 16049,  2046, 26161, 25211, 10000, 16434,
          6182,  2690, 26161,  5216,  1135, 24788, 17117, 12128,  3755,  8437,
         27129,  4151, 19830, 19994, 14203, 13934, 27479,  9141, 14323, 23059,
          9757,  5732, 18949,  3396,  7693, 18609, 26161,  8683, 21100, 25393,
         12132, 21100,  8437,  8918, 16626, 19994, 25393,  8501,  2244,  4226,
          5882, 18611, 26161, 15020,  4381, 25808, 27540, 16221, 10301,  4226,
         19754,  8603,  7700, 25851,   392, 26161,  4881,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1,  3401, 18620, 14027,  1302, 10354,  1324, 24230, 16159, 20578,
          6094,  1028, 27314,  7693,  9610, 16221, 15425,  9452, 18620, 14027,
          4766,  6094, 14070,   489, 27479,  9610, 21873, 13799, 17472, 24756,
          3008,  4366, 18709,   642, 11678, 20942, 27314, 22862,  9610, 24939,
         21239, 17743, 26889, 20941,  8441,  6094, 16205, 10045,  4845, 22887,
         10232, 15663,   759, 11630, 26170,  6094, 22310,  6278, 17204, 23001,
         22887, 14317, 14388, 24834, 15663, 16502, 16032,  4948,  6586, 11736,
         15024, 12922,  6946, 18709,   642,  6094, 24368, 18588, 26919, 25639,
         19019, 15783, 25061,  2549, 23007,   469, 18949, 24719, 15288,   867,
         10512, 14027, 11180, 23440, 14027,  1549, 15448,  6094,  8872, 23566,
         11041,  1758, 24369, 27471,  1202, 16205, 18085,  3545,  4538, 17962,
          6129, 15663,  9630,  2448, 10045, 27314, 20828, 14948, 20187,  6094,
          9452,  3561, 10456,  3861, 24823,  3401, 12651, 27037,    80,  7803,
         26161, 10512, 15268, 23566, 14881,  4985, 10203, 10995, 27479,   517,
         26403, 18949,  6728,  4166, 14795, 24092,  1129,  6094,  6094,  6248,
          9807, 16205, 10045, 21344, 25483,  1307, 15448,  3007, 18949, 14688,
          5955, 22468,   757,  7252,  2457,  7219,  9131,   553, 14897, 16205,
         10045,  3514, 27314, 14027, 24040, 10351, 26212,  3557, 19262,  4216,
          6671,  5548,  7639, 18990,  6952,  6094, 10351, 19084, 22927, 16605,
         16616,  8879,  1101,     0],
        [    1, 17725, 21344,  4227, 17089, 12876, 21157,  6904, 24369, 22135,
          1656, 12341,  5442, 17047,   168,  9823, 20196,  1024, 21157,  6200,
         24364, 19358,  6129, 12616, 23119,  8153, 15393, 21157,  9905, 19232,
          6129, 21874,  5780, 21326,  9905, 21157, 14552, 18451, 26945, 15678,
           168, 16999, 13159, 25122, 27295,  5522, 14604,  6129, 10422,   539,
         17725, 21344,  4227, 17089,  2244,  5916, 20510, 13442, 15635, 21157,
          5506, 14367, 20735, 20643, 11630,  1183,  6129, 15268,  8917, 25201,
          6875, 17725, 21344,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 27552, 11169,  ...,     0,     0,     0],
        [    1, 14604,  7282,  ...,     0,     0,     0],
        [    1, 27552, 17577,  ...,  9024, 12780,     0],
        [    1,  2303, 12922,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6867e+00,  2.2214e+01, -5.4280e-01,  ..., -1.9567e+00,
           3.9340e-01,  6.6484e-01],
         [-5.8029e+00, -9.0972e-01, -1.6703e+00,  ..., -5.2708e+00,
          -1.9991e+00,  3.0040e-01],
         [-4.9779e+00,  4.1502e-02, -1.0067e+00,  ..., -5.0629e+00,
          -1.7645e+00, -4.4301e-01],
         ...,
         [-2.5713e+00, -1.1566e+00, -1.8961e+00,  ..., -2.2927e+00,
          -1.2032e+00, -5.3046e-01],
         [-2.4847e+00, -1.2232e+00, -1.8310e+00,  ..., -2.2242e+00,
          -1.2319e+00, -5.9921e-01],
         [-2.3889e+00, -1.3623e+00, -1.7126e+00,  ..., -2.1095e+00,
          -1.1900e+00, -6.0714e-01]],

        [[-1.3447e+00,  2.2807e+01,  8.3518e-04,  ..., -7.0764e-01,
           8.7740e-01,  7.9513e-01],
         [-3.0384e+00, -1.0264e-01, -1.6778e+00,  ..., -2.6704e+00,
          -2.0140e+00, -3.7480e-02],
         [-3.0803e+00, -5.2673e-01, -9.9241e-01,  ..., -3.3671e+00,
          -8.0994e-01,  5.4337e-01],
         ...,
         [-2.4944e+00, -1.6295e+00, -1.6362e+00,  ..., -2.1654e+00,
          -1.3139e+00, -4.3923e-01],
         [-2.1982e+00, -1.5709e+00, -1.4610e+00,  ..., -1.8920e+00,
          -1.2385e+00, -4.3065e-01],
         [-2.1583e+00, -1.6934e+00, -1.3612e+00,  ..., -1.8288e+00,
          -1.2022e+00, -4.5599e-01]],

        [[-2.3492e+00,  2.2612e+01, -4.2263e-01,  ..., -1.6095e+00,
           5.4103e-01,  4.3468e-01],
         [-5.1107e+00, -3.1556e+00, -2.7434e+00,  ..., -4.3601e+00,
          -1.3984e+00, -8.1178e-01],
         [-3.9170e+00, -4.6270e+00, -1.5701e+00,  ..., -3.1734e+00,
          -1.7662e+00, -1.3884e+00],
         ...,
         [-7.2137e+00, -4.6725e+00, -3.4548e+00,  ..., -7.4144e+00,
          -3.9024e+00, -2.4040e+00],
         [-6.4321e+00, -3.9474e+00, -3.4460e+00,  ..., -6.0132e+00,
          -3.1539e+00, -1.8686e+00],
         [-1.7821e+00, -1.0754e+00, -1.5769e+00,  ..., -1.5946e+00,
          -8.9616e-01, -1.0045e+00]],

        [[-3.0346e+00,  2.2079e+01, -7.2418e-01,  ..., -2.2276e+00,
           2.2753e-01,  7.0592e-01],
         [-9.6008e+00, -4.4261e+00, -3.8421e+00,  ..., -8.6206e+00,
          -4.6079e+00, -1.2568e+00],
         [-7.3411e+00, -2.9609e+00, -3.4001e+00,  ..., -6.5757e+00,
          -3.0139e+00, -3.9486e-01],
         ...,
         [-4.1876e+00, -2.0849e+00, -2.5916e+00,  ..., -3.8335e+00,
          -2.0344e+00, -4.9322e-01],
         [-4.0215e+00, -2.1025e+00, -2.4993e+00,  ..., -3.6818e+00,
          -2.0239e+00, -5.3646e-01],
         [-3.8904e+00, -2.2154e+00, -2.3478e+00,  ..., -3.4948e+00,
          -1.9232e+00, -5.2434e-01]]], device='cuda:0') tensor([[    1, 21269, 17117, 10035,  4845, 27552,  7510, 26161,  5569, 24884,
          5273,  9131, 24117,  6660,  1926,   759,   417, 10075,  3517, 26161,
          5569, 17556,  6200, 19297, 27552,  1936, 19265, 21269, 18949, 26552,
         19453,  5549, 14101,  1637, 20446, 21344, 26161, 13319, 27552, 14101,
         27351, 27552, 14001, 21530,  1576, 26493, 26161,  1936, 13988, 27552,
         22742, 26421, 11736,  3309,  4038,  5569, 27552,  9145,  1936, 26161,
         11631, 26170, 12668,  3401, 13988, 10904,  9523, 21364, 13498, 17117,
         19119, 25920, 27545,   914, 17257, 27552,  4038,  5569, 10190, 14143,
         17171, 22571,  1937,  2002, 19303,  9188, 10075, 21269, 23440, 17576,
          4845,  8615, 27115,  1576, 27545,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1, 13657,  9408, 23440, 25932, 18104, 24938,   243, 16819,   290,
          9157, 22357,  7282,  9801,  6745,   483, 18485, 17795, 27529, 14948,
         20256,  9408, 23440, 25932, 16099, 21874, 19573,  4696,   340, 20139,
         16099, 16875, 27076, 14296,   198,  8687, 22503, 22063,   241, 15640,
          4977, 11466,  9408,  6925, 27479, 17131,  4518,  4452,  5915, 13134,
         16099,  1132, 19197,  9157, 25932,  4750, 17761, 23440, 25932, 14564,
           539,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1, 15520, 21344, 26251, 27552, 22151, 10447,  2690, 26509, 16859,
         22513, 20643, 21269, 10512,   244, 22153,  8830, 10711, 15520, 10237,
          2032, 11539,  4845,  5319, 27552, 21535, 12008, 21269, 10512,  1258,
         21914, 27546, 25920,  9844, 16387, 27552, 17571,  2690,  1758, 24485,
         27483, 17194, 14876, 17577,  7928, 21269, 17117,  9260, 27552, 23911,
         21269, 10512,  2690, 21268, 22448,  4103, 16616, 19785,  8637, 21530,
          5522, 14881,  6765, 15520, 18955,  3785, 16205, 13520,  5885,  8772,
          9704, 24482,  8435,  4081, 17171,  9631, 15520, 13726, 13934, 27479,
         21890, 22899, 27552, 14857, 19119,  1278, 27544, 23440, 21239, 17117,
         10711, 21108,  2690, 17095, 15179,  1758, 24482,  2448, 26750, 21269,
         10512,  5274,  1531, 27552, 18158, 22150, 26750,  3432, 27546, 27338,
          8761, 14298, 14433, 21344, 24935, 17349,  6846, 10711, 15520,   168,
         15520, 10512,   246,  5293,  8086,  4103, 25341,  6577, 20190,  6868,
          8086, 12778,     0],
        [    1,  2303, 20597, 23200, 23542, 21344,  9905,  2387, 24789, 27115,
          4030, 14036,  2303, 11631, 27115,  9266, 25435, 22513,  1324, 14451,
         26234, 18475,  4158,  3711,  5862, 23975,  3683, 10195, 25025,  2102,
         14451, 25947, 27115, 25435, 27479, 14451, 14953, 19640,  2303, 17279,
          3656, 23542, 10195, 18475,  4030, 14036,   818, 18729,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]], device='cuda:0')

 65%|██████▌   | 73/112 [00:05<00:02, 14.85it/s, loss=0.86]

tensor([[    1,  8406, 10614,  ...,     0,     0,     0],
        [    1,   241,  6638,  ...,     0,     0,     0],
        [    1,  9997,  7234,  ...,     0,     0,     0],
        [    1,  9913,  1787,  ..., 18423, 13295,     0]], device='cuda:0') tensor([[[-1.8400, 22.3144, -0.1312,  ..., -0.9331,  0.6701,  0.8688],
         [-5.1203, -1.2461, -2.5836,  ..., -4.1052, -2.0437, -1.0276],
         [-5.8367, -3.5506, -2.5241,  ..., -5.5895, -3.0164, -1.1846],
         ...,
         [-3.1169, -1.6231, -1.2754,  ..., -2.3215, -1.5024, -0.2041],
         [-3.2510, -1.9811, -1.4146,  ..., -2.4441, -1.6072, -0.1681],
         [-3.6976, -2.3979, -1.6938,  ..., -2.9282, -1.8506, -0.2668]],

        [[-2.8262, 21.9766, -0.6658,  ..., -2.1612,  0.2017,  0.6325],
         [-3.7655,  2.1109, -1.7485,  ..., -3.6562, -1.3315,  0.0750],
         [-5.6399, -4.8150, -2.4551,  ..., -6.0846, -2.6360, -1.1469],
         ...,
         [-2.8298, -1.6954, -1.6153,  ..., -2.4321, -1.4159, -0.3100],
         [-3.0721, -2.1095, -1.7827,  ..., -2.6526, -1.5771, -0.3056],
         [-3.4893, -2.4748, -2.0434,  ..., -3.0886, -1.7857, -0.3913]],

        [[-2.3382, 22.3847, -0.3752,  ..., -1.5247,  0.5574,  0.5018],
         [-3.0229,  0.4756, -1.6565,  ..., -3.2525, -1.0372, -0.3573],
         [-5.7742, -2.4470, -2.9480,  ..., -5.8516, -3.0424, -2.3031],
         ...,
         [-2.8217, -1.6195, -1.5631,  ..., -2.2794, -1.2363, -0.6919],
         [-3.0799, -2.0043, -1.7561,  ..., -2.4979, -1.4051, -0.7000],
         [-3.6166, -2.4773, -2.0982,  ..., -3.0609, -1.6845, -0.8306]],

        [[-2.2891, 22.7450, -0.3949,  ..., -1.5583,  0.6555,  0.4433],
         [-1.4043, -1.0065, -1.3815,  ..., -1.8057, -0.8573, -0.2856],
         [-6.6601, -5.6530, -2.8954,  ..., -6.0300, -3.5009, -0.8272],
         ...,
         [-2.9704, -1.8552, -1.3398,  ..., -3.2849, -1.1294, -1.6021],
         [-3.0894, -4.0282, -1.1552,  ..., -2.2274, -1.2320, -0.7937],
         [-2.6980, -1.5147, -1.9321,  ..., -2.3695, -1.1661, -0.9224]]],
       device='cuda:0') tensor([[    1, 23426,  8406, 22942,  5255, 22340, 27479, 11471,  4867,  3904,
          5255,  1014, 24718,  1014, 23090, 11268,  6447, 13941, 27479,  6037,
          3140,  5445,  3545, 11932, 24938,  5255, 24718,  1028,  5255, 11268,
         13549, 25643, 15268, 25644, 22524, 21265, 13934, 27479,  8872, 26604,
         26185, 18303, 24938,  2367,  8406, 22942, 22340,  6447, 17047,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 10512, 16326,   241, 19550, 13988, 14587, 21230,  6638,  9543,
         24670, 24131, 27201, 25364, 25939, 15151, 20989, 21344, 10512,   123,
         21230, 20062, 12226, 18739,  5996, 12318,  5522,  4381, 10512,  7803,
         24431, 20568, 12117, 13266, 13988, 14587, 13988, 14587,   218, 21044,
         10512, 21530,  7036, 26170,   875,  8552,  6638,  6943,  1154,  3118,
          4362, 21344, 16207, 20989, 21344, 13988, 14587, 21230, 14367, 12668,
         14101, 17230, 18826,  6202,  7790, 17171, 14876, 13988, 14587, 21344,
         21229, 12233,  8397,  5330, 11781, 20882,   731,  6639, 26818,  6939,
         10703, 16462, 12073, 23463, 27338, 25445, 10512,   123, 13266, 27290,
         27199, 21344, 16207, 20989, 26750, 13799,   244,  3118, 10512,  5522,
         14023,   244, 14101,  1245,  8397,  5569, 11781, 20882, 23676,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 11736, 22952, 18491, 25076, 21912,  2690, 23147,  9984, 26172,
          3429, 24992,  5167,  7839,  1358, 27314,  2438,  9984, 19361,  9984,
         25076, 26426,  9984,  5168,  4952, 19294, 18673,  8447,  9973, 22899,
         15731,  5394,  9266, 16735,  6106, 21364,  7901, 16857, 21365, 27411,
          9984, 21100, 27479, 26255, 27499, 20286,  9141, 22340, 15024,  5394,
          9973, 22899, 26818,   770, 20287, 16894, 23241, 23645, 10801,  9997,
          9973,  2134, 23760,  4876, 27479,  8047, 22899, 15731,  5394,  8976,
         14795,  8919, 21914, 26426,  9973, 24938, 25639,   759, 20001, 22030,
         16924,  9984,   209,  7311, 18470, 23463, 21914,  5394, 27479, 16626,
         10130,  5168, 20287, 15093,  5272,  3334, 12341, 15243, 12253,  7119,
         19727,  9984, 19830, 16626,  1583,  3143, 18482,  2030,   240,   493,
         10116, 21344,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 16205,  3193, 21344, 27150, 24040,  8458,  6102, 21344, 19151,
           525,  7400,  6623, 24938,  9913, 23968, 13295,  9913,  9181, 15785,
          1768, 18450, 27374,  6161, 27314, 18662,  5548, 16205,  3193, 21344,
          9913, 15785,   525,  6290,  6159, 12648, 17936, 20440,  5548,   442,
         25488,  8047, 16205,  3193, 21344, 14874,  3028, 12668, 17297, 17077,
         16259,  6159, 20301, 26293,  3301, 16010, 17571, 18662,  5548, 25639,
          4036, 10480,  3193, 21344, 14542, 15448, 27314, 22049, 20828, 16465,
         27338, 20346,  6159, 20301, 23968,  5522,  2205,  9172, 23340, 19098,
          6161, 17571, 18662,  5548,  3294, 27483,  6161, 22496, 25974, 19854,
         27314,  9179, 24346,  3688, 21344, 26161, 21535,  3607, 24040, 16205,
          3193, 12668,  9181,  8771,  2821,   546,  6671,  5548,  9913, 15785,
          3517,  9370, 12668,  8526, 19782, 21344,  8522, 26577, 27338, 12093,
          7693, 10721, 26161, 25335, 21835, 13175, 24493, 21344, 26161,  5522,
         24040, 11979, 14116, 19098, 25639, 18450, 12668,  9181,  8771, 11286,
          6129,  6159,  6671, 27314,   525, 21344, 16221, 16010, 18510, 26161,
         27499,  7016,  2102,  5461, 21344, 15448, 19113, 16179, 25173, 25639,
           818, 16221, 27290, 16522,  2102,  5460, 17886,  2025, 21344,   527,
         19033, 17297, 12797, 14564, 27338, 27290, 18813, 26161,  4899,  4812,
         18786, 20068, 19303,  9188, 21344,     0]], device='cuda:0')
tensor([[    1, 12845,  7551,  5522,  2619, 14948, 26189,  2428, 12847, 13249,
         15370, 13175, 14831, 23358, 14958, 25923, 20472, 20255,  9573, 17077,
          4559, 23975, 24944, 23975, 24570, 21530, 17240,  9573, 24348,  2428,
         26161, 25596, 14904, 10326, 16205, 10326, 10494, 18117, 14564,  4559,
           179, 13934, 26882, 12845,  2456, 16205, 15370, 16205, 14831, 21344,
          2244,  2428, 25809,  4559, 19251, 16205, 14831, 16205, 15370, 11536,
         23358,  5824,  8694, 12777, 26315, 18791,  2619,  2428, 16205, 10326,
          9184,  1770, 12226, 13249, 16082, 26161, 12777,  1926, 21344,  1758,
          2428, 25944, 19937,  1778, 17578, 14070,  4559, 22153, 11736, 16221,
         23119, 12845,  7551, 22496, 24789, 19003, 17078, 17597, 22147, 11392,
          8141, 16205, 10326, 23370, 18900, 14036,  9505,  4559, 22513, 16205,
         14831, 16205, 15370, 12919, 23443, 13939,  9765, 21533, 20329, 14551,
         24650, 12780, 14948, 26189, 23975, 24570, 21535,  2695, 14958, 25923,
           759,  5153, 14952,  3435, 17597, 10395,   539,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  3510, 22036,  9202, 23287, 14887,  4948, 19157, 21837, 23283,
         18056, 11570, 17953,  5522,  8761, 11248,  9202,  3510, 13027, 16626,
         13988, 12725, 19262,  4948, 26179, 22887, 13663, 23287, 14115,  1186,
         10515,  1299, 21653,  6577, 21324, 18056, 10852, 11286, 19262, 18149,
         12408, 23287,  5153,  4948,  8637, 17171,  2438, 16920, 21854, 24839,
          8772, 17949, 26179,  4766, 27479, 22887,  3363,  4952,  4686, 27044,
         19727, 12408, 27331,    55, 11411, 18149,  6071, 14317, 17856, 14526,
          6623,  5674,  3679, 16927, 19157, 22959,  4044,  9755,  2169, 12137,
          8273, 17171,  9572, 23287,  3517,   424,    55,  4686, 12408,  4948,
         26177, 26850, 24074, 20643, 18056,  2760, 18664,   377, 11013,  4538,
         26774,  5084,  6152,  9634,  1061, 23287,  2459,  3510, 23515,   539,
         23440,  5216, 19265, 23287,   241,  1947, 12545, 22887, 24351,  5313,
          1042,  4948,   759, 20513,  4842, 26868,  6901, 26986, 24294, 12544,
         23287,  5218,    58, 21865,  5996, 24789,  8830, 26413, 12734, 22887,
         16626, 13988, 15103,  5274, 25352,  3510, 25173, 25149, 19056, 20882,
         19939, 24111,  7631, 26864,  9626, 17953, 12377, 24102, 22887,  1674,
         17171, 11011, 21973, 23287, 19157,  5885, 26179, 26716, 19265, 23287,
         25547,  9724, 19157, 23284,   268,  1706,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 23492,  9260,  5915, 13159, 15896, 23492, 17171, 27314, 13919,
         23492, 19115,  5522,  5915, 13159, 16654,  9293, 27483,  4199,  8552,
         21344, 16592,  2032,  4845,  7510,  4897,  2690,   230, 26161,  9260,
         12889, 16654, 16048, 14891, 17171, 13919, 10351,  9265, 13574, 11736,
         13841, 15896, 25025, 12780,  4746,  4845, 22190, 24828, 13159, 12285,
          2847, 14827, 21530, 13155, 14602, 27338,  8829, 16205, 15896, 25025,
         26161, 12780,   230, 12668, 23492, 10711,  4898,  4845, 27338,   557,
         20064, 27295,  1030,  5522, 21859, 27295, 25398, 23337, 12776, 15950,
          7996, 10395, 16205, 15896, 25025,  5025,  4194, 15896, 23492,  9580,
         13934, 27479, 16205, 15896, 14477, 11540, 15564,  7566,  9260, 12913,
          4744, 15896, 23492, 12889, 27338,  1028, 21365,  2690, 19119,  3630,
         15731, 25057, 15896, 23492, 23201, 21344,  6201, 13155,  5921, 14795,
         27499, 25483,  5657, 24146, 23492, 12341, 26713, 12765, 16626, 24534,
         23203, 21344, 15896, 23492, 17224,  5548, 15024,  3402, 17808,  7646,
          8396, 19000, 23440, 17576, 11765, 27296,  8001, 23337, 13422,   747,
         13916, 17224, 21060,  5951, 20495, 23007,   468, 25923, 23446,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 27552, 23913,  9634,  9265,  2690, 21269, 17117,  9260, 27552,
         23911,  9634,  4842, 21044, 13934, 27479,  9523, 23440,  1576, 13498,
         17117, 19119, 25920, 27545, 27552,  4385,  2690,  5996, 27544, 22899,
          6182, 22040,  1758, 24485,  9634,  4842, 16388, 13988, 23943, 10035,
         10232, 10075, 25920, 10076, 12777,  4845,  1831, 23440, 17117,  9260,
         21108, 27552, 23842, 23943, 11725,  9145,  1936, 26919, 23941,  5996,
         27552,  1401, 26161,  5569, 21932, 24482,  7038, 21269, 10512, 12668,
          1211,   759, 23842, 20427, 18439, 17795,  4065,  1936,  9150,  4422,
         27552, 13726,  3545, 11162, 13934, 27479, 27552, 11472,  2448,  2690,
          1758, 24485, 25969,  9202, 22040,  2448, 21268,  9523, 27552, 21909,
         27545, 27552,  3517, 21364, 12008, 25547,  5580, 26161,  7769, 20147,
          5313, 17117, 19119,  3401,   759, 26613, 26170, 14101, 15398,  7030,
         10395,  9260, 25387,  3429, 24344,  5313,  1444,  7612, 16048, 23911,
         21269, 10512,  2690,   914, 19533, 26986, 26161,  5569, 13319, 21269,
          4842, 16109, 17089,  6997, 27552, 14101, 27350, 15396, 11725,  1936,
         13264, 14189,  4419, 23428, 25593,  6102, 11199,  8984, 11197,  1260,
         26986, 26161,  5569, 19216,  9610,  3785, 24833, 14101,   244, 27552,
          1936,  9150, 11725,  7759, 13934, 27479,  1576, 11736,  4974, 27338,
          3857,  5569,  2076, 10075, 10076, 27194,  1576, 27545, 22899, 14437,
         13663, 12777,  9260,  1831,  9181, 10711,  6106, 13941,  1831, 10061,
          5313,  4845, 23440, 21239, 17117, 10711, 21108,  2690, 21108, 15401,
           525, 15563, 10075,  3107, 13916,  4305, 21268, 19138, 17117,  3401,
          1758, 23440,  5313, 27552,  4386, 20882, 22150, 11995, 19397, 18620,
           818,  9630, 15702, 13520, 16205, 13520, 21268, 20828, 14948, 19051,
          4080,  9704, 24482,  8435, 20446,  6443,  1832,     0]],
       device='cuda:0') tensor([[[-2.7459, 21.8984, -0.5390,  ..., -1.9986,  0.1012,  0.6571],
         [-7.3931, -2.0831, -2.0416,  ..., -7.2004, -3.3757, -2.6339],
         [-1.3990,  0.8138, -0.3636,  ..., -1.6126, -0.9614,  0.5339],
         ...,
         [-3.3017, -2.1693, -1.7029,  ..., -2.9907, -1.9399, -0.4178],
         [-3.1403, -1.9117, -1.6163,  ..., -2.8554, -1.9633, -0.4462],
         [-3.0578, -1.5974, -1.5990,  ..., -2.7610, -1.8713, -0.3571]],

        [[-3.0515, 22.0292, -0.6986,  ..., -2.2663,  0.1872,  0.6955],
         [-5.2326, -1.2570, -1.8936,  ..., -4.9091, -2.0002, -2.6165],
         [-4.1683, -2.4557, -1.8491,  ..., -3.9913, -1.0263, -1.1523],
         ...,
         [-3.4825, -2.2918, -2.2354,  ..., -3.3389, -1.7791, -0.9582],
         [-3.3875, -2.0842, -2.1969,  ..., -3.2610, -1.8289, -1.0106],
         [-3.4136, -1.8422, -2.2340,  ..., -3.2871, -1.8049, -0.9629]],

        [[-2.3916, 22.1212, -0.3709,  ..., -1.6050,  0.5967,  0.6340],
         [-2.4203, -0.5015, -1.1059,  ..., -1.2945, -0.2133, -0.2365],
         [-6.8807, -3.3857, -4.0718,  ..., -7.5196, -3.1553, -1.4541],
         ...,
         [-2.5319, -1.8070, -1.5912,  ..., -2.2905, -1.4203, -0.7029],
         [-2.3891, -1.5734, -1.5226,  ..., -2.1580, -1.4423, -0.7408],
         [-2.3196, -1.2744, -1.5007,  ..., -2.0752, -1.3493, -0.6615]],

        [[-2.3112, 22.4950, -0.2426,  ..., -1.4585,  0.6111,  0.5947],
         [-6.1018, -1.5686, -1.6774,  ..., -5.5499, -2.2546, -0.0472],
         [-5.0895, -0.1882, -1.0554,  ..., -5.1043, -1.8506, -0.5448],
         ...,
         [-4.2812, -2.0197, -3.0652,  ..., -3.9330, -2.5224, -1.4064],
         [-5.3729, -6.1584, -1.7267,  ..., -5.3370, -2.9267, -1.4431],
         [-1.6590, -0.8655, -1.2816,  ..., -1.4641, -0.8800, -0.8382]]],
       device='cuda:0') tensor([[    1, 12845,  2456, 16205, 15370, 16205, 14831, 21344,  2244,  2428,
         25809,  4559, 19251, 16205, 14831, 16205, 15370, 11536, 23358,  5824,
          8694, 12777, 26315, 18791,  2619,  2428, 16205, 14831, 16205, 15370,
         12919, 23443, 13939,  9765, 21533, 20329, 14551, 24650, 12780, 14948,
         26189, 16205, 10326, 23370, 18900, 14036,  9505,  4559, 22513,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 13027, 16626, 13988, 12725, 19262,  4948, 26179, 22887, 13663,
         23287, 17171,  9572, 23287,  3517,   424,    55,  4686, 12408,  4948,
         26177, 26850, 24074, 23440,  5216, 19265, 23287,   241,  1947, 12545,
         22887, 24351,  5313,  1042,  4948, 22887,  3363,  4952,  4686, 27044,
         19727, 12408, 14887,  4948, 19157, 21837, 23283, 18056, 11570, 17953,
          5522,  8761, 11248,  9202,  3510, 23287,  5153,  4948,  8637, 17171,
          2438, 16920, 21854, 24839,  8772, 17949, 26179,  4766, 27479,  5885,
         26179, 26716, 19265, 23287, 25547,  9724, 19157, 23284,   268,  1706,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 15896, 23492, 17171, 27314, 13919, 23492, 19115,  5522,  5915,
         13159, 16654,  9293, 27483,  4199,  8552, 21344, 15896, 23492, 17224,
          5548, 16205, 15896, 25025, 26161, 12780,   230, 12668, 23492, 10711,
          4898,  4845, 27338,   557, 20064, 27295,  1030, 15896, 23492, 23201,
         21344,  6201, 13155,  5921, 14795, 27499, 15896, 23492,  9580, 13934,
         27479, 16205, 15896, 14477, 11540, 15564,  7566,  9260, 12913, 11736,
         13841, 15896, 25025, 12780,  4746,  4845, 22190, 24828, 13159,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,

 69%|██████▉   | 77/112 [00:05<00:02, 15.77it/s, loss=1.41]

tensor([[    1,  3474,  6751,  6129, 18296, 22693,   546, 14795, 23013,   469,
          3474, 22030,  6668, 25639,  9260, 18296, 25905,   977,  7566,  9494,
         10232, 25905, 11286, 18230,  9260,  6667, 22799,  5232, 11611,  8716,
         18296, 22153, 13299, 16644,   914, 21533, 21365, 27479, 18739, 18451,
         14267, 18296, 26172, 24828, 27483, 21433,  3397, 13356,  6562, 23471,
         11814, 23789, 20472, 22354, 18451,  5868,  1135, 12560, 20067,  3529,
         12598, 14317, 15024,  8589, 19123, 18296, 19933, 12443,  8995, 25905,
         18767, 25122, 26919,  9905, 21175, 19118, 21365,  6129, 19119, 11611,
          3474, 18296, 16940, 23007,   468,   759, 20925,  7790, 15731, 18456,
         18768, 11808, 15734, 21344, 18296,  4199,  8552, 20823,  7147,  9260,
         12444, 11623, 15093, 22693,  7469, 11611, 18223, 20525,  4671,  3545,
          8047,   914, 21344, 25905,  5522, 13963, 16626, 19123,  6129, 10422,
         14551, 26818, 20627, 15093,  8816, 18296, 18381, 18223,  8591, 21344,
           913,  8292, 20126, 16795,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 20903,  9237, 11472,  4585, 27376,  6749, 15573, 13555,  4585,
         27376,  5549, 11472, 20903,  9237,  6745,  5076, 11203,  8798,   483,
         23430, 22524, 22945, 10426, 16310, 14952, 14566,  5549, 23411, 10976,
         27091, 13252, 27387, 20903,  9237, 13304,  3766,  3789,  9905, 27064,
         13176,  3789, 26935, 21683, 18673, 11472, 25199, 13555, 11203, 24081,
           759,  6705, 14701,  3586,  6143,  1570, 25339, 25765,  3586,  9266,
         21904, 18041, 25076, 11472,  6139, 14941, 17171,  9266, 22944, 27387,
          1356, 27243, 16159, 22899, 15731,  5394, 19996,  4440, 13578, 27387,
         20903,  9237, 13304,  3766,  3789, 26011, 14622, 13176, 13941, 15121,
          9266, 19996, 27530, 22552,   996,  3766, 13176, 26935, 14881, 23888,
         13304,  3766,  3789, 19000, 21344, 26129, 11839, 13555, 24366, 22942,
         27201,  5676,  2245,  5675, 13934, 27479, 13555, 25547,  1705,  6816,
         26974,  8616, 11604, 10976, 27091, 13252, 12560, 24092, 19953, 14298,
           210,  1702, 12668,  8172,  3433,  1458,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  9973, 26753, 16326,  4460, 26500, 26426,  9984,  3753, 13918,
         26753, 17761, 25794,  4216, 18485, 25211, 12341, 21835, 21344, 17884,
         11363,  8615,  3514, 13988,  1941, 21364, 19781,  9984,  4216,  8091,
          2387,  9984, 12341, 15448, 23975,  4974, 15024,  4216, 18485,  9984,
           558,   385, 12223, 11392, 14203, 26499, 17761,  8615, 23143, 15734,
         26426,  9984,  4285, 18940, 26500,  9984, 11472,  5323,  9973, 14978,
          2555, 17761, 27479, 17131, 23500, 17654, 23320,  6143, 14128,  8984,
         16117, 10295, 21344, 22940, 13559, 26761, 14079, 12988, 14290, 21982,
         15748,  2215,  9973, 18606, 12771, 23500, 16286,  6997, 12395, 14978,
         17795, 14101,  3785,   539, 23975, 15448, 14542, 16208, 11363, 21344,
         19290, 25639, 26398,  9984, 12341,  4974, 15024,  4216, 18485,  9984,
         22899,   385, 21035,  2308, 11162,  9987, 12341,  2720,  7901, 21344,
          1941, 26500,  9984, 27338, 27381, 21344, 26713, 10395, 21148, 21874,
         10512, 24045, 12341, 10512, 11539, 15448,  9765, 12341, 20658, 20482,
         26919,  3118,  2695,  9157,  4432,  6945, 13788, 14795,  4460, 16208,
         11363, 21344,   385, 25337,   385,  4216,  4216, 12126, 20660, 20585,
          4433, 21909,  9984, 11392, 14203, 26499, 15796,  8253, 17761, 16521,
         13657, 15687,  3434,  4216, 26426,  9984,  6759,  9165, 26430, 17761,
         10719, 18485,  9984, 26818,  4216, 16521, 14564,  3694, 12166,  5248,
         26753, 23708, 21365,  8092,  3514,  1768,  5848, 15425, 23221, 21835,
         24679, 13241, 21344, 14186,  4207, 26786, 24703,  3999, 15173, 14186,
         10395, 23742,  4559, 14186, 18475, 19781,  9973, 19033,   385, 14881,
         12411,  4242,  4216,   783, 16521, 19263,  1088,  5350, 21914, 19781,
          9973,  4207, 12988, 22571, 16050,  9199, 21019,  9984, 14887, 14978,
         21344, 17857, 15098,  9984, 20607, 24435,   409,   385,     0],
        [    1,  1930, 14599, 22070,  4381,  9581,  8552, 14542, 17086, 15577,
         14726, 14604, 22063,  6941,  3785, 26161, 12777,  1926,  8000, 25370,
          6997, 23520, 26469,   699, 22073,  6941, 25844, 17929, 27479, 17131,
          4381, 25851,  6996, 20646, 21306,  1600, 17797, 26424, 14323,  3625,
          4866, 24967,  9649,  1401,  8708,  5996,  1437, 16626, 27479,   244,
          2438,  4381, 11198,  8000, 25370, 25639, 26441, 22935, 24680,  3785,
         25370,  6193, 16208, 26469, 25852,  6997, 20371, 21943, 18741,  8186,
         26654, 21859, 23945,   767, 18724,  5522,  9626, 17296, 16208, 26469,
          9581, 11162, 15577, 19057,  4490,  3401,  8396, 14795,  6200, 26986,
          1124, 23203, 14001,  6554,  6200,  6879, 18582,  5732, 15577, 19092,
         27199, 14151, 13266, 25370, 26105, 16208, 26469,  4381, 26414,  3970,
         23100, 12922, 12226,  3314,  7599, 14855,  5104,  5282, 21344,  9626,
          8469, 13811,  5848,  1926, 21344, 23428,  3785, 18092, 10116, 15577,
         21344, 23443, 16208, 26469, 20371, 18147, 19191, 18724, 20456,  1042,
         27245, 15577, 14726,  6239,  5660, 25462, 15571,  8458,  7995, 17239,
           386,  2032, 22606, 11013, 27290,  2032, 14542,  9184,  7100, 16208,
         26469, 27292, 15577, 10351, 19057,  4490,  3401,  8396, 12776,  9873,
         15577, 12126,  5910,  7998, 25025,  9905, 27483,  4845, 14795, 20072,
         15577, 14726,  6443, 16208, 26469,  4386, 21344, 20371, 18741,  8707,
         14602,  9260, 23919,  5264,  9260, 25025, 25370, 16208, 26469,  7137,
         14600, 26882, 15577, 21344, 16208, 26469, 13801, 14028, 22606, 25544,
          1302, 25920,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0') tensor([[[-1.9214e+00,  2.2441e+01, -3.7779e-01,  ..., -1.1223e+00,
           6.0794e-01,  8.4118e-01],
         [-3.3126e+00,  2.1397e+00, -2.2041e+00,  ..., -2.2027e+00,
          -2.1915e+00,  4.2469e-01],
         [-2.9857e+00, -2.6894e+00, -8.6407e-01,  ..., -3.1119e+00,
          -4.6022e-01, -5.9480e-01],
         ...,
         [-1.4396e+00, -7.6016e-01, -1.1239e+00,  ..., -1.0556e+00,
          -5.9536e-01, -2.2266e-01],
         [-1.4527e+00, -8.4080e-01, -1.1537e+00,  ..., -1.0880e+00,
          -5.8225e-01, -2.9649e-01],
         [-1.4721e+00, -7.9837e-01, -1.1362e+00,  ..., -1.0817e+00,
          -5.9097e-01, -3.4214e-01]],

        [[-2.3224e+00,  2.2144e+01, -3.1723e-01,  ..., -1.4176e+00,
           5.9133e-01,  5.8424e-01],
         [-5.5747e+00, -6.7734e-01, -2.7760e+00,  ..., -5.4507e+00,
          -2.8199e+00, -1.8085e+00],
         [-5.9110e+00, -4.2852e+00, -2.1569e+00,  ..., -6.0692e+00,
          -2.8074e+00, -1.6687e+00],
         ...,
         [-1.7831e+00, -5.9146e-01, -7.6781e-01,  ..., -1.2734e+00,
          -7.1861e-01, -1.0239e-01],
         [-1.8449e+00, -7.0745e-01, -8.2818e-01,  ..., -1.3699e+00,
          -7.2865e-01, -1.7899e-01],
         [-1.9701e+00, -7.1301e-01, -8.6985e-01,  ..., -1.4713e+00,
          -7.7900e-01, -2.5585e-01]],

        [[-2.1029e+00,  2.2666e+01, -3.0225e-01,  ..., -1.2504e+00,
           8.0845e-01,  4.3802e-01],
         [-6.4557e+00, -1.5188e+00, -2.4988e+00,  ..., -5.7933e+00,
          -3.5499e+00, -1.5809e+00],
         [-1.3350e+00, -4.7400e-03, -1.7615e+00,  ..., -2.1286e+00,
          -8.5415e-01, -4.5635e-01],
         ...,
         [-2.3281e+00, -9.4820e-01, -4.2697e-01,  ..., -2.0601e+00,
          -7.5308e-01, -6.5116e-01],
         [-2.1168e+00, -7.2464e-01, -2.3050e-01,  ..., -1.8554e+00,
          -6.5783e-01, -5.8806e-01],
         [-1.6420e+00, -1.1469e+00, -1.3832e+00,  ..., -1.5261e+00,
          -5.1723e-01, -1.0584e+00]],

        [[-3.0146e+00,  2.1986e+01, -9.7663e-01,  ..., -2.4014e+00,
           8.0812e-02,  1.5745e-01],
         [-4.2630e+00, -2.2222e-01, -2.1096e+00,  ..., -3.5221e+00,
          -1.7555e+00, -8.3522e-01],
         [-1.1599e+00, -3.9246e-01, -4.1789e-01,  ..., -1.4668e+00,
          -3.9123e-01,  6.2185e-01],
         ...,
         [-1.5300e+00, -8.7250e-01, -1.4832e+00,  ..., -1.3858e+00,
          -7.2375e-01, -6.5664e-01],
         [-1.6731e+00, -1.0715e+00, -1.5746e+00,  ..., -1.5908e+00,
          -7.7896e-01, -7.8056e-01],
         [-1.7893e+00, -1.1164e+00, -1.6047e+00,  ..., -1.6875e+00,
          -8.3813e-01, -8.7622e-01]]], device='cuda:0') tensor([[    1, 22693,   546, 14795, 23013,   469,  3474, 22030,  6668, 25639,
          9260, 18296, 25905,  6129, 19119, 11611,  3474, 18296, 16940, 23007,
           468,   759, 20925,  7790, 15731, 18456, 18768, 11808, 15734, 21344,
         18296,  4199,  8552, 20823,  7147, 18296, 19933, 12443,  8995, 25905,
         18767, 25122, 26919,  9905, 21175, 19118, 21365,  9260, 12444, 11623,
         15093, 22693,  7469, 11611, 18223,   977,  7566,  9494, 10232, 25905,
         11286, 18230,  9260,  6667, 22799,  5232, 11611,  8716,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 27387, 20903,  9237, 13304,  3766,  3789, 26011, 14622, 13176,
         13941, 15121, 27387, 20903,  9237, 13304,  3766,  3789,  9905, 27064,
         13176,  3789, 26935, 21683, 18673, 11472, 25199,  9266, 19996, 27530,
         22552,   996,  3766, 13176, 26935, 14881, 23888, 13555, 11203, 24081,
           759,  6705, 14701,  3586,  9266, 21904, 18041, 25076, 11472,  6139,
         14941,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1,   539, 23975, 15448, 14542, 16208, 11363, 21344, 19290, 25639,
         26398,  9984, 12341,  4974, 15024,  4216, 18485,  9984, 22899,   385,
         26500, 26426,  9984,  3753, 13918, 26753, 17761, 25794,  4216, 18485,
         25211, 12341, 21835, 21344, 17884, 11363,  8615,  3514, 13988,  1941,
         21364, 19781,  9984,  4216,  8091,  2387,  9984, 12341, 15448, 23975,
         26426,  9984,  6759,  9165, 26430, 17761, 10719, 18485,  9984, 26818,
          4216, 26500,  9984, 11472,  5323,  9973, 14978,  2555, 17761, 27479,
         17131, 23500, 17654, 23320,  6143, 14128,  8984,  4974, 15024,  4216,
         18485,  9984,   558,   385, 12223, 11392, 14203, 26499, 14186, 18475,
         19781,  9973, 21035,  2308, 11162,  9987, 12341,  2720,  7901, 21344,
          1941, 26500,  9984, 27338, 27381,  1088,  5350, 21914, 19781,  9973,
          4207, 12988, 22571, 16050,  9199, 16208, 11363, 21344,   385, 25337,
           385,  4216,  4216,     0],
        [    1, 15577, 14726,  6443, 16208, 26469,  4386, 21344, 20371, 18741,
          8707, 14602,  9260, 23919,  5264, 16208, 26469,  9581, 11162, 15577,
         19057,  4490,  3401,  8396, 14795,  6200, 26986,  1124, 25370,  6193,
         16208, 26469, 25852,  6997, 20371, 21943, 18741,  8186, 26654, 21859,
         23945,   767, 18724,  5522,  9626, 17296, 15577, 21344, 16208, 26469,
         13801, 14028, 22606, 25544,  1302, 25920, 16208, 26469, 20371, 18147,
         19191, 18724, 20456,  1042, 27245,  9260, 25025, 25370, 16208, 26469,
          7137, 14600, 26882, 25370, 26105, 16208, 26469,  4381, 26414,  3970,
         23100, 12922, 12226,  3314,  7599, 14855,  5104,  5282, 21344,  9626,
          8469, 13811,  5848,  1926, 21344, 23428,  3785, 18092, 10116, 15577,
         21344, 23443,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 19474,  5155,  ...,     0,     0,     0],
        [    1, 11907, 19456,  ...,     0,     0,     0],
        [    1,  9757, 11622,  ...,  7219,  1926,     0],
        [    1,  1140, 26072,  ...,     0,     0,     0]], device='cuda:0') tensor([[[ -2.8742,  22.0497,  -0.7260,  ...,  -2.2390,   0.1450,   0.4760],
         [ -4.5478,  -0.7608,  -1.5297,  ...,  -4.3553,  -2.6931,  -0.6894],
         [ -6.6371,  -5.3294,  -2.2500,  ...,  -6.2903,  -3.1422,  -0.9567],
         ...,
         [ -2.5348,  -0.8000,  -1.4467,  ...,  -2.1148,  -1.1834,  -0.3532],
         [ -2.4093,  -0.9833,  -1.2952,  ...,  -1.9989,  -1.1975,  -0.3476],
         [ -2.5303,  -1.4706,  -1.2949,  ...,  -2.1546,  -1.3762,  -0.4190]],

        [[ -3.0234,  21.4908,  -0.7956,  ...,  -2.3064,   0.0407,   0.5678],
         [ -6.0481,  -2.5903,  -1.9240,  ...,  -6.5504,  -2.7934,   0.1075],
         [ -4.6347,  -4.6582,  -1.5376,  ...,  -3.7984,  -1.9355,  -0.9194],
         ...,
         [ -3.4233,  -0.8262,  -1.8394,  ...,  -3.0147,  -1.4877,  -0.4343],
         [ -3.3159,  -1.0866,  -1.6846,  ...,  -2.9247,  -1.5508,  -0.4608],
         [ -3.4071,  -1.6176,  -1.6479,  ...,  -3.0560,  -1.6974,  -0.5376]],

        [[ -2.0367,  22.8400,  -0.2275,  ...,  -1.2707,   0.8302,   0.5193],
         [ -1.1343,  -1.1580,  -1.2657,  ...,  -1.5651,  -0.7290,  -0.2540],
         [ -4.0897,  -0.9264,  -1.8362,  ...,  -3.5500,  -1.5528,  -1.0606],
         ...,
         [ -5.4268,  -1.9304,  -2.4680,  ...,  -5.6622,  -3.4104,  -1.3344],
         [ -2.2228,   0.7992,  -1.3134,  ...,  -2.1002,  -1.0976,  -0.2335],
         [ -1.2031,  -0.6503,  -0.9709,  ...,  -1.0007,  -0.4498,  -0.8090]],

        [[ -2.2954,  22.3734,  -0.4352,  ...,  -1.6645,   0.5546,   0.6221],
         [ -5.7864,  -2.0933,  -2.1569,  ...,  -5.5358,  -3.0185,  -0.0579],
         [-10.1890,  -6.5882,  -4.7154,  ..., -10.0875,  -4.9951,  -3.3768],
         ...,
         [ -2.6252,  -0.7601,  -1.6317,  ...,  -2.2954,  -0.8811,  -0.4645],
         [ -2.4914,  -0.9211,  -1.4745,  ...,  -2.1776,  -0.8994,  -0.4697],
         [ -2.6862,  -1.4489,  -1.4924,  ...,  -2.4178,  -1.1031,  -0.5876]]],
       device='cuda:0') tensor([[    1, 19474,  9479, 14023,   576, 16186, 23337, 17098, 13159,  5522,
         22234, 17524, 16650, 20471, 23443, 19474, 21344, 14566,  3287, 17224,
         17524, 25916,  5729, 18739, 16177, 15268,   441,  3462, 14869, 23337,
         21533, 19474, 19138, 19474,  5049, 14566, 26986, 15687, 20017, 23001,
         19123, 17524, 18768, 13185, 26339, 21344, 27338,  5271,  5657, 13159,
          1616,  1617,   573, 19474,  5522, 25264, 15024, 13159, 11570,  5549,
         21869, 21511,  5506,   168, 16650, 20476, 25916, 19834,   980, 20471,
          6904,  1257, 19474, 19138, 16521, 24344,   244, 10426, 10205, 14639,
          5492, 23769, 27098, 23004, 24788, 17524, 16650, 19580, 19474,  4199,
          8552, 10162,  7149, 21533,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0],
        [    1, 11907, 21344, 24346, 23515, 20601, 10610,  5909,  6392, 17204,
         23001, 22887, 14388, 17204, 23001, 22887, 16179,  2032, 18905,  6670,
          9724, 24959,  5423,  4916, 22887, 19157, 11907, 23144, 16654, 24840,
         27483,  2188,  4809, 14388, 22887, 11907, 21344, 16010,  9862, 26280,
         24523, 20525, 15096, 12450,  2821, 14388, 26170,  3789, 12454, 26172,
         11286,  5910, 26170, 14388,  8458, 25606,  6676, 10951,  4952, 18270,
         20877, 18794, 22021,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,

 72%|███████▏  | 81/112 [00:05<00:01, 16.14it/s, loss=0.987]

tensor([[    1, 26850, 19628,  ...,  4585, 19119,     0],
        [    1,  7672,  3522,  ...,     0,     0,     0],
        [    1, 24738,  6596,  ...,     0,     0,     0],
        [    1,  6121, 16507,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.5124e+00,  2.2732e+01, -1.7839e-01,  ..., -1.0766e+00,
           9.5190e-01,  5.2385e-01],
         [-9.8147e-02,  4.1335e-01, -6.6166e-02,  ...,  6.3267e-02,
          -4.3529e-01,  1.4142e+00],
         [-4.4318e+00, -3.2082e+00, -2.3388e+00,  ..., -3.9645e+00,
          -2.2028e+00, -6.3558e-02],
         ...,
         [-1.4241e+00,  5.9755e-01, -1.6033e+00,  ..., -2.0503e+00,
          -1.9283e+00, -7.6184e-01],
         [-3.8016e+00, -4.5310e+00, -3.1252e+00,  ..., -3.9730e+00,
          -2.8545e+00, -2.1987e+00],
         [-1.1396e+00, -1.0914e+00, -1.6364e+00,  ..., -1.3289e+00,
          -5.7084e-01, -8.8266e-01]],

        [[-3.1149e+00,  2.1913e+01, -7.9583e-01,  ..., -2.4872e+00,
          -5.7992e-02,  2.4330e-01],
         [-2.6258e+00,  1.3734e+00,  1.5258e-01,  ..., -1.7514e+00,
          -1.1427e+00, -1.8575e-01],
         [-6.7149e+00, -1.2673e+00, -3.3753e+00,  ..., -6.8149e+00,
          -3.7700e+00, -1.6175e+00],
         ...,
         [-3.8081e+00, -1.8335e+00, -2.2314e+00,  ..., -3.4208e+00,
          -2.0420e+00, -9.1290e-01],
         [-3.8887e+00, -1.8942e+00, -2.3699e+00,  ..., -3.5119e+00,
          -2.1235e+00, -9.2836e-01],
         [-3.8609e+00, -2.0769e+00, -2.4292e+00,  ..., -3.4955e+00,
          -2.1049e+00, -9.5176e-01]],

        [[-3.1553e+00,  2.1711e+01, -9.0979e-01,  ..., -2.3662e+00,
           3.4623e-02,  3.4203e-01],
         [-9.6650e+00, -5.0621e+00, -3.8332e+00,  ..., -8.2707e+00,
          -3.9637e+00, -1.5294e+00],
         [-6.5479e+00, -2.3957e+00, -3.6331e+00,  ..., -6.6205e+00,
          -3.7530e+00, -1.5586e+00],
         ...,
         [-4.2034e+00, -2.5311e+00, -2.4169e+00,  ..., -3.7014e+00,
          -2.0359e+00, -7.6610e-01],
         [-4.2682e+00, -2.5466e+00, -2.5384e+00,  ..., -3.8041e+00,
          -2.1224e+00, -7.9656e-01],
         [-4.2853e+00, -2.7242e+00, -2.5975e+00,  ..., -3.8293e+00,
          -2.1049e+00, -8.6815e-01]],

        [[-1.9410e+00,  2.2301e+01, -2.9191e-01,  ..., -1.3358e+00,
           5.9203e-01,  8.0291e-01],
         [-5.5465e+00, -1.1239e+00, -2.5255e+00,  ..., -5.1074e+00,
          -2.1638e+00,  2.1512e-02],
         [-2.5939e+00,  4.0109e-01, -1.6763e+00,  ..., -2.9194e+00,
          -1.2391e+00, -9.4762e-02],
         ...,
         [-3.4803e+00, -1.7113e+00, -2.1031e+00,  ..., -3.0626e+00,
          -1.8127e+00, -5.8924e-01],
         [-3.5331e+00, -1.6951e+00, -2.2077e+00,  ..., -3.1463e+00,
          -1.8757e+00, -5.8562e-01],
         [-3.4726e+00, -1.8302e+00, -2.2425e+00,  ..., -3.1024e+00,
          -1.8165e+00, -6.1057e-01]]], device='cuda:0') tensor([[    1, 15726, 21535, 26713, 12223, 16310, 16644, 27314, 23052, 13894,
         11449, 11621, 19748, 16387, 21535, 26850,  2032, 19628,  6691, 11704,
         23052, 13894, 19748, 11449, 11621, 25206, 19867, 10395, 19628, 14414,
         11449, 11621, 23052,   134, 21535, 15016, 15726, 16467, 21404,  6746,
          3510, 16387, 25132, 13578, 15016, 15726, 21535, 11449, 11621, 14025,
         23039, 15726, 21535, 23039,   265,  2219, 25923, 23446,  9673, 24657,
         17471, 19748, 11449, 11621, 19119, 26850, 15687, 20877, 15444, 23052,
         13894, 11449, 11621, 20877, 19867, 11013, 23052, 11449, 11621, 21589,
         10205, 14864, 19628, 24095, 15024,  5148, 23039, 14025, 23052, 13894,
         19748, 11449, 11621,  5153,  7962,  1248, 13947,   839, 11449, 11621,
         21589, 15726, 21535,  9193, 16221, 23052, 13894, 11449, 11621, 14595,
          3461,  6116, 18439,  9913, 17171, 15632, 11704, 11449, 11621,   263,
         11449, 11621, 19748,   265, 19567, 18673, 23052, 23083, 27314, 14496,
          1356, 25438, 15096, 27290,    74, 15630, 11449, 11621,  8872, 15536,
          8872, 23052, 23083, 27314, 19764, 10205,  4035, 11197, 10711, 25206,
         19628,  2042,  2966, 17171,  2367,  7941, 23039, 20877, 15726, 21535,
         22558, 14417,   240, 23052, 23083, 27314, 26161,  4845,  3107, 19748,
         11449, 11621,  8012,  8330,  4948, 26179,  8463, 16327, 27513,  5885,
         17171, 11704, 25206, 13948,  4734, 15726, 25593,  9774, 22030,  4044,
         26715, 14881, 10712, 14317, 14595,  3461,  6116, 18439,  9913,   134,
          8872, 10353,     0],
        [    1,  8397,  4801,  3517, 25459,  2076,  9673, 10193,  3014,  6297,
         14354,  1021,  6200,  8275,  9673, 10193, 14412,  6297, 21226,  3022,
          8385, 21344, 24938, 13820,  5658, 21230, 15399, 24432, 27479, 17648,
          3106,  3268,  9537,  2032,  7672, 18872, 10084, 10721, 10193, 16654,
         27479,  9673,  9673, 10193,  3011, 27479,  4801,  4989, 25593,  5548,
          1128, 25199,  5450,  8524,  6298, 21344, 23443, 16177,  3545,  9673,
         10193, 26613, 21239,  3268,  6298,  8385,  3625,  9266, 24938,  9634,
         27483,  8385, 21229, 15499,  5548, 16326, 13442,  6298,  8385,  8617,
         10190,  6297,  8829,  8829, 10084, 16654, 27479, 27479,  9673,  9533,
          7458,  8615, 27479,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1, 24738, 19310, 24133, 15863, 24680, 17155,  6200, 17557, 11896,
         21344, 24093,  6200, 10621, 25370,  6197, 26986,  1124,  6200,  5569,
          1210, 23221, 10621, 23262, 13406, 24738, 21535,  7604,  4867,  4459,
         15863,  7473, 24680, 12274, 10621, 25370, 24738,  4860, 13708, 13473,
         19310, 24133, 11896,  6182, 15863, 24840,  7473, 24693, 11896,  6192,
          4867, 10618,    74, 24738, 25025, 26475, 16650,  9266, 12702, 22513,
          1492, 17155,  3607,  6460, 14795, 14606, 15875, 24938,  3607, 20930,
          8462,   209, 22467, 26818,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1, 22513, 11736,  9094,  3755, 14604, 15093, 22147,  9260, 18346,
         14602, 18439, 19680, 16626, 16010,  5915, 10382, 23358, 10885, 10190,
          9260, 26715,  3429,  9094, 17444,  6121, 15103, 18581,  9094,  9935,
         20877, 21909,  3670,  7137, 10382, 17795,   715,   525,  6129, 20645,
         19596, 10382,  5975,   739,  9094, 10382, 27040,  8397, 17224, 14600,
         16010, 14554, 26717, 25988,  9094, 25920,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]], device='cuda:0')
tensor([[    1, 15307,  7624,  ...,     0,     0,     0],
        [    1, 15663, 20288,  ...,     0,     0,     0],
        [    1, 20365,  5313,  ...,  9973,   987,     0],
        [    1,  3118, 14258,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.3468, 22.4507, -0.4661,  ..., -1.6811,  0.5093,  0.4437],
         [-2.8327,  1.3653, -0.7110,  ..., -2.4626, -1.1826, -0.7633],
         [-5.6956, -3.0769, -1.6293,  ..., -5.4514, -2.7562, -1.6448],
         ...,
         [-2.8940, -1.7105, -1.9791,  ..., -2.6519, -1.2741, -0.8258],
         [-2.8342, -1.6049, -1.9633,  ..., -2.5653, -1.1864, -0.8205],
         [-2.6604, -1.5127, -1.8765,  ..., -2.4826, -1.1128, -0.7681]],

        [[-1.6095, 22.4655, -0.0447,  ..., -0.9238,  0.6597,  1.1506],
         [-5.9422, -2.0112, -2.3857,  ..., -5.6461, -3.4943, -1.4243],
         [-5.0738, -1.6715, -2.6967,  ..., -5.0436, -2.9866, -1.4624],
         ...,
         [-3.2779, -1.5486, -1.9342,  ..., -2.8277, -1.7146, -0.4222],
         [-3.1344, -1.4252, -1.8695,  ..., -2.6550, -1.6018, -0.3797],
         [-2.9263, -1.3022, -1.7647,  ..., -2.5332, -1.5189, -0.2892]],

        [[-2.6205, 22.3684, -0.4976,  ..., -2.0021,  0.4222,  0.3147],
         [-2.0161, -1.8344, -1.5752,  ..., -2.5450, -1.2377, -0.6510],
         [-2.3967, -0.9229, -0.8483,  ..., -2.3533,  0.1293,  0.1971],
         ...,
         [-6.9909, -4.4853, -3.2428,  ..., -7.3100, -4.6324, -2.6626],
         [-7.2091, -5.4913, -4.7737,  ..., -7.3466, -3.1282, -2.2449],
         [-2.0524, -1.2688, -1.7201,  ..., -2.0997, -0.8635, -1.0194]],

        [[-2.9240, 21.8429, -0.8010,  ..., -2.2529,  0.1167,  0.6635],
         [-4.1088, -1.1782, -1.6211,  ..., -3.8592, -1.9184, -2.0425],
         [-2.3801, -0.6954,  0.1123,  ..., -2.3161, -2.1945, -0.5322],
         ...,
         [-2.7063, -1.3373, -1.7434,  ..., -2.2655, -1.1627, -0.2386],
         [-2.6388, -1.2423, -1.7362,  ..., -2.1614, -1.0574, -0.2256],
         [-2.5016, -1.1682, -1.6588,  ..., -2.0939, -1.0151, -0.1755]]],
       device='cuda:0') tensor([[    1,  7539, 25923, 14953, 11900, 15307, 20489, 21304,  4003,  7706,
         24810,  3520,  8047, 23119,  9905,  7539, 25923, 18483,  8691, 22912,
         15307, 22405, 21701,  5862, 27115, 19521, 23007, 11900, 15307, 14551,
          6621, 24364, 16924,  1242, 12226,  5883, 14036, 18724, 14997,  8591,
         14036,  5862,   290, 11736,  5274, 23119, 17171, 10456,  8332, 22055,
          5780,  9984,  4766, 21490, 23813, 12525, 25865,  3401, 26876,  9639,
         14036, 17171, 24509,  1167, 21237,  7986, 24826,   818, 10395,  1758,
          7539, 25923, 25800, 15307, 27338, 21305, 22200, 26876, 14953, 17902,
         23813, 27095, 20701, 24405,  9293, 16050,  8610, 14074, 22955, 21344,
         16326, 10205,  7771,  5883, 18158, 21344, 24810,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 15663, 26750, 17949, 26179, 26092, 24294, 13943, 21854,  9298,
          9356, 27123, 19157, 17171,  5726, 17863, 15663, 14795,  1666, 12126,
         17171,  9298, 11971,  9356, 16049, 21854,  3305,  9309,  7790,  5726,
         21854, 11544,  5522, 14071, 17953, 17204,  1526, 14096, 25972, 17107,
          5726,  9354,  1017, 23071, 26513,  9479, 11570, 26179,  3402, 14071,
          9354, 25972, 12126, 17174,  4427,  5726, 16924, 11544,  5153,  5726,
         26185,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 16205, 25815,   759, 14191, 18056,  4750, 18147, 19715, 11818,
         22296,  9973,   987, 16205, 25815, 18449, 19452, 17171, 20891,  4956,
         14502, 22742, 20539, 24703, 19715, 14186, 18056, 22296, 26280,  9973,
           987, 16205, 25815, 21344, 12675, 11822,  5522, 18673,  6861, 11821,
         25672, 10205, 27269,  7070, 11821,  3607,   457, 25406, 24703, 13175,
         25815, 14948,  2219, 14442, 22329, 26867, 21344, 11932, 20365,  5313,
         11822,  3545, 27479,   517, 26794,  6253, 26390, 26853,  1042, 16588,
         22558,   757, 14442, 22329, 22558, 14191, 18056, 22296, 21141, 17725,
         22462, 24435, 15799, 22299, 22028, 22742,  8995, 26179, 24344,  5313,
          3548, 20866, 26170, 23232, 22296,  9973,   987, 20966,  1302, 11235,
         24703, 19715, 16859, 23624, 16205, 25815, 14194, 18056, 11818, 26003,
         12128,   987, 27076, 18343, 24703,  4845,  5154, 14194, 26850, 26179,
         26170, 20365,  5315, 20866, 22296,  6253,  1055, 27076, 18343, 23443,
         21185, 21344, 10596,  4976, 18056,   731, 10395, 17181, 20366,  5313,
         20866, 15700,  2324, 27081,  6846, 24703, 17776, 27081,  6469, 21344,
          5883, 11822, 23465,  5586, 16588, 20365, 11822,     0],
        [    1,  3118, 14258,  5269,  8669, 26822, 24534, 11286, 26161, 12166,
         22024, 26179, 21344, 14730,  3105,  4199,  8552,  3118, 14258, 14876,
         26530, 26715,    58,   130,  7599, 14850, 26919,  3118, 14258,  3817,
         26530,  3118, 14258,    58, 10205, 27169, 12675,   130,   749,  8707,
         12408,  1666,  8856, 19846, 21087, 24534, 25364, 22513, 15268, 26166,
         14203, 14881, 14258, 14542,   251, 19349, 11702,  3118, 14258, 19937,
          1302, 26530,  6102, 22022,  1302, 19843, 27479, 23793, 20721, 26530,
         14258,  3744, 13914, 23793,  5016,  5205,  3290, 27625,  9626, 26530,
          3545, 14258, 22555, 26170,  3401,  3951,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 13177,  1020,  ...,     0,     0,     0],
        [    1, 19453,  1787,  ...,   539, 18447,     0],
        [    1, 12930, 12838,  ...,     0,     0,     0],
        [    1,  2303, 13963,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.0003e+00,  2.2137e+01, -7.0521e-01,  ..., -2.3214e+00,
           2.7381e-01,  2.0134e-01],
         [-6.0920e+00, -4.8793e-01, -2.8945e+00,  ..., -6.6821e+00,
          -2.8599e+00, -1.6952e+00],
         [-1.9046e+00,  1.9753e+00,  5.0326e-01,  ..., -1.7926e+00,
          -1.4508e-03, -4.6856e-01],
         ...,
         [-2.8085e+00, -1.7966e+00, -1.7089e+00,  ..., -2.6044e+00,
          -1.2130e+00, -7.6628e-01],
         [-2.7068e+00, -1.6380e+00, -1.7665e+00,  ..., -2.4834e+00,
          -1.1147e+00, -7.8883e-01],
         [-2.4985e+00, -1.3730e+00, -1.7116e+00,  ..., -2.2827e+00,
          -9.7834e-01, -7.8968e-01]],

        [[-1.8824e+00,  2.2851e+01, -1.4419e-01,  ..., -1.1106e+00,
           7.9682e-01,  6.3007e-01],
         [-2.9929e+00, -2.7004e-01, -2.2317e+00,  ..., -2.7306e+00,
          -1.7500e+00,  2.3383e-02],
         [-5.7149e+00, -2.5429e+00, -2.6264e+00,  ..., -4.7866e+00,
          -2.2196e+00, -8.7510e-01],
         ...,
         [-3.5512e+00, -3.8795e+00, -1.6039e+00,  ..., -3.5638e+00,
          -9.2681e-01, -8.0583e-02],
         [-3.9893e+00, -1.1699e+00, -5.9705e-01,  ..., -3.4385e+00,
          -1.5571e+00,  5.4945e-01],
         [-1.7559e+00, -9.9962e-01, -1.5168e+00,  ..., -1.5088e+00,
          -5.8878e-01, -7.1111e-01]],

        [[-2.4677e+00,  2.2402e+01, -6.0167e-01,  ..., -1.6279e+00,
           5.0244e-01,  4.3163e-01],
         [-6.5132e+00, -8.0044e-01, -2.6343e+00,  ..., -6.6497e+00,
          -2.9089e+00, -3.2687e+00],
         [-7.3377e+00, -5.0943e+00, -3.6935e+00,  ..., -7.1787e+00,
          -3.3816e+00, -1.8577e+00],
         ...,
         [-2.7284e+00, -1.7556e+00, -1.8156e+00,  ..., -2.5423e+00,
          -1.1721e+00, -9.8274e-01],
         [-2.6164e+00, -1.5934e+00, -1.8667e+00,  ..., -2.4219e+00,
          -1.0580e+00, -1.0114e+00],
         [-2.4266e+00, -1.3106e+00, -1.8049e+00,  ..., -2.2310e+00,
          -9.1384e-01, -1.0189e+00]],

        [[-2.4622e+00,  2.2090e+01, -6.3273e-01,  ..., -1.7504e+00,
           2.5722e-01,  8.0793e-01],
         [-3.4988e+00,  3.5990e-01, -1.9317e+00,  ..., -3.4538e+00,
          -1.4396e+00, -1.0834e+00],
         [-2.6479e+00, -5.5993e-02, -1.9843e+00,  ..., -2.9529e+00,
          -1.6717e+00, -8.1612e-01],
         ...,
         [-3.4870e+00, -2.3571e+00, -1.9362e+00,  ..., -3.2200e+00,
          -1.8571e+00, -3.3617e-01],
         [-3.3812e+00, -2.2323e+00, -1.9848e+00,  ..., -3.0762e+00,
          -1.7401e+00, -3.8353e-01],
         [-3.0858e+00, -1.9494e+00, -1.8805e+00,  ..., -2.7719e+00,
          -1.5551e+00, -3.4824e-01]]], device='cuda:0') tensor([[    1, 13177,  3658,  8111, 27314,  5862, 10367, 18475,  9172, 15199,
         13304,  9973, 13206, 10609, 26818,  8047, 21804,  8047,  3690, 21344,
         13177,  9581,  8111,  3656, 15139, 13177,  1017, 20673, 21216, 25914,
          8047, 21804,  5038, 14795, 20877,  6200, 20673, 21344, 13177, 13177,
           783, 20737,  8111,  8872,  3659,  8111,  7393, 27314,  5862, 27115,
          1616, 24247, 14412,   211, 23624, 14541, 21216, 25914,  9266, 10351,
         24022,  8662, 27314,  5862, 21344, 19290, 17795, 13177,  8889,  1101,
         15149,  3657, 13177,   759, 17171,  9203, 21827, 21169,  8447, 18475,
          9973, 13177,   759, 11765, 23888,  3656, 14128, 10767, 24922,  1758,

 74%|███████▍  | 83/112 [00:06<00:01, 16.70it/s, loss=1.4]

tensor([[    1, 24479, 23411,  ...,     0,     0,     0],
        [    1,  3380,  1703,  ...,     0,     0,     0],
        [    1, 25364,  2207,  ...,     0,     0,     0],
        [    1,  9984, 14886,  ..., 11625,  4285,     0]], device='cuda:0') tensor([[[-2.7803, 21.9115, -0.7977,  ..., -2.2290,  0.2253,  0.4984],
         [-4.2711, -1.4666, -1.6664,  ..., -3.5603, -2.3028, -1.2843],
         [-3.5855, -2.2034, -1.5210,  ..., -3.8379, -1.9468, -0.0882],
         ...,
         [-2.1422, -1.1318, -1.2201,  ..., -2.0479, -1.3288, -0.6714],
         [-2.1454, -0.8351, -1.2471,  ..., -2.0340, -1.2750, -0.6210],
         [-2.3607, -0.7170, -1.4194,  ..., -2.2327, -1.2556, -0.5453]],

        [[-2.6570, 21.6155, -0.3428,  ..., -1.6569,  0.3297,  0.8892],
         [-3.2566, -0.4563, -1.0426,  ..., -2.5933, -1.6177, -1.4426],
         [-7.1000, -4.8016, -2.9354,  ..., -6.9955, -3.9601, -2.1559],
         ...,
         [-2.2459, -0.9483, -1.0394,  ..., -1.4907, -1.3063,  0.0567],
         [-2.2129, -0.6367, -1.0317,  ..., -1.4492, -1.2460,  0.1129],
         [-2.4057, -0.5674, -1.1873,  ..., -1.6350, -1.2190,  0.1790]],

        [[-2.2643, 22.3158, -0.3804,  ..., -1.4902,  0.4340,  0.9423],
         [-6.1308, -2.7564, -1.8071,  ..., -5.3664, -2.7868, -1.0421],
         [-4.2318, -2.8923, -2.5691,  ..., -4.6097, -1.8503, -1.0536],
         ...,
         [-2.1666, -1.8539, -1.4393,  ..., -1.9977, -1.4151, -0.6745],
         [-2.1440, -1.5488, -1.4539,  ..., -1.9690, -1.3594, -0.6060],
         [-2.2744, -1.3614, -1.5814,  ..., -2.0974, -1.3008, -0.5171]],

        [[-1.9238, 22.5855, -0.1023,  ..., -1.1466,  0.8066,  0.8058],
         [-4.5121, -0.4207, -1.1985,  ..., -4.5475, -2.0700, -1.2438],
         [-2.3809, -1.8671, -0.1396,  ..., -1.8985, -1.0611,  0.5103],
         ...,
         [-3.1103, -1.3198, -1.5152,  ..., -2.9926, -1.2329, -1.3931],
         [-4.9194, -3.8772, -1.2692,  ..., -4.4035, -1.7889, -0.6005],
         [-1.8456, -0.8567, -1.4277,  ..., -1.6545, -0.7505, -0.6553]]],
       device='cuda:0') tensor([[    1,  9746,   261,  1596, 24479, 23411, 11472,  9157,   828, 18475,
          9028, 14023,  9157,   277,  5955, 26480,  4624, 20471, 16183, 26368,
          6012,  3193,  2367, 21914, 16889,  6839, 21073, 11730,   759, 23426,
         25035, 10977, 13117,   759, 20606,  6840, 24479,   828, 13964,   261,
         14864, 17352, 27150,  6846, 21073, 11730,  4272, 24479, 17795, 18884,
          9746,   261,  2436, 16387, 11561, 23411,   759, 23424, 14023, 21044,
          5727,   146,  9157,  6857, 18982, 24788,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  3118,  8086,  9260,  3380,  8086,  1703, 25593, 18768, 14669,
         17117,  8663,  5288,  7783,  3380,  8086,   757, 18930,  7783,  1703,
          8663,  5282, 13934, 27479,  6129, 10302,  3380,  8086,   130, 12285,
         17117, 10035, 12341,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  8553, 11287, 16205,  2880, 17273, 23039,  2438,  1926, 15565,
         21436,  1902,  3945, 11462, 25364,  7959,  2880,  4003, 23039, 18794,
          1926, 21436,  3945, 11462, 23430, 14803, 23185,   699, 16205,  2880,
          5273, 14023, 21436, 12580,  2690, 24348, 13934, 16894,  3118,  1926,
            24, 16456, 16205,  5413,  9581,  3959, 21436,   759,  1401,  5569,
         16626,  8469,   353, 16205,  2880,   198, 15887,  1926,  9873,  1186,
         17935,  8400,  2792, 18046, 17940, 25593,  9581,  8553,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,   341, 25025,  2102, 16644, 17181, 21914,  1252, 26818, 21511,
         21239,  3789,  1252,  2219, 11070, 18772,  9984, 19298, 11193,  9420,
          3789,  4845,  1252, 26750, 14633,  3789,  6106,   517, 22153, 24133,
         25219, 14542, 23594,  8526, 16644, 14601,  3545, 13636, 10426, 20070,
         21344, 13040, 17775, 17171,  9973,  6670, 21305,  1252,  1252, 14891,
          9984, 27483, 17171, 13919, 12274,  9984,  6670, 25639, 16205, 17775,
         21344, 23337, 25025, 13155, 14602, 16515, 21511,  1252, 10426, 16626,
          6135,  6342, 14029,  1252, 26748, 15666, 17047, 21247,  3789, 24132,
         25219, 22153, 14542, 23594,  8526, 17171,  3115, 13919, 12274,  9973,
         14887,  1252,  9984, 19452, 21364, 14606, 18056, 24130,  1252, 25438,
         24938, 25025,  2102, 16644, 17181,     0]], device='cuda:0')
tensor([[    1, 21334,  5371,  ...,     0,     0,     0],
        [    1,  2549, 18511,  ..., 12596,  5556,     0],
        [    1, 17810,  3287,  ...,     0,     0,     0],
        [    1, 26827,  6071,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.9963e+00,  2.1535e+01, -1.1982e+00,  ..., -3.3006e+00,
          -3.7774e-01,  1.4797e-01],
         [-8.1415e+00, -2.1802e+00, -5.0682e+00,  ..., -7.8227e+00,
          -4.2920e+00, -2.2042e+00],
         [-4.3932e-01,  6.9062e-01,  6.8372e-01,  ..., -1.8109e-02,
           9.6321e-01,  9.6590e-01],
         ...,
         [-1.6577e+00, -7.6706e-01, -1.2976e+00,  ..., -1.6374e+00,
          -6.8971e-01, -2.4760e-01],
         [-2.1174e+00, -1.0737e+00, -1.5274e+00,  ..., -2.1317e+00,
          -9.8877e-01, -3.6061e-01],
         [-2.5683e+00, -1.4089e+00, -1.7721e+00,  ..., -2.5146e+00,
          -1.2469e+00, -5.3845e-01]],

        [[-2.3014e+00,  2.2633e+01, -4.8646e-01,  ..., -1.5450e+00,
           5.9932e-01,  4.6365e-01],
         [-1.2477e+00, -1.5582e+00, -1.3841e+00,  ..., -1.6022e+00,
          -8.4255e-01, -3.6110e-01],
         [-6.2433e+00, -6.0328e+00, -2.8557e+00,  ..., -5.7082e+00,
          -3.3847e+00, -8.4202e-01],
         ...,
         [-1.9532e-01, -4.2543e-01,  3.6807e-02,  ...,  2.1234e-01,
           1.6587e-01,  5.0024e-01],
         [-4.0727e+00, -4.9964e+00, -1.8898e+00,  ..., -3.7586e+00,
          -2.2059e+00,  3.0820e-01],
         [-1.1154e+00, -1.0382e+00, -1.2208e+00,  ..., -1.1998e+00,
          -4.9520e-01, -5.2592e-01]],

        [[-2.0279e+00,  2.2390e+01, -3.1974e-01,  ..., -1.4164e+00,
           6.0102e-01,  5.4170e-01],
         [-5.1899e+00, -3.1565e+00, -3.1478e+00,  ..., -5.1129e+00,
          -2.0423e+00, -2.1796e+00],
         [-3.8310e+00,  1.2776e+00, -2.0693e+00,  ..., -3.3747e+00,
          -1.7030e+00, -1.1295e+00],
         ...,
         [-1.4541e+00, -1.0386e+00, -1.2459e+00,  ..., -1.4029e+00,
          -5.8777e-01, -3.8576e-01],
         [-1.8546e+00, -1.2795e+00, -1.4536e+00,  ..., -1.8372e+00,
          -8.5234e-01, -4.8946e-01],
         [-2.3451e+00, -1.5940e+00, -1.7052e+00,  ..., -2.2575e+00,
          -1.1246e+00, -6.7770e-01]],

        [[-3.0377e+00,  2.1954e+01, -8.0837e-01,  ..., -2.1842e+00,
           1.9341e-01,  5.5177e-01],
         [-5.3191e+00, -2.3815e+00, -3.0893e+00,  ..., -5.0515e+00,
          -2.3441e+00, -2.8973e+00],
         [-4.7264e+00, -4.8858e+00, -3.0936e+00,  ..., -4.6086e+00,
          -2.3168e+00, -4.2440e-01],
         ...,
         [-1.3070e+00, -5.0744e-01, -9.9793e-01,  ..., -9.8114e-01,
          -4.4650e-01,  2.2322e-01],
         [-1.6554e+00, -7.2084e-01, -1.1648e+00,  ..., -1.3383e+00,
          -7.1769e-01,  1.3219e-01],
         [-2.1531e+00, -1.0657e+00, -1.4268e+00,  ..., -1.7665e+00,
          -1.0145e+00, -8.5834e-02]]], device='cuda:0') tensor([[    1,  8610, 21399,  8950, 18960, 26969, 21344,  9266,  9172, 27115,
         24809, 13174, 21859, 27150, 10559, 22638,  1087, 11736, 21334, 11624,
         27150,  1617, 17204, 10298,  2241, 16528, 27115, 10559, 22633, 24992,
         21919,  9180,  9746, 17204,  2244, 27115, 27479, 17131, 22281, 18193,
         21399, 26161, 17204,  9172, 27115,  9266, 14874, 24990, 14604, 25593,
          1617, 17204,  9180, 21334,   353,  2209,  7317, 26986, 27338, 27115,
          1042, 10559, 22633, 14600,  9266, 22030, 14469, 11363, 23975,  9172,
         21334, 21344,  2200,  7317, 14600, 21135, 17171, 13934, 27479, 21334,
         21344, 10301, 27112, 27150, 21827, 10559, 22633, 24990,  4046, 15752,
         14070, 17239, 27115, 14070,  4035, 21344, 18056,  3607, 18475, 11013,
          5569, 18056,  3607, 18475,  4450, 16639,  5775,  1617, 17204,  4028,
         15037, 21334, 21227,  4035, 27150, 27112,  9905,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 16205,  3193,   702, 21344,  5522, 14554,  2244,  1089, 16205,
          2549, 25025,  8487, 13793, 14025, 16559, 13588, 21344, 16205,  2549,
         16205,  3193,  5522,  6129, 15425,  9751,  5274, 21530, 27338,   727,
         21160,  5994, 13793,  3118, 12651, 16205,  3193, 21535,  6946,  7822,
          3557, 16205,  2549, 21490, 19187, 18475, 17795, 21973,  2102, 12702,
         16205,  3193, 21344, 19019, 15783, 27338,  7087, 10493, 16626,  2797,
          3193,  3115, 23975, 24570, 13235, 20982, 18189, 21535, 16205,  2549,
         26935,  1758, 18509, 14881, 26818, 16205,  3193,  3463,   719, 12698,
         13304, 16205,  2549, 25025, 17779, 13793, 17825, 16005, 13657,  8461,
          3463, 10512, 16859, 10426, 10205, 26818, 25898, 13793, 17825, 25898,
         18724, 27150, 24797, 24650, 18056,  6597, 16521, 16626,  2797, 21535,
         19019, 15783, 26935,  1758, 18509, 16205,  3193, 23387, 16654, 10121,
          7822, 12126, 25898, 26818,  8156,  7822, 13793, 10512, 21344, 16005,
         16205,  2549, 23203, 21344, 19019, 15783,  6648, 10205,  3401, 10512,
          2247, 18056, 26713, 16205,  2549, 23083, 16203,   853,  9757, 21237,
         20869, 10480,  3193,     0],
        [    1, 20171, 18620, 17810, 20510, 22030, 19512,  7255, 11179, 14496,
          5186, 17810, 19933, 13793, 17825, 19934,  7255,  9172, 19512, 16626,
          9141, 22340, 22450,  7255,  3545, 20674, 15732,  3403, 18251, 22548,
          4289, 17170, 10061, 17825, 23962, 20125, 14827, 27090, 11115, 16966,
         10061, 13919,  7254,  5144,  2316, 21273,  2126, 16506,  5144, 21827,
         18423,  7255, 25128, 14237,  6414, 19934, 14237,  6414, 13919,  7271,
         13226, 21168, 20116, 25474, 14654,  4845, 19194, 18620, 20116,  5193,
          4044, 10061, 23962, 16506, 10885, 19934, 18620, 17810, 14413,  7825,
          4801,   759,  7255, 25083,  5144, 21701,  3401, 10712,  9452, 21697,
         12568, 12668, 20525, 27314, 13919, 12274,  5025,  4845,   759,   867,
         10247, 25098,  7255, 25128,  2131,  5444, 22024,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0],
        [    1, 25841,  9141, 22340, 14857, 19084,  9746,  7700, 10721, 27201,
         12168,  8000, 21344, 15040, 25137,  7698, 16451,  1945, 18672, 17117,
         19006, 26892,  5216, 23144, 22311, 24650, 18768,  5036, 21344, 24938,
          9181, 15783, 16690, 21465, 26750, 11392, 17117, 19006, 18721, 24833,
          9746, 10721,  9746, 23455,   488, 12508,  8617,  7700, 10715, 27479,
          3335, 23760,  5216, 23144,  3401, 12777,   914, 21344,  9746,  4842,
         13437, 19262, 19136, 15068, 24938, 20929,  8086,  5506, 20322, 24344,
          8715, 23337,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 12845,  1498,  ..., 22162, 18160,     0],
        [    1,  2192, 10232,  ...,     0,     0,     0],
        [    1, 17352, 16794,  ...,     0,     0,     0],
        [    1,  2536, 26205,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.8400, 22.8909, -0.1585,  ..., -1.1499,  0.7284,  0.6972],
         [-3.0733, -0.3656, -1.9609,  ..., -2.7648, -1.1977, -0.4982],
         [-2.8871, -1.5923, -0.0687,  ..., -2.5320, -1.1394, -1.6756],
         ...,
         [-2.1452, -1.6665, -1.5580,  ..., -1.8435, -1.0131, -0.7267],
         [-2.5659, -2.0300, -1.8597,  ..., -2.3037, -1.2423, -0.8463],
         [-2.7934, -2.1671, -2.0441,  ..., -2.5927, -1.3500, -0.9516]],

        [[-1.9100, 22.3721, -0.2232,  ..., -1.0435,  0.6466,  0.9143],
         [-3.4276, -1.2940,  0.1086,  ..., -2.7224, -1.3244, -0.5985],
         [-7.3124, -4.4170, -2.3872,  ..., -6.8343, -3.4275, -0.9445],
         ...,
         [-3.1622, -1.7964, -1.5485,  ..., -2.4315, -1.6098, -0.2605],
         [-3.6761, -2.2789, -1.8691,  ..., -2.9834, -1.8818, -0.3788],
         [-4.0642, -2.5350, -2.1362,  ..., -3.4469, -2.0725, -0.5303]],

        [[-2.6100, 22.2064, -0.6825,  ..., -1.8543,  0.3495,  0.5346],
         [-3.9468, -1.1578, -1.5020,  ..., -3.4496, -0.1669, -2.1669],
         [-5.6624, -3.9514, -2.8115,  ..., -5.9186, -2.3412, -0.9096],
         ...,
         [-3.3574, -2.1391, -1.9890,  ..., -2.7972, -1.6023, -0.5285],
         [-3.7454, -2.5325, -2.2429,  ..., -3.2172, -1.8064, -0.6225],
         [-4.1009, -2.7600, -2.5107,  ..., -3.6564, -1.9814, -0.7862]],

        [[-1.8515, 22.8581, -0.0862,  ..., -1.0928,  0.9010,  0.4858],
         [-0.3971,  2.0050,  0.8112,  ...,  0.7184,  0.6154, -0.5789],
         [-6.3435, -1.5930, -2.0264,  ..., -5.7895, -2.9659, -2.9355],
         ...,
         [-3.6507, -2.5038, -2.0293,  ..., -4.0814, -0.9395, -0.3231],
         [-8.1177, -7.6873, -3.8315,  ..., -7.9126, -4.4588, -2.7709],
         [-3.1289, -2.2862, -2.2392,  ..., -2.8845, -1.3788, -1.2733]]],
       device='cuda:0') tensor([[    1, 23428, 27479, 22055, 16829, 12838,  1494, 10159, 11630, 19497,
          9984,  4750,  1600,  9572, 12458, 17902,  3132, 14547, 23388,  2128,
         19304, 22948, 23958, 17154,  8889,  1101, 14437, 23585,  7979, 12845,
          1498, 26792, 25199,  9111,   244,  2200,  1492,  8849, 17896, 25753,
          7945,   770,   685,  5623, 18092,  1493,  8397, 16455, 19496,  9172,
         17077, 11622,  9905,  4750, 13939,  1600, 11688,  6106, 14833, 23335,
          1492, 25025, 26161, 25462, 23707, 12845,  1498,   193, 13799, 14070,
         22948, 14951, 14881,  1492,   807,  1758,   244,  5558, 26886, 13941,
          2137, 27314,  4426,  9111,  9403, 14426, 13343, 20960, 19596, 14542,
         14874,  4031,  6106, 15268, 25947, 21874, 13934,  4876, 10995, 26935,
          1758,  7279,  7615,  9172,   770, 16859, 25820, 26818, 12525,  9218,
         19596, 15799,  2219, 27148, 15585,  6259, 11622, 15350, 16616, 10494,
         16502,  2367, 23967,  9639, 18423,  3118, 25367,  7761,  8054, 11630,
         14891, 18440, 12461, 18432, 25546,  9978, 25315, 21135,  8396, 21794,
         19497, 15089,  2367,  5522,   208, 15863, 22055, 16050, 25249, 18999,
         27156, 20346, 17171, 12845,  1498, 10609, 27483, 14177, 26882, 17155,
         23221, 21011, 16644, 11622,  3840, 14538, 24682,  1939, 23862,  8241,
         13007, 15350, 10014, 25546, 27617,  3193, 17902, 15356,  5248, 26794,
          1492,   244, 24587, 21731,     0,     0,     0],
        [    1, 12196,  9580,  1600,  2238, 12637,  2890,  3008,  3055,   813,
          3059, 10232, 12196,   525,  3429,   657,  7689, 23358, 23972, 12637,
         21268, 21827, 13919,  3055,  8400, 23972, 12637,  8001, 23337, 17581,
          3056,  7790, 21269,  4358, 13626, 12945, 21457, 13766, 26599, 17167,
         18114, 16898,  6129, 10302, 12196, 27314,  2438,  2193, 16502, 25122,
          5313, 21269,  3055,   657,  7689, 26338,  3637,  1278, 21269,  5077,
           657, 10711, 17171,  9127, 23358, 23972, 12637,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  2438,  2929, 17083, 11482,   867, 27479, 16794,  1685, 24346,
         26161,   770, 24353, 25639, 19830,  8879, 27479,  4574, 17352, 16794,
         14070, 18673, 27483,   168,  2929, 17083,  9141, 24985,  2690, 27317,
          2929, 17083, 10494, 14606, 18056, 26377, 12648, 26161,  9293, 16789,
          2367,  9157, 21874,  9085, 18056, 16185, 18999, 27483, 15024,  9157,
         12341,  8255,  1702,  2929, 17083, 23888,  1705,  2032,  2929, 17083,
         18676,  4973, 19788, 24585,  3966,  9157, 24346, 27317,  3966,  8446,
         25062,  2690, 15731, 18056, 26161, 21874, 27479, 16794,  4850, 15731,
         15731, 19939, 27483, 12341,  2369,  1705, 24789,  2367,  9165, 27479,
         22340, 19873,  2438,  1582, 24985, 25062, 11570, 17353,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 21158,   559, 27115,  5862, 22052, 24938, 11471,  9266, 24938,
         27483,  8761,  1042, 20461,  4031, 17245,  8446,  7033,  3683,  8486,
         17768, 24797, 21135,  2536, 18481, 22513,  9127, 21135, 24912,  3375,
         25593, 14036, 17408,  1708, 11570,  7404,  6531, 14600, 18967, 23541,

 78%|███████▊  | 87/112 [00:06<00:01, 14.23it/s, loss=2.1]

tensor([[    1, 13793,  4255,  ...,     0,     0,     0],
        [    1,  4823, 11818,  ...,     0,     0,     0],
        [    1, 19619, 24317,  ...,  2387,  1493,     0],
        [    1,  6272, 24939,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1690, 22.2327, -0.3376,  ..., -1.3720,  0.4147,  0.5955],
         [-3.1983,  0.3249, -1.7402,  ..., -3.1118, -2.0556, -0.0981],
         [-5.1511, -2.8775, -2.1663,  ..., -4.1853, -3.5835, -0.8948],
         ...,
         [-3.6720, -1.8801, -1.8711,  ..., -3.1922, -1.9758, -1.0820],
         [-3.6666, -1.7762, -1.8353,  ..., -3.1483, -1.9139, -1.0293],
         [-3.6167, -1.8153, -1.7992,  ..., -3.0080, -1.8560, -0.8999]],

        [[-2.8379, 22.0567, -0.5792,  ..., -2.1814,  0.2819,  0.4843],
         [-3.7261,  0.5209, -1.5617,  ..., -3.6876, -1.1123, -0.8692],
         [-7.4914, -4.3072, -3.5825,  ..., -7.1354, -2.4223, -2.3751],
         ...,
         [-2.5871, -1.2364, -1.4299,  ..., -2.3212, -1.3253, -0.7522],
         [-2.6410, -1.2041, -1.4250,  ..., -2.3221, -1.3016, -0.7103],
         [-2.6851, -1.3523, -1.4521,  ..., -2.2942, -1.3132, -0.6477]],

        [[-1.9599, 22.7761, -0.1865,  ..., -1.2205,  0.6144,  0.5483],
         [-4.3317, -1.6682, -1.7599,  ..., -4.7613, -2.5111,  0.6516],
         [-6.6525, -2.7461, -3.0914,  ..., -6.8752, -3.4072, -2.2395],
         ...,
         [-4.7677, -3.3515, -1.2558,  ..., -4.0759, -1.3785, -1.7292],
         [-2.3009, -3.1913, -0.8474,  ..., -1.9989, -0.3985, -0.0670],
         [-1.6086, -0.6940, -1.1520,  ..., -1.3633, -0.6824, -0.7407]],

        [[-2.4604, 22.3347, -0.4043,  ..., -1.8300,  0.4704,  0.4038],
         [-4.8336, -1.9135, -1.7777,  ..., -4.4056, -1.5527, -0.3157],
         [-2.2081, -3.9292, -0.7588,  ..., -1.8825, -0.1405, -0.1596],
         ...,
         [-2.4272, -1.1774, -1.5138,  ..., -2.3082, -1.1240, -0.8615],
         [-2.4544, -1.0804, -1.4892,  ..., -2.3014, -1.0900, -0.8134],
         [-2.4503, -1.1299, -1.4699,  ..., -2.2231, -1.0714, -0.7430]]],
       device='cuda:0') tensor([[    1, 13793, 17825, 11536,  1661,  5025, 14958,  2542,  5049, 27483,
         14857, 18620, 17810, 21118,  2542,  2910,  3098, 17825, 21344, 27338,
         20701,  2542, 16644, 16221, 13918,  1028,  5025, 10049,  2542, 21874,
          2656,  4597, 20578,  4667,  1416,  2542, 11691,  1458, 21344, 25385,
         11013, 14881, 24062,  4750,  1758,  2542,  9266, 24938, 22513, 17825,
          4273, 14958, 11678,  1028,  8441,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1,  4080, 21842, 19349, 17278,   241, 18606, 21344, 17069, 25358,
         11713,  4823,  5705, 17069, 21344, 17171, 15516,  6090, 20073, 11077,
         10373, 21344, 22049, 19282, 27338, 18497, 10776,  4081, 19243, 19349,
         17278,   241, 17069, 13934, 26882,  5552,   715, 21344, 11824, 27338,
         15447, 14106,  6102,  1897, 11822,  7206,  4759,  9522, 23080, 15645,
         15139, 13941, 21344, 15516, 26172,  9561, 14192,  9935,   130, 11713,
          4823, 11287, 10205,  4538,  4023, 17779, 17835, 11537, 15516, 22910,
         15238, 13639, 21344, 24938, 17037, 15516,  4815,  5705, 17069, 17777,
         26715, 14881,  8162, 11713,  4823,  4023,  9503,  5705, 17069,  7257,
         20698,  7790, 19282, 23641, 11713,  4823,  4023,  6149, 11822,  2448,
          4080,  7006,  5015, 15516,  1315, 21982,  3385,  4023,  3863, 11822,
          1897,  6149, 10905,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1, 17903, 19619,  8764,  1253,  2438, 24680,  3690, 16626, 27522,
          4366, 15038, 23975, 20824,   759, 18588,  5008, 16626, 27522,  5014,
         23760, 18289,  7024, 19619, 20824, 27488,   523,  5522, 25544, 25310,
           392, 23433, 16626, 27522, 19619, 16616, 19598,  8160, 25937,  6106,
          1492, 15038, 19619,  6554,  6200,  8160, 16626, 27522, 15038, 12177,
          3970, 24898, 14412, 18149, 10404, 17903, 10494, 10609, 21248, 11471,
         26919, 25593, 26130,  1492, 23932, 14874, 15038, 24344,  9844, 16048,
         23428,  3290, 21344, 27488, 15038, 21245, 19619,  2367,  9771,  9024,
          7066, 21245, 14461, 27488, 20721, 27479, 17131,   757,  1706,  8687,
         19349, 21759, 16626, 27522, 16221, 26794, 15425, 19349, 25593, 18739,
         17389, 16626, 27522, 27115, 14596, 24824, 26919, 24789, 27326, 27488,
         25025,  2102, 23221,  4044, 11471, 26750, 20824,  1758, 23234, 19349,
         21759,  1537,  8275,  7311,  6881,  1492, 17155,  8794,  9214, 15038,
          2102, 23221,  8499,  4020,  8772, 19619,   539,  2436, 19596, 17131,
           269, 10205, 23657,  1758, 11658, 24845, 20824, 25025,  2102, 23221,
         27488, 21535, 24789, 19077, 14881, 17903,   561,  5522, 22487,  4901,
         19596, 14891, 24062, 23566,  8126, 21247, 20824, 21535, 16326,  1690,
          7977, 24435, 20037, 19619,  4961, 19077, 14059, 14606,  1801,  8627,
          1492, 24938,     0],
        [    1,  9266, 24938, 21530, 27338, 24482,  5921,  7822, 18056,  4457,
          4241, 16205,  2549, 26779, 24482,  5142, 17825, 10298, 26251, 16010,
         24482, 14177, 18982, 21323,  2374,  1461, 20982, 12968,  9179,  6193,
         13298, 22258, 24221, 13793,  2280, 16626, 15193,  6193, 24938,  1018,
         10611, 18739, 12081,  2436, 11932,  2690, 21517, 26779,  3346, 16205,
         11730, 18510, 18523,  1758, 19349, 22024, 24482,  5921,  7822, 10426,
          6193, 20982, 12968,   290, 16205, 11730,  1017,  2690,  7616, 21517,
          2690, 26172, 18530, 13793,  4384,  9184,  2530, 11543, 14096, 10426,
         24482,  5921, 16205, 14195,  9266,  3268, 15024, 25114,  2280,  5808,
         16205, 11730, 10205,  1758, 17189, 17131, 25114, 24482,  5921,   489,
          8461, 26953, 27299, 25173, 15268, 10121,  7822, 16205, 11730,  7604,
         15029,  4457,  7077, 18609,   558,  9179, 22236, 25098, 20571,  6516,
         18627, 22353, 16205, 11730, 13664, 20933,   196, 20643, 27338, 22645,
         19349, 22024,  1538, 22296,  9642,  9266, 16205, 11730, 11736,  7000,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]], device='cuda:0')
tensor([[    1, 16644,  5442,  ...,     0,     0,     0],
        [    1, 10002, 20732,  ...,     0,     0,     0],
        [    1, 12675,  2812,  ...,  9921,  8872,     0],
        [    1, 26161,   543,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.2754, 22.2351, -0.4162,  ..., -1.5233,  0.5915,  0.4830],
         [-4.6399, -0.2961, -1.0669,  ..., -4.2702, -2.4491, -2.0395],
         [-5.4743, -2.8774, -3.3348,  ..., -5.6123, -2.9178, -2.0269],
         ...,
         [-2.8514, -2.1407, -1.6512,  ..., -2.4471, -1.3579, -0.5580],
         [-3.3441, -2.5768, -1.9616,  ..., -2.9657, -1.6269, -0.6935],
         [-3.7077, -2.7770, -2.2070,  ..., -3.3784, -1.8212, -0.8484]],

        [[-3.2050, 21.9970, -0.9428,  ..., -2.3683,  0.0918,  0.3693],
         [-3.4078, -0.4908, -2.0000,  ..., -2.8946, -2.2126, -0.7231],
         [-4.2466, -0.5675, -1.7294,  ..., -2.8433, -1.3910, -1.6263],
         ...,
         [-3.3207, -1.7945, -1.8370,  ..., -2.7858, -1.5415, -0.4305],
         [-3.8059, -2.2140, -2.1492,  ..., -3.2964, -1.7871, -0.5490],
         [-4.1648, -2.4392, -2.4136,  ..., -3.7454, -1.9699, -0.6937]],

        [[-2.0149, 22.7680, -0.2948,  ..., -1.2464,  0.5857,  0.4620],
         [-7.9501, -1.3833, -3.8180,  ..., -7.9823, -4.2844, -2.4345],
         [-5.1896, -3.2615, -1.6434,  ..., -4.5441, -1.9636, -1.2037],
         ...,
         [-2.5017, -1.3009, -0.4282,  ..., -2.3536, -1.6673, -0.6175],
         [-7.2003, -4.2656, -3.4657,  ..., -6.5065, -3.2675, -1.9388],
         [-3.0499, -1.9852, -2.3025,  ..., -2.6989, -1.5839, -1.2229]],

        [[-2.8928, 22.1336, -0.7169,  ..., -2.2584,  0.2357,  0.3224],
         [-5.2726, -2.5544, -2.8766,  ..., -5.6165, -1.7657, -1.1748],
         [-4.9724, -1.8897, -2.9338,  ..., -5.5425, -1.6848, -2.1156],
         ...,
         [-3.1869, -2.0102, -1.7053,  ..., -2.6527, -1.6437, -0.4632],
         [-3.6197, -2.4071, -1.9894,  ..., -3.1077, -1.8557, -0.5634],
         [-3.9539, -2.5944, -2.2354,  ..., -3.5201, -1.9948, -0.7078]]],
       device='cuda:0') tensor([[    1,   168,  9184, 24944,  4199, 17220, 17084, 18194,  4179, 21344,
         16644,  5442, 13534, 25614, 18982, 16221, 26426,  9984,  4842, 26426,
          9984,  2436,  3401, 17725, 19580, 16205,  4179, 21533, 16644,  5442,
         15425,  4845,  5315,  1617,  2455, 21254, 16292,  8741, 16177, 26426,
          9984, 15093,  9673, 25627, 17171,  8396,  2438, 26426,  9973, 19362,
         25483, 20327, 12274, 22513,  7839,  1358,  1017, 18450,  3429,  9260,
         19003, 24329, 20108, 11227, 12777,  6672,  4842, 26426,  9984, 19307,
           744, 19138,  9854, 23888, 19123, 22952, 18491, 15663, 27406,  2929,
         16740,  9973,  5823,  2822,  6392, 26426,  9984, 23777, 10000,  4842,
         14317,  7839,  1358,  4759, 11392, 19003, 24326, 16654, 24916,  4842,
          8644,  5025, 18266,  1272,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 12838,  4586,  7706, 23958, 24093,  8111,  4586,   952, 20989,
         21344,  3970, 15089,  5831, 17185,  6871, 25481,  3018, 24789, 25481,
         26919, 27292, 10111, 10456, 25481, 21685, 13657,  8111, 18481, 26919,
         10998, 14888, 10456, 26424, 26161, 12838,  3656,  3061,  7445, 21685,
         22405, 25481, 21344,  6364,  9027, 18094, 26919, 27338, 27115,  8111,
           759, 18481, 26919, 14888, 24209,   952, 22564, 25593, 27466, 21859,
         26986, 17100, 13657,   952,  5522, 13663, 21344, 23958, 25481, 16177,
         27292, 26882, 12838,  9444, 10885, 21078, 10002, 10866, 22405, 26424,
          8111, 23090, 27115,  2514, 14821, 10172, 16295, 10609,  3018,  6445,
         11377,  3454, 21344, 19867, 19867, 11013,  9973, 17171, 24509, 27292,
         19867, 19867, 11013, 21135,  8875,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  2215, 17181, 22307,   759,  4051, 21344, 22528,  2438, 19880,
         18056, 26935, 17181, 27479, 19003, 21344, 16205, 21096,   290, 15024,
         20660, 27299, 11013, 19892,  5218, 17181, 22308, 21323, 10468, 17279,
         18940, 27338,  1321, 24938,  4285, 11986,  8868,  4199, 20734, 17084,
         22308,  4734, 21344, 10718, 16927, 18056, 26183,  3135,  7453, 12648,
         17181, 22308,  1674, 22306, 23143,  3123, 14023,  8396,   444, 17181,
         22308,   412,  5218, 10298, 22309, 14437, 24938, 26185,  9839, 17282,
         10301, 17181,  3434, 19307, 18673, 10711, 18056,  8610, 14606,  4285,
         10245,  3434, 17181, 27479, 20476, 12341, 10711,  9537, 18867,  3118,
         18056, 23143,  2690,  3434, 10247, 17181,  9074, 21804, 12249, 24116,
           759, 22340,  1674,   874, 18056, 23144, 20929, 19727, 10468, 11003,
          3429, 17181,   744, 10885, 25639, 18678, 22303, 17181,   168,  9141,
          4687, 12634, 15425, 20658, 10711, 20485, 26850, 20660, 16221, 17181,
         22308, 14323,  7257, 27290, 24938,   168, 20525,  3744, 21854,  9260,
         21351,  2344, 22887,   744, 24797, 16010, 23147, 17181,  4285,  4750,
          3118, 26686, 19437,  4850, 10190, 22307, 12927, 10245,  3433, 24111,
         11687, 23936, 15024, 15516, 18877, 22303, 17181,  1690,  7925,  3434,
         25608, 18940, 14376, 27212, 10289, 15024, 18056,   759, 26183,  7664,
         10205, 11536,  9923,  8437, 20287,  5549,     0],
        [    1, 26161, 19248,  4080, 16735,  9494, 24036, 11290,  7566, 20659,
           543, 12388,  7623, 16735,  4080, 27292, 24036,   543,   198, 22453,
          8839,  7192, 20270,   874, 16010, 17635, 20659, 19195, 19123, 23636,
         24036, 19531, 21344, 12389,   874, 16010, 17635, 19303,  1595, 22448,
         14193,   731,   543, 12388,  7623,   543, 27314,  9639, 13919, 24014,
          3996,   543, 11472, 11174,  8984,  7945,   178, 12860, 26161, 23857,
          9496, 14177, 22057, 15024,  8214, 11736, 22513,   543, 27292, 11013,
         19915, 20501, 12779,  5036, 24938, 21552,   543, 21874, 15024,  8396,
          8149, 17834,   896,  8960,  3517, 16735, 26327, 13498, 12430, 19098,
          5370,  2808,   543,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  6846, 16379,  ..., 15997,  3315,     0],
        [    1, 12915, 14568,  ...,     0,     0,     0],
        [    1,  9283,  2386,  ...,     0,     0,     0],
        [    1,  7039, 16747,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.4128, 22.5921, -0.2763,  ..., -1.6900,  0.5140,  0.3449],
         [-8.5070, -6.6184, -5.2400,  ..., -8.0982, -2.8202, -4.0635],
         [-0.6221, -1.1687, -0.0380,  ..., -1.0582, -0.7612,  0.1559],
         ...,
         [-5.3811, -3.9613, -1.5198,  ..., -5.6664, -3.0974, -1.0348],
         [-3.3482, -4.4184, -1.1188,  ..., -2.6718, -1.5511, -1.3209],
         [-1.6616, -1.6675, -1.0605,  ..., -1.6153, -0.7599, -1.1473]],

        [[-2.0434, 22.3420, -0.2958,  ..., -1.3337,  0.6228,  0.7866],
         [-2.1252, -2.1229, -1.7503,  ..., -2.4556, -1.2352, -0.3975],
         [-0.9333,  1.1259,  0.5729,  ..., -0.6808,  0.3298,  0.9994],
         ...,
         [-2.7171, -1.0816, -1.3484,  ..., -2.3200, -1.4295, -0.4986],
         [-3.0388, -1.6192, -1.4643,  ..., -2.7143, -1.6400, -0.6407],
         [-3.2287, -1.9429, -1.5686,  ..., -2.9944, -1.7579, -0.7633]],

        [[-2.1343, 22.0737, -0.4372,  ..., -1.6883,  0.5241,  0.6609],
         [-3.0126,  0.7719, -0.9733,  ..., -2.4371, -1.9300, -0.5183],
         [-5.7045, -1.6929, -2.0468,  ..., -5.7147, -2.4829, -1.1509],
         ...,
         [-2.5896, -0.8232, -1.2811,  ..., -2.2976, -1.2693, -0.3619],
         [-2.8581, -1.2998, -1.3726,  ..., -2.6574, -1.4853, -0.4851],
         [-2.9934, -1.5499, -1.4509,  ..., -2.9050, -1.5926, -0.5786]],

        [[-2.5337, 21.9475, -0.7249,  ..., -1.7251,  0.1691,  0.6995],
         [-4.7997, -4.3724, -2.3448,  ..., -5.7532, -1.7279, -1.5715],
         [-5.8154, -2.1210, -1.7928,  ..., -5.4303, -1.0893, -1.2587],
         ...,
         [-2.8512, -1.4407, -1.1976,  ..., -2.2176, -1.4452, -0.3956],
         [-3.0707, -1.8853, -1.2488,  ..., -2.4989, -1.6269, -0.5324],
         [-3.1497, -2.0813, -1.3142,  ..., -2.6773, -1.6996, -0.6227]]],
       device='cuda:0') tensor([[    1, 12285,  9157,  6846, 15802, 16379, 21344, 24847, 10301,  4035,
         14881, 27090, 14885, 24720, 16889, 26266,  8801,  2797,  8950, 14290,
         16379, 21344,  9157, 18304, 26818, 24720,  2847, 12284, 16178,  8111,
         27529, 14948, 21874, 27314,  9266,  2168, 22162,  4899, 15508,  4067,
         19971, 19971, 13813, 26713, 13813, 26715,  3251, 24291, 21344, 21995,
         19867, 17078, 26266,  8801, 23790,  9452,  8981,  7093, 16035, 26872,
         16379, 25025,  2102, 27314, 22023, 15191, 19151, 16379,   759,  6282,
          6200,  3798,   839,   261, 20080, 27196,  2168, 22162,  6600,  8774,
         20609,  3798,  3118, 12845, 16379, 21344, 24823,  5658, 16521,  9161,
         25382,  8774,   759, 11287,  9157,  9157, 16626,  8059,  2168, 22162,
         21247, 16626, 14290, 12284, 16379, 21344, 13299,  4035, 27290,  9157,
          5321, 14795,  2750, 23818, 12226, 25593, 22942,  6015, 21154,  9157,
         21827, 10885, 10494, 17132, 19839, 24789, 24720,  4418,  4457, 22436,
         22870,  8774,  2847, 12284,  3545,  8111, 27529, 14948, 10061,  8743,
         17450, 27499, 12516, 21904,  9841, 19220,  9266, 15602, 11839,   259,
         21282, 18254, 21344, 13649, 16521,  9366, 10287, 13188,  2168, 22162,
          8446,  9844,  2659, 27245,  5567,  9157,  2797, 17171,  4431,  8112,
         14431, 23645, 21610, 24718,  3958, 22862,  4502,  2168, 22162, 18481,
          9157, 20080, 27196, 17078, 16654,  2367, 24787, 19859, 26266,  8801,
           265, 17171,  8950, 16892, 22513, 27483, 17131, 12845,  3844,  2696,
         21630, 12284,  3798, 12737,  9165,  3798, 15024, 16796,   260,  3798,
           260, 21344,     0],
        [    1, 16205,  9274,  8761,  6361,  1855,   241, 18620,  7693, 24657,
         16205, 22161,  9181, 15783,  2472, 16589,   759,  1768, 16791,  1160,
           759, 19681, 11630,  5522,  3106,  9757, 12777, 18099,  8437, 12168,
          5549,  5674, 19787, 16205,  9274,  9266, 26935, 12915, 22571, 16050,
           744,  7955,  6197,  9179, 20701, 26161, 23403,  9274, 26403,  4003,

 79%|███████▉  | 89/112 [00:06<00:01, 13.33it/s, loss=1.69]

tensor([[    1, 21158, 20255,  ...,     0,     0,     0],
        [    1,  9983,  5522,  ...,     0,     0,     0],
        [    1,  9984, 27115,  ..., 21248, 13027,     0],
        [    1,  7282, 17204,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.4122, 21.8894, -0.2903,  ..., -1.8278,  0.4492,  0.4786],
         [-7.6435, -3.3690, -2.3388,  ..., -7.8888, -3.9941, -1.4813],
         [-4.5929, -4.9305, -1.4403,  ..., -3.7605, -1.9093, -0.9809],
         ...,
         [-2.3458, -0.8342, -1.3181,  ..., -2.3846, -1.3827, -0.4182],
         [-2.2669, -1.0529, -1.3430,  ..., -2.2303, -1.2871, -0.5620],
         [-2.2300, -1.3317, -1.3438,  ..., -2.1119, -1.2027, -0.6487]],

        [[-1.8626, 22.6261, -0.1369,  ..., -1.1297,  0.7121,  0.6489],
         [-3.6093, -3.0231, -1.5412,  ..., -2.5257, -1.8215, -1.1550],
         [-3.7802, -3.1917, -1.7299,  ..., -4.0215, -1.7434, -0.5960],
         ...,
         [-1.7834, -1.0738, -1.5742,  ..., -1.9227, -1.0103, -0.9710],
         [-1.7404, -1.2780, -1.6280,  ..., -1.8164, -0.9654, -1.0956],
         [-1.8036, -1.5880, -1.6648,  ..., -1.7941, -0.9518, -1.2100]],

        [[-2.3295, 22.5977, -0.4654,  ..., -1.5962,  0.5694,  0.4943],
         [-1.7432,  0.2860, -0.0253,  ..., -1.1320, -0.2287, -0.2505],
         [-6.4296, -2.9404, -2.2643,  ..., -5.5602, -3.3738, -0.4850],
         ...,
         [-4.7518, -1.9292, -1.7200,  ..., -5.2978, -1.7364, -1.1214],
         [-0.4450,  0.0985, -0.5371,  ..., -0.7098,  0.8397, -0.5511],
         [-2.2681, -1.7655, -1.9433,  ..., -2.3242, -1.0375, -1.4121]],

        [[-2.1783, 22.6962, -0.1951,  ..., -1.4864,  0.5189,  0.6409],
         [-3.9818, -4.3734, -1.4071,  ..., -3.2001, -1.7299, -1.0379],
         [-5.5485, -3.3104, -2.1174,  ..., -5.2237, -2.8743, -1.3088],
         ...,
         [-2.1671, -1.3383, -1.6693,  ..., -2.2054, -1.2219, -0.9789],
         [-2.1229, -1.5426, -1.7172,  ..., -2.0807, -1.1644, -1.0962],
         [-2.1441, -1.8216, -1.7464,  ..., -2.0190, -1.1314, -1.2008]]],
       device='cuda:0') tensor([[    1,  2536, 21344,   748, 26713, 15675, 27091, 20256, 19230, 19731,
         18482, 24177,  6129, 27091,  4960,  6129,  9046, 14566, 25947,  4538,
         25264, 27122, 19731, 23566,  4035, 21783,  6129, 27091, 21344,  6713,
         10320, 19731,   527,  2536, 20256, 24797,  2428, 19731, 21697,  3656,
          2019,  9046,  2102, 23221, 14064, 24824,  2536, 26713, 15675,  4199,
          8552, 13175, 27091,  5049,  4559, 23566,  6713, 19731, 24884, 19731,
         21344, 27338, 12252, 17077,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  8458,  9973, 10426, 18477, 11158, 19077, 25639,  9987, 10426,
         24787, 10426, 19867,    58, 22340, 14564, 25564, 11158, 19867,   362,
          3139,  8646,  7369, 25505, 15268, 10130, 16654,  9984,  5168, 25593,
         12339, 19867,  4699, 16654, 10130,  5168, 11158, 24040, 14964,  7369,
         15089, 25505,  9984, 24294,  6846,  6775,  5248,  9260, 24891, 25025,
          2102, 16644, 26867, 15268, 21859,  5754, 18467,  6672,  9984,  2171,
          4820,  7639,    58, 24344, 17949,  9973,  1154,  5167, 21535, 11395,
          3630, 23632,  6944, 11158,  7573,  2663, 19814, 22030, 23388, 16654,
         21135,  9984,  5168,   732,  6670, 21086,  6621, 10582, 25564,  9165,
          9984, 10090, 24938, 16654, 20769, 25268, 19501, 21731, 11158, 17081,
           251, 14373, 14367, 14795, 18414,  5522, 14881,  9984, 19119, 22687,
          8623, 24792,  7369, 25505,  5167,  6670, 24823, 11158, 17081, 19119,
          4049, 23388, 25639, 25564, 18320, 14795, 14373, 18414, 18581, 21535,
          7369, 25505,  9984,  5522,  2169, 14177, 12634, 16185, 11158, 21535,
         25279,  4899, 21790, 19501,  2436, 21726,  4323, 20286,  6759,  8264,
            58, 19933, 11158, 22445, 16522, 24823,  8623, 14428, 10426, 10205,
         18581, 14586, 20906,  9973,  8501, 10426,  4541,  4541,   264,  9157,
          8332,  3990, 23796,  7573,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  2662, 19814,  1458, 21344, 24884,  9984, 10233,  7839,  1358,
         26547, 27338, 24040,  7573,  9577, 16205,  7210, 21344,  9983, 19809,
         11392, 19501, 10582, 24534, 16654, 10130, 24992, 16654, 10130,  7574,
         11536, 11392,  6308, 26426, 22987, 25116,  2662, 19814, 11624,  7950,
          7573,  9577, 26719,   602,  2376, 26389,  9131, 20575, 16654, 27479,
         16654, 10130,  7573, 18483, 23428,  4750, 16654, 10130,  7574,   759,
            58, 23633, 12040,  6071,  7600, 14029,  9984,  6669, 19361,   290,
          6377, 11392,  6308,  9984,  9905, 26541,  2662, 19814,  3630,  9858,
         12635, 16522, 13577, 19174, 18449,  2662, 19814,  1768,  9265, 12226,
         22952,  4875, 25116, 16513,  1768, 11158,  7573,  9577,  4241,  9905,
          9165,  9984,  2662, 19814,  6890,    58, 23633, 10077, 11392, 19501,
          6071, 25116, 11158,  7573, 11536, 10077, 26193,  2663, 13928,  2032,
         24534, 14881, 17254, 13928,  6890, 11536, 22571, 24944, 16221, 25008,
          7573, 22952, 19940,  1017, 27338, 26183, 24534, 16654, 10130, 18492,
         21973, 18955,  5025,  5216,  7841, 22340, 13927, 26311, 25116,  1017,
          7573, 18483, 24534, 27338, 15093,  8047,  9288, 15941,  5883,  7573,
         24532, 15398,  4931, 10582, 16221, 16221, 19501, 14604,  9984, 16177,
         18274, 19854,  3627,  5883, 24534, 14352, 16205,  7210,   290, 14891,
         24062,  6944,  5522, 21484, 11392,  6308, 16528, 12226,    55, 19994,
         17189,  7574, 22743,  6944,  9283,  3543,     0],
        [    1, 21344, 19123, 14891, 26816, 16654, 27479,  6412,  5248,  6677,
         24532, 10298, 18056,  9727, 16310, 26426, 12040,  3890, 18869, 27338,
         22055, 13498, 24534, 25354, 26786,  4766, 27479, 24869, 27479, 22340,
         24532, 19452, 18056,  4079, 16262,  5248, 23633, 14414, 26786, 26713,
          6677, 24938,  1092, 25352, 18869,  5271,   168,  3890,   914, 27035,
         22262,  5216, 24532,  8615, 10715,  5216,  7841,  9923, 18242, 27479,
           168,  9141, 20287,  3978, 17301,  3890, 25503, 24828, 24534, 14629,
         12341,  8637, 10050, 13927, 26311,  1028,  5216,  7841, 22340, 23645,
         27479, 20331,  6775,  4899, 25273, 20775, 19123, 26818, 18056, 12629,
         13076, 13226,  5216,  7841,  1458, 25025,  2102, 16644, 26867,  8801,
         22345, 13943, 24532,  9923, 11472, 22309, 16654, 27479,  8919, 10718,
         24532, 12224,  2562,  7573, 15425, 14400,  5811,  7024, 25567,  6775,
         26426, 19998, 18692, 16310, 18483, 22340,   759, 12225, 22055, 23124,
         13498, 24534,  4842, 12605, 15663, 11365, 17614,   867, 17367, 18692,
          6677,  4745, 15922, 24579,  6775, 16310, 26426, 18483,   759, 18673,
           770, 27046, 18869, 16205, 10045, 27338, 22346, 16626, 27411, 15425,
         20476,  3798,  7317, 27338, 24368, 13502,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 22524,  4283,  ...,     0,     0,     0],
        [    1, 26665, 15134,  ...,     0,     0,     0],
        [    1, 16626, 21229,  ..., 20899, 21344,     0],
        [    1, 13210, 15422,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.3584e+00,  2.1867e+01, -5.4110e-01,  ..., -1.5157e+00,
           5.3825e-01,  8.5987e-01],
         [-3.9240e+00, -2.0565e-01, -2.0626e+00,  ..., -3.1725e+00,
          -1.7165e+00,  1.4308e-01],
         [-2.6844e+00, -1.1528e+00, -1.2090e+00,  ..., -2.4110e+00,
          -1.0098e+00, -9.5673e-01],
         ...,
         [-2.1175e+00, -2.5437e-02, -1.3097e+00,  ..., -1.5970e+00,
          -1.1219e+00,  2.1046e-02],
         [-2.2036e+00, -5.6099e-01, -1.3464e+00,  ..., -1.7177e+00,
          -1.1881e+00, -2.9548e-02],
         [-2.0959e+00, -7.8564e-01, -1.2939e+00,  ..., -1.6505e+00,
          -1.1690e+00, -4.4996e-02]],

        [[-2.4700e+00,  2.2368e+01, -5.7031e-01,  ..., -1.6928e+00,
           3.7376e-01,  6.9584e-01],
         [-7.3351e+00, -5.3502e+00, -3.1753e+00,  ..., -7.1715e+00,
          -3.3535e+00, -2.8078e+00],
         [-5.8715e+00, -3.3085e+00, -3.0556e+00,  ..., -5.5593e+00,
          -2.1033e+00,  9.2317e-02],
         ...,
         [-3.2366e+00, -4.5442e-01, -1.8694e+00,  ..., -2.8144e+00,
          -1.6598e+00, -4.1392e-01],
         [-3.2663e+00, -8.9513e-01, -1.8728e+00,  ..., -2.8795e+00,
          -1.7022e+00, -4.5529e-01],
         [-3.1957e+00, -1.1156e+00, -1.8239e+00,  ..., -2.8601e+00,
          -1.7146e+00, -5.0250e-01]],

        [[-2.5979e+00,  2.2512e+01, -5.8117e-01,  ..., -1.9052e+00,
           4.4785e-01,  3.1255e-01],
         [-3.4849e+00, -1.3586e+00, -1.4929e+00,  ..., -3.1870e+00,
          -5.8406e-01, -1.5685e+00],
         [-4.3397e+00, -2.3873e+00, -2.0248e+00,  ..., -4.8318e+00,
          -2.5749e+00, -8.5115e-01],
         ...,
         [-1.7781e+00,  2.3874e+00, -1.3980e+00,  ..., -1.1573e+00,
          -1.0824e+00,  1.8889e-01],
         [-4.6426e+00, -4.0253e+00, -1.6926e+00,  ..., -4.6033e+00,
          -1.7144e+00, -2.1934e+00],
         [-2.1029e+00, -1.0077e+00, -1.5448e+00,  ..., -1.8953e+00,
          -9.6146e-01, -9.3103e-01]],

        [[-3.4313e+00,  2.1451e+01, -9.7322e-01,  ..., -2.6842e+00,
           3.6347e-03,  7.5499e-02],
         [-3.6132e+00,  4.4983e-01, -2.7700e+00,  ..., -3.9793e+00,
          -2.2513e+00, -1.7263e+00],
         [-4.4131e+00, -1.7204e+00, -1.9418e+00,  ..., -4.0401e+00,
          -2.8542e+00, -1.0748e+00],
         ...,
         [-3.1294e+00, -7.3273e-01, -1.8498e+00,  ..., -2.5849e+00,
          -1.6225e+00, -5.0477e-01],
         [-3.0774e+00, -1.1789e+00, -1.7954e+00,  ..., -2.5807e+00,
          -1.6347e+00, -5.0913e-01],
         [-3.0161e+00, -1.4289e+00, -1.7260e+00,  ..., -2.5720e+00,
          -1.6473e+00, -5.3565e-01]]], device='cuda:0') tensor([[    1,   535,  2367, 18664,  4671, 11472, 25199, 13816, 15109, 14332,
         13571, 15269, 18363, 13934, 27479, 18304,  1702,  2367,  9028, 18664,
         26555, 18092,  2147, 16626, 27522,  2847,   535, 19830, 16924, 17171,
         25639,  6163, 11472, 10147,  2883, 17047, 18664, 23411,  4283,   535,
         15123, 16310,  8552, 13217,  2995, 22524,   491,  5049,   535,  3384,
         17189, 18664, 21589, 27150,  2367, 16626,  1353, 10553,  2995, 19232,
         10553, 27150, 22524,   535, 11545, 25822, 14502,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 26665, 15134, 21344, 12771,  4386, 18450, 19372,  3887, 25360,
         22590,   703, 26665, 15134, 13636, 17075, 27285,  3930, 16310, 21365,
         26867, 13998, 21869,  9522, 26665, 15134,  3929, 16310, 20370, 23636,
         15152, 13998,  9145, 26774,  5555,   703, 26665, 15134,  6179,  5910,
         19457, 26752, 13789,  5586, 26665, 15134, 22036, 11392, 23389, 27338,
         18739,  7868,  8458, 12038, 27285, 25077, 12315, 15687,  9193, 16978,
         26665, 15134, 23203, 10822, 27016, 25025, 11316, 14850, 10861,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 16626, 21229, 15119,  9543, 16464, 14457, 25639,  4766,  9522,
         11570, 17083, 21535, 16626, 21229,   558, 20067, 16924, 22122, 15120,
          8358, 27479, 21229, 15398,  3787, 11570, 21835, 10426, 15119, 20175,
         13934, 20578, 20802,  2403, 13059, 21344, 16626, 21229, 19226,  6943,
         25503, 16796,  8385, 16464,  1101,  4362, 24235, 14282, 11915, 16838,
         12614, 26870, 25639, 16326,  7803, 17015, 26515,   732, 10205, 15121,
          8160,  5549,  1154, 11570, 17083,  3973, 15119,  1183, 16205, 20899,
         22023,  6846, 20178, 15120,  3049,  5523, 16825, 26945, 14542, 21344,
          5148, 16626, 13988, 12417,  4368, 14252, 20176, 23203, 15089, 20899,
         21344, 26914, 16626, 15119, 20195,  2245, 27338, 22450,  6651, 20470,
         19360, 13934, 13295,  5754, 17825,  4813, 23441, 22450, 20930, 16626,
         19092, 12233, 20877, 15123, 12725, 20636,  7036, 21044, 20176,  1487,
         12073,   241, 16988, 20470, 24130, 22122, 15120, 11570, 17083, 13498,
         15024, 19246, 14566, 18056, 27040, 20877, 15123,  3012, 14566, 24352,
          3785, 11781, 20882,  5569, 16208,  2403, 21344, 25503, 16796,  8385,
          4362, 16521, 11570, 17083,  1183, 15123, 16626, 21229,   759,  3517,
         19531, 17779, 13185,  4813, 11781, 20882,     0],
        [    1,  9626, 10776, 23745, 15422,  1939, 25593, 27483, 21344, 18777,
         27314,  1061,  7289,   488,  4199,  6728, 18777, 21535, 15084, 13210,
         23745, 15422,  9626, 10776, 24352,  1939, 23863,  1401, 24945, 15422,
          5522, 24346, 18777, 21344, 12918, 13210,  9293, 15422, 17155,  6444,
         26183,  7473, 21535, 24344, 14101,   244,  5236,   699,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 13176,  6508,  ...,     0,     0,     0],
        [    1, 27017, 18918,  ...,     0,     0,     0],
        [    1,  9923,  9963,  ...,  6573,  1702,     0],
        [    1, 14296, 10517,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.8483, 22.5284, -0.2071,  ..., -1.1920,  0.6747,  0.8083],
         [-2.5892, -1.3526, -0.4627,  ..., -2.7041, -1.8695, -0.6583],
         [-5.9215, -3.3928, -1.9888,  ..., -5.7794, -2.7914, -1.6452],
         ...,
         [-1.2294, -0.5324, -1.0110,  ..., -0.7876, -0.7660, -0.0703],
         [-1.1012, -0.1092, -0.9538,  ..., -0.6208, -0.5961, -0.0378],
         [-1.2268,  0.1655, -1.0066,  ..., -0.7454, -0.5610, -0.1736]],

        [[-2.3680, 22.4003, -0.2889,  ..., -1.6302,  0.4180,  0.4968],
         [-4.0487, -1.3429, -0.4663,  ..., -3.5656, -1.4829, -1.9429],
         [-2.3227, -1.4018, -1.3966,  ..., -2.4449, -1.0028, -1.2590],
         ...,
         [-2.1969, -1.1971, -1.5270,  ..., -1.7663, -1.2785, -0.6116],
         [-2.1158, -0.8437, -1.4898,  ..., -1.6475, -1.1391, -0.5810],
         [-2.2586, -0.6261, -1.5431,  ..., -1.7786, -1.1127, -0.7045]],

        [[-1.3603, 23.0365,  0.0767,  ..., -0.7101,  1.0518,  0.8886],
         [-2.3444,  0.8907, -0.9061,  ..., -2.0686, -0.4320, -0.7695],
         [-4.6445, -2.7265, -1.9801,  ..., -4.2453, -2.7222, -0.6775],
         ...,
         [-3.5659, -1.3110, -2.2392,  ..., -3.1513, -2.1438, -1.1408],
         [-4.1258, -1.8050, -2.9776,  ..., -4.9095, -1.7247, -2.2486],
         [-0.6817,  0.4161, -1.1291,  ..., -0.4405, -0.1220, -0.4591]],

        [[-2.6775, 22.0757, -0.5537,  ..., -2.0397,  0.3868,  0.3326],
         [-6.6553, -3.8268, -2.4257,  ..., -6.4062, -2.7907, -1.3745],
         [-1.9959, -1.2019, -0.7430,  ..., -1.7467, -1.1054, -1.1248],
         ...,
         [-2.0339, -0.8127, -1.5453,  ..., -1.5313, -1.0579, -0.5280],
         [-1.9849, -0.4754, -1.5299,  ..., -1.4696, -0.9476, -0.5268],
         [-2.0620, -0.1780, -1.5613,  ..., -1.5396, -0.8923, -0.6259]]],
       device='cuda:0')

 81%|████████▏ | 91/112 [00:06<00:01, 12.80it/s, loss=0.963]

tensor([[    1, 18481, 16221, 22008, 21955, 21044, 16654, 14874,  9157,  7267,
          2992, 18713, 25755,  5386, 12380, 14809, 20903, 25564,  9266, 14795,
          6508, 23411, 13176,  6508, 27040, 13943, 21044, 18194, 17683,  5667,
         13146,  2007,  9194, 16617,  3905, 17171, 11561, 15255, 24360, 23430,
          9157,  3690, 18485,  7278, 24545, 11656,  9157, 16713,  7894, 23703,
         24756,  4216, 14431,  6508,  3690, 14551,  1458, 24935,  3389, 22030,
          5271, 16654, 21044, 18485, 27103, 27257, 20332, 20965,  5970,  4429,
          4093,  4240,  8781,  1042, 21044,  3389,  7705, 27262, 23424,  6508,
          5652,  5842,  9157, 14886, 27262,  6508,  2169, 25947, 14874, 23411,
         10301, 18879, 24352,  6051, 11956, 21045, 12560, 24063,  2929, 17083,
         11481, 25593, 27483, 13941, 18481, 22900, 17141, 23619, 26439,  8230,
         18472, 13943, 21044,  9194, 16617,  8666, 13146,  2007, 20273, 24255,
          4216, 14551, 21247, 27299, 20273,  8253, 25736,  6846, 24935,  3389,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 27479, 17131, 14795, 15179,  5307,  8111, 14128,  3859, 13939,
          1253,  9572, 24923, 11162, 19211, 27314, 25147, 21753, 19211, 13289,
         27017,  8616, 20654, 26669, 10298, 21131, 20850,  8111, 22571, 16465,
         17206,  3683, 21490, 13657, 16221,  8625, 24923, 11162, 10298,  3951,
         10298, 17860,  1758, 24788, 10395, 27381, 26713, 24364, 26818,   290,
          9572, 11287, 18056, 18475, 14128, 18056, 14317, 15139, 13177, 10549,
         21168, 14128, 24923, 11162,  9572, 14290, 14891,  8111, 16924, 24840,
         22274, 27017, 15858, 26293, 14876, 13934, 27479, 22571, 16465, 13633,
         12461, 19766,  8441, 10205, 10426, 10302, 14606,  5036, 18056, 14317,
         23079,  9572, 12838,  8951, 13657, 10609, 24787, 25161, 27017, 17171,
          8626, 15500,  8111, 23290, 24351,  9111, 21490, 10456, 21804,  8879,
         23433, 27435,  9266,  9973, 22571, 16465,  8458, 18482, 26717,  9266,
          3545, 23290, 18056, 14317, 13040, 14165, 15139, 13177,  9266,  4750,
         24364, 24788, 11286,  6612, 23007,   468, 17345,  7491, 19725, 21751,
         25581, 13934,  1661, 10298,  8111, 18467, 12153, 26424, 18481,  2514,
         24923, 11162, 24789,  8948, 18724, 14576, 11162, 10456,   290,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 17171, 13498, 12922, 13437,  9921, 26179, 23633,  6775, 12040,
          1584, 26426,  9146, 16202, 24967,  6775, 26168, 16310, 18483,  4750,
          1312,  8914,  4728, 24352, 14033,  1140, 12818, 15770,  2797,  6573,
         20108,  6582,  9923, 14564, 10456, 19290, 22987, 19501,  1586, 14568,
          6573,  5127,  5216,  5956, 22036, 22717, 24344, 25639, 17171,  4967,
         22665, 14568, 16221, 24534, 17171,  9921, 15687, 11286, 24213,  4689,
         21443, 24967, 10951, 26621,  3457,  3542,  1042, 12483,  6573,  8108,
          1702, 27148,  4000, 14568, 14317,  3670, 21810, 22591,  9663, 10395,
         21364,  1192,  8615,  5492,   770, 18028,  6573, 13964, 24840, 16050,
           517,  6676,  7987, 13916, 23632, 26919, 10456, 14568,  8913,  5127,
          9921,  9117,  9921,  8615, 10395, 21364, 23967,  5492, 16623, 25593,
          1705,  3978, 17171, 10287,  2367,  9771,  1702,  1042, 12483,  6573,
          8108, 25639,  6775, 19628, 24534, 13663,  5956, 27308, 22687,  6759,
         24534,  8383,  5445, 18689,  6577, 17597,  6775, 19628, 22030, 13964,
          5956, 19628, 25639, 26919, 21474, 19628, 22030, 26161, 13574, 23632,
          1127, 18056, 26713, 17953, 14564,  5371, 21344, 21780, 18689, 19628,
         22030, 10395, 21364,  8047, 13027, 26161,  9266, 19512, 25639,  1674,
         18147, 14258,  6775, 12040,  8359,  5216,  7841,  1458, 17296,  2219,
          3978,  5216,  7841, 22340, 13927, 26311, 10098, 17738, 16626,  9923,
         24532, 13964,  9634,  6102,  8441, 12040, 26426, 23634, 21771, 15514,
         18692,  6677, 15398,  6071, 14317,  1584, 23634,  3679,  8709, 26168,
          7447,  3978,  2367, 12484,  6573,  8108,  1702, 22742,  8141, 22695,
         18563, 27299, 11570,  3135, 16606, 17953,  9921,  3294, 27169,  4727,
         22487, 12652,  4747, 11392, 19501, 26426, 23568, 22742,  6676,     0],
        [    1,  7369,  2529, 21344, 18056,   759, 26172,  3548, 18270,  6759,
         26822,  9157,  8437,  6775,  3549, 11736, 21344, 13031, 18056,  8286,
         19533, 26170,  3548, 18267, 14070, 16048,  7369,  2529, 21344,  7615,
         20476,  3548, 18267, 26166, 13030, 21871, 12122, 12483, 10426,  9399,
          7369,  2529, 21344,   770,  5218,   783, 26170, 18267, 22194, 26280,
         16626, 10965, 24532, 14881, 18739, 10541,  7447, 16626, 10844, 14297,
         23793,  8286, 12703, 15922, 18267, 17578, 26822, 26170, 18267,  7369,
          2529, 21344, 10712,  7496, 18378, 15212, 12649, 25483, 16626, 24788,
          2219, 23428, 15024, 25354, 18267, 26170,  5294, 21344,  3548, 18270,
         26172, 16221,  3666, 15997, 27343,  8460, 14290,  6719,   783, 18673,
         15922, 18267,  8332, 17171,  8265,  3548, 11292, 13442,  6759,  9572,
         11469, 12341, 16221,  9452, 26183, 24534, 21344,  7369, 15645,  2529,
         21943,   417, 15922, 15425,  8286,  5216,  8163, 13784,  1042,  8777,
         10511, 23127,  4044, 15922, 18267, 26170, 22487, 23127, 16626,  6677,
          2890, 18378, 15212, 17171, 10456,  8501,  6721, 27379,   867, 27530,
         18056, 21344, 16177,   258, 15922, 18267, 16221,  5328, 26818, 18056,
         10844, 20327, 21344,  7369,  2529,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 25114, 14025,  ..., 22352, 22513,     0],
        [    1, 13311,  7599,  ...,     0,     0,     0],
        [    1, 10428,  8837,  ...,     0,     0,     0],
        [    1, 27085,  9283,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7158, 22.3371, -0.5763,  ..., -2.0971,  0.2949,  0.2141],
         [-1.9258, -1.8183, -1.6441,  ..., -2.4157, -1.1612, -0.6120],
         [-1.5050, -1.5801,  0.3114,  ..., -1.7873, -0.7051,  0.5752],
         ...,
         [-5.0822, -1.6705, -1.9445,  ..., -5.3799, -2.4978, -0.3764],
         [-7.8058, -2.7307, -3.5069,  ..., -7.4786, -3.8831, -1.8227],
         [-2.0080, -0.5218, -1.7440,  ..., -2.1665, -1.0573, -0.9542]],

        [[-2.3160, 21.8780, -0.3513,  ..., -1.5397,  0.4730,  0.7640],
         [-4.8055, -3.8401, -2.8964,  ..., -4.9464, -2.2767, -0.5880],
         [-5.3798, -5.2647, -2.1223,  ..., -5.3879, -3.2424, -2.0864],
         ...,
         [-1.8019, -0.2555, -1.0153,  ..., -1.5181, -0.9259,  0.0658],
         [-2.0702, -0.0473, -1.1493,  ..., -1.8009, -1.0905, -0.0296],
         [-2.3679,  0.2948, -1.3016,  ..., -2.0316, -1.2097, -0.1360]],

        [[-2.7046, 22.0615, -0.6833,  ..., -1.8756,  0.3873,  0.5485],
         [-6.9228, -1.9504, -3.6261,  ..., -5.8995, -3.4173, -2.1506],
         [-4.1254, -1.7142, -1.7778,  ..., -4.0738, -2.0205, -0.7776],
         ...,
         [-2.7365, -1.4046, -1.8683,  ..., -2.4332, -1.4040, -0.4220],
         [-2.9676, -1.2084, -1.9586,  ..., -2.6646, -1.5904, -0.4857],
         [-3.1757, -0.8526, -2.0432,  ..., -2.7848, -1.6863, -0.5589]],

        [[-1.3422, 22.8439, -0.0332,  ..., -0.6500,  0.7554,  0.8357],
         [-2.1804,  0.1675, -1.2520,  ..., -2.0696, -0.5394, -0.2381],
         [-7.0021, -4.5356, -2.8609,  ..., -6.2859, -3.6691, -1.6665],
         ...,
         [-1.7489, -0.5891, -1.2975,  ..., -1.4386, -1.0783, -0.0272],
         [-2.0740, -0.4323, -1.4415,  ..., -1.7692, -1.2855, -0.1520],
         [-2.3280, -0.0772, -1.5588,  ..., -1.9499, -1.3871, -0.2511]]],
       device='cuda:0') tensor([[    1, 16205, 11730,  8615, 21530,  1302,  2690,  1666, 24482,  5921,
         14888,  1018, 16005, 25114, 14025, 15645, 11730, 21535, 17825, 21511,
          2690, 10512, 23144, 24318, 26779,   744,  8458, 12274,  8634, 21535,
         10205,  1042, 13793, 10512, 10426, 17929, 11395, 24485, 16205, 11730,
         12525, 16010, 27338, 18524,  1758,  9800, 22024, 14317, 16662, 21639,
         20609, 26172,  5915, 10512,  2856, 20064, 24485, 16205, 11730, 21344,
           309,  2887, 14367,  2887, 14367,  7822, 18056,  4457,  4241, 16205,
          2549, 26779, 24482,  5142, 10512, 10298, 26251, 16010, 24482, 14177,
          2690, 14096, 27338, 23147, 20067, 10512,  2856,   290,  3301,  2690,
         21512, 24318,  3346, 12347, 24294, 10395,  1758,  9800, 22024, 16205,
         11730, 21344, 16205, 11730, 21344, 24788, 10995, 18626, 27338,   441,
         17388,  7822, 11736,  4199, 25335, 21835, 17902,  2704, 21344, 16798,
         25098,  9141,   288, 14881, 21517, 17929, 24482,  5921, 15398, 10738,
          5915, 25098,  2690,  5921, 11484,  9800, 19349, 22024, 11013, 11570,
         17083, 23144,  5522,  5915,  2690,   168,  9172, 12550, 27479, 14551,
         20746, 17795,  2690, 10426,  1154,  9156, 10512,  2530, 11543, 20067,
          2856,     0],
        [    1,  9141,  7599, 14850, 14952,  9260,  7909, 24294,   613,  9265,
          1539,  5388,   874, 23042,  2931, 26512, 14850,   179,  7599, 14850,
         25226,   912,  9260,  9626,  7909, 24294, 20097, 22742, 25639,  2032,
          8108,  9260, 19934, 23346, 15731,  7599, 14855, 13027, 26512, 25226,
         22720,  6441, 22023,  1531, 12249,   168,  9260, 25606, 23042,  5885,
         21960, 23877,   764, 13934, 16050,   168,  7909, 24294,   912,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1, 19003, 10428,  8830, 12668, 16008,  9862, 21344, 14564, 26822,
         26183, 10428, 20541, 19297,  6159, 20301,  6159, 20301, 21873, 13299,
         25076, 10351,   489,  8461,  5355, 21914, 12055, 10428,  2367, 26818,
          9612, 26161, 26384, 18439, 21909, 12055, 10428,  4254, 21344, 14566,
         26822, 22927, 19084, 12055, 25057, 10428, 17378, 12055, 26253, 10428,
         20541, 17377, 19003,  9297, 24641, 15605,  5883, 15093, 26251, 12055,
          2866, 21032, 19794,  1401,  9913, 15785,  3753, 23793,  8974, 20716,
         21914, 10428, 20541, 20716, 11540, 12055, 15268,    58, 21909,  2457,
          7219, 10428, 26170,  3789,  3580,  6161, 17571, 27314, 18662, 16465,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [    1,  8111,  3656, 13214, 27085, 14881, 14551,  1698, 20701, 12461,
          7719, 21490, 27085, 18481, 22513, 12460,  2423, 17047, 25062, 17795,
          9844,  5223, 25249, 16631,  8826, 26876, 27085, 27479,  7050, 12461,
         16299, 19084,  9480,  7790, 16050, 22414, 22331, 12461, 24147, 27314,
          5862,  9172, 27479, 17131, 15858,  8111,  1661, 12672,   496, 10859,
         26121, 20877,  1278, 21455,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]], device='cuda:0')
tensor([[    1, 13477, 14300,  ...,     0,     0,     0],
        [    1,  1140, 12818,  ...,     0,     0,     0],
        [    1, 18627, 11966,  ..., 23428,  3591,     0],
        [    1, 26611,  5915,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.4076e+00,  2.2152e+01, -4.9423e-01,  ..., -1.7840e+00,
           3.0030e-01,  6.9819e-01],
         [-4.3867e+00, -3.0735e+00, -1.5600e+00,  ..., -4.0753e+00,
          -2.0999e+00, -2.4389e-01],
         [-4.8778e+00, -2.6967e+00, -2.3718e+00,  ..., -5.2765e+00,
          -1.0854e+00, -1.6231e+00],
         ...,
         [-2.9438e+00, -1.7149e+00, -1.8556e+00,  ..., -2.8995e+00,
          -1.5881e+00, -8.1280e-01],
         [-2.7974e+00, -1.8779e+00, -1.7905e+00,  ..., -2.6626e+00,
          -1.4428e+00, -8.5375e-01],
         [-2.8848e+00, -2.1348e+00, -1.8223e+00,  ..., -2.6736e+00,
          -1.4403e+00, -8.7833e-01]],

        [[-2.6857e+00,  2.2393e+01, -6.4761e-01,  ..., -2.1165e+00,
           3.4511e-01,  4.2758e-01],
         [-1.1256e+00,  1.8081e+00, -1.5015e-01,  ..., -5.2942e-01,
           5.5789e-01, -9.8454e-03],
         [-4.1838e+00, -3.6898e+00, -1.8498e+00,  ..., -4.3298e+00,
          -2.3823e+00,  4.7770e-02],
         ...,
         [-2.7341e+00, -1.7758e+00, -2.0723e+00,  ..., -2.7654e+00,
          -1.3616e+00, -1.1658e+00],
         [-2.7112e+00, -2.0408e+00, -2.0813e+00,  ..., -2.6422e+00,
          -1.3016e+00, -1.2483e+00],
         [-2.7315e+00, -2.2589e+00, -2.0730e+00,  ..., -2.5938e+00,
          -1.2683e+00, -1.2361e+00]],

        [[-1.7260e+00,  2.2948e+01, -1.2186e-01,  ..., -1.0500e+00,
           7.8925e-01,  8.6269e-01],
         [-5.5429e+00, -5.3080e-01, -3.0386e+00,  ..., -5.6977e+00,
          -2.2111e+00, -1.5993e+00],
         [-7.6915e+00, -6.2968e+00, -2.6954e+00,  ..., -7.7844e+00,
          -3.0930e+00, -2.2278e+00],
         ...,
         [-2.0656e+00,  5.2901e-01, -8.5086e-02,  ..., -1.4582e+00,
          -1.1232e+00,  1.8164e+00],
         [-1.0097e+00, -1.8511e+00, -4.2131e-01,  ..., -7.1820e-01,
          -1.0291e-01, -2.1303e-01],
         [-1.5329e+00, -1.6383e+00, -1.5679e+00,  ..., -1.4770e+00,
          -8.0963e-01, -1.0504e+00]],

        [[-2.1295e+00,  2.2452e+01, -3.6264e-01,  ..., -1.3805e+00,
           5.6640e-01,  6.3733e-01],
         [-4.6990e+00, -1.8613e+00, -1.0955e+00,  ..., -3.9009e+00,
          -2.6069e+00,  1.8674e-01],
         [-1.4266e+00, -1.9036e+00, -8.6554e-02,  ..., -1.4805e+00,
          -4.3863e-01,  5.5917e-01],
         ...,
         [-3.2891e+00, -1.6441e+00, -2.0574e+00,  ..., -3.0131e+00,
          -1.7970e+00, -9.0359e-01],
         [-3.1844e+00, -1.8592e+00, -2.0208e+00,  ..., -2.8247e+00,
          -1.6675e+00, -9.6500e-01],
         [-3.3256e+00, -2.1618e+00, -2.0898e+00,  ..., -2.8864e+00,
          -1.6659e+00, -9.9956e-01]]], device='cuda:0') tensor([[    1, 15155, 15858, 13477, 27314,  5754,  5549, 25367,   999, 19084,
           597, 12525, 27338, 24344,  6895,   244, 25944,  5522, 19293, 19867,
         12458, 13478,  4589, 24509,  6192, 26986,  4168, 12224, 24509, 16048,
         27314,  5754,  5549,  4032, 13477,  1498,  2720, 20741,  1897, 15038,
         21245, 24124,  4168, 14795, 17087,  1117,   597,   759,  7460, 11071,
         23385, 24840, 24938, 27314,  5754,  5549, 13630,  4028,  7723, 15155,
          4168, 10301, 19880,    78, 21344,   597,  4199, 12886, 13594,  6878,
         10301,  4035,  4867, 27314,  5754,  5549,  4032,   597, 12525, 14891,
          8501,  4168,  1941,  4876,  8047,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 11981, 12341,  2720, 21344, 18676, 18692, 16310, 18483,  2219,
         10721,  4845, 11630, 13442,  7233, 18423,  6775, 16310, 15093,   759,
         21344, 10428,  4726, 26368, 15770, 27338,  7460, 13943,  4020, 10718,
          6775, 16310,  9921, 15093, 12223, 12818, 15770, 15938, 11536, 10077,
          4850, 18999, 10077, 17171, 26161,   385, 15731, 18056, 17581,  6775,
         16310, 18482, 22974, 17316, 12818, 25062,  7615, 14023,  6775, 16310,
         18482, 15093, 24736, 13916, 23632,  3630, 22487,  6573,  1140,  8602,
         12818,  8853, 20286, 16654, 10130,  6775, 16310, 18483, 10077, 26368,
           759,   290, 12818, 18274,  8853,   914, 21530,  7634, 26170, 10721,

 85%|████████▍ | 95/112 [00:06<00:01, 12.72it/s, loss=0.783]

tensor([[    1, 15899, 22445,  ...,     0,     0,     0],
        [    1,  3514,   244,  ..., 14876, 21550,     0],
        [    1, 14470, 14542,  ...,     0,     0,     0],
        [    1, 12838, 23007,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.0072, 22.1440, -0.7430,  ..., -2.0895,  0.2457,  0.5799],
         [-4.0349, -1.7401, -1.7807,  ..., -3.6829, -1.7107, -0.7762],
         [-5.4005, -0.5126, -1.8790,  ..., -5.2694, -1.6507, -1.2498],
         ...,
         [-4.0522, -2.2023, -2.0893,  ..., -3.7453, -2.6193, -1.2574],
         [-4.0799, -2.1869, -2.1256,  ..., -3.8299, -2.6785, -1.3525],
         [-4.0839, -1.9974, -2.1625,  ..., -3.8109, -2.6397, -1.3227]],

        [[-2.6714, 22.3375, -0.5733,  ..., -1.9461,  0.6141,  0.3896],
         [-1.5166,  0.5851,  0.3878,  ..., -1.7313, -0.3389,  0.1193],
         [-3.5059,  0.2232, -1.6657,  ..., -3.3423, -0.4389,  0.1352],
         ...,
         [-4.4687, -2.6367, -1.8996,  ..., -4.7501, -2.8473, -2.1429],
         [-1.2677, -2.3132, -1.0950,  ..., -2.4391, -0.9448, -0.2031],
         [-2.0270, -1.2116, -1.6616,  ..., -2.2384, -1.3785, -1.4030]],

        [[-2.2159, 22.2152, -0.4283,  ..., -1.3911,  0.5476,  0.8279],
         [-2.5812,  3.3393, -1.0769,  ..., -1.4948, -0.1718,  0.4267],
         [-5.9497, -3.2191, -1.7625,  ..., -5.4398, -3.0662, -0.7692],
         ...,
         [-3.1247, -1.4019, -1.6592,  ..., -2.7900, -2.2107, -0.9167],
         [-3.0870, -1.3723, -1.6583,  ..., -2.7994, -2.2321, -0.9907],
         [-3.0249, -1.1359, -1.6694,  ..., -2.7166, -2.1467, -0.9402]],

        [[-2.1404, 22.4507, -0.2800,  ..., -1.2362,  0.5731,  0.6649],
         [-2.6666,  0.5702, -1.4808,  ..., -2.6175, -0.9115, -0.2408],
         [-3.3264, -4.5066, -1.3329,  ..., -3.1669, -1.6216,  0.2029],
         ...,
         [-2.1194, -1.2317, -1.3779,  ..., -1.9671, -1.7386, -0.9335],
         [-2.1809, -1.2308, -1.4356,  ..., -2.0489, -1.7951, -1.0872],
         [-2.1041, -0.9911, -1.4366,  ..., -1.9417, -1.7135, -1.0554]]],
       device='cuda:0') tensor([[    1,  6600,  1122,  ...,     0,     0,     0],
        [    1, 18267,  4842,  ...,   442, 21550,     0],
        [    1,  9822, 25062,  ...,     0,     0,     0],
        [    1, 11736, 25593,  ...,     0,     0,     0]], device='cuda:0')
tensor([[    1, 11702, 26179,  ...,     0,     0,     0],
        [    1, 21269, 17117,  ..., 24482,  2448,     0],
        [    1, 15663, 18450,  ...,     0,     0,     0],
        [    1,  8986, 26755,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.7768, 21.6655, -0.6318,  ..., -1.9435,  0.1864,  0.7017],
         [-7.0753, -4.5712, -3.8232,  ..., -7.0870, -3.5301, -0.9670],
         [-5.8947, -3.7718, -3.1917,  ..., -6.6921, -2.1466, -1.3492],
         ...,
         [-3.1379, -1.5375, -1.5327,  ..., -2.4375, -1.3762, -0.3363],
         [-3.4249, -1.4380, -1.5679,  ..., -2.7397, -1.5434, -0.3223],
         [-3.5195, -1.3733, -1.5802,  ..., -2.8841, -1.6428, -0.2812]],

        [[-2.2770, 22.4400, -0.4754,  ..., -1.4526,  0.5653,  0.6179],
         [-1.5157,  0.0550, -0.5930,  ..., -1.7282, -0.2739, -0.8688],
         [-3.8922, -2.0877, -1.2241,  ..., -3.6764, -2.6188, -1.9348],
         ...,
         [-2.5307, -1.7962, -1.1373,  ..., -3.0703, -1.2358, -0.1500],
         [-5.1845, -4.6197, -2.2976,  ..., -5.0059, -3.5373, -1.4763],
         [-2.1405, -1.1323, -1.3030,  ..., -1.8927, -0.7872, -0.6605]],

        [[-2.9243, 22.1802, -0.7311,  ..., -2.1411,  0.1188,  0.4940],
         [-6.7875, -2.4232, -2.9530,  ..., -6.4427, -3.8481, -1.9165],
         [-5.5247, -1.0475, -1.6738,  ..., -5.7218, -1.9257, -0.2808],
         ...,
         [-3.0277, -1.9879, -1.7271,  ..., -2.5389, -1.2801, -0.7920],
         [-3.2146, -1.8801, -1.7300,  ..., -2.7504, -1.3683, -0.7390],
         [-3.2295, -1.7474, -1.6926,  ..., -2.8234, -1.4407, -0.6687]],

        [[-2.5588, 22.3439, -0.5663,  ..., -1.5414,  0.4646,  0.5995],
         [-4.8406, -0.7088, -2.4276,  ..., -3.3208, -1.7477, -1.5814],
         [-2.9071, -2.0325, -0.8157,  ..., -3.5921, -0.5822, -1.8041],
         ...,
         [-3.0335, -1.7463, -1.4230,  ..., -2.2838, -1.3331, -0.5506],
         [-3.3444, -1.6912, -1.4669,  ..., -2.6117, -1.4854, -0.5057],
         [-3.4623, -1.6516, -1.4793,  ..., -2.7879, -1.5965, -0.4563]]],
       device='cuda:0') tensor([[    1, 22624,   733, 18056, 14881,  9724, 17949,  2032,  3522, 22624,
         26179, 26179, 16521, 22624,   171,  7349,  9724,    58, 14881, 16588,
          3522, 26390, 27041,  9090, 27201, 17934, 16588,   130, 17635, 22023,
          7496, 22624,  8879,  1562, 26179, 27169, 19300,  3148, 16588, 24579,
          9260, 22624, 21051, 22023, 11703,  1302, 25639, 26882, 18450,   288,
         17635, 22024,  9598, 13966, 26426,  5027, 26566, 14850, 22624, 22023,
         27338,   727, 26179, 19933, 18267,  3522, 13873, 15923,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 17017, 14876,  5313, 10075,  2205, 14238, 15093, 10075, 22153,
         16205, 15729,   290, 15565, 21269, 10035, 10232, 10075, 17117,  9260,
         21108, 10395,   539, 12223, 27544,  5321,  2890, 13934, 27479, 10075,
          4199,   655, 15729,  5049, 21108, 17576, 27544, 17795,  6129, 12560,
         23271, 23083, 16912, 24587,  5315, 10075, 16205, 15729,   290, 27544,
         24167, 21108, 13939, 13934, 27479, 17216, 21973, 23440, 17576, 17117,
          9260, 11167,  5883, 21108,  4199, 22000,  2728, 25650, 12338, 10075,
         16528, 27544,   290, 21344, 13943,  6672, 22496, 12660, 23515,   727,
          9544, 25211, 10075, 15565,  1768, 21269,  1637,   727,  9544, 25211,
         10075, 22153, 23440, 26715,  5313, 10075,   732,  9544, 25211,   914,
         21344,  6129, 27338, 10298, 10075,  5313, 21268, 25122, 17117, 19119,
         12168,  5883, 23566,  8879, 14177, 22147, 27338,  9936,   759, 24346,
         27544, 27544, 22899, 14437, 13663, 22206,  4845,  7039,  1576,  6182,
          9482, 15024, 24824, 18621, 16126,  1526, 27552,     0],
        [    1, 15663, 18449, 14881, 27123, 12675,  8667, 21847, 12226, 22887,
         10298, 18056,  5313, 18149, 12408, 15663,  6671, 16626, 26368, 12675,
          8667,  3203, 17220, 24291, 27123,  4624, 16388, 14557, 24291, 27338,
          6755, 18999,  1540, 14881, 17181, 25259, 21847, 21344, 15663,   770,
          9354,  9297, 15663,  4750, 20187,  5732, 16924, 21854, 14573, 12675,
          8667, 12400,  3686, 11286, 18056, 14949, 18149,  6623, 17953, 14881,
         17181, 22024, 21329, 21344, 15663, 15645, 23523,  6846, 15663, 27123,
         22020,  7137, 27338,  5047, 11736, 26986, 16626, 12400,  3686, 11928,
         24291,  3294,  5883, 27123, 27430, 26368, 14557, 17853, 10869, 23634,
         26177, 12408,  3950, 16588, 13943, 24291, 23633,  6071, 26177, 17949,
         13934, 27479, 20287, 14874, 21854, 26092, 27123, 22023, 17609,  4739,
         21854,  4976,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 15800,  6182, 15448, 19450, 19782, 22348, 18611, 14887,  8986,
         27321,   119, 12390, 13498,  8986,  9873, 19780, 20926, 18075, 18588,
         27479, 14633, 19830, 14551,  1531, 26161, 14568, 22030,  5272,  2821,
         12648, 19782,   168,  8987, 20539, 17054,  8945,  2821, 19782, 16654,
         15448,  7615,  8984,  7699, 21344, 24346, 19514, 22441,   503, 16182,
         12648, 19782,  4750,  4457, 22442, 19450,  7218,  8391, 10389, 26876,
          6515, 26161, 22153,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 25098, 17243,  ...,     0,     0,     0],
        [    1,  2549,  6286,  ...,  7615, 19098,     0],
        [    1, 16165,  8320,  ...,     0,     0,     0],
        [    1,  7002,  1787,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.5431, 22.5161, -0.5263,  ..., -1.9019,  0.4094,  0.4323],
         [-2.9978,  2.4707, -1.4377,  ..., -2.9119, -0.9529, -0.0980],
         [-2.2208, -2.4732, -0.5182,  ..., -2.3204, -0.8583,  0.3802],
         ...,
         [-2.3334, -1.2900, -1.6202,  ..., -2.1858, -0.8861, -1.1283],
         [-2.2937, -1.0883, -1.5606,  ..., -2.0108, -0.8132, -1.0070],
         [-2.2802, -1.0041, -1.5754,  ..., -1.9328, -0.7945, -0.8912]],

        [[-2.5908, 22.5587, -0.6434,  ..., -1.8005,  0.3001,  0.5671],
         [-1.9853, -1.6999, -1.7573,  ..., -2.3656, -1.1697, -0.4033],
         [-5.6508, -1.4024, -2.9088,  ..., -6.1828, -3.2087, -1.5253],
         ...,
         [-4.2993, -4.5840, -1.9427,  ..., -4.5616, -2.2806, -0.6668],
         [-5.7579, -2.4977, -2.6782,  ..., -5.5092, -2.4988, -1.1712],
         [-1.7515, -0.6025, -1.3670,  ..., -1.2931, -0.6471, -0.6499]],

        [[-2.4590, 22.4643, -0.5411,  ..., -1.7618,  0.4712,  0.4719],
         [-2.0235,  0.9054, -1.6478,  ..., -1.6337, -0.6585, -0.2851],
         [-4.2032, -1.1304, -1.8788,  ..., -3.9933, -1.4964, -1.3011],
         ...,
         [-1.9474, -0.6498, -1.5380,  ..., -1.7702, -0.7101, -0.8305],
         [-1.9307, -0.4784, -1.5049,  ..., -1.6342, -0.6537, -0.7257],
         [-1.9338, -0.4453, -1.5472,  ..., -1.5907, -0.6370, -0.6337]],

        [[-2.6467, 22.2136, -0.6300,  ..., -1.9111,  0.2730,  0.5061],
         [-2.0645, -1.1077, -0.7012,  ..., -2.4216, -1.4682,  0.0453],
         [-6.4253, -4.9948, -3.5718,  ..., -6.1757, -3.1481, -2.0683],
         ...,
         [-2.3243, -0.7865, -1.3668,  ..., -1.8991, -0.8996, -0.7193],
         [-2.2395, -0.5610, -1.2799,  ..., -1.7014, -0.8012, -0.5666],
         [-2.3025, -0.5177, -1.3272,  ..., -1.7189, -0.8084, -0.4670]]],
       device='cuda:0') tensor([[    1, 10512, 27338, 10395,   539,  4049, 27338, 10298, 18606, 18791,
         24314,  8524,  7441,   290, 26750,  7441,  8349,   731, 17204, 24840,
          9634, 16090, 18606, 27338, 24344, 17085,  6102, 22237, 17278, 13155,
          7761, 16709,  7612, 27479, 21172,  4696, 18291, 21344, 17241, 18439,
          8701,  7441, 11712,   757,  8232,  2464,  7441,  7612,  4199,  5179,
         10622, 19533, 17085, 27338,    58, 18812,  1154, 18802,   732, 22384,
         19084, 18906, 23203,  6090,  6093, 21344, 15785,  8794, 14881, 17825,
          1706,  4973,   867, 21943, 18606, 18450, 27338,  3859,  1061, 22862,
          2215, 16881, 18606,  4199, 23541, 10622, 21344, 12478, 18056, 27338,
         23915, 25098, 21530, 18450,  8701, 19348, 17207, 24944, 19452, 11536,
          2464,  7441,  5313,  6600,  1778, 13988,  4044, 13934, 27479, 15783,
         20823,  3468, 21344, 10512, 24318,  3861, 24274, 19084,   732, 18802,
          4538, 19084, 18906,     0,     0,     0,     0],
        [    1, 16205,  2549, 25025,  2102,  5313, 17282, 27338, 26172, 14351,
          4345,  2102, 18620,  5460, 26412, 27529, 21344,  9572,  4980, 15409,
         14323, 16522, 10205, 14115, 11713, 14587, 13793, 14876, 27338, 20509,
         24040, 17810, 23975,  5142, 22096, 11570, 21835,  6090,  6093,  4384,
         13268, 27338, 10205, 18802, 12918,  6638, 17282, 21344, 14115, 25322,
         18180, 13326, 27338, 20327, 25970,  8437, 13264, 12797,  7615, 19098,
         22129,  4012,  6846,  4368, 14252, 18960, 10711, 14255, 21344,    58,
         12918,  5313, 17282, 14857, 12918, 25114, 14025, 15645, 11730, 25025,
          2102, 16644, 10512, 14891, 15872, 21264,  1061, 24672, 14115, 10512,
          5274, 12524,  5313, 17282, 16326, 12919, 11570, 21835,  1954,  9477,
         27040,  9266, 11839, 13558, 11713,  1314, 23007,   468,  1102,  8271,
          5049, 27338, 26604, 10512,  5734, 17245,  4368, 20882,   256, 27321,
         11570, 21835, 18791, 12918,  6638, 17282,     0],
        [    1, 21859, 17171, 20086,  9266, 10885,  1042, 21827, 21344, 16165,
          4158,  2866, 13223, 16165,  8761,  9505,  1458,   244,  4792, 14795,
          3711,  5862, 24912, 14958, 25923, 16165, 12709, 25923,  2866, 22548,
           651,  9046, 12396, 20086, 16500,  2019,  7551, 26672, 25527, 25015,
         10885, 24938, 16165,  4974,  9046,  5336,  2019,  9480, 12239,  7024,
         17087, 20086,  5315,  9973, 17171, 26818,  9266, 10885, 21827,  7368,
          9724, 13535,  8750, 23203, 25025,  2102, 23221, 24352,   244, 16165,
         20089,  4199, 13453, 10853,  2247, 16165, 20683,  4792,  9046,  2019,
          2247,  2669,  2866, 19533, 12604, 21827, 14099,  8626, 20086, 24368,
         19501,  9973, 19783, 20088, 16165,   290, 15199,  8171, 10400,  7400,
         12525, 24509,  5522, 23566, 19829,  9172, 25593,  1451,  9639, 17087,
           759, 22932,  7897,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  9157, 10232,  7002, 21535, 19112,  9905,  7574, 26183, 22952,
          2662, 19814,  6890, 24534, 21227, 20942,  9577,  6668, 25116, 16654,
         10130,  7573, 24534,  1768, 22952, 19934, 14874,  2821,  7002, 21344,
          9165, 27338,  1666,  2662, 19814,  9577,  7573, 18483, 23388, 26935,
         21364, 16825,   838, 13030,  8615, 25593,  4875,  7573,  9579,  2662,
         19814,  6668, 22952, 17367, 25116, 11158,  7573,  5576, 25076,  9157,
         23791, 22055, 16050,  9642,  6193, 10395,  2662, 19814, 27338, 15393,
          9577, 27338, 22147,  7573,  5248,  7002, 13943, 23790,  1016, 24534,
          1778,  9577,  2076, 15817,  2376, 26370, 26389, 26719, 25928, 23428,
         19117,  9165, 11158,  7573,  9577, 17747, 23428, 20289, 24992, 26183,
         23388,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 21698, 22784,  ..., 25003, 22780,     0],
        [    1,  6878, 21700,  ...,     0,     0,     0],
        [    1, 23411, 25346,  ...,     0,     0,     0],
        [    1, 13697,  5674,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.1757, 22.6372, -0.3578,  ..., -1.5785,  0.5967,  0.4524],
         [-1.8369, -0.5554, -0.1018,  ..., -1.5608, -0.8120,  0.2440],
         [-3.9092, -1.8725, -1.2597,  ..., -3.5188, -1.9914, -1.3506],
         ...,
         [-5.0407, -3.4384, -2.4596,  ..., -4.6529, -2.1550, -0.9706],
         [-2.1905, -2.3190,  0.0304,  ..., -2.3965, -1.4234, -0.1736],
         [-1.5209, -1.4141, -1.1050,  ..., -1.6687, -0.7462, -0.9146]],

        [[-1.4618, 22.6142, -0.0959,  ..., -0.6326,  0.7652,  1.1307],
         [-3.8461,  1.1445, -0.8792,  ..., -3.0233, -2.3296, -1.0757],
         [-2.2540, -1.2132, -0.9025,  ..., -2.9585, -1.3661,  0.0310],
         ...,
         [-2.7712, -1.5717, -1.7238,  ..., -2.4730, -1.5109, -0.3044],
         [-2.7716, -1.7329, -1.6354,  ..., -2.5053, -1.5656, -0.3400],
         [-3.0510, -2.1114, -1.6947,  ..., -2.7841, -1.7481, -0.4058]],

        [[-2.1072, 22.2623, -0.2343,  ..., -1.5315,  0.6160,  0.5796],
         [-3.2592,  1.6385, -1.9004,  ..., -3.4358, -0.6127, -0.3995],
         [-4.9183,  0.8006, -2.2280,  ..., -5.5537, -2.3602, -0.9787],
         ...,
         [-2.9736, -1.4910, -1.8414,  ..., -2.8256, -1.3671, -0.6892],
         [-2.8611, -1.5227, -1.6894,  ..., -2.7436, -1.3561, -0.6686],
         [-3.0196, -1.8125, -1.6632,  ..., -2.9020, -1.4950, -0.6832]],

        [[-2.3179, 22.0918, -0.5206,  ..., -1.5884,  0.2907,  0.8169],
         [-2.9138,  2.0394, -1.3090,  ..., -2.6848, -1.2039, -0.2603],
         [-6.1688, -5.9186, -2.0678,  ..., -6.0974, -3.0906, -0.7898],
         ...,
         [-1.7387, -0.8707, -1.0849,  ..., -1.3759, -0.7211, -0.1698],
         [-1.6599, -0.9609, -0.9427,  ..., -1.3215, -0.7156, -0.1530],
         [-1.8312, -1.2605, -0.9215,  ..., -1.4909, -0.8469, -0.1738]]],
       device='cuda:0')

 87%|████████▋ | 97/112 [00:07<00:01, 12.31it/s, loss=0.749]

tensor([[    1, 25025, 21701, 17777, 26876,  4927,  1897, 22784, 19349, 18428,
         27338, 12725, 23252, 21344, 24938,  4750,  1897, 22784, 19349, 18428,
         21701, 10622, 17825, 11188, 23206,  7819, 21700, 21344, 18505, 21697,
         27338,  9482, 23888, 23638, 16626, 27522, 12838, 16205, 15314, 21344,
          5549, 11188, 19782, 13849, 14070, 22784, 23443, 17777, 16205, 15314,
         21344, 14267, 25211, 27338,  1401, 13181,  8634,  4813, 19043,  1897,
          4766,  9522, 16205, 15314,  4384,  8469, 22784,  1947, 11287, 22783,
          7803, 10298, 19548, 22780, 14177, 11188,  1260,  8879, 17467, 14377,
         19349,  7043,  4897,  1897,  4386, 14267, 25211, 13159, 27338, 14604,
         25025, 16214, 21701,  5142, 17825, 14025,  6090, 15366, 19533, 27338,
          8558,  1897,  7612, 21701,  8552,  5153, 19727, 17263,   525, 25689,
         12724,  1897, 22784, 19349, 18428, 21344,  9202, 27338, 14209,  7998,
         14264, 27338, 20371, 16796,  4909,  4457, 21697, 16326, 11268,  1758,
         18660, 19349, 11188, 22528,  2438,  5307,  6686, 10512, 14881, 20064,
         25033, 18990,  6143,  3860, 22784,     0],
        [    1, 26545, 22646, 18149,  2367,  8246, 23052, 19994, 24938, 21839,
         13737,  7293,  4528, 21839, 21839, 20592, 11214, 21839, 19714, 21839,
         22721,  9266, 11896, 12322, 10559, 19069,  4338,  9172,  6307, 14062,
          5901,  3971, 21227,  4021, 15418, 16654, 26882, 21344,  7641, 13554,
          1493, 21700, 22687,  6878, 21239,  9172, 19596,  9017, 26545,  8252,
         23052, 19994,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 23411, 25346,  8163,  2200,  9482, 23411, 25346, 23169, 22007,
         16654, 10130,  6248, 23033, 16735, 26618, 23411, 25346,  8872, 24346,
          9844, 17630,   268, 14595,   961, 24944,  1537, 18162, 25564,  8553,
         21713, 23411, 25346,  8163,  8163, 23426,  9581, 19508, 14052,   259,
         21700,  1848,  3656,  1222, 22030, 17316, 23411, 25346, 22007,  8872,
          1302, 27314, 18399, 17929,   402, 11172, 21511, 23411, 25346,   402,
          6554, 23411, 25346,  9677,  5845, 11921, 24718,  9172,  8235, 23411,
         25346,  8163,   565, 26161, 15268,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 14219,  3679, 24836,  4677, 11765,  6161,  9260,  5678,  9581,
         17757, 23525, 20520, 23007, 13696, 13919,  5674,  3679,  9260,  1679,
         14403,  9482, 17171, 25393,  1832,  9260,  5678, 14219,  3679, 25483,
           523,  6129, 21847,  9905, 22055, 26886, 14219,  3679, 20702, 19136,
         21982, 16522,  3637,  1690, 24867, 15093, 14219,  3679, 22049, 15731,
          5910,  4677, 27338, 21960, 22286,  5549,  7700, 14219,  3679, 16521,
          9184,   546, 13783,  4251, 10836,  8552,  6846, 13696,  6672,  1926,
         17171,  9260,  5678, 21344,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  8385, 26161,  ...,     0,     0,     0],
        [    1, 12930, 26669,  ...,   948,  4661,     0],
        [    1, 11713, 19006,  ...,     0,     0,     0],
        [    1, 21732, 24317,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.8875, 21.6855, -1.0611,  ..., -3.0400, -0.1232,  0.1657],
         [-6.7698, -2.5717, -4.0487,  ..., -6.3253, -2.6716, -1.7627],
         [-4.5094,  0.6214, -1.7227,  ..., -3.7362, -2.9549, -0.7562],
         ...,
         [-4.2267, -2.6489, -2.7329,  ..., -3.7038, -1.9220, -0.9603],
         [-3.8980, -2.0953, -2.5093,  ..., -3.3396, -1.6856, -0.8006],
         [-3.6682, -1.4336, -2.3138,  ..., -3.0887, -1.5170, -0.6904]],

        [[-2.0343, 22.6509, -0.1445,  ..., -1.2968,  0.6045,  0.5758],
         [-2.3744, -0.9109, -1.0862,  ..., -2.0576, -1.1415, -0.9830],
         [-4.6199, -3.6825, -3.0229,  ..., -4.8979, -2.6021, -1.9895],
         ...,
         [-1.7314, -2.3828, -1.5829,  ..., -1.9249, -0.8243, -1.4401],
         [-2.5980, -1.8903, -1.1640,  ..., -2.0514, -1.5642,  0.1790],
         [-0.8587, -0.4333, -1.0846,  ..., -0.5927, -0.1951, -0.6704]],

        [[-3.3601, 21.7734, -0.8253,  ..., -2.5567, -0.0595,  0.1338],
         [-4.2735, -0.7683, -1.5941,  ..., -3.6923, -2.5220, -0.7739],
         [-6.1734, -3.8626, -3.3071,  ..., -6.5343, -2.1239, -1.7452],
         ...,
         [-3.8480, -2.6535, -2.4265,  ..., -3.4312, -1.8036, -1.1975],
         [-3.4253, -2.1178, -2.1540,  ..., -2.9656, -1.4910, -0.9961],
         [-3.1798, -1.5007, -1.9673,  ..., -2.6878, -1.3051, -0.8707]],

        [[-3.1551, 21.7783, -0.7080,  ..., -2.4836,  0.1290,  0.2778],
         [-1.9441,  1.2107,  0.0314,  ..., -2.6460, -0.5391, -0.6034],
         [-3.8164, -1.5992, -1.1799,  ..., -3.9314, -1.6836, -1.1392],
         ...,
         [-3.9335, -2.4229, -2.5316,  ..., -3.6548, -1.7819, -1.3043],
         [-3.5873, -1.9068, -2.2851,  ..., -3.2762, -1.5153, -1.1275],
         [-3.3377, -1.2999, -2.0926,  ..., -2.9972, -1.3264, -0.9902]]],
       device='cuda:0') tensor([[    1, 22415, 11622, 19829, 16544,  6129, 23440,   546, 19934,  8397,
           569, 14886,   568, 26161, 20942,  2723, 16205, 14966, 21344,   527,
          8385, 26161,  5049, 27096, 20574,  7038,  1270, 16205, 14966, 21344,
         26161,  9145,  4894,  3226, 27396, 23440,   546,   568, 19201, 20668,
          8385,  4894, 26161, 24040,  2723,  8385, 26161,   525,  2204, 24369,
          8059, 23858, 10301,   569, 14887,  8385, 25211,  4803, 18194, 14966,
          1017, 16205, 14966, 21344,  8385, 26161, 11623,  1690, 20574,  7038,
         27314, 25211, 17296, 21975, 27314, 13919, 17610,  6377,  4845, 26127,
         21344, 18425, 17278,   568, 24011,  9745,  3754, 13115, 17262,  3429,
         25407,  6208,   569, 11736, 26127, 21344,  5924, 18999, 17278, 22743,
           568, 18442,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  9913, 24809, 10837, 14711, 22138,  9913, 11312, 27091, 13210,
         17995,  9913, 13088,  6092, 13210,  1737,  4616, 19587, 22425, 12954,
         24809, 27091, 17572, 26669, 20148,  5313, 21827, 25481, 23318, 15799,
         11312, 14491, 11392, 13528, 14096,  5433, 22138, 13299, 11395, 16753,
          7306, 24718, 24680, 25481,  9444, 10885, 23521, 13210,   290,  9634,
          5341, 26669, 14866, 23991, 23428, 27479, 25161, 11312, 21960, 14711,
         23693,  1708, 14481, 15144, 27091,  9327, 22348, 16884, 10703,  1866,
         17623, 18741, 13210,   298,  5340, 13210, 25672,  5342,  6116, 15076,
         11472, 26124, 18024,  1537, 12930, 12930,  5522, 20008,  2656, 23760,
         24076, 10014, 24809, 10609, 14483, 15144, 27091, 20457, 13496, 16082,
         21525, 22134, 27091, 21549, 26669, 19452, 17388,  2405,  7317, 25593,
         23991, 25387,  9634, 15800, 11710, 11918,  3495,  3545, 22574, 25481,
         23991, 24040, 27290, 22134, 27091,  3967, 24200,  4748, 21932, 22425,
         14096,  5433, 14662, 17336, 20468, 17171, 12930, 21827, 10885,  7771,
          3049,  4616, 22134, 27091, 20982, 22425, 21784, 26424,  4480, 11392,
         13528, 11312,   744,  3190, 25481, 10882, 14711, 21043,  6116, 15076,
         14675, 16753, 14795, 11086,  4385,  1866,  2898, 25138, 26669, 25580,
         24836, 21690,  8794,  9193,  5780, 17835, 12930, 11472,  1758,  2663,
         24718, 15799,  7357, 26669, 10938, 12461, 23916, 14711,  9639, 15800,
         23061,  1042, 15284, 21239, 22134, 27091,  2134, 22055, 18483,  7634,
          9215, 18794,   969, 21239, 14505,  4616,     0],
        [    1, 25639, 11713, 19006, 12250,  6182,  9266, 16049, 20925, 22513,
         21982, 10889, 21344,  1674, 19003, 11713, 25639, 23396, 10889, 21344,
          1926, 21344, 19939, 17896, 11713, 19006, 20929,  8919, 16825,  8111,
          5272,  6182, 16048, 16048, 26577, 10889, 11713, 19003,  6071,  7086,
          8774,  4457,  7363, 25352, 11713, 19006,  3637,  7696, 23443, 21344,
         13934, 26882, 16466, 21344, 11713, 19006,  9019,  6182,  1028, 12390,
         21247, 24840, 27479, 14633, 15139,  7889, 10889,  4199,  7698, 21344,
         16521, 20753,  1926, 18871, 14795, 13934, 16048, 19006, 27338,  8829,
          2438,  6217, 21874, 26669, 19006,  9019,  1241,  8626, 23760, 11713,
         19003, 10721, 16825, 26945, 27525, 11790, 10889, 21344, 19006, 21100,
         25593, 20169, 20592, 16048, 20643,  1028, 11713, 19003, 12390,  6833,
          9172, 16050,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 16588, 26179, 10210,  4035,  9131,  1758, 23042, 26868, 12675,
         18694, 14721, 14795, 21732,  8062, 20507,  6071, 22560, 21909, 10468,
         22024, 15537, 23042,  7599, 14850, 16205, 18631, 21344, 12623, 23624,
         23042, 26868, 27299, 23833, 16221,  6071,  5388, 22560, 19764, 26170,
           408, 17095, 11685,  5506,  3340, 11392,  1913,  2459,  5522, 14881,
         23042,  8623, 21344, 16205, 18631, 14721, 26713, 26170,  7599, 14850,
          9131,  1758, 21344, 16205, 18631, 26179, 20171, 26179, 14721,  7348,
         26170, 21732, 10210, 24828, 18056,  7348, 26170, 21732, 14721, 11630,
         10205, 23047, 26868,  5183, 21247,   744,  9844,  3630, 16616, 19867,
         22923,  2436, 19084, 23042,  6004,  4126,  7651, 21344, 14939, 18631,
         23203, 14721,  8396,  6600, 22881, 13963, 16205, 18631, 21344, 21732,
          7350, 24944, 13934,  9634,  6106, 21344, 21732,  3694, 27380,  8156,
           874, 25226, 10127, 26177, 17503, 26850, 14348,  4035, 15875, 14795,
         14721, 26183, 18056,  8156, 22560, 21914, 23042, 10468,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 26161,  2630,  ...,     0,     0,     0],
        [    1,   113,  1705,  ..., 17171, 16709,     0],
        [    1, 13793,  2076,  ...,     0,     0,     0],
        [    1, 21794, 26765,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.3894, 22.3507, -0.4433,  ..., -1.7624,  0.3050,  0.4022],
         [-6.7148, -3.3900, -2.5303,  ..., -6.4119, -3.6923, -2.7646],
         [-7.8098, -5.2202, -4.6088,  ..., -7.9400, -3.2792, -1.9776],
         ...,
         [-3.4716, -2.9385, -2.3580,  ..., -3.2034, -2.1883, -0.9607],
         [-3.2234, -2.6959, -2.2434,  ..., -3.0144, -2.0773, -0.7812],
         [-2.9508, -2.1783, -2.0511,  ..., -2.7900, -1.8857, -0.6501]],

        [[-1.9521, 22.8382, -0.1071,  ..., -1.1544,  0.8065,  0.7933],
         [-4.1080, -1.1153, -1.4312,  ..., -3.6546, -1.1324,  0.0853],
         [-0.9324, -1.1322, -0.1844,  ..., -1.2849, -0.7790,  0.3971],
         ...,
         [-3.3311, -2.2588, -1.0126,  ..., -3.0155, -1.3924, -1.0785],
         [-5.0401, -5.8394, -2.2436,  ..., -5.2691, -3.2504, -1.1268],
         [-1.6997, -1.1432, -1.5560,  ..., -1.6753, -0.9102, -0.6768]],

        [[-3.0613, 21.8729, -0.9227,  ..., -2.4357,  0.1500,  0.2349],
         [-2.0543, -1.7790, -1.7731,  ..., -2.4494, -1.2242, -0.5146],
         [-6.4719, -2.6273, -2.3269,  ..., -6.1053, -2.8722, -1.3293],
         ...,
         [-3.6504, -2.5789, -2.5280,  ..., -3.4433, -2.1899, -1.0752],
         [-3.3037, -2.2548, -2.3606,  ..., -3.1445, -2.0381, -0.8637],
         [-3.0757, -1.7640, -2.1762,  ..., -2.9623, -1.8726, -0.7277]],

        [[-2.2300, 22.3328, -0.2972,  ..., -1.5343,  0.4743,  0.6175],
         [-6.9306, -1.9394, -2.9567,  ..., -6.6646, -3.6513, -0.8609],
         [-6.4130, -0.8981, -2.8799,  ..., -5.9624, -3.6260, -2.2641],
         ...,
         [-3.1183, -2.3707, -2.3037,  ..., -2.8979, -1.9684, -0.8906],
         [-2.8251, -2.1029, -2.1540,  ..., -2.6654, -1.8276, -0.7022],
         [-2.6266, -1.5938, -2.0064,  ..., -2.5161, -1.6654, -0.5959]]],
       device='cuda:0')

 88%|████████▊ | 99/112 [00:07<00:01, 12.00it/s, loss=1.57]

tensor([[    1,  6385, 23205,  5049, 26876, 16208, 22486, 14554,  7995, 23205,
         20251, 18724, 26876,  5050, 16208, 22486, 14554,  4845, 24133,  6385,
         21982, 16208, 22486, 25025,  2102, 16644, 26867, 19934, 26752,  8647,
         24133, 21982, 23443, 21344, 12447, 14101,   244,   573, 27383, 24655,
         14101,  8634, 26161, 23117,  6385, 15687,  4974,  9098,  5248,  2628,
         15268, 14382,  1758,   573, 12040, 18745, 16208, 22486,  1017,  2628,
          9242, 16894, 19521, 22622,  6668, 16050,  4067, 20877,   168, 16208,
         22486, 19521, 22622, 19934, 14606, 24040,   410, 10351,  2633,  4839,
         22513, 16644, 24137,  3190, 14308,  2102, 16644, 26867, 17367, 16616,
         15399, 22935, 11047,  4845, 25794, 24789, 11047, 16208, 22486, 21344,
         26161,   573,  1545, 24133, 12189, 12040,  2628, 26850,  6721, 21535,
          9242,  6129, 27338, 21859, 18357,   123, 17929,  5915, 20701, 20877,
          3429, 15731,  6385, 22153, 25916, 21344,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  9266,  9157, 27115, 27140, 23424,  4407,  2917, 22461, 16183,
         27115,  2436,  1702,   113, 22030, 16796, 19136, 17296, 15500,  6759,
          9157,  6898, 27376,  7509, 16676, 20139,   113,  1702, 21730, 12516,
         27377, 10769, 23735, 24938,  9266, 24585,  3966,  2707, 11622, 15293,
         17199, 16287,  9266, 24938, 24824, 26172, 19036,  4732, 22424, 22620,
         26172,  6553, 13408, 11314,  9266,  2367,   261, 27115, 24040, 26719,
          7769,   113, 10945, 18459, 17352, 23461, 27398,  9266, 27483, 27149,
         14412, 10945, 16651,  5522, 19359, 18552, 27149, 19360, 14595,   961,
         24944, 18552, 15394, 10757,  8162,  3966, 13636,   757, 13636, 20647,
          7328,  8802, 23306,  9266, 18949, 17523,  9266,  1705, 23430,  9266,
           113,  1705, 10945,  4848, 14633, 13498,  6816, 11268, 11561, 21090,
         11691, 20960, 15949,  6102, 11570, 13941, 20721, 16467,   839,   261,
         15071,  5805,  5724,   352, 12225,  9157,  5679, 20106, 11392, 23389,
           113, 19930,   113,  1702, 16791,   210, 25917,  7076,  7622, 23090,
         15570, 14891, 17459,  5307,  9157, 26719, 27149,  8528, 18459,  1705,
         19854, 24787,  3651, 26613, 27338, 16616, 10395,  1705, 26935,  9482,
         27479,  4686,  1702, 10995, 17171, 16709,  3966, 16334, 10347, 25547,
         15024,  9028, 23426, 17259,  6437,  6051,  7425,  5322,  9927, 24840,
         18056, 20139, 17353, 12226,   259, 10174,  3457, 21700, 21344, 27032,
         24787,  6397,  6143, 15139, 14713, 13578, 21525, 18757, 25593,  6106,
         15089, 20585, 11710,  6341,  9482,  1421,  1537, 18949, 21074, 19852,
         27149, 25680, 16626,  2059, 21263, 25435,  6577, 15636,  1336,  6846,
          3900, 10235, 20643, 21784,  8202, 24291, 12725, 14029, 21832, 24136,
          9154, 16709, 10998, 25008, 17171, 18673, 23645,   113, 14256, 15060,
         11346, 21344, 23458, 14565, 14317, 25724, 17352,     0],
        [    1, 16205, 15709, 21344,  7700, 27338, 24344,  3951, 23340, 13793,
          3557, 27338, 26802,  7822, 13934, 23387, 24741, 16205, 15709, 21344,
          6200, 24346, 27499, 26986,  6090,  2673, 27338, 19183, 21044,  7822,
         16205, 15709, 21344, 13793, 22699, 27338,  3115, 27299, 14186, 25098,
         27358, 16205, 15709, 21344, 27338,   759, 10610,  7769, 22030,  8761,
          8761, 15449, 15785,  7826, 16205, 15709, 21344, 13793, 15425,  7769,
         24938, 27338,  9452, 14496, 16651,  3139,  8458, 14496, 19628, 23449,
         10301,  4035, 12702, 19019, 15783, 13793,  7822,  4199,   612, 15709,
          6443, 17825, 25483, 11382, 19019, 15783, 25046,  3557, 21344, 16205,
         15709, 27338,  5337, 20800, 23212, 14177, 21740, 14177, 16456, 14496,
         14177,  2032, 12922,  4966, 18056, 25114,  4585,  4003, 14227,  9642,
         21344, 13793, 18450, 22348, 16205,  2549, 24667,  8772, 19216, 21759,
          2076,  3392, 23818,  3557,  7803, 21344, 16205,  3193, 11167, 13793,
         18915, 18999, 18633, 16205, 15709, 24352, 21044, 24938,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  6585, 21794, 15093,  2171, 12253,  5770, 10471,  1094, 27445,
         15024, 22743,  9265, 25165, 19157, 11286, 18056,  9193,  9146, 15024,
          9265, 20287,  6585, 21794, 24294, 19940, 15024, 17367, 26170,  6585,
         25065, 14186, 21794, 12408, 15235, 19149, 26183, 10426, 11232, 10609,
         19596, 21794, 10471, 15663, 27445, 21344, 17047, 10471, 20287,  6585,
         21794, 22887,  3818,  9146, 17949, 14191, 26179, 26170, 17171, 25063,
          9193,  7599, 14850, 15594, 23248, 24704,  9146, 18934, 15663,  4766,
         13939,  6585, 21794,  1244, 22887,  4849,  8947, 19157, 13916, 16924,
         20946, 15024,  9120,  6239, 18679, 26179, 15024, 18056, 26170, 21794,
          8104,  9266, 17630, 10395, 10210, 16588,  6585, 21794,  2169, 12126,
         22055, 19885,  8047, 15663,   561, 13963, 21794, 22887,  9193, 13574,
          9144, 17949, 11013,  7447, 13949, 19940,  2890, 23439, 13797, 10205,
         10964, 21794, 22887, 18056, 26170,   759, 21794, 12253, 13498, 26818,
         18056, 10205,  1302, 12675, 13175,  5116, 15663,  4199,  9184, 17084,
         21344, 24680, 26368,  6585, 21794, 22887,  1666,  7348,  8047, 27479,
         15663, 14795,  1018,  9598, 21794, 22887,  3514,  9184,   914, 24364,
          9266, 19512, 20647,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 12944, 21786,  3579, 26424, 21992,   901, 12944,  3667,  9266,
         27394, 24990, 23657, 22036, 26424, 11812, 15484,  5954,  9172,  3579,
          4429, 27479, 17131, 25062, 15800, 24344, 15199, 12944,  2134,  5954,
         13934, 21135, 19497, 11812, 14795, 14857,  7400, 14668, 14597, 13404,
         23307, 27194, 12458, 12944, 21344, 19867, 16580,  2205, 19374, 16221,
         27381, 13308, 27112,  9177, 13934, 27479,   290,  9266, 27394, 24990,
         27115, 19867, 10301,  8086, 18813, 12166, 12944, 18475, 16496, 21860,
         12947,  2297,  5951, 20495,  9266, 21135, 21344,  1617, 17204, 15481,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 25041, 23475,  9453,  8396, 14551, 13300,  4274, 25041,  5915,
         21603,  8156,  9849,  9283,  8397, 12322,  4032, 27479, 17131, 15793,
         12461, 19374, 12668, 15450, 14803, 14287, 26882, 26919, 26741, 26847,
         25249, 13904, 16859, 22008, 21344,  4586, 18194, 23403, 23660, 16299,
            32,  2497, 15448,  1758,  9844, 25249, 23262, 15089, 14213,  9681,
           759,  4867, 14803, 24884,  2497,  1493,  4528, 21804,  2367, 21831,
          2497, 13934, 26882,   759, 18885,  9452,  1552, 16654, 16048,  8397,
         12322,  4032, 14213,  9681, 21245,  3118, 24509, 15206, 13040, 10010,
          8398, 24840, 27483,   517,  5271, 25249, 11570, 15401, 25041, 23566,
         21799,  9266, 14874, 15418, 21804, 22354,  5522, 22974,  9572, 10525,
         23232, 18570, 14803, 15671,  1493, 13299, 21804,  2367,  2497, 10559,
         19069, 10456,  8141, 19449, 27314, 12322,  4028, 21510, 23739, 21827,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  8111, 13963, 20083, 19275,  8111, 19275, 12668, 21216,  2695,
         20086, 18092,  6264, 12838, 20476,  5972, 14850,  8111,  4586,   952,
         20989,  3517,  8487, 12668, 20089,  4667, 11392, 23541, 13867,   909,
         22055, 13209, 13372,  6201, 26713, 10395, 24416,  4667, 23541, 20989,
         25025,  5972, 14850, 26713, 23079, 12836, 24789, 17171, 22405, 20087,
         11392, 21216,  9505, 25914, 20089, 14953,  4384, 13372, 14795, 24840,
         14874,  8310,  4046, 17388, 23975, 15199,  8111,  2136, 12845,  7499,
         24797, 23657,  6264, 22571, 16465, 12668, 21216,  2695,  6878, 11392,
         25025,  5972, 14850, 13209, 13372, 25076, 27314, 12668, 18092, 27338,
           124, 27633, 18904, 17171, 20089,  7257, 27338,  1789, 13531, 14891,
          1160,  8112, 20086, 20087, 14317,  8397, 15199, 27338, 12497, 19531,
         22932, 18094, 14317, 27338, 19374, 16654,  9973,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 17041, 25576, 19662,  2929, 17083, 17041, 25576,  5703,  3634,
         21983, 23425, 10174,  4537,  2958, 18404, 13288, 20985, 10447, 23657,
         16924, 17171, 26161,  2929, 17083,  4101, 25062, 26883, 24900, 21365,
           168, 23790,  8359, 21983,  9483, 15183,  5710, 25481, 19372, 24840,
         14874, 11266,   240,  8396, 13651, 13934, 26882, 16924, 17171, 16456,
         25331, 24797, 18423, 26943, 22827,  2546, 25403, 21827, 24352, 21139,
         25076,  9293,   989,  8754, 18601,  8690, 23425, 25035, 10977,  9074,
          4756,  4285, 13721, 17041, 25576,  2929, 17083, 25414, 15103,  9639,
          2438, 17207,  6182, 20286, 26161, 24840,  9165, 14586, 20906, 25396,
         21983, 16436,  2134, 18863, 17041,  7858, 25062, 17207, 26883, 25122,
         20332,  9157, 23425,  9688, 22512, 19776, 17609, 17041,  7858,  6839,
         17352, 27150,  6846, 23542, 22874, 22874, 20704,  6837, 11472, 21983,
         20710,  4537, 18404, 20985, 15233,  6007,   952, 10007,  7888, 10504,
          3843, 27604, 13210, 13184, 23411,  3798,  9854, 10456, 11545, 16183,
         21344,  6012,  9022, 18949,  7096, 26751,  3183, 11736, 26161,  5734,
         14177,  4912, 19168, 14595,   961, 24944, 13788,  7019, 26266, 19168,
         15711, 20746, 16626, 27522, 24944,  7496, 21983, 25670, 25419,     0]],
       device='cuda:0') tensor([[[-2.7637, 21.9868, -0.8278,  ..., -2.1578,  0.3653,  0.3782],
         [-4.1600, -0.8086, -2.5143,  ..., -3.9770, -1.5075, -0.5438],
         [-2.6729, -2.9486, -1.2955,  ..., -1.6511, -0.8700, -1.3271],
         ...,
         [-3.0277, -1.7227, -2.1328,  ..., -2.8013, -1.5661, -0.8902],
         [-2.9727, -1.8024, -2.1912,  ..., -2.7623, -1.5472, -0.9033],
         [-3.1239, -2.0666, -2.3677,  ..., -2.9583, -1.7055, -0.9814]],

        [[-2.2457, 22.3950, -0.5649,  ..., -1.4704,  0.3676,  0.6039],
         [-3.7352, -1.3326, -2.9492,  ..., -3.2141, -1.5680, -0.5617],
         [-7.1265, -4.1162, -3.7101,  ..., -7.7763, -3.2895, -2.3573],
         ...,
         [-1.2368, -0.5293, -1.3006,  ..., -0.9541, -0.8037, -0.6105],
         [-1.1807, -0.5589, -1.3411,  ..., -0.9101, -0.7950, -0.6038],
         [-1.3997, -0.8458, -1.5282,  ..., -1.1685, -0.9958, -0.7299]],

        [[-2.8092, 21.9730, -0.7111,  ..., -2.0503,  0.1860,  0.5689],
         [-3.4755, -1.1549, -1.8656,  ..., -3.3045, -1.0199, -0.2444],
         [-7.3357, -3.6402, -3.6199,  ..., -7.1113, -4.0571, -1.9316],
         ...,
         [-2.3335, -1.4268, -1.5827,  ..., -2.0300, -1.1800, -0.6970],
         [-2.3789, -1.5341, -1.6907,  ..., -2.0939, -1.2275, -0.7175],
         [-2.6532, -1.8367, -1.9141,  ..., -2.3846, -1.4579, -0.8215]],

        [[-2.1725, 22.6245, -0.5171,  ..., -1.4177,  0.8248,  0.6217],
         [-8.4062, -4.7631, -4.8741,  ..., -8.0996, -3.4807, -2.2846],
         [-9.0387, -1.9004, -3.6209,  ..., -8.5529, -3.0034, -2.2442],
         ...,
         [-0.7062,  0.9804,  0.2818,  ..., -0.4140,  0.6325,  0.8220],
         [-3.5586, -2.0810, -2.2911,  ..., -3.1383, -1.4947,  0.0234],
         [-1.6675, -1.0601, -1.8454,  ..., -1.4872, -0.7554, -1.0100]]],
       device='cuda:0') tensor([[    1, 21992,   901, 12944,  3667,  9266, 27394, 24990, 23657, 22036,
         26424, 11812, 15484,  5954,  9172,  3579,  4429, 12944,  2134,  5954,
         13934, 21135, 19497, 11812, 14795, 14857,  7400, 14668, 14597, 13404,
         23307, 27194, 12458, 13308, 27112,  9177, 13934, 27479,   290,  9266,
         27394, 24990, 27115, 19867, 10301,  8086, 18813, 12166,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  2497,  1493,  4528, 21804,  2367, 21831,  2497, 13934, 26882,
           759, 18885,  9452,  1552, 16654, 16048,  8397, 12322,  4032, 27479,
         17131, 15793, 12461, 19374, 12668, 15450, 14803, 14287, 26882, 26919,
         26741, 26847, 25249, 13904, 14551, 13300,  4274, 25041,  5915, 21603,
          8156,  9849,  9283,  8397, 12322,  4032, 15671,  1493, 13299, 21804,
          2367,  2497, 10559, 19069, 10456,  8141, 19449, 27314, 12322,  4028,
         21510, 23739, 21827,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  8111, 19275, 12668, 21216,  2695, 20086, 18092,  6264, 12838,
         20476,  5972, 14850, 12668, 21216,  2695,  6878, 11392, 25025,  5972,
         14850,  8112, 20086, 20087, 14317,  8397, 15199, 27338, 12497, 26713,
         10395, 24416,  4667, 23541, 20989, 25025,  5972, 14850, 17171, 20089,
          7257, 27338,  1789, 13531, 14891,  1160,  8111,  4586,   952, 20989,
          3517,  8487, 12668, 20089,  4667, 11392, 23541, 13867,   909, 22055,
         13209, 13372,  6201,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 17041, 25576,  5703,  3634, 21983, 23425, 10174,  4537,  2958,
         18404, 13288, 20985, 10447, 23657, 16924, 17171, 26161,  2929, 17083,
          4101, 21983, 16436,  2134, 18863, 17041,  7858, 25062, 17207, 26883,
         25122, 20332,  9157, 23425,  9688, 22512, 19776, 17609, 17041,  7858,
          6839, 17352, 27150,  6846, 23542, 22874, 17041, 25576,  2929, 17083,
         25414, 15103,  9639,  2438, 17207,  6182, 20286, 26161, 24840,  9165,
         14586, 20906, 25396, 22874, 20704,  6837, 11472, 21983, 20710,  4537,
         18404, 20985, 15233,  6007,   952, 10007,  7888, 10504, 15711, 20746,
         16626, 27522, 24944,  7496, 21983, 25670, 25419,     0]],
       device='cuda:0')
tensor([[    1, 11302, 11021,  ...,     0,     0,     0],
        [    1, 24700,  1250,  ...,     0,     0,     0],
        [    1,  1487,  4216,  ..., 25593,  5548,     0],
        [    1, 26681, 23703,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.4688, 22.1986, -0.6503,  ..., -1.7491,  0.3766,  0.4130],
         [-4.1993, -1.0111, -2.7956,  ..., -4.5727, -1.6687, -0.8653],
         [-5.8348, -2.9265, -2.1477,  ..., -5.2416, -3.0836, -1.3779],
         ...,
         [-2.3256, -0.9386, -1.5697,  ..., -1.7163, -1.0017, -0.2226],
         [-2.1644, -0.8044, -1.4585,  ..., -1.6875, -1.0100, -0.1445],
         [-2.2104, -0.6986, -1.4618,  ..., -1.8432, -1.1220, -0.1263]],

        [[-1.8176, 22.8134, -0.2292,  ..., -1.1233,  0.6143,  0.5333],
         [-4.5361, -2.3198, -3.3140,  ..., -4.4229, -2.0748, -2.5929],
         [-5.7734, -4.5507, -3.2713,  ..., -6.1193, -3.7591, -1.4918],
         ...,
         [-1.9800, -1.1886, -1.5501,  ..., -1.6493, -0.9313, -0.6940],
         [-1.6744, -0.9977, -1.3703,  ..., -1.4568, -0.8693, -0.5828],
         [-1.7228, -0.9109, -1.3798,  ..., -1.5907, -0.9947, -0.5702]],

        [[-2.1046, 22.5307, -0.3989,  ..., -1.3583,  0.6276,  0.7065],
         [-3.4997,  0.5105, -2.2422,  ..., -3.3323, -1.7761,  0.3592],
         [-3.1647, -0.9903, -1.4604,  ..., -2.8564, -1.3028, -1.0098],
         ...,
         [-4.8896, -2.0702, -2.5248,  ..., -4.7894, -2.3746,  0.2377],
         [-5.5178, -2.1646, -2.9756,  ..., -5.9904, -2.4719, -1.4753],
         [-0.5401, -0.1115, -1.0810,  ..., -0.6411, -0.2537, -0.3056]],

        [[-2.7334, 21.6707, -0.8578,  ..., -2.1317,  0.2145,  0.4766],
         [-6.0145, -3.5611, -3.1824,  ..., -5.2376, -2.9975, -1.5151],
         [-7.8684, -5.0916, -3.9404,  ..., -7.4564, -3.7110, -2.1280],
         ...,
         [-2.4220, -1.4035, -1.4930,  ..., -1.9164, -1.2607, -0.0739],
         [-2.0914, -1.1990, -1.3098,  ..., -1.7139, -1.1612,  0.0465],
         [-2.1659, -1.1216, -1.3230,  ..., -1.8678, -1.2727,  0.0744]]],

 92%|█████████▏| 103/112 [00:07<00:00, 12.59it/s, loss=0.974]

tensor([[    1,  9157, 10232,  7002, 21535, 19112,  9905,  7574, 26183, 22952,
          2662, 19814,  6890, 24534, 21227, 20942,  9577,  6668, 25116, 16654,
         10130,  7573, 24534,  1768, 22952, 19934, 14874,  2821,  7002, 21344,
          9165, 27338,  1666,  2662, 19814,  9577,  7573, 18483, 23388, 26935,
         21364, 16825,   838, 13030,  8615, 25593,  4875,  7573,  9579,  2662,
         19814,  6668, 22952, 17367, 25116, 11158,  7573,  5576, 25076,  9157,
         23791, 22055, 16050,  9642,  6193, 10395,  2662, 19814, 27338, 15393,
          9577, 27338, 22147,  7573,  5248,  7002, 13943, 23790,  1016, 24534,
          1778,  9577,  2076, 15817,  2376, 26370, 26389, 26719, 25928, 23428,
         19117,  9165, 11158,  7573,  9577, 17747, 23428, 20289, 24992, 26183,
         23388,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  4093, 11519,  1980, 15858, 22571, 18023, 27440, 13866, 22571,
          9673, 19452, 26530,  9791, 19083, 13528,  9673,  3951,  6001, 25242,
         21525, 15089,  5831, 18021, 11539,  1866, 24314, 27440, 10303,  9673,
         14023, 13528, 27044, 21864,  1042,  1537,  7458, 22311, 27440, 19452,
          9673,   539, 22574, 18024, 15800, 14096,  1980,   759, 15858, 25593,
         14554, 19727,  7771,  9266, 10885,  7428,  4538,  8111, 21685, 21827,
          5343, 25481,  8111,  5522,  9973, 24840, 15800, 14096, 11519, 19450,
          7651,  7458, 10397, 17239, 27044, 12954, 20989,  5831, 12954, 16803,
          1980, 12954, 14214,  3457, 11519, 10837,  7889,  9913, 21168, 24810,
         17597, 26410, 10653,  1737, 13416, 12954, 27330, 13781, 16059,  5471,
          8111, 23916,  7792,  6264, 24693, 21751, 10885,  6801, 27440,  2826,
          9673, 26424, 25581, 11519,  7615, 17239, 22040,  8112, 16579, 19450,
         23658, 18024,  1537, 27044,  6836, 17207, 21827, 10885,  9673, 24845,
         24840,  9612, 20458,  1537, 20022, 22567, 27136, 13136, 15108,   757,
          6467, 12458, 11519,  5343,   290, 18024, 17171, 22055,  9746, 12418,
          9397, 14023, 27440, 16668,  1708, 14023, 24797, 18024, 15800,  8111,
         21960,  2277,  4639, 15233,  6099,  1980, 13528, 21525,  4288,  7244,
         24344,  1866, 14367, 23340, 22030, 26424, 18467,  9673, 25580, 25547,
          8111,  1866,  3019,  7615, 11570, 22405, 23774, 10126,  9612, 16000,
         17171,  2277, 13416,  4079,  1101,     0],
        [    1, 25488, 25372, 22942,   759,  8979,   673, 13505, 26324, 20777,
         24935, 15341,  1705, 22340,   759,  8979, 18093, 25620, 10622,  6102,
           673, 13505, 13371, 26945, 14583,  1060,  7513, 14323, 17171,  2438,
         24368, 18588, 22525, 13090, 14583, 11839, 15040,  1060, 13947, 18664,
         23411, 18091,  7513, 16048, 10553,  1705, 14595,   961,  1060,  2156,
         14583, 24797, 11839, 13304,   759, 25372, 19814,  4092,  8983,  2789,
         19684,  2461, 18967,  3908, 23013, 21010, 24935, 15341, 10651, 27106,
         14732, 22623,  6730,  2390,  7906,  2509, 16789, 27479,  2367, 13947,
         18664,   630,  2367, 21377, 15562,   630,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 16304,  6239,  3690, 13939, 14108, 22524, 19814,  4092, 17204,
          9581, 19999, 23790, 14595,   961, 16205,  6780, 21344, 19999, 23790,
         17086, 26172,  4092, 15024, 27483, 19996, 16221, 13934,   630, 10148,
         14630,  4845, 11623, 16304,   759, 11713,  7744,  3951,  9482,  6143,
          4092,  7790, 10553,  1705, 12226,   630, 27479, 10148, 14630,  4845,
          4689,  7514,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 16447, 12590,  ...,  5522, 25669,     0],
        [    1, 26161,  6071,  ...,     0,     0,     0],
        [    1, 10395,   539,  ...,     0,     0,     0],
        [    1, 24840,  7160,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-3.5304, 21.9498, -1.1408,  ..., -2.8431,  0.0816,  0.1166],
         [-4.6492, -3.2709, -2.2692,  ..., -4.6241, -1.6891, -1.3568],
         [-5.9963, -1.7370, -3.1764,  ..., -6.6433, -3.3312, -1.8911],
         ...,
         [-3.4710, -1.0166, -2.1815,  ..., -4.0373, -1.0720, -0.9107],
         [-3.9363, -1.7311, -1.1529,  ..., -3.8517, -1.1932, -0.9194],
         [-2.7701, -1.3872, -1.9467,  ..., -2.6584, -1.0327, -1.2974]],

        [[-3.1684, 22.2689, -0.8506,  ..., -2.4013,  0.1693,  0.2371],
         [-2.7985, -0.0816, -0.6679,  ..., -2.9061, -1.1487, -0.3517],
         [-4.8618, -5.1841, -2.0807,  ..., -5.4673, -1.3689, -1.2892],
         ...,
         [-2.3676, -1.4275, -1.8059,  ..., -2.2384, -0.8248, -0.9875],
         [-2.5004, -1.4425, -1.8360,  ..., -2.3413, -0.9089, -1.0803],
         [-2.5761, -1.2828, -1.8133,  ..., -2.3155, -0.9140, -1.0678]],

        [[-2.3337, 22.0806, -0.5293,  ..., -1.5357,  0.3901,  0.8418],
         [-2.9262, -0.2739, -0.8031,  ..., -2.9153, -1.0654, -0.7786],
         [-4.5914, -4.3394, -1.8205,  ..., -4.1598, -2.1184, -1.7138],
         ...,
         [-1.7809, -1.0886, -1.2428,  ..., -1.4299, -0.8735, -0.3129],
         [-1.8173, -1.0284, -1.2305,  ..., -1.4348, -0.8755, -0.3830],
         [-1.9070, -0.8807, -1.2040,  ..., -1.4155, -0.8669, -0.3669]],

        [[-2.0652, 22.7979, -0.3925,  ..., -1.3486,  0.6736,  0.7357],
         [-7.2988, -0.9602, -4.5306,  ..., -7.5146, -3.9110, -1.4259],
         [-5.7020, -2.3068, -2.4018,  ..., -4.8396, -3.2407, -2.5916],
         ...,
         [-4.5574, -3.2012, -2.1090,  ..., -4.9674, -2.3636, -1.6931],
         [-3.6877, -2.0841, -1.8602,  ..., -4.2643, -1.8182,  0.3702],
         [-1.7750, -0.7500, -1.3930,  ..., -1.5839, -0.4516, -0.8000]]],
       device='cuda:0') tensor([[    1, 25061,  2549, 21344, 26713, 11395, 24482, 19782, 25076,  7620,
         26876, 21344, 24482, 19188, 27338, 14096, 13793, 14984,  1527, 25114,
         18450, 19098,  1487,  4386,    74, 16205, 11730, 21344, 13793, 19232,
         11932, 10456, 16205,  2549,  4385, 24482, 18511, 14096, 14984, 10301,
         17171, 16203, 25503, 25076, 19780, 12229, 24482,  1255, 16205, 11730,
         19019, 15783, 19538,   759, 21525, 16205,  2549, 18867, 16626, 18450,
         27338, 19077,  5915, 16588, 12073, 16205, 11730, 19839, 14192, 10512,
         18450,  8397,  5523, 15785, 19101,  1487, 21867, 17449,  8385, 18585,
         16456, 12590,   290,  8461, 13664, 24482, 10395, 13793,  4457, 24482,
         27338, 16205,  2549, 21344,   100, 27338, 26880,  3996, 15694,  8852,
          1653, 10205, 20877, 22040, 12071, 27294, 27338,  8047, 16205, 11730,
         18582, 12568,  9272, 23789, 18872, 13793, 16521, 12249, 24485,  5586,
          2690, 10000, 23144, 18450,     0],
        [    1, 25932, 12280,  5216, 23144,  9019,  7615,  8984, 13027,  5522,
         12288,  8829, 20658, 23144, 26161, 19349, 18807, 27338,  1254, 10634,
          5271, 19680, 19782, 15406, 17600, 21344, 13165, 19558,  4199, 15093,
         23442,  1926,   838,  3637, 14952,  5216, 23144,   179, 26161,  7693,
           258, 26441, 10060, 11188,  7700, 15655,  6071,  4540, 16998, 11900,
         22219,  4199, 26161,  7698, 11392,  9753,  7696, 21344, 18807, 20470,
         16221, 14177,   615,  9266, 10315,  4973, 25216, 15687, 12680,  2436,
         13298,  5423, 18807, 12105,  8986,   503, 15406, 16177, 16186, 19782,
         21344, 17902,  4177,  4199, 15093,   913, 23388, 18660, 27035, 19006,
         26161, 21100,  8919, 19780, 22571, 27483, 13027,   168, 10512,  6071,
         11736,  9765, 17532,  5423, 18807,  5423,  9139, 24077, 17857, 16050,
          2438, 27479, 27479,  9935, 16735, 27483,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 18381,  3294, 26161, 20171,   622, 14754,  3299, 17117,  5445,
           621,  3298, 14753, 10301, 10395,   539,  5199,  2690, 17117, 18381,
         17835,  1862, 18039, 19168,   561,   727,   767, 18716, 22264, 21269,
          3796, 17117, 16818, 10422, 25539, 18716, 13630, 18381, 21239,  3299,
         18690,  3350,  2530, 21774,   622,  4366, 26553,   373,  4596,  5760,
         14753, 17171, 12126, 12414, 19174, 20168,  8385,  8391,  1506, 12603,
         26947,  1863, 21344,   622, 19019, 15783,  8935, 16406,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 13939, 13175, 17995,  2102, 19628, 22340, 23884,  8984, 24840,
         22357, 11681, 24840,  7160,  9455,  7119, 16796,  4794, 16310, 24840,
          7160,  5271, 11678,  5883, 22357, 19628, 19628,  5316,   952, 17762,
         21344,  2244, 22007,  7160, 11685, 21899, 22357, 17171, 16310, 24990,
          8156, 14100, 14453, 19628, 21344, 22340, 27338, 25481, 20455, 17995,
         27338, 20925,  4016, 13445, 14100,   688, 25983, 16310, 11860, 23522,
          5885, 17171, 10885, 19628, 24884, 16709, 22340,  2378, 11860, 26669,
          8668, 16626, 16310,  8332,  4766,   263,  3024, 26669, 17171, 16310,
         16626, 19628,   757,  8590, 26867, 17079,   410,  1406, 16310, 12341,
         19999,  6407, 22453, 19994,  5282, 27046,   127, 13175, 17995, 16616,
         20456, 21344, 19628, 23449, 22340,  6239, 22346,  2367, 25639,  2530,
         16310,  3141, 14442, 22029, 17107, 10303, 16626,  1356,  9266,  4035,
         18091, 14442, 16456, 19628,     0]], device='cuda:0')
tensor([[    1,  3123,  8986,  ...,     0,     0,     0],
        [    1,  3896, 17211,  ...,  9918,  7298,     0],
        [    1, 14881, 10626,  ...,     0,     0,     0],
        [    1, 15645,  9157,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6979, 22.2423, -0.5563,  ..., -1.9671,  0.3839,  0.6616],
         [-4.3548, -2.9684, -1.8351,  ..., -3.2670, -2.1504, -1.1412],
         [-2.9566, -1.6084, -0.0643,  ..., -3.3928, -1.2660, -0.2261],
         ...,
         [-3.7111, -2.2162, -2.1338,  ..., -3.2187, -1.9168, -0.9764],
         [-3.5712, -2.2081, -2.0821,  ..., -3.0508, -1.9008, -0.9728],
         [-3.5583, -2.1584, -2.0732,  ..., -3.0554, -1.8975, -0.9845]],

        [[-2.2127, 22.6142, -0.2764,  ..., -1.4422,  0.5200,  0.5186],
         [-3.6011,  0.5475, -1.0868,  ..., -2.5340, -1.3874,  0.6879],
         [-3.6670, -4.3151, -0.3348,  ..., -3.2882, -1.9698, -0.6244],
         ...,
         [-1.6526, -1.3708, -1.3113,  ..., -1.3099, -0.8960, -0.8170],
         [-1.4293, -1.2951, -1.2379,  ..., -1.0329, -0.8313, -0.8184],
         [-1.2906, -1.1989, -1.1719,  ..., -0.8818, -0.7596, -0.7892]],

        [[-1.7555, 22.8637, -0.0544,  ..., -1.0086,  0.8535,  0.6806],
         [-4.1380, -1.1386, -2.1101,  ..., -4.4098, -1.7393, -2.4824],
         [-2.2287,  0.4995,  0.1028,  ..., -1.9306, -0.7504, -0.1767],
         ...,
         [-2.9045, -1.9748, -1.4671,  ..., -2.6317, -2.2802,  0.9369],
         [-4.7474, -3.0831, -2.1362,  ..., -4.5472, -1.2897, -1.6264],
         [-1.1407, -1.1351, -1.0538,  ..., -0.8425, -0.6833, -0.7816]],

        [[-2.2335, 22.0192, -0.5810,  ..., -1.5868,  0.4455,  0.5097],
         [-6.4107, -4.7633, -3.3604,  ..., -5.9269, -2.8538, -1.7020],
         [-6.9752, -5.0104, -3.4507,  ..., -6.8403, -3.2304, -2.1041],
         ...,
         [-2.5616, -1.7896, -1.4930,  ..., -2.1621, -1.4351, -0.4996],
         [-2.4720, -1.8553, -1.4652,  ..., -2.0603, -1.4223, -0.5254],
         [-2.5481, -1.8820, -1.4851,  ..., -2.1739, -1.4518, -0.5796]]],
       device='cuda:0') tensor([[    1,  8458, 16048, 19006,  7458, 18056, 25483, 24231, 21344,  6925,
         11765, 26280, 19088, 17171,  2438, 12922,  5883, 24035, 27198, 12408,
         18056, 16521, 10298, 16626, 24035, 21344, 24935,  6041,  7727, 17949,
         19072, 24797,  3135, 26179, 12703,  8986,  5883, 19301,  5522, 24968,
         11914, 24792, 24935,  6041,  7727, 17949, 19072, 14813, 24111,  5016,
         17949, 19072, 14813, 20721, 15024,  3123, 25888, 12675, 22023, 19006,
         22030,  7458,  8437,  4766, 16050, 16205,  6041,   415,  8461, 22303,
          1302,  3694, 24111,  9626,  3243, 24981,   252,  7065,  5910, 14074,
         17079, 14636, 19003, 18267,  3580, 23850, 17808,  1801, 16644,  3243,
         25639,  2438, 12675, 24035,   744, 24840, 24944, 15024, 18056, 25483,
         14071, 13183,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  6775, 11570, 11875, 24756, 22340,  5522, 13934,  2436, 27479,
          3896, 21344, 24797, 10130, 15923,  6775, 11570,  3135, 13498, 24758,
         22340, 17171, 12650, 24788,  3896,  4463, 22340,  6217, 21344, 16205,
         27262,  3896, 17301,  5658,  6775, 11570, 10890, 10970, 14317,  3291,
         11713, 22340,  3548, 18270, 14323, 19293, 12650,  2076, 10703, 22340,
         21344,  2277, 27262, 19029,   913, 20525,  9260, 10031, 13697, 10233,
         14219,  7841, 21400, 22340, 11752, 10966, 22340, 24534, 22030, 21048,
         26161,  8396, 13696, 16654, 27479, 10731,  3601,  8461, 26935, 16310,
         14790, 16310, 10426,  2436, 24756, 26327,  3896, 21344, 16205, 27262,
          3896,  5522,  2169,  2081, 25593,  4875, 15617, 10210, 25564, 15923,
           759, 14323, 19297, 23340, 24534, 22649,  4867,  9913, 24758, 12223,
         25564,  8014, 15923,  2901,  5657,  3437, 10901, 26562, 26072, 19287,
         10965, 22340, 14442,  6775, 24587,  3896, 27314, 13919, 11371, 24521,
          8801, 17205,  7282, 10985, 14564, 13943, 24532, 11581,  3402, 22952,
          8286, 26170,  8801, 22340, 26633, 19940, 26070, 26677,  2983, 18267,
         23119, 16146, 15268, 26069, 21042, 10965, 27046, 24969,  9266,  3753,
          1140, 12938, 16310, 22887,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [    1, 21864, 24787, 24534, 12341, 20643,  2457,  6677, 17131, 15922,
         18270,  1069, 10952, 20029, 27483,  4750,  1140, 10208, 26818, 14606,
         18056, 10426,  3434, 16626, 14744, 15770, 24866,  1708, 17131, 17949,
         13445, 16021, 18109, 17131,  8141, 11149, 26779, 16024,   747,  9844,
          1332, 14023, 18739,  4916,  5522, 26173, 14565,  1302, 17083,  9193,
         25593, 16024, 17131, 17949, 25593, 17131, 10952, 24840,   931, 13914,
          9634,  1069, 15922, 18270,  4689, 19948,  2073,  8437, 23972, 27312,
         14554, 19867, 16221, 26170,  2448, 24810, 24792, 24938, 19077, 20345,
         24344, 17131, 15922, 24014,  7458,  2929, 14070,  8446,  9266,  3670,
         19714,  9634, 23411, 18210, 19384, 26293, 19506, 14023,  1509,  7465,
          1302,  3540, 10426, 12126, 11030, 15020,  8396, 22513,  1600, 16626,
         26779,  7839,  7830,  8264,  6843, 16987,   123, 20702, 19123, 20031,
          3670,  8104,  3785, 18581, 14023,   304, 11287, 23624, 18210, 26269,
          8656,  7615,  5941, 18244,  3517, 13652, 22496, 26172, 27201, 19854,
         24824,  8774, 14023, 27338,  8047,  1509, 17131, 17174,  4229, 10232,
         12605, 19940,  2200, 22264,  4948,  4338,  2699, 14023,  9724, 20108,
         10718,  1707, 17795, 24534, 12341, 19123,  6577,  3294,  8210,  9773,
         26822,  3429, 18210, 14023,   304,  2387, 20643,     0],
        [    1, 24824,  8643,  6873, 21344, 15645,  2335,  9157,  9072, 13963,
          7188, 22524, 10174, 15645, 21344, 16626,  9157, 14290, 23428, 20676,
         19349, 26440,  9157,  6759, 23645,  4296, 15645, 14290,  3690, 18149,
         23776, 15645, 21344,  9157,  6839, 23009, 16098, 27338, 19452, 25593,
          6170,  8847,  5261,  6759, 23645, 22354,  2335,  9157,  9072, 21727,
          2102, 17171, 23566, 10426, 14891, 16310, 21344,   290, 10426,  1302,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')

 96%|█████████▌| 107/112 [00:07<00:00, 13.93it/s, loss=0.687]

tensor([[    1, 25593, 15731, 18837, 17282,  6676, 13030, 16740,  5038, 13442,
         16924, 17171, 23232, 15093, 14025, 16740, 11736, 20289, 10951,  5167,
         21535, 20773, 26818,  9984, 18481, 16740,  9266, 13964,  9974,  5167,
          7235, 15093,  8447, 22513, 16740, 10301,  6670,  9724, 20224, 26192,
          7492, 21731,    55,  5313,   244, 22496, 25143, 21726, 14949,  5657,
         24992, 26170, 16740,  7487, 13498,  8981, 27032, 16626, 15093,  9983,
          5522, 17204, 25593, 21731, 27169,  5106,  1798,  4858,  9974,   386,
          7487,  3971, 16924, 25917, 21914, 18588, 11019,  9983, 14059,   276,
         16626, 26818, 18485,  5522, 19293,   134, 26818,  9987, 16896, 25650,
         23888,  8798,  6676, 14284, 10964,  6670, 23990, 15083,  7487,  8817,
          5661, 16740,  4429, 11678, 16626, 15770,  9984, 16626, 14203, 15922,
          9987, 12341, 22030,  8653, 16924, 11392, 19134,  6677, 17079, 19727,
          9987,  8981, 16183, 16310, 18478, 21731,  5718,  4457,  2887, 25593,
         25138, 21955, 13031,  9987, 10232, 11630,  7487, 14865,  9260, 18837,
          7963, 12253,  4878, 15922,  9987, 15093,  9973, 14568, 23806, 18692,
         14760, 22987, 12153, 22742, 14760,     0],
        [    1,  1330,  2866,  1331, 26934, 21535, 18450, 22441, 16626, 10398,
         13027, 25264, 27122, 26934,  3190, 15016,   745, 13934, 24840,  9984,
          9572, 13093, 14126, 23050, 19204, 15875,  8461, 17230,   288, 26934,
           290, 26934, 12062, 18450, 19922,  9581,  8111, 12668, 23779, 24493,
         14484, 23135, 14128,  6149, 10447, 14551,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 21994, 27091,   980, 20256,  4386, 22552, 26342,  6220,  9522,
         24634, 21994,  1617, 17204, 21919,  9180, 26342, 26935,  9639, 21135,
         15394, 10447, 13934,  7790, 13934,  9293, 10559, 22633,  1130, 21994,
           290, 26342, 22057, 23659, 23616, 13657, 15024,  7257, 25076,  4538,
          8853, 21994,  5272, 21994,  6443,  4016,  8788, 21533,  8801, 24975,
         21533,  1089, 21994,   759, 21344, 18056, 24620,  9562, 12081, 16286,
         22552, 27500, 19003,  8853, 22567, 18425, 17857, 14437, 27479,  7651,
          4750, 18091,  2367, 19865, 15024, 24788, 12126,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 21425, 15819,  9266, 12285, 27245, 19829, 24797, 21135, 10559,
         22633, 24634,  8441, 14604, 27248,  8950, 21994, 27091,  5038, 24789,
         10426,  7651, 15819, 21344, 21827, 21135, 27115,   557, 27115, 21135,
         15819, 13308, 27112,  7314, 24990, 27148,  2156,  9266, 12285, 27245,
         19829, 24797, 21135, 10559, 22633, 24634,  8441,  2134, 11812, 18204,
         14970, 26876, 27479, 17131, 15819, 10494, 27076,  3679,  8200,  1617,
         17204, 15481, 14604, 27091, 24797, 21135, 27091, 25062, 15800,  6264,
         15819, 21345,  9639, 21135, 26224, 14795, 21827, 21135,  1617, 17204,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 21334, 20304,  ...,     0,     0,     0],
        [    1,  4036, 19693,  ...,     0,     0,     0],
        [    1,  9983, 22803,  ...,     0,     0,     0],
        [    1,  9642,  1531,  ..., 19349, 25474,     0]], device='cuda:0') tensor([[[-2.9335, 21.7007, -0.6860,  ..., -2.2127,  0.1680,  0.5749],
         [-6.7506, -2.5403, -1.4423,  ..., -6.2331, -1.5723, -2.0955],
         [-6.1480, -4.2604, -2.6477,  ..., -5.3889, -2.5510, -2.0547],
         ...,
         [-2.1617, -0.9438, -1.2771,  ..., -1.9396, -0.9978, -0.3013],
         [-2.1279, -1.0391, -1.1658,  ..., -1.9354, -1.0212, -0.3276],
         [-2.2801, -1.3460, -1.1538,  ..., -2.0905, -1.1402, -0.3610]],

        [[-2.9837, 21.8818, -0.6547,  ..., -2.2815,  0.2190,  0.3401],
         [-3.9611, -4.1331, -1.3207,  ..., -3.0993, -1.5912, -0.9501],
         [-4.7372, -4.4807, -2.0364,  ..., -4.1384, -1.7305, -0.6821],
         ...,
         [-2.3043, -1.5833, -1.4773,  ..., -2.0627, -0.9657, -0.7291],
         [-2.3014, -1.6808, -1.3985,  ..., -2.1079, -1.0145, -0.7461],
         [-2.3975, -1.9527, -1.3540,  ..., -2.2181, -1.1206, -0.7435]],

        [[-1.8583, 22.1839, -0.5186,  ..., -1.1039,  0.5621,  0.8322],
         [-6.0406, -4.0624, -3.0021,  ..., -6.2502, -3.5368, -2.3414],
         [-7.8569, -2.2528, -3.5763,  ..., -7.2511, -3.7203, -1.2783],
         ...,
         [-3.3150, -1.8646, -1.9105,  ..., -2.8193, -1.6707, -0.4738],
         [-3.2638, -1.9790, -1.7862,  ..., -2.7914, -1.6806, -0.4927],
         [-3.4391, -2.3067, -1.7838,  ..., -2.9911, -1.8338, -0.5470]],

        [[-2.2591, 22.5965, -0.4145,  ..., -1.6120,  0.5365,  0.4399],
         [-1.8880, -1.5894, -1.7249,  ..., -2.2998, -1.1681, -0.5789],
         [-5.1989, -1.0262, -2.6250,  ..., -5.7633, -2.9791, -1.5424],
         ...,
         [-3.1649,  0.3280, -1.9029,  ..., -3.4048, -1.4697, -1.9318],
         [-5.9484, -0.9526, -4.2169,  ..., -6.2388, -3.6140, -1.6196],
         [-2.2297, -1.7048, -1.5387,  ..., -2.3299, -1.0771, -1.0617]]],
       device='cuda:0') tensor([[    1, 16580, 18475, 24634, 21344, 21334, 10205, 11765,  5036, 21035,
         10609, 18482, 21344, 21334,  2134, 14469, 14317, 10205, 16221,  5036,
         19867, 18475, 10609, 15037, 21334,   353, 24824, 23919,  1042,  1617,
         17204,  9172, 16713, 14604, 17207, 22030, 14469, 11363, 27115,  2436,
         24992,  2134, 11765, 18483,  9180, 21919,  9180, 24797, 22030, 23905,
         25544,  1302,  4899, 26818,  8610, 21344, 21334,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 21344, 25114, 18450,  5915,  2690, 24482, 27338,  5915,  6248,
         19349, 22023,  3945,  7135, 14367,  7822,  5142, 17825, 24352,  3115,
          1758, 18449,  6248,  5921,  2690, 22024, 13793, 10512, 24352,  3115,
          9612, 18467, 23328, 20116, 20397, 11676, 21639, 19349, 22024, 19290,
         21530, 23143,  2690,  4036, 21344, 26604,  8615,  8829, 15268, 10298,
          4457,  9863,  4241, 13793, 12777,  5142,  5921, 21344, 22049, 27483,
         13793, 25271, 17825, 25475,  7700, 17825, 25475,  7700, 17825,  7996,
          7998, 14955, 21344, 17615,  1582, 10046, 21336,  3951,  4036, 21344,
          5921, 19232, 22096,  4036, 17141, 14195,  8268, 21306,  8458, 24502,
         10521, 16938,  5549, 25025,   256,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 16740, 10397, 22258, 15731, 16626, 16740,  7487, 10951,  5168,
         15044, 22952, 21535, 12615, 22258, 24840, 15731,  5168, 15044, 16740,
         20287, 16626,  7487,  5167,  7612, 27479,   757, 19681, 22261, 24435,
          6676, 19334, 21914, 13030, 27491, 16740,  7487,  5167, 21915, 26161,
         13030,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 16205,  2549, 21344, 26986, 19349,  4272, 15645, 11730, 16205,
         13467, 27338, 20643, 25114, 10512, 13793, 10512,  5549, 10422,  1758,
         16177,  9612, 25114,  4585,  4003, 14227,  9642, 23083, 16205,  2549,
         25025, 13793, 15500, 25098, 17078, 11013, 20877,   489,  7369,  9642,
         20139,  6945, 26883, 16650, 20476, 17825, 20432,  9581, 25114, 25333,
         14586,  1381, 21344, 17825,  5522, 27115,  7822, 14231,  6436,   197,
         16205,  2549, 14891, 25146,  9006, 23123, 13793,  6346, 11286, 20147,
         19349, 25474, 25114,  4585,  4003,  1527, 13793, 22571, 16626, 18511,
         26216, 21344, 16205,  2549, 27321, 26607, 27338, 24344, 20733,  8798,
          6371,  7369,  9642,   198, 16205,  2549,  3463, 15785, 24594, 14284,
         17235, 18609,  1530, 14284, 21874, 11408, 18149, 23123, 10046, 23975,
         16205,  2549, 21344, 17847, 11814,  9266, 26672,  7279,  7345, 23703,
         15401, 14231,  6391, 14025,  4092, 13467,  8615,  1526, 16205,  2549,
         27288,  2207, 16466, 25154, 16005, 27338,  6945, 20476, 17825, 20432,
         14586,  1381, 18869,  7822,  6264,     0]], device='cuda:0')
tensor([[    1,  5218,  7447,  ...,     0,     0,     0],
        [    1, 14958, 27151,  ...,     0,     0,     0],
        [    1, 26360, 21786,  ...,     0,     0,     0],
        [    1, 10736,  9634,  ..., 27201,  4079,     0]], device='cuda:0') tensor([[[-3.1241, 21.6984, -0.8574,  ..., -2.5061,  0.0524,  0.4120],
         [-5.3634, -1.9353, -1.8561,  ..., -5.1856, -2.3121, -0.3156],
         [-3.5583, -2.0960, -0.5447,  ..., -3.3262, -1.2577, -0.4893],
         ...,
         [-3.4227, -1.7505, -1.8426,  ..., -3.0897, -1.8075, -0.7383],
         [-3.5266, -2.1195, -1.9805,  ..., -3.1642, -1.8919, -0.7723],
         [-3.3888, -2.2492, -1.9717,  ..., -2.9705, -1.8646, -0.7720]],

        [[-2.0829, 22.2591, -0.3034,  ..., -1.3022,  0.4374,  0.6298],
         [-3.1830,  0.2809, -1.7387,  ..., -3.1110, -2.0699, -0.1064],
         [-5.0500, -2.8550, -2.1371,  ..., -4.1010, -3.5610, -0.8745],
         ...,
         [-3.4670, -1.7877, -1.8748,  ..., -3.0163, -1.9603, -0.9554],
         [-3.4945, -2.0776, -1.9462,  ..., -2.9843, -2.0035, -0.9516],
         [-3.4057, -2.2473, -1.9379,  ..., -2.8238, -2.0074, -0.9583]],

        [[-2.7865, 21.7848, -0.7715,  ..., -2.0229,  0.0948,  0.6298],
         [-7.0857, -2.2200, -2.8993,  ..., -6.9266, -4.0665, -1.5556],
         [-4.1390, -1.1555, -1.6841,  ..., -3.8567, -1.8143, -2.1341],
         ...,
         [-3.2632, -1.5334, -1.7968,  ..., -2.8411, -1.7933, -0.6401],
         [-3.3716, -1.9012, -1.9057,  ..., -2.8892, -1.8617, -0.6918],
         [-3.3126, -2.1375, -1.9038,  ..., -2.7650, -1.8663, -0.7096]],

        [[-2.6099, 22.4947, -0.4318,  ..., -1.8251,  0.5698,  0.4154],
         [-5.4682, -3.0355, -2.2935,  ..., -5.2078, -3.1499, -1.8498],
         [-6.3581, -4.2424, -2.2163,  ..., -5.8709, -2.3671, -2.6665],
         ...,
         [-6.2671, -3.1667, -3.7327,  ..., -6.2457, -3.3505, -0.9015],
         [-5.3054, -2.7987, -1.7978,  ..., -5.2821, -2.9300, -1.7456],
         [-2.2396, -1.4084, -1.5410,  ..., -1.8658, -1.1003, -1.0054]]],
       device='cuda:0') tensor([[    1,  2205, 10721, 14861,  7449,  5216, 23144,  9673,  7693, 10721,
           118, 13934, 24840, 16050,  7449,  5216, 23144, 20470, 22357,  9673,
         23566, 23760,  7693, 10721, 21344, 15040, 25166,  7698, 16451,  1945,
         18672,  5216, 23144,  9639, 19512,   759, 19908,  3401, 12777, 10061,
         20012,  8715, 22338,  5216, 23144, 23566, 11392,  7693, 10721, 21873,
         26919,  1853, 21344, 16690,  4406,   913,  3885, 16221, 10000, 10721,
          8000,  6600,  4976,   914, 18582,  9673, 17433, 14876,  8397,  5542,
          7700, 14566, 21000, 18999, 27483,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 13793, 17825, 11536,  1661,  5025, 14958,  2542,  5049, 27483,
         14857, 18620, 17810, 21118,  2542,  2910,  3098, 17825, 21344, 27338,
         20701,  2542, 16644, 16221, 13918,  1028,  5025, 10049,  2542, 21874,
          2656,  4597, 20578,  4667,  1416,  2542, 11691,  1458, 21344, 25385,
         11013, 14881, 24062,  4750,  1758,  2542,  9266, 24938, 22513, 17825,
          4273, 14958, 11678,  1028,  8441,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1, 26360, 24348,  2076, 26161, 18267,  9260, 15348,  2428, 27332,
          2690, 20476, 21530, 15565, 15348, 26360, 27338,  9127,  2454,  7218,
         24567,  6129, 22513, 17047, 26161, 24567, 15093,  5171,  8917,  9581,
         14551,  7066, 10232,  2890,  9581, 23857, 21536,  7612, 27479,  2690,
         13934, 26882, 21536,  4830,   525,  3429,  9581, 17757, 18267, 25236,
          2690, 15348, 26161, 21827,  2438, 14551,  7066,  9260,  3434, 15348,
         27338, 10298,  7803, 19586, 26360,   130, 15348, 10351, 16603,  3401,
          2032, 23848,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0],
        [    1,  4368, 20882, 10711, 14255, 21344,  6364,  3517, 10512, 20286,
         15516, 12269,  6625, 25639, 27201,  4079, 25364,  9634,  8852, 12411,
         20701, 12797, 20187,  6949, 10512, 16205, 23688, 21344, 16205, 23688,
         21344, 26161,   525, 20286,  9634, 12621,  4904,  6949, 21854, 21344,
         10512, 16546, 20701,  6627, 22513, 21344, 17447, 21344, 19567,  4463,
           839, 10512,  2214,  3011, 12668, 13988,  3118, 10512, 26715, 17795,
         26715, 10736,  2092, 22384, 21344, 23566, 22008, 19538, 18739, 24833,
          9634, 18720, 25639, 25339, 19934,  6625,  1401, 18739,  5996, 16205,
          2201,  6627,  5522,  3106, 26161, 16205, 10419, 21344, 18056, 10205,
         20287, 19051,  9626, 19245, 26054, 19567, 20880,  1703, 22579, 23971,
         16010, 14000, 14617,  4279, 20485, 16205,    23, 16205, 16219, 21344,
         10512,   242, 22956,  9293,  3118,  6627, 20287, 10736, 15044, 13934,
         27479, 19533, 25639, 18606, 20287, 27201,  4079,  9634,  3123, 11268,
         26161, 10736,  2092, 20702, 25639, 27199, 26886,  9543, 21835, 12958,
         23688, 25025,  4823, 25503, 15918,  2201, 13793, 16197, 21035, 10419,
         26914, 20286, 21344, 19538, 20329, 25691, 17808,  4081, 26161,   759,
          1017, 27479, 17131,  1617, 14943, 10841, 19000,   198, 24673, 17070,
         20287, 27201,  4079,  3555,  6385,     0]], device='cuda:0')
tensor([[    1,  8991,  4386,  7495,  5774, 27314, 16924, 17171, 21035,  8991,
           290,  7495,  4031, 25435, 14551, 14412, 23889, 10301, 24680, 12942,
         14463, 25076, 21860,  8991, 14565,  5567,  7651, 26424, 24876,  7792,
         21860,  9266, 22030, 14463,  2134, 24935, 11305, 13934,  7790,  7519,
          6248, 21847, 21827, 22030, 24636, 24913, 24230, 23411,  8991, 14596,
          5371, 24823, 25550, 23818, 27115,  6197, 22030, 15199, 21239, 13934,
         26882,  9172, 27314, 12322, 25161, 21127,  8991, 25416, 14463, 23717,
          9293, 22036, 19867, 26715, 10205, 10456, 23428, 24938,  5522, 19867,

 97%|█████████▋| 109/112 [00:08<00:00, 14.28it/s, loss=1.25]

tensor([[    1, 11818,  6407, 13793, 15448, 19072, 11818, 24043, 22030, 19275,
         13793, 23252,  5025,  5552,   715, 21535,  8617, 24043,  6425, 11822,
          1897,   525, 13442,  6429, 22558, 22405, 20947, 25603,  5025, 26340,
         10046,  2428, 17556, 13988,  1941, 11822,  7206,  8111, 26669,  2209,
          5569,  1124,  1897,  4759,  9522,  8984,  5569,  1124,  8615, 21226,
          7615, 16654, 26882, 26986,   715,  4016, 23884, 20823,  7194, 20168,
          6846,  5552,   715, 21344,  8615, 24043, 25605, 14881, 19275, 11818,
         11648, 18420,  3560,  1401,  3106,   987,   635, 16205,  7194, 21344,
          2244, 27338, 20444, 25438, 15118, 19072, 11818,  6429, 17449, 17777,
         21982, 11539, 23447,  6429, 20350, 13793, 10426,  1708, 21344, 16834,
         18606, 21344, 17986, 15728,  3071,  6429, 22558, 22384, 16515,  1450,
          4199,  5179,  6090, 26725, 14224, 22055, 19275, 10712, 21344, 16548,
         10447, 26919,  8930, 13326, 18048, 20882,   256, 23624, 26719,  3560,
           759,  8615,  6425, 24840,  6102,  5025, 23436,  9765, 19072, 11818,
          3560,  4386, 17777,   241,  8704, 20877, 11713,  4823, 17519, 11713,
         14587, 12745, 16616, 17841, 18001, 11392,  5569, 13934, 16048, 21227,
           241, 26239, 19232, 11822,  1897, 13989, 19072, 11818, 24043,  9576,
         13964, 21827, 14101,  4016,  1897, 14542, 11392,  5569, 24884,  5552,
           715, 14516, 17730, 21868, 13272, 20746, 11781, 20882, 10709,   986,
         26917, 10712, 26914,  1897, 15024,  3558,  1897,  6170, 21533, 11822,
          5787, 25962,     0],
        [    1, 25639,  9265,  7935,  7599,  4793, 25639,  9265,  7935, 12675,
         25219, 17238, 16616,  7599,  4793, 15783, 15700,  3086, 21535, 10512,
          4802, 23793, 19737, 25639, 24797, 27314, 12280, 26170, 12408,  4829,
         24534, 20470, 23936, 25639,  9265, 26183,  3135, 15658,  3402, 25219,
         17181, 16205,  3086, 21344, 25639,  3402, 23264,  9612, 11927, 26170,
          4020,   539, 20470,  3744, 12275,  5207,  2833,   707, 10919, 11371,
          8396, 18425, 25639, 24797,  2219, 24197, 12838,  3401, 26170, 11927,
         22348,  3118,  3401,  3190, 10610, 15245, 11927, 26170, 26183,  3135,
         12250, 16927,  3107, 11927,  3401, 18450, 26183, 16626, 24532, 26566,
           248, 19155,  6585, 26426,  5026, 16205,  3086, 21344, 12249, 19224,
          3401,  5101,  3135, 22357, 25639,  4842,  7935, 17238, 11927,  3106,
         17808,  8042, 21859, 22742,  3402,  2205, 16432,  6775,  7130,  1131,
         17205, 19939, 27483, 10512, 27338, 18475, 17795,  5844,  8207, 12408,
          4829, 24532,  9413, 16205,  3086, 21344,  4457, 15590, 20470, 21939,
          7760, 26170, 11927,  3106, 19854, 12169,  3401, 18092,  3401, 11736,
          9218, 14367, 27499, 15024,  4020, 20327, 25639, 19829,   557,  2171,
         27314, 14029,  7599,  7700,   290, 12668,  2282, 23793,  2032, 24575,
         12705,  3402, 25639,  3402,  7792, 22007,  8500,   365,  6497, 11927,
         27314, 12335, 16465,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1,  7311, 12461,  2656, 23734, 26669, 26669,  3951, 22949, 17771,
         16924,  7790, 21282, 13210, 15857, 21490,  9973, 12930, 12461, 17771,
         20009, 25308, 16577, 16517, 13484, 27115,  8111, 25035, 22138,  8615,
          5271,  3951, 13210,  5995,  4681,  2780,  4766, 20457,  8111, 13184,
          9327,  4667,  4108, 22414, 15401, 15700, 21206, 15268, 14881, 10063,
         11312,  9266,  4241, 13532, 21064,  3951, 26669, 11337, 22571, 16465,
         27115,  8111, 13870, 11765, 13939, 18024, 27044,  4505,  9973,  9266,
          4241, 13532, 23521, 13210, 10945, 20604, 11312, 10610, 13534, 19727,
          9444, 10885,   757, 15858, 16924, 22330, 10397,  9266,   557, 10205,
         10063, 22041, 24509, 10303, 13535, 22935, 24364, 21899, 26882, 26669,
          4586, 15700, 21206, 25025,  2102, 23221, 26669, 11312, 21535, 20314,
         15425, 11874, 11196, 22513, 13934, 21490,  9973, 24851, 24789, 14888,
         18091,  2387, 21344, 10307, 22311, 26882, 12930,  9973, 16221,  3287,
          8111,  9444, 21064, 24884,  1758, 18485,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0],
        [    1, 23958,  5522, 21239, 27316, 22948, 23958, 12289, 27338, 14317,
         17801, 16654, 16048, 27314,  5754,  5549,  4032, 23318,  8382,  1498,
         12838, 11445, 27479, 17131,  4608, 21245, 15268, 12224, 17087, 14367,
          8441,  9673, 15044, 19306, 24512, 21897, 13934, 21490, 16464, 21441,
         17088,  1017, 26882, 23958, 18931, 18921, 14542, 15038,  1192, 17804,
         23958,  5884, 25249,  2030,  1616, 27338,  2821, 12838, 24509,  3173,
         24840, 27483,   510,  9266, 24840, 21441, 13934, 21490, 13196,  3454,
         15071, 15308,  9232,  3128,  1652, 21900, 14323,  9572, 17795, 14551,
          5567, 24509, 23958,   759, 24344, 17795,  3337, 10609, 12838, 21239,
          1192,  7499,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0]], device='cuda:0') tensor([[[-2.5769, 22.3380, -0.6153,  ..., -1.9791,  0.3267,  0.4902],
         [-4.3710, -0.7564, -1.8045,  ..., -3.5447, -2.7981, -0.2999],
         [-8.8177, -4.6723, -3.9528,  ..., -9.6154, -5.1057, -3.2108],
         ...,
         [-3.0613, -3.9993, -1.7532,  ..., -3.2286, -1.9894, -0.8019],
         [-5.8178, -1.7867, -2.8514,  ..., -5.4537, -2.9897, -1.3643],
         [-3.2938, -2.1429, -2.2564,  ..., -3.4257, -1.8991, -1.3532]],

        [[-2.6862, 22.0961, -0.4509,  ..., -1.9281,  0.3242,  0.5614],
         [-3.0264, -2.4324, -2.0727,  ..., -3.2835, -1.5485, -0.6819],
         [-5.0402, -3.5205, -1.5066,  ..., -4.5246, -2.4304, -1.0668],
         ...,
         [-3.3967, -1.2477, -1.8246,  ..., -2.9590, -1.6949, -0.9151],
         [-3.2045, -1.2171, -1.7603,  ..., -2.8170, -1.5970, -0.9344],
         [-2.9778, -1.2430, -1.7214,  ..., -2.6551, -1.5753, -1.0204]],

        [[-3.0245, 22.2249, -0.7136,  ..., -2.2146,  0.0243,  0.4942],
         [-5.2492,  0.6326, -2.2408,  ..., -4.9720, -1.3972, -0.5851],
         [-5.9380, -2.3156, -2.0258,  ..., -5.9133, -3.0542, -2.3418],
         ...,
         [-3.5963, -1.7113, -2.0000,  ..., -3.2204, -2.0243, -0.9774],
         [-3.4956, -1.6796, -1.9826,  ..., -3.1521, -1.9751, -1.0032],
         [-3.1864, -1.6630, -1.9055,  ..., -2.9104, -1.8871, -1.0435]],

        [[-1.7331, 22.2180, -0.3705,  ..., -0.9068,  0.6803,  0.9310],
         [-6.2425, -3.8895, -3.3693,  ..., -6.0155, -2.6360, -1.8662],
         [-8.4572, -1.5764, -3.5903,  ..., -7.4940, -4.7156, -2.0892],
         ...,
         [-3.6293, -1.4171, -1.9761,  ..., -2.9911, -2.0028, -0.4220],
         [-3.4099, -1.3707, -1.9150,  ..., -2.8201, -1.9190, -0.4371],
         [-3.0221, -1.2696, -1.8063,  ..., -2.5173, -1.8022, -0.4895]]],
       device='cuda:0') tensor([[    1,  5552,   715, 21535,  8617, 24043,  6425, 11822,  1897, 19072,
         11818, 24043,  9576, 13964, 21827, 14101,  4016,  1897, 14542, 11392,
          5569, 24884, 20823,  7194, 20168,  6846,  5552,   715, 21344,  8615,
         24043, 25605, 14881, 19275, 11818, 11648, 18420,   986, 26917, 10712,
         26914,  1897, 15024,  3558,  1897,  6170, 21533, 11822,  5787, 25962,
         11392,  5569, 13934, 16048, 21227,   241, 26239, 19232, 11822,  1897,
         13989, 19072, 11818, 24043, 22030, 19275, 13793, 23252,  5025, 16205,
          7194, 21344,  2244, 27338, 20444, 25438, 15118, 19072, 11818,  6429,
         17449, 17777, 21982,  2428, 17556, 13988,  1941, 11822,  7206,  8111,
         26669,  2209,  5569,  1124,     0],
        [    1, 16205,  3086, 21344, 25639,  3402, 23264,  9612, 11927, 26170,
          4020,   539, 16205,  3086, 21344, 12249, 19224,  3401,  5101,  3135,
         22357, 25639,  4842,  7935, 17238, 11927,  3106, 10512,  4802, 23793,
         19737, 25639, 24797, 27314, 12280, 26170, 12408,  4829, 24534, 20470,
         23936, 25639,  9265, 26183,  3135, 15658,  3402, 25219, 17181, 20470,
          3744, 12275,  5207,  2833,   707, 10919, 11371,  8396, 18425, 25639,
         24797,  2219, 24197, 12838,  3401, 26170, 11927,  4457, 15590, 20470,
         21939,  7760, 26170, 11927,  3106, 19854, 12169,  3401, 18092,  3401,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 26669,  3951, 22949, 17771, 16924,  7790, 21282, 13210, 15857,
         21490,  9973, 12930, 12461,  3951, 26669, 11337, 22571, 16465, 27115,
          8111, 13870, 11765, 13939, 18024, 27044,  4505,  9973, 15401, 15700,
         21206, 15268, 14881, 10063, 11312,  9266,  4241, 13532, 21064,  9266,
           557, 10205, 10063, 22041, 24509, 10303, 13535, 22935, 24364, 21899,
         26882, 26669,  4586, 15700, 21206, 25025,  2102, 23221, 26669, 17771,
         20009, 25308, 16577, 16517, 13484, 27115,  8111, 25035, 22138,  8615,
          5271,  3951,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0],
        [    1, 17804, 23958,  5884, 25249,  2030,  1616, 27338,  2821, 12838,
         24509,  3173, 24840, 27483,   510, 23958,   759, 24344, 17795,  3337,
         10609, 12838, 21239,  1192,  7499, 23958, 18931, 18921, 14542, 15038,
          1192,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1,  1685, 26343,  ...,     0,     0,     0],
        [    1,  7225, 24291,  ...,     0,     0,     0],
        [    1, 27244,  1156,  ...,     0,     0,     0],
        [    1,  9905, 18563,  ...,  8872, 14442,     0]], device='cuda:0') tensor([[[-1.9984, 22.5843, -0.2953,  ..., -1.3652,  0.7037,  0.5817],
         [-4.5254, -3.0426, -1.5980,  ..., -4.5716, -2.1516, -1.9614],
         [-4.4650, -5.1180, -2.0582,  ..., -4.3367, -2.2187, -1.2342],
         ...,
         [-3.3866, -4.3687, -0.9501,  ..., -3.6893, -1.4763,  0.1810],
         [-5.0556, -4.6283, -1.7663,  ..., -5.1148, -1.4071, -0.6882],
         [-2.4793, -1.7032, -1.9171,  ..., -2.4512, -1.0961, -0.9952]],

        [[-1.9173, 22.7694, -0.1468,  ..., -1.1975,  0.6567,  0.7585],
         [-5.8046, -3.6020, -3.0305,  ..., -4.7955, -3.2423, -1.8457],
         [-0.9159, -0.0240, -0.1726,  ..., -0.6178, -0.4585,  0.6369],
         ...,
         [-2.8915, -1.7053, -1.6937,  ..., -2.4353, -1.3286, -0.6733],
         [-3.3770, -2.1217, -2.0053,  ..., -2.9617, -1.5821, -0.7936],
         [-3.7022, -2.3316, -2.2441,  ..., -3.3501, -1.7430, -0.9288]],

        [[-2.6208, 21.6910, -0.6395,  ..., -1.8041,  0.3289,  0.5616],
         [-3.3399,  1.4395, -1.1762,  ..., -2.5640, -1.2661, -0.4704],
         [-5.6232, -4.9531, -2.8823,  ..., -5.0079, -3.3371, -2.4484],
         ...,
         [-3.7014, -2.3007, -1.8248,  ..., -3.0027, -1.8356, -0.3075],
         [-4.1826, -2.7543, -2.1237,  ..., -3.5266, -2.0964, -0.4329],
         [-4.6323, -3.0380, -2.4247,  ..., -4.0621, -2.3082, -0.6028]],

        [[-2.4447, 22.6153, -0.4223,  ..., -1.6858,  0.4829,  0.4633],
         [-5.1913, -1.1968, -2.6268,  ..., -5.2388, -2.3275, -1.3965],
         [-5.3035, -2.2980, -2.1992,  ..., -4.1943, -1.9844, -1.3482],
         ...,
         [-2.3694, -1.7512, -1.7500,  ..., -1.9932, -1.0904, -0.7858],
         [-2.7890, -2.1450, -2.0414,  ..., -2.4490, -1.3220, -0.8984],
         [-3.0243, -2.3369, -2.2323,  ..., -2.7602, -1.4347, -1.0092]]],
       device='cuda:0') tensor([[    1, 26343,  7390, 21685,  2367,  6846, 15700, 14131, 12054, 23469,
         25062, 11696,  5258,  2367,   261,  1702,  2367,  3118,  9157, 23967,
         14622, 23645, 25593, 27529, 27248,  6671, 20273,  9645, 16183, 19814,
          2473, 18300, 13939, 22524, 19814,  4092,   759, 25062,  2367, 22987,
          1685,  6214,  2367,  9157, 23411,  3831,  2560,  2367, 24044,   261,
         13009,  9645,  2367,   259, 19814,  3118,   259,  4524, 17572, 25062,
          2367, 24044,   259,  4541,  6727, 14604,  2367,   259,  1815,  9645,
          8761,   113,  1705, 25593, 26886, 24938, 27149, 12224, 16138,  6719,
         25062,  2367,  9543,  9157,  2367, 16310,  8368, 23988, 23233, 15752,
          2367, 17316, 21730,  2367,  7724, 11561,  2621,  1685, 14633,  3268,
          3118, 16183, 26343,  7390, 22148, 14857, 11608,  1815,  9157,  1705,
          1685, 25062,  9634,  1705,   759,  4688,  2367, 14881, 10872, 19119,
          6573, 26343,  7390,   759, 21673,  2367,  5507,  6573,  6846, 14131,
          2134, 15139, 21694,  2367,  6846,  1702, 25025,  1582,   783, 21530,
         24092, 22937, 21344, 15399,  2436,  3118, 11622, 13405, 27152, 26672,
          1708,  8008, 10945, 21490,  6600, 25593, 16792,  2367,   261, 24847,
         10590,  6364, 23888, 26343,  7390,  2822, 21365, 10872, 16595, 18367,
         10456, 21344,   128,  1702,  2367,   259,  9645,  5522, 14881,  3966,
           261, 11269, 15813, 19839,   125, 23123,     0],
        [    1,  8820, 17941,  4734,   757, 20171, 16588,  7225, 10232, 26357,
         22932,  9480,  6149,  1302, 12669,  7225, 16387, 24291, 21344, 16205,
          7588,  4948,  4624, 27338,  6759, 22558, 27338, 14023, 26179,  5522,
          8820, 11932, 19293, 18581, 19783, 14918,  8820,  7225, 10945,  1758,
         17941, 22036, 27324, 18851, 16205,  7588, 21344, 20646,  7225,  7025,
         26179, 27338, 14564, 11940, 19854, 22558, 21269, 14564, 14317,  8112,
         24291, 14881,  7637,  5657, 26867,   307, 26183,   755, 14317,  5950,
          5522, 17204,  1758,  7279, 21548, 25211,  2720, 26750, 20172, 16391,
         14564, 14317, 14118,  4842, 14023, 26179,  8820, 22560,  6577, 23481,
         17856,  5674,  3679,  6623,  5522,  2169, 27032, 14606,  7637,  6648,
         21548, 21535, 23521,  7588,  6846, 25641,  3517,  1375,  4630, 26172,
         20479,  8397, 13895, 13895, 11862, 24291,  3517, 25896, 26172, 25639,
         12675,  9610,  4974, 24291, 14186, 21548,  5657,  8820, 22560,  7639,
         12669,  7225, 16391, 24291, 27290, 19158, 27483, 19940,  1186, 12675,
          7839, 24449,  9522,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1, 11516, 14382, 20701,  9581,  4559, 23008, 27244, 19596, 22024,
         10332, 11516, 26070, 16626, 27244, 14953, 25503, 27479, 17131, 13941,
         20702, 14952, 23008, 23884, 13210,  7257, 27244,  9973, 22513, 21305,
         23278, 21982, 27292,   749, 27244,  3699,  2866, 23779, 10603, 23008,
         22513,  1152, 26049, 18741,  9673, 14953,   759, 14382, 20701, 23008,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [    1,  9297, 14367, 18270,   759, 23428, 10205, 16221, 22008,  4876,
         24534,  9584, 16387, 26566, 12812, 26573, 21151,  3522, 26390, 16588,
         12560,  9297, 14367, 18267, 16603, 16182, 25922, 15922,  9297, 18270,
         14564, 22030, 10205,  7984,  2204, 27479, 24797, 10130, 15922, 18270,
          2169, 12353, 16146,  1017,  6129,  1140, 19112, 18267, 27308, 12938,
         22023, 11862,  9923, 23221,  2436, 15514, 14608,  9861,  2169,  4822,
         12560, 17227, 14323, 19449, 24788,  9913, 18270, 26426, 15595, 16262,
          3626,   757,  3548, 18270, 14564, 22030,  4016,  6775,  3549, 14323,
         27115,  8872, 16254, 15461,  6677, 10395, 21364, 13472, 14323, 22558,
         25639,  9266, 27111, 16603,  7510, 10395, 14442,  5522, 26818, 21257,
          1242, 10205, 11392, 23127, 16588,   130, 22023, 20778,  1302, 11862,
          6676, 26180, 15922, 16606, 24233,  1758,  9297, 14367, 11570, 22234,
         24534, 14633,  5492, 26566,  3522, 15398, 17227, 14596, 22450,  4305,
         20734, 24566, 20196, 17065,  6214,  1241,  4624, 26573,  3522, 14323,
         21859, 14606,  5216,  9453, 26573,  3514, 22024, 23433,  8761,  4876,
          7950, 24532, 27111, 10098,  9921,  8858, 16654, 16050, 14564, 14317,
         10426, 14606,  9854,   757,  8715,  3630,  9913, 16606, 14191, 17077,
         10456,  6135, 26566,  3522, 19782, 19077, 15202, 17227,     0,     0,
             0,     0,     0,     0,     0,     0,     0]], device='cuda:0')
tensor([[    1, 20946,  1140,  ...,   744,  7029,     0],
        [    1, 14468, 18450,  ...,     0,     0,     0],
        [    1,  2303, 13242,  ...,     0,     0,     0],
        [    1, 25114,  8634,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-1.9737, 22.6658, -0.1908,  ..., -1.2302,  0.9235,  0.5588],
         [-5.8770, -2.0737, -2.1595,  ..., -5.4639, -2.8858, -0.1464],
         [-7.0194, -3.6409, -2.9374,  ..., -5.6839, -2.6761, -0.3646],
         ...,
         [-5.3254, -2.2350, -2.2314,  ..., -4.7598, -2.1971, -1.2043],
         [-1.3890, -1.6026, -1.0263,  ..., -0.9155, -0.5688,  0.4546],
         [-2.1618, -1.7827, -1.9063,  ..., -2.3517, -1.2892, -1.1601]],


100%|██████████| 112/112 [00:08<00:00, 13.52it/s, loss=0.607]

tensor([[    1, 16080,  6163,  ...,     0,     0,     0],
        [    1,  3492, 22153,  ..., 22147, 19003,     0],
        [    1, 25639, 22030,  ...,     0,     0,     0],
        [    1,  1747,  2170,  ...,     0,     0,     0]], device='cuda:0') tensor([[[-2.6002, 22.0825, -0.6932,  ..., -1.9303,  0.2797,  0.5722],
         [-2.6506,  1.0064, -1.7045,  ..., -1.8044, -1.0872, -1.0202],
         [-0.3390,  0.0317,  1.1998,  ..., -0.1687,  0.2670,  1.0154],
         ...,
         [-2.9010, -1.3714, -1.8675,  ..., -2.5540, -1.3235, -0.4029],
         [-2.8525, -1.6103, -1.8519,  ..., -2.4844, -1.3749, -0.5123],
         [-2.7319, -1.6099, -1.7342,  ..., -2.3455, -1.3864, -0.5893]],

        [[-2.8026, 22.2369, -0.4512,  ..., -2.0741,  0.2774,  0.3487],
         [-4.6901, -2.1567, -1.1007,  ..., -4.0603, -2.4520, -0.7242],
         [ 0.6152,  1.9942,  1.1171,  ...,  0.6500,  0.4866,  1.0985],
         ...,
         [-2.5324, -1.2122, -2.0355,  ..., -2.4330, -1.1029, -1.1291],
         [-2.5008, -1.4118, -2.0448,  ..., -2.3944, -1.1562, -1.2535],
         [-2.3963, -1.4007, -1.9471,  ..., -2.2814, -1.1810, -1.3381]],

        [[-2.1832, 22.6348, -0.4493,  ..., -1.5139,  0.6270,  0.7130],
         [-4.1588, -1.2866, -1.8014,  ..., -3.8468, -1.2001, -1.3680],
         [-4.4167, -1.8002, -1.9346,  ..., -4.2122, -2.7116, -1.1540],
         ...,
         [-5.8579, -3.2004, -3.4153,  ..., -5.6628, -2.3860, -0.9595],
         [-2.5017, -1.8540, -2.0900,  ..., -1.9663, -0.8936,  0.2304],
         [-1.6260, -1.1439, -1.6657,  ..., -1.4992, -0.8429, -0.7556]],

        [[-2.3999, 22.3886, -0.3882,  ..., -1.7264,  0.5082,  0.7964],
         [-5.4373, -0.6247, -2.4015,  ..., -5.9520, -2.3135, -0.5699],
         [-7.6120, -4.9804, -3.0695,  ..., -7.6699, -3.4568, -1.9992],
         ...,
         [-2.6917, -1.2380, -1.9826,  ..., -2.6434, -1.1546, -0.8224],
         [-2.6110, -1.4249, -1.9286,  ..., -2.5455, -1.1726, -0.9236],
         [-2.4698, -1.4172, -1.7968,  ..., -2.3981, -1.1818, -1.0066]]],
       device='cuda:0') tensor([[    1,  3816, 21417, 16080, 13182, 19763, 10711,   262, 16789, 17352,
         23425,  9543, 13894,  9157, 21417, 16080, 20154, 17171, 19189,   262,
          1302, 15997,  4713,  2847,   261,  9172, 11622,  6846, 13228, 15133,
         21702, 26161,  4712, 14023, 15071,  9844, 10530,  2335,  9157,  9072,
         13323,  5522,  4254,  4094, 24777, 17352, 27150, 18092, 16036, 10061,
         24914,  1702,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [    1,  3492,   759, 21344, 10512,  2245,  4845, 14223, 17929, 24485,
         19119, 22155,  5282, 12780, 18346,  3492,  4845,  1017, 22450, 17117,
          9197, 12284, 27479,   759, 21344, 12285, 10512, 25025, 17929, 19119,
         24482,  3492,  1256, 14223,  4845, 21344, 24693, 22354, 22450,  9197,
         17171, 12285, 17117,  9114, 26090, 18767,  1242,  3492, 20145, 10512,
         18724, 16205,  9989, 21344,  4845, 21344, 19780, 27338, 21253, 18068,
         25056, 22049,  2004, 17117,  3492, 21344,  8359, 20754, 22450,  7341,
         12443,  8613,  3492,   290, 27338,  1165,  1042,  9111,  7615, 16654,
         27479, 23203,  9260, 21344, 24482, 27338, 27161,  9111,  5883, 26251,
          3492,   759, 17218, 16573,  1920,  3822,  9825, 12280, 14029, 25639,
         22153,  7612, 27479, 22162, 20925, 22147, 19003,     0,     0,     0],
        [    1, 16735, 17524,  7926, 11392,  4806,  4538,  7769, 21511, 16010,
         25639,  9543, 21835, 12958, 23688,  1017, 27380, 23443, 16205, 23688,
         21344, 21517, 14795, 11286, 25782, 11395, 19048, 27290, 14367,  9543,
          4824, 17083, 23677, 19044, 12226,  5533, 19177,  5533, 24672,  8086,
          4497,  4044,  9543, 17083,  5885, 25639,  2032, 23337, 22513, 17524,
         18759,  4539,  8541, 26876,  5921, 16626,  7926,  5202, 17205,  6831,
         18759, 25547, 14496, 23337, 10512, 16326, 10298,  8879,  4460, 19880,
         14891,  7393,  4049,  1017, 16326, 22340,  3118,  4794, 12651, 12651,
          3123,    74,   400,   442, 21344, 22096,  9543, 21835, 15645,   933,
         21344,  5181, 16521,  8156, 26251, 16010,  9543, 15867,  4049,  7510,
         19452, 18423,  8047, 21517, 14795,  5924, 23337, 21247,  5506,     0],
        [    1,  4515,  7650,  2932,  7391, 15731,  7218,  1747,  2169, 16626,
          8950, 27115,  2367, 18318, 17353, 23975, 15731,  7218,  1747, 22049,
         16792,  1685, 24044,  3833,  3831,  2560, 24969, 27115, 18092, 13407,
         11314,  1685, 16082,  9735,  8950, 24344, 11570,  9266,  8447, 17352,
         15731,  7218,  1747,  1685, 21685,  2367,  6846, 16791, 15139, 21694,
         16616, 17352, 23426, 14166,  6727,  3831,  2560, 16789,   243, 17353,
           168, 19395,  9157, 17548, 18999,  8950,  1685,  7650,   759, 24969,
         24344,  2367,  6846,  1702,  1008, 24810, 11561, 20473, 21344, 15731,
          7218,  1747, 11203, 27362, 23411, 11418, 24174,  8950, 27115,  2367,
           261, 13009,  9645, 24969, 27115,  2367,   259, 19814, 16789,  9157,
         16789, 16183,  2367, 18318, 24944, 13934, 27483,     0,     0,     0]],
       device='cuda:0')
tensor([[    1, 10193,  3522,  8385, 20116, 10190,  4036, 10186, 21644,  3517,
         19622, 20116,  8385, 23328, 17620, 10574,  5548,  9370,  3268,  6298,
         16205, 21644, 21344,  8589,  9272, 21229, 14579,   727,  5548, 21239,
          6298,  5883, 14348, 15602,  3970,  5724, 27379,  9184, 24944, 16205,
         21644,   759, 21344, 11180, 10512, 10610, 21530, 20120,  4049, 17620,
          7510,   525,  7693, 23968, 15044,  5883,  8385, 21229, 14348, 22578,
          8407,  5549,  6297, 10084,  5548,  8508, 24843, 14223, 11227,  9202,
          8397,  4801,   770, 22055,  5548, 12226, 10193,  3012, 21229,  5162,
         22513, 27201,  8772, 19400,  8397,  4801,   219, 13934, 16048, 27338,
         12133, 21409,  5548,  3018, 21229, 16205, 21644, 23467, 24042, 17620,
         22030, 21344,  8560, 16522, 24344,   171,  5492,  7230, 20116, 19155,
          4051,  7693,  5008, 23328, 17620, 27290,  2387, 12700,  8397, 12572,
          3269, 23022, 16456, 17780, 18122, 14351,  5008, 27387,  4870, 20588,
         15499, 23446, 27095,   681, 18609,  5162,  7693, 10404,  8385,  6298,
           731, 20925, 16205, 21644,  1255,  5548, 15447, 22055, 14964,  5724,
         12223, 10514,   364,  5504, 23768, 20120,  5548, 23919,  7693, 23351,
         16465, 22333, 23090,  7693,  3342, 19232,  4049, 27338, 14881, 11022,
          8397,  4801, 13963, 12417,   244, 23440,  3013, 17620, 21229, 16205,
         21644, 12700,  4759,   539, 15448,  8407,  9181, 15785, 16005,  6945,
         17620, 12918,   759,  6946, 25503,  7690, 15448,  9181, 15785,  8385,
         15500, 16205, 21644,   759,  3517, 11180, 10512, 18475, 13918, 21044,
         22144, 20120, 17620, 16924,  8385,  9181, 15785,  2245,  8945, 14351,
          4049,  8407, 21229,     0]], device='cuda:0') tensor([[[-2.8919, 22.1280, -0.5506,  ..., -2.3349,  0.2078,  0.2657],
         [-2.4136, -2.0847, -1.7335,  ..., -3.0048, -1.5220, -0.6160],
         [-3.0216, -0.5809, -0.8849,  ..., -2.6753, -0.9590,  0.4220],
         ...,
         [-4.4906, -5.0834, -1.2617,  ..., -5.5149, -3.8543, -0.4427],
         [-5.3034, -3.0786, -2.3489,  ..., -5.7665, -3.7832, -1.9784],
         [-2.3460, -1.3794, -1.4931,  ..., -2.4557, -1.3219, -1.1650]]],
       device='cuda:0') tensor([[    1, 16205, 21644,   759,  3517, 11180, 10512, 18475, 13918, 21044,
         22144, 20120, 17620, 16205, 21644, 21344,  8589,  9272, 21229, 14579,
           727,  5548, 21239,  6298,  5883, 14348, 15602,  3970,  5724, 16205,
         21644, 23467, 24042, 17620, 22030, 21344,  8560, 16522, 24344,   171,
          5492,  7230, 20116, 19155,  4051,  7693,  5008, 16205, 21644, 12700,
          4759,   539, 15448,  8407,  9181, 15785, 16005,  6945, 17620, 27379,
          9184, 24944, 16205, 21644,   759, 21344, 11180, 10512, 10610, 21530,
         20120,  6298,   731, 20925, 16205, 21644,  1255,  5548, 15447, 22055,
         14964,  5724, 10190,  4036, 10186, 21644,  3517, 19622, 20116,  8385,
         23328, 17620, 10574,  5548,  9370,  3268,  6298,     0]],
       device='cuda:0')
Final Test Accuracy =  58.946919026611646

In [135]:
import torch

# Save only weights (recommended)
torch.save(model.state_dict(), "summarizer_model.pth")

In [139]:
# When using Hugging Face
# model.save_pretrained("summarizer_model")
# tokenizer.save_pretrained("summarizer_model")

In [140]:
# import shutil

# shutil.make_archive("summarizer_model", 'zip', "summarizer_model")

In [137]:
torch.save({
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
}, "checkpoint.pth")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')